import type { Lesson } from '../types';

export const a2lektion20: Lesson = {
  id: 'a2-l20', level: 'A2', module: 6, number: 21,
  title: { de: 'Als, bis und seit(dem)', en: '"als", "bis" and "seit(dem)"', fr: '« als », « bis » et « seit(dem) »' },
  theme: 'Telling your life story: als vs. wenn, bis, seit(dem), and clause order',
  themeFr: 'Raconter sa vie : als ou wenn, bis, seit(dem) et l’ordre des propositions',
  goals: ['Use "als" for a single event in the past', 'Tell "als" and "wenn" apart', 'Use "bis" and "seit(dem)" as conjunctions', 'Put the subordinate clause first or second'],
  goalsFr: ['Utiliser « als » pour un événement unique au passé', 'Distinguer « als » et « wenn »', 'Utiliser « bis » et « seit(dem) » comme conjonctions', 'Placer la subordonnée en premier ou en second'],
  steps: [
    { kind: 'intro', title: 'Als ich Kind war … 📖', titleFr: 'Quand j’étais enfant … 📖',
      scene: 'At a family gathering, Grandma Helga tells her life story — school, first job, moving to a new city — and the grandchildren ask questions.', sceneFr: 'Lors d’une fête de famille, grand-mère Helga raconte sa vie — l’école, le premier travail, le déménagement — et les petits-enfants posent des questions.',
      goals: ['Tell events with "Als ich … war, …"', 'Choose between als and wenn', 'Say "until" and "since" with bis and seit(dem)', 'Tell a short life story in order'],
      goalsFr: ['Raconter des événements avec « Als ich … war, … »', 'Choisir entre als et wenn', 'Dire « jusqu’à ce que » et « depuis que » avec bis et seit(dem)', 'Raconter une courte histoire de vie dans l’ordre'] },

    { kind: 'vocab', item: { id: 'a2l20-als', german: 'als', english: 'when (one event in the past)', french: 'quand (événement unique au passé)', gender: null, syllables: ['ALS'], pronunciation: 'ahls', example: { de: 'Als ich Kind war, habe ich in Douala gewohnt.', en: 'When I was a child, I lived in Douala.', fr: 'Quand j’étais enfant, j’habitais à Douala.' } } },
    { kind: 'vocab', item: { id: 'a2l20-bis', german: 'bis', english: 'until / by the time', french: 'jusqu’à ce que', gender: null, syllables: ['BIS'], pronunciation: 'biss', example: { de: 'Ich warte, bis du fertig bist.', en: 'I am waiting until you are ready.', fr: 'J’attends que tu sois prêt.' } } },
    { kind: 'vocab', item: { id: 'a2l20-seit', german: 'seit / seitdem', english: 'since (up to now)', french: 'depuis (que)', gender: null, syllables: ['SEIT', 'dem'], pronunciation: 'zite / zite-DAME', example: { de: 'Seitdem ich in Berlin wohne, lerne ich Deutsch.', en: 'Since I have been living in Berlin, I have been learning German.', fr: 'Depuis que j’habite à Berlin, j’apprends l’allemand.' } } },
    { kind: 'vocab', item: { id: 'a2l20-schulzeit', german: 'die Schulzeit', english: 'school days', french: 'les années d’école', gender: 'die', syllables: ['SCHUL', 'zeit'], pronunciation: 'dee SHOOL-tsite', example: { de: 'Meine Schulzeit war sehr schön.', en: 'My school days were very nice.', fr: 'Mes années d’école étaient très belles.' } } },
    { kind: 'vocab', item: { id: 'a2l20-grundschule', german: 'die Grundschule', english: 'the primary school', french: 'l’école primaire', gender: 'die', syllables: ['GRUND', 'schu', 'le'], pronunciation: 'dee GROONT-shoo-leh', example: { de: 'Mit sechs Jahren gehen die Kinder in die Grundschule.', en: 'At six, children go to primary school.', fr: 'À six ans, les enfants vont à l’école primaire.' } } },
    { kind: 'vocab', item: { id: 'a2l20-abitur', german: 'das Abitur', english: 'school-leaving exam (Abitur)', french: 'le baccalauréat', gender: 'das', syllables: ['A', 'bi', 'TUR'], pronunciation: 'dahs ah-bee-TOOR', example: { de: 'Nach dem Abitur möchte ich studieren.', en: 'After the Abitur I want to study.', fr: 'Après le bac, je veux faire des études.' } } },
    { kind: 'vocab', item: { id: 'a2l20-ausbildung', german: 'die Ausbildung', english: 'vocational training', french: 'la formation professionnelle', gender: 'die', syllables: ['AUS', 'bil', 'dung'], pronunciation: 'dee OWSS-bil-doong', example: { de: 'Sie macht eine Ausbildung als Köchin.', en: 'She is doing training as a cook.', fr: 'Elle fait une formation de cuisinière.' } } },
    { kind: 'vocab', item: { id: 'a2l20-studium', german: 'das Studium', english: 'university studies', french: 'les études supérieures', gender: 'das', syllables: ['STU', 'di', 'um'], pronunciation: 'dahs SHTOO-dee-oom', example: { de: 'Mein Studium dauert drei Jahre.', en: 'My studies last three years.', fr: 'Mes études durent trois ans.' } } },
    { kind: 'vocab', item: { id: 'a2l20-umziehen', german: 'umziehen', english: 'to move (house)', french: 'déménager', gender: null, syllables: ['UM', 'zie', 'hen'], pronunciation: 'OOM-tsee-en', example: { de: 'Wir sind letztes Jahr umgezogen.', en: 'We moved last year.', fr: 'Nous avons déménagé l’année dernière.' } } },
    { kind: 'vocab', item: { id: 'a2l20-heiraten', german: 'heiraten', english: 'to marry', french: 'se marier', gender: null, syllables: ['HEI', 'ra', 'ten'], pronunciation: 'HY-rah-ten', example: { de: 'Meine Eltern haben 1995 geheiratet.', en: 'My parents got married in 1995.', fr: 'Mes parents se sont mariés en 1995.' } } },
    { kind: 'vocab', item: { id: 'a2l20-lebenslauf', german: 'der Lebenslauf', english: 'the CV / résumé', french: 'le CV', gender: 'der', syllables: ['LE', 'bens', 'lauf'], pronunciation: 'dair LAY-bens-lowf', example: { de: 'Mein Lebenslauf ist zwei Seiten lang.', en: 'My CV is two pages long.', fr: 'Mon CV fait deux pages.' } } },
    { kind: 'vocab', item: { id: 'a2l20-erinnerung', german: 'die Erinnerung', english: 'the memory', french: 'le souvenir', gender: 'die', syllables: ['er', 'IN', 'ne', 'rung'], pronunciation: 'dee er-IN-eh-roong', example: { de: 'Das ist eine schöne Erinnerung.', en: 'That is a nice memory.', fr: 'C’est un beau souvenir.' } } },
    { kind: 'vocab', item: { id: 'a2l20-erwachsen', german: 'erwachsen', english: 'grown up / adult', french: 'adulte', gender: null, syllables: ['er', 'WAK', 'sen'], pronunciation: 'er-VAHK-sen', example: { de: 'Jetzt bin ich erwachsen.', en: 'Now I am grown up.', fr: 'Maintenant, je suis adulte.' } } },

    { kind: 'grammar', note: {
      id: 'a2l20-als-wenn', title: 'als or wenn?', titleFr: 'als ou wenn ?',
      explanationMd: 'Both mean "when", but they are **not** interchangeable:\n\n- **als** → **one single event** in the **past**: **Als** ich zehn **war**, sind wir umgezogen.\n- **wenn** → **repeated** events (past, present or future) or the present/future: **Immer wenn** ich Ferien **hatte**, bin ich zu Oma gefahren. · **Wenn** ich Zeit **habe**, lese ich.\n\nWith **als**, the verb is in the **Präteritum** (war, hatte) or the **Perfekt**. Like every subordinate clause, the conjugated verb goes to the **end**.\n\nTip: if you can say "every time that", use **wenn** (**immer wenn**, **jedes Mal, wenn**).',
      explanationMdFr: 'Les deux signifient « quand », mais ils ne sont **pas** interchangeables :\n\n- **als** → **un seul événement** au **passé** : **Als** ich zehn **war**, sind wir umgezogen.\n- **wenn** → événements **répétés** (passé, présent ou futur) ou présent/futur : **Immer wenn** ich Ferien **hatte**, bin ich zu Oma gefahren. · **Wenn** ich Zeit **habe**, lese ich.\n\nAvec **als**, le verbe est au **Präteritum** (war, hatte) ou au **Perfekt**. Comme dans toute subordonnée, le verbe conjugué va à la **fin**.\n\nAstuce : si tu peux dire « chaque fois que », utilise **wenn** (**immer wenn**, **jedes Mal, wenn**).',
      examples: [
        { de: 'Als ich sechs war, bin ich in die Grundschule gekommen.', en: 'When I was six, I started primary school.', fr: 'Quand j’avais six ans, je suis entré à l’école primaire.' },
        { de: 'Immer wenn Oma kochte, roch das ganze Haus gut.', en: 'Whenever Grandma cooked, the whole house smelled good.', fr: 'Chaque fois que grand-mère cuisinait, toute la maison sentait bon.' },
        { de: 'Wenn ich Zeit habe, rufe ich dich an.', en: 'When I have time, I will call you.', fr: 'Quand j’aurai le temps, je t’appellerai.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l20-bis-seit', title: 'bis and seit(dem) as conjunctions', titleFr: 'bis et seit(dem) comme conjonctions',
      explanationMd: '**bis** = until, **seit / seitdem** = since (and still true now). Both start a subordinate clause, so the verb goes to the **end**:\n\n- Ich warte, **bis** der Bus **kommt**. — I wait until the bus comes.\n- Sie hat gearbeitet, **bis** es dunkel **wurde**.\n- **Seit(dem)** ich in Berlin **wohne**, fahre ich Rad. — Since I have lived in Berlin, I cycle.\n- **Seitdem** ich umgezogen **bin**, habe ich neue Freunde. — Since I moved, I have new friends.\n\nUse the **present** in the seit-clause for something that is still going on, and the **Perfekt** for a completed event. Do not mix up the preposition **seit + dative** (seit einem Jahr = for a year) with the conjunction (**seit** ich hier **bin**).',
      explanationMdFr: '**bis** = jusqu’à ce que, **seit / seitdem** = depuis (que) (et c’est encore vrai maintenant). Les deux introduisent une subordonnée, donc le verbe va à la **fin** :\n\n- Ich warte, **bis** der Bus **kommt**. — J’attends que le bus arrive.\n- Sie hat gearbeitet, **bis** es dunkel **wurde**.\n- **Seit(dem)** ich in Berlin **wohne**, fahre ich Rad. — Depuis que j’habite à Berlin, je fais du vélo.\n- **Seitdem** ich umgezogen **bin**, habe ich neue Freunde. — Depuis que j’ai déménagé, j’ai de nouveaux amis.\n\nUtilise le **présent** dans la subordonnée en seit pour ce qui continue, et le **Perfekt** pour un événement terminé. Ne confonds pas la préposition **seit + datif** (seit einem Jahr = depuis un an) avec la conjonction (**seit** ich hier **bin**).',
      examples: [
        { de: 'Wir bleiben hier, bis der Regen aufhört.', en: 'We are staying here until the rain stops.', fr: 'Nous restons ici jusqu’à ce que la pluie s’arrête.' },
        { de: 'Seit ich das Abitur gemacht habe, arbeite ich in einem Café.', en: 'Since I finished school, I have been working in a café.', fr: 'Depuis que j’ai le bac, je travaille dans un café.' },
        { de: 'Seit einem Jahr wohne ich in Hamburg.', en: 'I have been living in Hamburg for a year.', fr: 'J’habite à Hambourg depuis un an.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l20-satzstellung', title: 'Clause order and telling a story', titleFr: 'Ordre des propositions et récit',
      explanationMd: 'You can put the **subordinate clause** first or second — the meaning stays the same:\n\n- Wir sind umgezogen, **als** ich zehn **war**.\n- **Als** ich zehn **war**, **sind** wir umgezogen.\n\nWhen the subordinate clause comes **first**, the main clause starts with its **verb** (inversion): als-clause = position 1, verb = position 2. This works the same for **als, wenn, bis, seit(dem)**.\n\nFor life stories, link events with **zuerst** (first), **dann / danach** (then), **später** (later), **zuletzt** (finally).',
      explanationMdFr: 'Tu peux placer la **subordonnée** en premier ou en second — le sens reste le même :\n\n- Wir sind umgezogen, **als** ich zehn **war**.\n- **Als** ich zehn **war**, **sind** wir umgezogen.\n\nQuand la subordonnée vient en **premier**, la principale commence par son **verbe** (inversion) : subordonnée en als = position 1, verbe = position 2. C’est pareil pour **als, wenn, bis, seit(dem)**.\n\nPour raconter une vie, relie les événements avec **zuerst** (d’abord), **dann / danach** (puis), **später** (plus tard), **zuletzt** (enfin).',
      examples: [
        { de: 'Als ich das Abitur gemacht habe, war ich sehr stolz.', en: 'When I finished school, I was very proud.', fr: 'Quand j’ai passé mon bac, j’étais très fier.' },
        { de: 'Ich war sehr stolz, als ich das Abitur gemacht habe.', en: 'I was very proud when I finished school.', fr: 'J’étais très fier quand j’ai passé mon bac.' },
        { de: 'Zuerst war ich in der Grundschule, danach habe ich eine Ausbildung gemacht.', en: 'First I was in primary school, then I did vocational training.', fr: 'D’abord j’étais à l’école primaire, puis j’ai fait une formation professionnelle.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l20-e1', prompt: 'Ich war sehr nervös, ___ ich die Prüfung hatte. (single event in the past)', promptFr: 'Ich war sehr nervös, ___ ich die Prüfung hatte. (événement unique au passé)', answer: 'als', hint: 'One single past event → als.', hintFr: 'Un seul événement passé → als.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l20-e2', prompt: 'Immer ___ ich Zeit hatte, bin ich in die Bibliothek gegangen.', promptFr: 'Immer ___ ich Zeit hatte, bin ich in die Bibliothek gegangen.', options: ['als', 'wenn', 'bis'], optionsFr: ['als', 'wenn', 'bis'], answer: 1, explain: '"immer wenn" = repeated events, even in the past.', explainFr: '« immer wenn » = événements répétés, même au passé.', hint: 'Repeated action: "every time that".', hintFr: 'Action répétée : « chaque fois que ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l20-e3', tokens: ['sind', 'Als', 'ich', 'zehn', 'war', 'wir', 'umgezogen'], answer: ['Als', 'ich', 'zehn', 'war', 'sind', 'wir', 'umgezogen'], hint: 'als-clause first (verb last), then the verb "sind", then the subject.', hintFr: 'D’abord la subordonnée en als (verbe à la fin), puis le verbe « sind », puis le sujet.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l20-e4', pairs: [ { de: 'als', en: 'when (one past event)', fr: 'quand (un événement passé)' }, { de: 'wenn', en: 'whenever / repeated', fr: 'chaque fois que / répété' }, { de: 'bis', en: 'until', fr: 'jusqu’à ce que' }, { de: 'seit', en: 'since (still true now)', fr: 'depuis (encore vrai)' } ], hint: 'Match each conjunction to its meaning.', hintFr: 'Associe chaque conjonction à son sens.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l20-e5', prompt: 'Listen. What has she done every day since moving to Berlin?', promptFr: 'Écoute. Que fait-elle chaque jour depuis son déménagement à Berlin ?', audio: { ttsText: 'Seit ich in Berlin wohne, lerne ich jeden Tag Deutsch.' }, options: ['Learns German', 'Goes jogging', 'Visits her family'], optionsFr: ['Elle apprend l’allemand', 'Elle fait du jogging', 'Elle rend visite à sa famille'], answer: 0, hint: 'Listen after the comma.', hintFr: 'Écoute après la virgule.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l20-e6', prompt: 'Ich warte, ___ du fertig bist.', promptFr: 'Ich warte, ___ du fertig bist.', answer: 'bis', hint: '"until" as a conjunction.', hintFr: '« jusqu’à ce que » comme conjonction.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l20-e7', prompt: 'Ich habe viele Freunde, ___ ich in Köln studiere. (short form)', promptFr: 'Ich habe viele Freunde, ___ ich in Köln studiere. (forme courte)', answer: 'seit', hint: 'Short form of seitdem — 4 letters.', hintFr: 'Forme courte de seitdem — 4 lettres.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l20-e8', tokens: ['Ich', 'hier', 'bleibe', 'bis', 'der', 'Bus', 'kommt'], answer: ['Ich', 'bleibe', 'hier', 'bis', 'der', 'Bus', 'kommt'], hint: 'Main clause first, then "bis" with the verb at the end.', hintFr: 'D’abord la principale, puis « bis » avec le verbe à la fin.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l20-e9', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Als ich zehn war, ich wohnte in Berlin.', 'Als ich zehn war, wohnte ich in Berlin.', 'Als ich war zehn, wohnte ich in Berlin.'], optionsFr: ['Als ich zehn war, ich wohnte in Berlin.', 'Als ich zehn war, wohnte ich in Berlin.', 'Als ich war zehn, wohnte ich in Berlin.'], answer: 1, explain: 'Verb last in the als-clause, then the main clause starts with its verb.', explainFr: 'Verbe à la fin dans la subordonnée en als, puis la principale commence par son verbe.', hint: 'Two checks: verb at the end of the als-clause, verb first in the main clause.', hintFr: 'Deux vérifications : verbe à la fin de la subordonnée, verbe en premier dans la principale.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l20-e10', prompt: 'Listen. How old was she when she started primary school?', promptFr: 'Écoute. Quel âge avait-elle quand elle est entrée à l’école primaire ?', audio: { ttsText: 'Als ich sechs war, bin ich in die Grundschule gekommen. Meine Lehrerin war sehr nett.' }, options: ['Six', 'Seven', 'Five'], optionsFr: ['Six ans', 'Sept ans', 'Cinq ans'], answer: 0, hint: 'Listen to the number after "Als ich".', hintFr: 'Écoute le nombre après « Als ich ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l20-e11', prompt: 'Als ich sechs ___, bin ich zur Schule gegangen. (sein → Präteritum)', promptFr: 'Als ich sechs ___, bin ich zur Schule gegangen. (sein → Präteritum)', answer: 'war', hint: 'ich-form of sein in the past.', hintFr: 'Forme « ich » de sein au passé.' } },

    { kind: 'pronunciation', focus: 'Long vowels and endings in life-story words: Abitur (stress on the last syllable), Studium, Erinnerung', focusFr: 'Voyelles longues et terminaisons dans les mots du récit de vie : Abitur (accent sur la dernière syllabe), Studium, Erinnerung', items: [
      { id: 'a2l20-abitur-pron', german: 'das Abitur', english: 'school-leaving exam', french: 'le baccalauréat', gender: 'das', syllables: ['A', 'bi', 'TUR'], pronunciation: 'dahs ah-bee-TOOR', example: { de: 'Sie hat das Abitur gemacht.', en: 'She took the Abitur.', fr: 'Elle a passé le bac.' } },
      { id: 'a2l20-studium-pron', german: 'das Studium', english: 'university studies', french: 'les études supérieures', gender: 'das', syllables: ['STU', 'di', 'um'], pronunciation: 'dahs SHTOO-dee-oom', example: { de: 'Das Studium macht mir Spaß.', en: 'I enjoy my studies.', fr: 'Mes études me plaisent.' } },
      { id: 'a2l20-erinnerung-pron', german: 'die Erinnerung', english: 'the memory', french: 'le souvenir', gender: 'die', syllables: ['er', 'IN', 'ne', 'rung'], pronunciation: 'dee er-IN-eh-roong', example: { de: 'Ich habe viele Erinnerungen an die Schulzeit.', en: 'I have many memories of my school days.', fr: 'J’ai beaucoup de souvenirs de mes années d’école.' } },
      { id: 'a2l20-seitdem-pron', german: 'seitdem', english: 'since then / since', french: 'depuis (lors)', gender: null, syllables: ['seit', 'DEM'], pronunciation: 'zite-DAME', example: { de: 'Seitdem lerne ich Deutsch.', en: 'Since then I have been learning German.', fr: 'Depuis, j’apprends l’allemand.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now tell your life story: **als** for one past event (**Als ich zehn war, …**), **wenn** for repeated events, **bis** for "until" and **seit(dem)** for "since". The verb goes to the **end** of the subordinate clause, and if that clause comes first, the main clause starts with its **verb**. 📖',
      summaryFr: 'Tu sais maintenant raconter ta vie : **als** pour un événement passé unique (**Als ich zehn war, …**), **wenn** pour les événements répétés, **bis** pour « jusqu’à ce que » et **seit(dem)** pour « depuis (que) ». Le verbe va à la **fin** de la subordonnée, et si elle vient en premier, la principale commence par son **verbe**. 📖' },
  ],
};
