import type { Lesson } from '../types';

export const a2lektion23: Lesson = {
  id: 'a2-l23', level: 'A2', module: 4, number: 16,
  title: { de: 'Welch-? Dies-? Der da!', en: 'Which? This one! That one!', fr: 'Lequel ? Celui-ci ! Celui-là !' },
  theme: 'Asking "which?" with welch-, pointing with dies- and der/die/das',
  themeFr: 'Demander « lequel ? » avec welch-, montrer avec dies- et der/die/das',
  goals: ['Ask "Welcher / Welchen / Welches / Welche …?"', 'Point at things with dieser / diese / dieses', 'Answer with a demonstrative pronoun: Den da! Die hier!', 'Choose and describe things in a shop or at the lost-property desk'],
  goalsFr: ['Demander « Welcher / Welchen / Welches / Welche … ? »', 'Montrer des objets avec dieser / diese / dieses', 'Répondre avec un pronom démonstratif : Den da ! Die hier !', 'Choisir et décrire des objets dans un magasin ou au bureau des objets trouvés'],
  steps: [
    { kind: 'intro', title: 'Welch-? Dies-? Der da! 👉', titleFr: 'Lequel ? Celui-ci ! Celui-là ! 👉',
      scene: 'Clothes shopping with a friend, and a lost-property desk: "Which scarf do you mean?" — "That one, yes exactly!"', sceneFr: 'On fait du shopping entre amis, puis on passe aux objets trouvés : « Quelle écharpe veux-tu dire ? » — « Celle-là, oui, exactement ! »',
      goals: ['Ask which one with welch-', 'Say "this" with dies-', 'Point with der/die/das + da/hier', 'Use the dative: mit welchem, bei dem da'],
      goalsFr: ['Demander lequel avec welch-', 'Dire « ce/cette » avec dies-', 'Montrer avec der/die/das + da/hier', 'Utiliser le datif : mit welchem, bei dem da'] },

    { kind: 'vocab', item: { id: 'a2l23-kleid', german: 'das Kleid', english: 'the dress', french: 'la robe', gender: 'das', syllables: ['KLEID'], pronunciation: 'dahs klite', example: { de: 'Welches Kleid gefällt dir?', en: 'Which dress do you like?', fr: 'Quelle robe te plaît ?' } } },
    { kind: 'vocab', item: { id: 'a2l23-schal', german: 'der Schal', english: 'the scarf', french: 'l’écharpe', gender: 'der', syllables: ['SCHAL'], pronunciation: 'dair shahl', example: { de: 'Dieser Schal ist warm und weich.', en: 'This scarf is warm and soft.', fr: 'Cette écharpe est chaude et douce.' } } },
    { kind: 'vocab', item: { id: 'a2l23-muetze', german: 'die Mütze', english: 'the cap / hat', french: 'le bonnet / la casquette', gender: 'die', syllables: ['MÜT', 'ze'], pronunciation: 'dee MUET-seh', example: { de: 'Im Winter trage ich eine Mütze.', en: 'In winter I wear a hat.', fr: 'En hiver, je porte un bonnet.' } } },
    { kind: 'vocab', item: { id: 'a2l23-regenschirm', german: 'der Regenschirm', english: 'the umbrella', french: 'le parapluie', gender: 'der', syllables: ['RE', 'gen', 'schirm'], pronunciation: 'dair RAY-gen-sheerm', example: { de: 'Ich brauche einen Regenschirm.', en: 'I need an umbrella.', fr: 'J’ai besoin d’un parapluie.' } } },
    { kind: 'vocab', item: { id: 'a2l23-brille', german: 'die Brille', english: 'the glasses', french: 'les lunettes', gender: 'die', syllables: ['BRIL', 'le'], pronunciation: 'dee BRILL-eh', example: { de: 'Meine Brille liegt auf dem Tisch.', en: 'My glasses are on the table.', fr: 'Mes lunettes sont sur la table.' } } },
    { kind: 'vocab', item: { id: 'a2l23-schluessel', german: 'der Schlüssel', english: 'the key', french: 'la clé', gender: 'der', syllables: ['SCHLÜS', 'sel'], pronunciation: 'dair SHLUESS-el', example: { de: 'Wo ist mein Schlüssel?', en: 'Where is my key?', fr: 'Où est ma clé ?' } } },
    { kind: 'vocab', item: { id: 'a2l23-ausweis', german: 'der Ausweis', english: 'the ID card', french: 'la carte d’identité / la pièce d’identité', gender: 'der', syllables: ['AUS', 'weis'], pronunciation: 'dair OWSS-vise', example: { de: 'Haben Sie Ihren Ausweis dabei?', en: 'Do you have your ID with you?', fr: 'Avez-vous votre pièce d’identité sur vous ?' } } },
    { kind: 'vocab', item: { id: 'a2l23-verkaeuferin', german: 'die Verkäuferin', english: 'the shop assistant (f)', french: 'la vendeuse', gender: 'die', syllables: ['Ver', 'KÄU', 'fe', 'rin'], pronunciation: 'dee fair-KOY-feh-rin', example: { de: 'Die Verkäuferin zeigt mir drei Hosen.', en: 'The shop assistant shows me three pairs of trousers.', fr: 'La vendeuse me montre trois pantalons.' } } },
    { kind: 'vocab', item: { id: 'a2l23-aussuchen', german: 'aussuchen', english: 'to choose / pick out', french: 'choisir', gender: null, syllables: ['AUS', 'su', 'chen'], pronunciation: 'OWSS-zoo-khen', example: { de: 'Such dir eine Farbe aus!', en: 'Pick a colour!', fr: 'Choisis une couleur !' } } },
    { kind: 'vocab', item: { id: 'a2l23-anprobieren', german: 'anprobieren', english: 'to try on', french: 'essayer (un vêtement)', gender: null, syllables: ['AN', 'pro', 'bie', 'ren'], pronunciation: 'AHN-pro-bee-ren', example: { de: 'Darf ich die Jacke anprobieren?', en: 'May I try on the jacket?', fr: 'Puis-je essayer la veste ?' } } },
    { kind: 'vocab', item: { id: 'a2l23-meinen', german: 'meinen', english: 'to mean / to be talking about', french: 'vouloir dire / parler de', gender: null, syllables: ['MEI', 'nen'], pronunciation: 'MY-nen', example: { de: 'Welche Tasche meinst du?', en: 'Which bag do you mean?', fr: 'De quel sac parles-tu ?' } } },
    { kind: 'vocab', item: { id: 'a2l23-genau', german: 'genau', english: 'exactly', french: 'exactement', gender: null, syllables: ['ge', 'NAU'], pronunciation: 'ge-NOW', example: { de: 'Ja genau, den meine ich!', en: 'Yes exactly, that’s the one I mean!', fr: 'Oui, exactement, c’est celui-là que je veux dire !' } } },
    { kind: 'vocab', item: { id: 'a2l23-welcher', german: 'welcher / welche / welches', english: 'which', french: 'quel / quelle / quels', gender: null, syllables: ['WEL', 'cher'], pronunciation: 'VELL-kher', example: { de: 'Welcher Schal gefällt dir?', en: 'Which scarf do you like?', fr: 'Quelle écharpe te plaît ?' } } },
    { kind: 'vocab', item: { id: 'a2l23-dieser', german: 'dieser / diese / dieses', english: 'this / these', french: 'ce / cette / ces', gender: null, syllables: ['DIE', 'ser'], pronunciation: 'DEE-zer', example: { de: 'Dieses Kleid ist mir zu teuer.', en: 'This dress is too expensive for me.', fr: 'Cette robe est trop chère pour moi.' } } },

    { kind: 'grammar', note: {
      id: 'a2l23-welch', title: 'Asking "which?" with welch-', titleFr: 'Demander « lequel ? » avec welch-',
      explanationMd: '**welch-** is a question word that stands **before a noun**. It takes the same endings as **der / die / das**:\n\n- masc: **welcher** Schal (nom) · **welchen** Schal (acc) · mit **welchem** Schal (dat)\n- fem: **welche** Jacke (nom) · **welche** Jacke (acc) · mit **welcher** Jacke (dat)\n- neut: **welches** Kleid (nom) · **welches** Kleid (acc) · mit **welchem** Kleid (dat)\n- plural: **welche** Schuhe (nom/acc) · mit **welchen** Schuhen (dat)\n\nThe case depends on the job of the noun in the sentence. In **Welches Kleid gefällt dir?** the dress is the **subject** (nominative) and "dir" is the dative person (gefallen). In **Welchen Schal nimmst du?** the scarf is the **object** (accusative).',
      explanationMdFr: '**welch-** est un mot interrogatif placé **devant un nom**. Il prend les mêmes terminaisons que **der / die / das** :\n\n- masc : **welcher** Schal (nom) · **welchen** Schal (acc) · mit **welchem** Schal (dat)\n- fém : **welche** Jacke (nom) · **welche** Jacke (acc) · mit **welcher** Jacke (dat)\n- neutre : **welches** Kleid (nom) · **welches** Kleid (acc) · mit **welchem** Kleid (dat)\n- pluriel : **welche** Schuhe (nom/acc) · mit **welchen** Schuhen (dat)\n\nLe cas dépend de la fonction du nom dans la phrase. Dans **Welches Kleid gefällt dir?**, la robe est le **sujet** (nominatif) et « dir » est la personne au datif (gefallen). Dans **Welchen Schal nimmst du?**, l’écharpe est le **complément d’objet** (accusatif).',
      examples: [
        { de: 'Welches Kleid gefällt dir?', en: 'Which dress do you like?', fr: 'Quelle robe te plaît ?' },
        { de: 'Welchen Schal nimmst du?', en: 'Which scarf are you taking?', fr: 'Quelle écharpe prends-tu ?' },
        { de: 'Mit welchem Bus fährst du nach Hause?', en: 'Which bus do you take home?', fr: 'Avec quel bus rentres-tu ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l23-dies', title: 'Pointing with dies-', titleFr: 'Montrer avec dies-',
      explanationMd: '**dies-** ("this / these") is declined **exactly like welch-**:\n\n- masc: **dieser** Schal · **diesen** Schal · mit **diesem** Schal\n- fem: **diese** Jacke · **diese** Jacke · mit **dieser** Jacke\n- neut: **dieses** Kleid · **dieses** Kleid · mit **diesem** Kleid\n- plural: **diese** Schuhe · **diese** Schuhe · mit **diesen** Schuhen\n\nSo the answer to "Welchen Schal?" can be "**Diesen** Schal." In everyday speech, people also say **der Schal hier** ("this scarf here") or **der Schal da** ("that scarf there").',
      explanationMdFr: '**dies-** (« ce / cette / ces ») se décline **exactement comme welch-** :\n\n- masc : **dieser** Schal · **diesen** Schal · mit **diesem** Schal\n- fém : **diese** Jacke · **diese** Jacke · mit **dieser** Jacke\n- neutre : **dieses** Kleid · **dieses** Kleid · mit **diesem** Kleid\n- pluriel : **diese** Schuhe · **diese** Schuhe · mit **diesen** Schuhen\n\nLa réponse à « Welchen Schal ? » peut donc être « **Diesen** Schal. » À l’oral, on dit aussi **der Schal hier** (« cette écharpe-ci ») ou **der Schal da** (« cette écharpe-là »).',
      examples: [
        { de: 'Diesen Schal nehme ich.', en: 'I’ll take this scarf.', fr: 'Je prends cette écharpe.' },
        { de: 'Dieses Kleid ist schön, aber die Hose da gefällt mir besser.', en: 'This dress is nice, but I like the trousers over there better.', fr: 'Cette robe est belle, mais le pantalon là-bas me plaît davantage.' },
        { de: 'In diesem Geschäft ist alles billiger.', en: 'In this shop everything is cheaper.', fr: 'Dans ce magasin, tout est moins cher.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l23-demonstrativ', title: 'Der da! Demonstrative pronouns', titleFr: 'Der da ! Les pronoms démonstratifs',
      explanationMd: 'When the noun is clear, don’t repeat it: use **der / die / das** as a **pronoun** — spoken with stress, often with **da** (there) or **hier** (here):\n\n- Nominative: **der** · **die** · **das** · **die** (plural)\n- Accusative: **den** · **die** · **das** · **die**\n- Dative: **dem** · **der** · **dem** · **denen** (plural!)\n\nOnly the **dative plural** differs from the article: **denen**.\n\n— Welchen Schal meinst du? — **Den** da!\n— Ja genau, **den** meine ich.\n\nThe pronoun often stands in **first position**: **Die** finde ich toll. (verb stays second)',
      explanationMdFr: 'Quand le nom est clair, ne le répète pas : utilise **der / die / das** comme **pronom** — prononcé avec insistance, souvent avec **da** (là) ou **hier** (ici) :\n\n- Nominatif : **der** · **die** · **das** · **die** (pluriel)\n- Accusatif : **den** · **die** · **das** · **die**\n- Datif : **dem** · **der** · **dem** · **denen** (pluriel !)\n\nSeul le **datif pluriel** diffère de l’article : **denen**.\n\n— Welchen Schal meinst du ? — **Den** da !\n— Ja genau, **den** meine ich.\n\nLe pronom se place souvent en **première position** : **Die** finde ich toll. (le verbe reste en deuxième position)',
      examples: [
        { de: 'Welchen Regenschirm brauchst du? — Den da!', en: 'Which umbrella do you need? — That one there!', fr: 'De quel parapluie as-tu besoin ? — Celui-là !' },
        { de: 'Welche Mütze? Die hier? — Nein, die da.', en: 'Which hat? This one here? — No, the one there.', fr: 'Quel bonnet ? Celui-ci ? — Non, celui-là.' },
        { de: 'Welchen Kindern hilfst du? — Denen da.', en: 'Which children are you helping? — Those over there.', fr: 'Quels enfants aides-tu ? — Ceux-là.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l23-e1', prompt: '___ Kleid gefällt dir? (welch-, das Kleid, nominative)', promptFr: '___ Kleid gefällt dir ? (welch-, das Kleid, nominatif)', answer: 'Welches', hint: 'Neuter nominative: welches', hintFr: 'Neutre au nominatif : welches' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l23-e2', prompt: 'Ich nehme ___ Schal. (dieser, der Schal, accusative)', promptFr: 'Ich nehme ___ Schal. (dieser, accusatif) — « Je prends cette écharpe. »', answer: 'diesen', hint: 'Masculine accusative: dieser → diesen', hintFr: 'Masculin à l’accusatif : dieser → diesen' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l23-e3', prompt: '___ Schal meinst du? (the scarf is the object)', promptFr: '___ Schal meinst du ? (l’écharpe est le complément d’objet)', options: ['Welcher', 'Welchen', 'Welches'], answer: 1, explain: 'Masculine accusative: welcher → welchen.', explainFr: 'Masculin à l’accusatif : welcher → welchen.', hint: 'Der Schal is masculine; it is the object of "meinen".', hintFr: 'Der Schal est masculin ; c’est le complément de « meinen ».' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l23-e4', pairs: [ { de: 'die Brille', en: 'the glasses', fr: 'les lunettes' }, { de: 'der Schlüssel', en: 'the key', fr: 'la clé' }, { de: 'der Ausweis', en: 'the ID card', fr: 'la pièce d’identité' }, { de: 'die Mütze', en: 'the cap', fr: 'le bonnet' } ], hint: 'Match each object to its meaning.', hintFr: 'Associe chaque objet à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l23-e5', prompt: 'Listen. Which jacket does she mean?', promptFr: 'Écoute. De quelle veste parle-t-elle ?', audio: { ttsText: 'Welche Jacke meinst du? Die blaue? Nein, die schwarze da.' }, options: ['The blue one', 'The black one', 'The red one'], optionsFr: ['La bleue', 'La noire', 'La rouge'], answer: 1, hint: 'Listen to the answer after "Nein".', hintFr: 'Écoute la réponse après « Nein ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l23-e6', prompt: 'Welchen Regenschirm brauchst du? — ___ da.', promptFr: 'De quel parapluie as-tu besoin ? — ___ da.', options: ['Der', 'Den', 'Dem'], answer: 1, explain: 'Masculine accusative as a pronoun: den.', explainFr: 'Masculin à l’accusatif comme pronom : den.', hint: 'The same case as "Welchen".', hintFr: 'Le même cas que « Welchen ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l23-e7', tokens: ['Kleid', 'gefällt', 'Welches', 'dir'], answer: ['Welches', 'Kleid', 'gefällt', 'dir'], hint: 'Question word + noun first, then the verb, then "dir".', hintFr: 'Mot interrogatif + nom d’abord, puis le verbe, puis « dir ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l23-e8', prompt: 'Mit ___ Bus fährst du zur Arbeit? (welch-, der Bus, dative)', promptFr: 'Mit ___ Bus fährst du zur Arbeit? (welch-, datif) — « Avec quel bus vas-tu au travail ? »', answer: 'welchem', hint: 'mit + dative: welcher → welchem', hintFr: 'mit + datif : welcher → welchem' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l23-e9', prompt: 'Listen. Which glasses does she take?', promptFr: 'Écoute. Quelles lunettes prend-elle ?', audio: { ttsText: 'Ich nehme diese Brille, nicht die da.' }, options: ['The pair close to her', 'The pair over there', 'Both pairs'], optionsFr: ['Celles qui sont près d’elle', 'Celles qui sont là-bas', 'Les deux paires'], answer: 0, hint: '"diese" = this one; "die da" = that one there.', hintFr: '« diese » = celle-ci ; « die da » = celle-là.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l23-e10', word: 'Kleid', answer: 'das', hint: 'Learn it with its article: das Kleid.', hintFr: 'À apprendre avec son article : das Kleid.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l23-e11', prompt: 'Welchen Kindern hilfst du? — ___ da.', promptFr: 'Quels enfants aides-tu ? — ___ da.', options: ['Die', 'Denen', 'Den'], answer: 1, explain: 'helfen takes the dative; the dative plural pronoun is "denen".', explainFr: 'helfen se construit avec le datif ; le pronom au datif pluriel est « denen ».', hint: 'Dative plural: only this form is special.', hintFr: 'Datif pluriel : c’est la seule forme particulière.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l23-e12', prompt: 'Welche Hose? — ___ da! (die Hose, accusative pronoun)', promptFr: 'Quel pantalon ? — ___ da ! (die Hose, pronom à l’accusatif)', answer: 'Die', hint: 'Feminine accusative = nominative: die', hintFr: 'Féminin : accusatif = nominatif : die' } },

    { kind: 'pronunciation', focus: 'Stress and the ch in welch- (soft "kh"), and ü in Mütze / Schlüssel', focusFr: 'L’accent et le ch de welch- (« kh » doux), et le ü de Mütze / Schlüssel', items: [
      { id: 'a2l23-welchen-pron', german: 'welchen', english: 'which (masc., accusative)', french: 'quel (masc., accusatif)', gender: null, syllables: ['WEL', 'chen'], pronunciation: 'VELL-khen', example: { de: 'Welchen Schal nimmst du?', en: 'Which scarf are you taking?', fr: 'Quelle écharpe prends-tu ?' } },
      { id: 'a2l23-diesen-pron', german: 'diesen', english: 'this (masc., accusative)', french: 'ce (masc., accusatif)', gender: null, syllables: ['DIE', 'sen'], pronunciation: 'DEE-zen', example: { de: 'Diesen nehme ich.', en: 'I’ll take this one.', fr: 'Je prends celui-ci.' } },
      { id: 'a2l23-muetze-pron', german: 'die Mütze', english: 'the cap', french: 'le bonnet', gender: 'die', syllables: ['MÜT', 'ze'], pronunciation: 'dee MUET-seh', example: { de: 'Die Mütze da ist schön.', en: 'That cap there is nice.', fr: 'Ce bonnet-là est joli.' } },
      { id: 'a2l23-schluessel-pron', german: 'der Schlüssel', english: 'the key', french: 'la clé', gender: 'der', syllables: ['SCHLÜS', 'sel'], pronunciation: 'dair SHLUESS-el', example: { de: 'Den Schlüssel meine ich.', en: 'That’s the key I mean.', fr: 'C’est cette clé que je veux dire.' } },
    ] },

    { kind: 'wrapup', summary: 'To ask "which?", use **welch-** (welcher, welchen, welches, welche, welchem …). To say "this", use **dies-** with the same endings. To point without repeating the noun, use the stressed pronouns **der / den / dem / die / das / denen**: **Welchen Schal meinst du? — Den da!** 👉',
      summaryFr: 'Pour demander « lequel ? », utilise **welch-** (welcher, welchen, welches, welche, welchem …). Pour dire « ce/cette », utilise **dies-** avec les mêmes terminaisons. Pour montrer sans répéter le nom, utilise les pronoms accentués **der / den / dem / die / das / denen** : **Welchen Schal meinst du ? — Den da !** 👉' },
  ],
};
