import type { Lesson } from '../types';

export const a2lektion24: Lesson = {
  id: 'a2-l24', level: 'A2', module: 6, number: 23,
  title: { de: 'Erzählen im Präteritum', en: 'Telling a story in the past', fr: 'Raconter au prétérit' },
  theme: 'The Präteritum of regular and irregular verbs, and story connectors',
  themeFr: 'Le prétérit des verbes réguliers et irréguliers, et les connecteurs du récit',
  goals: ['Form the Präteritum of regular verbs (lebte, arbeitete)', 'Learn common irregular forms (kam, ging, sah, gab, fand)', 'Tell a story with zuerst, dann, danach, später, plötzlich', 'Write a short report about life abroad'],
  goalsFr: ['Former le prétérit des verbes réguliers (lebte, arbeitete)', 'Apprendre les formes irrégulières courantes (kam, ging, sah, gab, fand)', 'Raconter avec zuerst, dann, danach, später, plötzlich', 'Rédiger un court récit sur la vie à l’étranger'],
  steps: [
    { kind: 'intro', title: 'Es war einmal … 📖', titleFr: 'Il était une fois… 📖',
      scene: 'Amina tells her story: she lived in Yaoundé, came to Germany, found a job and, suddenly, met an old friend at the station.', sceneFr: 'Amina raconte son histoire : elle vivait à Yaoundé, est venue en Allemagne, a trouvé un travail et, soudain, a retrouvé une vieille amie à la gare.',
      goals: ['Use the Präteritum in stories and reports', 'Form regular verbs: stem + -te', 'Know the key irregular verbs by heart', 'Link events with dann, danach, später, plötzlich'],
      goalsFr: ['Utiliser le prétérit dans les récits et les comptes rendus', 'Former les verbes réguliers : radical + -te', 'Connaître par cœur les principaux verbes irréguliers', 'Enchaîner les événements avec dann, danach, später, plötzlich'] },

    { kind: 'vocab', item: { id: 'a2l24-sagen', german: 'sagen – sagte', english: 'to say – said', french: 'dire – dit', gender: null, syllables: ['SA', 'gen'], pronunciation: 'ZAH-gen', example: { de: 'Sie sagte: „Guten Morgen!“', en: 'She said, “Good morning!”', fr: 'Elle dit : « Bonjour ! »' } } },
    { kind: 'vocab', item: { id: 'a2l24-kommen', german: 'kommen – kam', english: 'to come – came', french: 'venir – vint', gender: null, syllables: ['KOM', 'men'], pronunciation: 'KOM-men', example: { de: 'Er kam um acht Uhr nach Hause.', en: 'He came home at eight o’clock.', fr: 'Il rentra à la maison à huit heures.' } } },
    { kind: 'vocab', item: { id: 'a2l24-geben', german: 'geben – gab', english: 'to give – gave', french: 'donner – donna', gender: null, syllables: ['GE', 'ben'], pronunciation: 'GAY-ben', example: { de: 'Die Lehrerin gab uns Hausaufgaben.', en: 'The teacher gave us homework.', fr: 'La professeure nous donna des devoirs.' } } },
    { kind: 'vocab', item: { id: 'a2l24-finden', german: 'finden – fand', english: 'to find – found', french: 'trouver – trouva', gender: null, syllables: ['FIN', 'den'], pronunciation: 'FIN-den', example: { de: 'Ich fand einen Job in Wien.', en: 'I found a job in Vienna.', fr: 'Je trouvai un travail à Vienne.' } } },
    { kind: 'vocab', item: { id: 'a2l24-sehen', german: 'sehen – sah', english: 'to see – saw', french: 'voir – vit', gender: null, syllables: ['SE', 'hen'], pronunciation: 'ZAY-hen', example: { de: 'Am Bahnhof sah ich meinen Bruder.', en: 'At the station I saw my brother.', fr: 'À la gare, je vis mon frère.' } } },
    { kind: 'vocab', item: { id: 'a2l24-gehen', german: 'gehen – ging', english: 'to go – went', french: 'aller – alla', gender: null, syllables: ['GE', 'hen'], pronunciation: 'GAY-hen', example: { de: 'Wir gingen zusammen zum Markt.', en: 'We went to the market together.', fr: 'Nous allâmes ensemble au marché.' } } },
    { kind: 'vocab', item: { id: 'a2l24-leben', german: 'leben – lebte', english: 'to live – lived', french: 'vivre – vécut', gender: null, syllables: ['LE', 'ben'], pronunciation: 'LAY-ben', example: { de: 'Er lebte drei Jahre in Kanada.', en: 'He lived in Canada for three years.', fr: 'Il vécut trois ans au Canada.' } } },
    { kind: 'vocab', item: { id: 'a2l24-arbeiten', german: 'arbeiten – arbeitete', english: 'to work – worked', french: 'travailler – travailla', gender: null, syllables: ['AR', 'bei', 'ten'], pronunciation: 'AR-by-ten', example: { de: 'Sie arbeitete als Krankenschwester.', en: 'She worked as a nurse.', fr: 'Elle travaillait comme infirmière.' } } },
    { kind: 'vocab', item: { id: 'a2l24-ploetzlich', german: 'plötzlich', english: 'suddenly', french: 'soudain', gender: null, syllables: ['PLÖTZ', 'lich'], pronunciation: 'PLOETS-likh', example: { de: 'Plötzlich klingelte das Telefon.', en: 'Suddenly the phone rang.', fr: 'Soudain, le téléphone sonna.' } } },
    { kind: 'vocab', item: { id: 'a2l24-danach', german: 'danach', english: 'afterwards', french: 'ensuite / après', gender: null, syllables: ['da', 'NACH'], pronunciation: 'dah-NAHKH', example: { de: 'Danach gingen wir essen.', en: 'Afterwards we went to eat.', fr: 'Ensuite, nous sommes allés manger.' } } },
    { kind: 'vocab', item: { id: 'a2l24-spaeter', german: 'später', english: 'later', french: 'plus tard', gender: null, syllables: ['SPÄ', 'ter'], pronunciation: 'SHPAY-ter', example: { de: 'Später fand sie eine Wohnung.', en: 'Later she found a flat.', fr: 'Plus tard, elle trouva un appartement.' } } },
    { kind: 'vocab', item: { id: 'a2l24-zuerst', german: 'zuerst', english: 'first (of all)', french: 'd’abord', gender: null, syllables: ['zu', 'ERST'], pronunciation: 'tsoo-AIRST', example: { de: 'Zuerst lebte ich in Douala.', en: 'First I lived in Douala.', fr: 'D’abord, je vivais à Douala.' } } },
    { kind: 'vocab', item: { id: 'a2l24-schliesslich', german: 'schließlich', english: 'finally / in the end', french: 'finalement', gender: null, syllables: ['SCHLIESS', 'lich'], pronunciation: 'SHLEESS-likh', example: { de: 'Schließlich bekam er ein Visum.', en: 'In the end he got a visa.', fr: 'Finalement, il obtint un visa.' } } },
    { kind: 'vocab', item: { id: 'a2l24-visum', german: 'das Visum', english: 'the visa', french: 'le visa', gender: 'das', syllables: ['VI', 'sum'], pronunciation: 'dahs VEE-zoom', example: { de: 'Sie brauchte ein Visum für Deutschland.', en: 'She needed a visa for Germany.', fr: 'Elle avait besoin d’un visa pour l’Allemagne.' } } },

    { kind: 'grammar', note: {
      id: 'a2l24-regelmaessig', title: 'Regular verbs: stem + -te', titleFr: 'Verbes réguliers : radical + -te',
      explanationMd: 'Regular verbs add **-te** to the stem, then the personal ending:\n\n- leben → ich **lebte**, du **lebtest**, er/sie/es **lebte**, wir **lebten**, ihr **lebtet**, sie **lebten**\n\nThe shortcut: **ich** and **er/sie/es** are **identical** and have no ending.\n\nStems ending in **-t / -d** (and many in -n, -m) add **-ete** so you can still pronounce them: arbeiten → **arbeitete**, warten → **wartete**, öffnen → **öffnete**.',
      explanationMdFr: 'Les verbes réguliers ajoutent **-te** au radical, puis la terminaison de la personne :\n\n- leben → ich **lebte**, du **lebtest**, er/sie/es **lebte**, wir **lebten**, ihr **lebtet**, sie **lebten**\n\nLe raccourci : **ich** et **er/sie/es** sont **identiques** et sans terminaison.\n\nLes radicaux en **-t / -d** (et beaucoup en -n, -m) ajoutent **-ete** pour rester prononçables : arbeiten → **arbeitete**, warten → **wartete**, öffnen → **öffnete**.',
      examples: [
        { de: 'Ich arbeitete drei Jahre in Lyon.', en: 'I worked in Lyon for three years.', fr: 'J’ai travaillé trois ans à Lyon.' },
        { de: 'Wir wohnten in einer kleinen Wohnung.', en: 'We lived in a small flat.', fr: 'Nous habitions un petit appartement.' },
        { de: 'Er wartete eine Stunde am Flughafen.', en: 'He waited an hour at the airport.', fr: 'Il attendit une heure à l’aéroport.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l24-unregelmaessig', title: 'Irregular verbs: a new stem, no -te', titleFr: 'Verbes irréguliers : un nouveau radical, pas de -te',
      explanationMd: 'Irregular (strong) verbs **change the stem vowel** and have **no -te**. Again, **ich** and **er/sie/es** have no ending:\n\n- kommen → ich **kam**, du **kamst**, er **kam**, wir **kamen**, ihr **kamt**, sie **kamen**\n\nLearn the common ones as pairs (infinitive → Präteritum):\n\n- gehen → **ging** · sehen → **sah** · geben → **gab** · finden → **fand**\n- bleiben → **blieb** · fahren → **fuhr** · schreiben → **schrieb** · sprechen → **sprach**\n- nehmen → **nahm** · essen → **aß** · stehen → **stand**\n\nAnd your old friends: sein → **war**, haben → **hatte**. A few verbs mix both: denken → **dachte**, bringen → **brachte**, wissen → **wusste**.',
      explanationMdFr: 'Les verbes irréguliers (forts) **changent la voyelle du radical** et n’ont **pas de -te**. Là aussi, **ich** et **er/sie/es** sont sans terminaison :\n\n- kommen → ich **kam**, du **kamst**, er **kam**, wir **kamen**, ihr **kamt**, sie **kamen**\n\nApprends les plus courants par paires (infinitif → prétérit) :\n\n- gehen → **ging** · sehen → **sah** · geben → **gab** · finden → **fand**\n- bleiben → **blieb** · fahren → **fuhr** · schreiben → **schrieb** · sprechen → **sprach**\n- nehmen → **nahm** · essen → **aß** · stehen → **stand**\n\nEt tes vieux amis : sein → **war**, haben → **hatte**. Quelques verbes mélangent les deux : denken → **dachte**, bringen → **brachte**, wissen → **wusste**.',
      examples: [
        { de: 'Sie gab mir ein Geschenk.', en: 'She gave me a present.', fr: 'Elle me donna un cadeau.' },
        { de: 'Wir fanden ein günstiges Hotel.', en: 'We found a cheap hotel.', fr: 'Nous trouvâmes un hôtel bon marché.' },
        { de: 'Er hatte kein Visum, aber er blieb ruhig.', en: 'He had no visa, but he stayed calm.', fr: 'Il n’avait pas de visa, mais il resta calme.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l24-erzaehlen', title: 'Telling a story: connectors and word order', titleFr: 'Raconter : connecteurs et ordre des mots',
      explanationMd: 'For **stories, reports and biographies** (especially in writing), German uses the **Präteritum**. In everyday speech you still prefer the Perfekt for most verbs (see "Früher war das anders").\n\nBuild the story with time words: **zuerst, dann, danach, später, plötzlich, schließlich**. They take **position 1**, so the verb comes **second**, then the subject:\n\n- **Dann kam** sie nach Deutschland.\n- **Plötzlich sah** ich meinen Bruder.\n\n**Separable verbs:** in the Präteritum the prefix goes to the **end**: aufstehen → Ich **stand** um sechs Uhr **auf**. · ankommen → Sie **kam** spät **an**.',
      explanationMdFr: 'Pour les **récits, comptes rendus et biographies** (surtout à l’écrit), l’allemand utilise le **prétérit**. À l’oral, on préfère encore le Perfekt pour la plupart des verbes (voir « Früher war das anders »).\n\nConstruis le récit avec des mots de temps : **zuerst, dann, danach, später, plötzlich, schließlich**. Ils occupent la **position 1**, donc le verbe vient **en deuxième**, puis le sujet :\n\n- **Dann kam** sie nach Deutschland.\n- **Plötzlich sah** ich meinen Bruder.\n\n**Verbes à particule :** au prétérit, la particule va **à la fin** : aufstehen → Ich **stand** um sechs Uhr **auf**. · ankommen → Sie **kam** spät **an**.',
      examples: [
        { de: 'Zuerst lebte Amina in Yaoundé. Dann kam sie nach Deutschland.', en: 'First Amina lived in Yaoundé. Then she came to Germany.', fr: 'D’abord, Amina vivait à Yaoundé. Puis elle vint en Allemagne.' },
        { de: 'Später arbeitete sie in einem Hotel. Schließlich fand sie eine Wohnung.', en: 'Later she worked in a hotel. In the end she found a flat.', fr: 'Plus tard, elle travailla dans un hôtel. Finalement, elle trouva un appartement.' },
        { de: 'Ich stand um sechs Uhr auf und fuhr zur Arbeit.', en: 'I got up at six and drove to work.', fr: 'Je me levai à six heures et partis au travail.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l24-e1', prompt: 'Er ___ 2015 nach Deutschland. (kommen, Präteritum)', promptFr: 'Er ___ 2015 nach Deutschland. (kommen, prétérit)', answer: 'kam', hint: 'Irregular: kommen → kam', hintFr: 'Irrégulier : kommen → kam' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l24-e2', prompt: 'Sie ___ zwei Jahre in Wien. (leben, Präteritum)', promptFr: 'Sie ___ zwei Jahre in Wien. (leben, prétérit)', answer: 'lebte', hint: 'Regular: stem leb- + -te', hintFr: 'Régulier : radical leb- + -te' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l24-e3', prompt: 'Wir ___ sofort ein Hotel. (finden, Präteritum)', promptFr: 'Wir ___ sofort ein Hotel. (finden, prétérit)', answer: 'fanden', hint: 'finden → fand; wir → fanden', hintFr: 'finden → fand ; wir → fanden' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l24-e4', pairs: [ { de: 'ging', en: 'gehen (to go)', fr: 'gehen (aller)' }, { de: 'sah', en: 'sehen (to see)', fr: 'sehen (voir)' }, { de: 'gab', en: 'geben (to give)', fr: 'geben (donner)' }, { de: 'fand', en: 'finden (to find)', fr: 'finden (trouver)' } ], hint: 'Match each Präteritum form to its infinitive.', hintFr: 'Associe chaque forme du prétérit à son infinitif.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l24-e5', prompt: 'What is "ich" in the Präteritum of "arbeiten"?', promptFr: 'Quelle est la forme de « ich » au prétérit de « arbeiten » ?', options: ['arbeitte', 'arbeitete', 'arbeite'], answer: 1, explain: 'The stem ends in -t, so we add -ete: arbeitete.', explainFr: 'Le radical se termine par -t, on ajoute donc -ete : arbeitete.', hint: 'Stems in -t need an extra -e-.', hintFr: 'Les radicaux en -t prennent un -e- supplémentaire.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l24-e6', prompt: 'Listen. What did Amina do later?', promptFr: 'Écoute. Que fit Amina plus tard ?', audio: { ttsText: 'Zuerst lebte Amina in Yaoundé. Dann kam sie nach Deutschland. Später arbeitete sie in einem Hotel.' }, options: ['She worked in a hotel', 'She lived in Yaoundé', 'She studied in Berlin'], optionsFr: ['Elle travailla dans un hôtel', 'Elle vivait à Yaoundé', 'Elle étudia à Berlin'], answer: 0, hint: 'Listen after "Später".', hintFr: 'Écoute après « Später ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l24-e7', tokens: ['sah', 'Plötzlich', 'ich', 'meinen', 'Bruder'], answer: ['Plötzlich', 'sah', 'ich', 'meinen', 'Bruder'], hint: 'The connector is in position 1, so the verb comes second.', hintFr: 'Le connecteur est en position 1, donc le verbe vient en deuxième.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l24-e8', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Ich gehte nach Hause.', 'Ich ging nach Hause.', 'Ich gang nach Hause.'], answer: 1, explain: 'gehen is irregular: ging.', explainFr: 'gehen est irrégulier : ging.', hint: 'gehen does not add -te.', hintFr: 'gehen n’ajoute pas -te.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l24-e9', prompt: 'Listen. What did the speaker do after getting up?', promptFr: 'Écoute. Que fit le locuteur après s’être levé ?', audio: { ttsText: 'Ich stand um sechs Uhr auf, dann fuhr ich zur Arbeit.' }, options: ['Drove to work', 'Ate breakfast', 'Went back to sleep'], optionsFr: ['Il alla au travail', 'Il prit son petit-déjeuner', 'Il se recoucha'], answer: 0, hint: 'Listen after "dann".', hintFr: 'Écoute après « dann ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l24-e10', tokens: ['stand', 'Ich', 'auf', 'um', 'sechs', 'Uhr'], answer: ['Ich', 'stand', 'um', 'sechs', 'Uhr', 'auf'], hint: 'The separable prefix "auf" goes to the end.', hintFr: 'La particule séparable « auf » va à la fin.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l24-e11', prompt: 'Which word means "suddenly"?', promptFr: 'Quel mot signifie « soudain » ?', options: ['danach', 'plötzlich', 'schließlich'], answer: 1, explain: 'plötzlich = suddenly; danach = afterwards; schließlich = finally.', explainFr: 'plötzlich = soudain ; danach = ensuite ; schließlich = finalement.', hint: 'Think of a surprise.', hintFr: 'Pense à une surprise.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l24-e12', prompt: 'Er ___ kein Visum. (haben, Präteritum)', promptFr: 'Er ___ kein Visum. (haben, prétérit)', answer: 'hatte', hint: 'haben → hatte', hintFr: 'haben → hatte' } },

    { kind: 'pronunciation', focus: 'Vowel length in irregular forms: long in kam, sah, gab — short in ging, fand', focusFr: 'Longueur des voyelles dans les formes irrégulières : longues dans kam, sah, gab — courtes dans ging, fand', items: [
      { id: 'a2l24-kam-pron', german: 'kam', english: 'came', french: 'vint', gender: null, syllables: ['KAM'], pronunciation: 'kahm (long a)', example: { de: 'Er kam spät.', en: 'He came late.', fr: 'Il arriva tard.' } },
      { id: 'a2l24-sah-pron', german: 'sah', english: 'saw', french: 'vit', gender: null, syllables: ['SAH'], pronunciation: 'zah (long a)', example: { de: 'Ich sah einen Film.', en: 'I saw a film.', fr: 'Je vis un film.' } },
      { id: 'a2l24-ging-pron', german: 'ging', english: 'went', french: 'alla', gender: null, syllables: ['GING'], pronunciation: 'ging (short i)', example: { de: 'Sie ging nach Hause.', en: 'She went home.', fr: 'Elle rentra chez elle.' } },
      { id: 'a2l24-fand-pron', german: 'fand', english: 'found', french: 'trouva', gender: null, syllables: ['FAND'], pronunciation: 'fahnt (short a, final d sounds like t)', example: { de: 'Wir fanden ein Café.', en: 'We found a café.', fr: 'Nous trouvâmes un café.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now tell a story in the past. **Regular verbs** add **-te** (lebte, arbeitete), **irregular verbs** change the stem (kam, ging, sah, gab, fand), and **ich / er/sie/es** never take an ending. Link events with **zuerst, dann, danach, später, plötzlich, schließlich** — verb second! 🎉',
      summaryFr: 'Tu sais maintenant raconter une histoire au passé. Les **verbes réguliers** ajoutent **-te** (lebte, arbeitete), les **verbes irréguliers** changent de radical (kam, ging, sah, gab, fand), et **ich / er/sie/es** n’ont jamais de terminaison. Enchaîne les événements avec **zuerst, dann, danach, später, plötzlich, schließlich** — verbe en deuxième position ! 🎉' },
  ],
};
