import type { Lesson } from '../types';

export const a2lektion16: Lesson = {
  id: 'a2-l16', level: 'A2', module: 4, number: 15,
  title: { de: 'Adjektive nach dem bestimmten Artikel', en: 'Adjectives after the definite article', fr: 'Adjectifs après l’article défini' },
  theme: 'Sightseeing: adjective endings after der/die/das and dieser (nominative, accusative, dative)',
  themeFr: 'Visiter une ville : terminaisons des adjectifs après der/die/das et dieser (nominatif, accusatif, datif)',
  goals: ['Use -e and -en after der/die/das in the nominative, accusative and dative', 'Point things out with dieser/diese/dieses', 'Give opinions about buildings and places', 'Compare the three adjective patterns in one overview'],
  goalsFr: ['Utiliser -e et -en après der/die/das au nominatif, à l’accusatif et au datif', 'Désigner des choses avec dieser/diese/dieses', 'Donner son avis sur des bâtiments et des lieux', 'Comparer les trois schémas d’adjectifs en un aperçu'],
  steps: [
    { kind: 'intro', title: 'Schaut mal, der schöne Dom! ⛪', titleFr: 'Regardez, la belle cathédrale ! ⛪',
      scene: 'A sunny day in the old town: a cathedral, an old bridge, a famous castle — and friends who cannot stop pointing and commenting.', sceneFr: 'Une journée ensoleillée dans la vieille ville : une cathédrale, un vieux pont, un château célèbre — et des amis qui ne cessent de montrer du doigt et de commenter.',
      goals: ['-e / -en after der, die, das', 'The dative: mit dem alten Führer', 'dieser / diese / dieses', 'One summary of all adjective endings'],
      goalsFr: ['-e / -en après der, die, das', 'Le datif : mit dem alten Führer', 'dieser / diese / dieses', 'Un résumé de toutes les terminaisons d’adjectifs'] },

    { kind: 'vocab', item: { id: 'a2l16-dom', german: 'der Dom', english: 'the cathedral', french: 'la cathédrale', gender: 'der', syllables: ['DOM'], pronunciation: 'dair dohm', example: { de: 'Der Dom ist von weitem zu sehen.', en: 'The cathedral can be seen from far away.', fr: 'On voit la cathédrale de loin.' } } },
    { kind: 'vocab', item: { id: 'a2l16-sehenswuerdigkeit', german: 'die Sehenswürdigkeit', english: 'the sight / attraction', french: 'la curiosité touristique', gender: 'die', syllables: ['SE', 'hens', 'wür', 'dig', 'keit'], pronunciation: 'dee ZAY-ens-vuer-dikh-kite', example: { de: 'Was ist die wichtigste Sehenswürdigkeit der Stadt?', en: 'What is the most important sight in the city?', fr: 'Quelle est la curiosité la plus importante de la ville ?' } } },
    { kind: 'vocab', item: { id: 'a2l16-fuehrung', german: 'die Führung', english: 'the guided tour', french: 'la visite guidée', gender: 'die', syllables: ['FÜH', 'rung'], pronunciation: 'dee FUE-roong', example: { de: 'Die Führung beginnt um zehn Uhr.', en: 'The guided tour starts at ten o’clock.', fr: 'La visite guidée commence à dix heures.' } } },
    { kind: 'vocab', item: { id: 'a2l16-turm', german: 'der Turm', english: 'the tower', french: 'la tour', gender: 'der', syllables: ['TURM'], pronunciation: 'dair toorm', example: { de: 'Vom Turm sehen wir die ganze Stadt.', en: 'From the tower we can see the whole city.', fr: 'Depuis la tour, nous voyons toute la ville.' } } },
    { kind: 'vocab', item: { id: 'a2l16-bruecke', german: 'die Brücke', english: 'the bridge', french: 'le pont', gender: 'die', syllables: ['BRÜ', 'cke'], pronunciation: 'dee BRUE-ke', example: { de: 'Wir gehen über die Brücke.', en: 'We walk across the bridge.', fr: 'Nous traversons le pont.' } } },
    { kind: 'vocab', item: { id: 'a2l16-altstadt', german: 'die Altstadt', english: 'the old town', french: 'la vieille ville', gender: 'die', syllables: ['ALT', 'stadt'], pronunciation: 'dee AHLT-shtaht', example: { de: 'In der Altstadt gibt es viele kleine Cafés.', en: 'There are many little cafés in the old town.', fr: 'Dans la vieille ville, il y a beaucoup de petits cafés.' } } },
    { kind: 'vocab', item: { id: 'a2l16-schloss', german: 'das Schloss', english: 'the castle / palace', french: 'le château', gender: 'das', syllables: ['SCHLOSS'], pronunciation: 'dahs shloss', example: { de: 'Das Schloss liegt auf einem Hügel.', en: 'The castle stands on a hill.', fr: 'Le château se trouve sur une colline.' } } },
    { kind: 'vocab', item: { id: 'a2l16-beruehmt', german: 'berühmt', english: 'famous', french: 'célèbre', gender: null, syllables: ['be', 'RÜHMT'], pronunciation: 'be-RUEMT', example: { de: 'Das berühmte Schloss ist heute offen.', en: 'The famous castle is open today.', fr: 'Le célèbre château est ouvert aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'a2l16-beeindruckend', german: 'beeindruckend', english: 'impressive', french: 'impressionnant', gender: null, syllables: ['be', 'EIN', 'dru', 'ckend'], pronunciation: 'be-INE-droo-kent', example: { de: 'Der Turm ist wirklich beeindruckend.', en: 'The tower is really impressive.', fr: 'La tour est vraiment impressionnante.' } } },
    { kind: 'vocab', item: { id: 'a2l16-geschlossen', german: 'geschlossen', english: 'closed', french: 'fermé', gender: null, syllables: ['ge', 'SCHLOS', 'sen'], pronunciation: 'ge-SHLOSS-en', example: { de: 'Montags ist das Museum geschlossen.', en: 'On Mondays the museum is closed.', fr: 'Le lundi, le musée est fermé.' } } },
    { kind: 'vocab', item: { id: 'a2l16-malerisch', german: 'malerisch', english: 'picturesque', french: 'pittoresque', gender: null, syllables: ['MA', 'le', 'risch'], pronunciation: 'MAH-le-rish', example: { de: 'Die malerische Altstadt ist voller Touristen.', en: 'The picturesque old town is full of tourists.', fr: 'La vieille ville pittoresque est pleine de touristes.' } } },
    { kind: 'vocab', item: { id: 'a2l16-historisch', german: 'historisch', english: 'historic', french: 'historique', gender: null, syllables: ['his', 'TO', 'risch'], pronunciation: 'his-TOH-rish', example: { de: 'Das historische Rathaus ist 500 Jahre alt.', en: 'The historic town hall is 500 years old.', fr: 'L’hôtel de ville historique a 500 ans.' } } },
    { kind: 'vocab', item: { id: 'a2l16-dieser', german: 'dieser / diese / dieses', english: 'this (masc / fem / neut)', french: 'ce, cet / cette / ce', gender: null, syllables: ['DIE', 'ser'], pronunciation: 'DEE-zer', example: { de: 'Dieses Schloss gefällt mir am besten.', en: 'I like this castle best.', fr: 'C’est ce château que je préfère.' } } },
    { kind: 'vocab', item: { id: 'a2l16-zuerst', german: 'zuerst … danach', english: 'first … afterwards', french: 'd’abord … ensuite', gender: null, syllables: ['zu', 'ERST', 'da', 'NACH'], pronunciation: 'tsoo-AIRST dah-NAHKH', example: { de: 'Zuerst besichtigen wir den Dom, danach essen wir etwas.', en: 'First we visit the cathedral, afterwards we eat something.', fr: 'D’abord nous visitons la cathédrale, ensuite nous mangeons quelque chose.' } } },

    { kind: 'grammar', note: {
      id: 'a2l16-definit', title: 'After der/die/das: -e or -en', titleFr: 'Après der/die/das : -e ou -en',
      explanationMd: 'After the definite article the adjective has only two endings — **-e** or **-en**:\n\n- Nominative: der schön**e** Dom · die alt**e** Brücke · das berühmt**e** Schloss\n- Accusative: **den** schön**en** Dom (masc!) · die alt**e** Brücke · das berühmt**e** Schloss\n- Dative: **dem** schön**en** Dom · **der** alt**en** Brücke · **dem** berühmt**en** Schloss\n- Plural (all cases): die schön**en** Türme · mit den schön**en** Türmen\n\nRule of thumb: **-e** in the nominative and in the feminine/neuter accusative — **-en** everywhere else.',
      explanationMdFr: 'Après l’article défini, l’adjectif n’a que deux terminaisons — **-e** ou **-en** :\n\n- Nominatif : der schön**e** Dom · die alt**e** Brücke · das berühmt**e** Schloss\n- Accusatif : **den** schön**en** Dom (masc !) · die alt**e** Brücke · das berühmt**e** Schloss\n- Datif : **dem** schön**en** Dom · **der** alt**en** Brücke · **dem** berühmt**en** Schloss\n- Pluriel (tous les cas) : die schön**en** Türme · mit den schön**en** Türmen\n\nRègle pratique : **-e** au nominatif et à l’accusatif féminin/neutre — **-en** partout ailleurs.',
      examples: [
        { de: 'Schaut mal, der schöne Dom!', en: 'Look, the beautiful cathedral!', fr: 'Regardez, la belle cathédrale !' },
        { de: 'Wir besichtigen den alten Turm.', en: 'We are visiting the old tower.', fr: 'Nous visitons la vieille tour.' },
        { de: 'Die Touristen stehen vor dem berühmten Schloss.', en: 'The tourists are standing in front of the famous castle.', fr: 'Les touristes sont devant le célèbre château.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l16-dieser', title: 'Pointing things out: dieser / diese / dieses', titleFr: 'Désigner : dieser / diese / dieses',
      explanationMd: '**dieser / diese / dieses** ("this") declines like **der/die/das** — and so do the adjectives after it:\n\n- Nom: dieser / diese / dieses / diese (plural)\n- Akk: **diesen** / diese / dieses / diese\n- Dat: **diesem** / **dieser** / **diesem** / **diesen**\n\nDieser schön**e** Dom! · Ich mag diese alt**e** Brücke. · In diesem klein**en** Café gibt es tollen Kuchen.\n\nGive your opinion with **finden**: Ich finde den Turm **beeindruckend**. (After "finden" the adjective has no ending.)',
      explanationMdFr: '**dieser / diese / dieses** (« ce, cette ») se décline comme **der/die/das** — et les adjectifs qui suivent aussi :\n\n- Nom : dieser / diese / dieses / diese (pluriel)\n- Acc : **diesen** / diese / dieses / diese\n- Dat : **diesem** / **dieser** / **diesem** / **diesen**\n\nDieser schön**e** Dom ! · Ich mag diese alt**e** Brücke. · In diesem klein**en** Café gibt es tollen Kuchen.\n\nDonne ton avis avec **finden** : Ich finde den Turm **beeindruckend**. (Après « finden », l’adjectif n’a pas de terminaison.)',
      examples: [
        { de: 'Dieser Turm ist am höchsten.', en: 'This tower is the tallest.', fr: 'Cette tour est la plus haute.' },
        { de: 'Ich finde diese alte Brücke sehr malerisch.', en: 'I find this old bridge very picturesque.', fr: 'Je trouve ce vieux pont très pittoresque.' },
        { de: 'In diesem kleinen Café gibt es tollen Kuchen.', en: 'In this little café they have great cake.', fr: 'Dans ce petit café, il y a un super gâteau.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l16-uebersicht', title: 'Summary: the three adjective patterns', titleFr: 'Résumé : les trois schémas d’adjectifs',
      explanationMd: 'Order per line: **masculine · feminine · neuter · plural**.\n\n**1) After der / dieser (definite)**\n- Nom: -e · -e · -e · -en\n- Akk: -en · -e · -e · -en\n- Dat: -en · -en · -en · -en\n\n**2) After ein / kein / mein (indefinite)**\n- Nom: -er · -e · -es · -en\n- Akk: -en · -e · -es · -en\n- Dat: -en · -en · -en · -en\n\n**3) No article**\n- Nom: -er · -e · -es · -e\n- Akk: -en · -e · -es · -e\n- Dat: -em · -er · -em · -en\n\nThe idea: the case and gender must be visible **once**. If the article already shows it (der, dem), the adjective relaxes to **-e / -en**. If the article is missing or shows nothing (ein), the adjective shows it.',
      explanationMdFr: 'Ordre dans chaque ligne : **masculin · féminin · neutre · pluriel**.\n\n**1) Après der / dieser (défini)**\n- Nom : -e · -e · -e · -en\n- Acc : -en · -e · -e · -en\n- Dat : -en · -en · -en · -en\n\n**2) Après ein / kein / mein (indéfini)**\n- Nom : -er · -e · -es · -en\n- Acc : -en · -e · -es · -en\n- Dat : -en · -en · -en · -en\n\n**3) Sans article**\n- Nom : -er · -e · -es · -e\n- Acc : -en · -e · -es · -e\n- Dat : -em · -er · -em · -en\n\nL’idée : le cas et le genre doivent être visibles **une fois**. Si l’article les montre déjà (der, dem), l’adjectif se relâche en **-e / -en**. Si l’article manque ou ne montre rien (ein), c’est l’adjectif qui le montre.',
      examples: [
        { de: 'Zuerst besuchen wir den alten Dom, danach gehen wir über die neue Brücke.', en: 'First we visit the old cathedral, then we cross the new bridge.', fr: 'D’abord nous visitons la vieille cathédrale, ensuite nous traversons le nouveau pont.' },
        { de: 'Das ist ein alter Dom. — Ja, der alte Dom ist berühmt.', en: 'That is an old cathedral. — Yes, the old cathedral is famous.', fr: 'C’est une vieille cathédrale. — Oui, la vieille cathédrale est célèbre.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l16-e1', prompt: 'Schaut mal, der schön__ Dom! (nominative, masculine)', promptFr: 'Schaut mal, der schön__ Dom ! (nominatif, masculin)', answer: 'e', hint: 'after der (nom) → -e', hintFr: 'après der (nom) → -e' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l16-e2', prompt: 'Wir besichtigen den alt__ Turm. (accusative, masculine)', promptFr: 'Wir besichtigen den alt__ Turm. (accusatif, masculin)', answer: 'en', hint: 'den + masculine accusative → -en', hintFr: 'den + accusatif masculin → -en' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l16-e3', prompt: 'Wir sind in der ___ Altstadt.', promptFr: 'Wir sind in der ___ Altstadt.', options: ['alte', 'alten', 'altes'], answer: 1, explain: 'Dative feminine ("in der"): the adjective ends in -en.', explainFr: 'Datif féminin (« in der ») : l’adjectif se termine en -en.', hint: '"in" + location = dative → -en.', hintFr: '« in » + lieu = datif → -en.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l16-e4', prompt: 'Die Touristen stehen vor dem berühmt__ Schloss. (dative)', promptFr: 'Die Touristen stehen vor dem berühmt__ Schloss. (datif)', answer: 'en', hint: 'dative → -en', hintFr: 'datif → -en' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l16-e5', prompt: 'Ich finde ___ Brücke malerisch.', promptFr: 'Ich finde ___ Brücke malerisch.', options: ['dieser', 'diese', 'dieses'], answer: 1, explain: 'Brücke is feminine; accusative feminine = diese.', explainFr: 'Brücke est féminin ; accusatif féminin = diese.', hint: 'die Brücke → diese Brücke.', hintFr: 'die Brücke → diese Brücke.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l16-e6', pairs: [ { de: 'berühmt', en: 'famous', fr: 'célèbre' }, { de: 'geschlossen', en: 'closed', fr: 'fermé' }, { de: 'beeindruckend', en: 'impressive', fr: 'impressionnant' }, { de: 'malerisch', en: 'picturesque', fr: 'pittoresque' } ], hint: 'Match each adjective to its meaning.', hintFr: 'Associe chaque adjectif à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l16-e7', tokens: ['alten', 'Turm', 'Ich', 'den', 'finde', 'beeindruckend'], answer: ['Ich', 'finde', 'den', 'alten', 'Turm', 'beeindruckend'], hint: 'Ich finde + object (den alten Turm) + opinion adjective without ending.', hintFr: 'Ich finde + complément (den alten Turm) + adjectif d’opinion sans terminaison.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l16-e8', prompt: 'Listen. What is closed today?', promptFr: 'Écoute. Qu’est-ce qui est fermé aujourd’hui ?', audio: { ttsText: 'Schaut mal, der schöne Dom! Leider ist der Turm heute geschlossen.' }, options: ['The tower', 'The cathedral', 'The bridge'], optionsFr: ['La tour', 'La cathédrale', 'Le pont'], answer: 0, hint: 'Listen for the word before "geschlossen".', hintFr: 'Écoute le mot avant « geschlossen ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l16-e9', prompt: 'Wir gehen mit der ___ Stadtführerin durch die Altstadt.', promptFr: 'Wir gehen mit der ___ Stadtführerin durch die Altstadt.', options: ['netten', 'nette', 'netter'], answer: 0, explain: '"mit" + dative feminine: der netten Stadtführerin.', explainFr: '« mit » + datif féminin : der netten Stadtführerin.', hint: 'After "mit der" the adjective ends in -en.', hintFr: 'Après « mit der », l’adjectif se termine en -en.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l16-e10', prompt: 'Wir sehen die alt__ Brücke. (accusative, feminine)', promptFr: 'Wir sehen die alt__ Brücke. (accusatif, féminin)', answer: 'e', hint: 'feminine accusative looks like the nominative → -e', hintFr: 'l’accusatif féminin ressemble au nominatif → -e' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l16-e11', word: 'Sehenswürdigkeit', answer: 'die', hint: 'Nouns ending in -keit are feminine.', hintFr: 'Les noms en -keit sont féminins.' } },

    { kind: 'pronunciation', focus: 'The umlaut ü (round your lips for "oo", say "ee") in Brücke, Führung, berühmt, Sehenswürdigkeit', focusFr: 'Le tréma ü (arrondis les lèvres comme pour « ou », dis « i ») dans Brücke, Führung, berühmt, Sehenswürdigkeit', items: [
      { id: 'a2l16-bruecke-pron', german: 'die Brücke', english: 'the bridge', french: 'le pont', gender: 'die', syllables: ['BRÜ', 'cke'], pronunciation: 'dee BRUE-ke', example: { de: 'Die Brücke ist sehr alt.', en: 'The bridge is very old.', fr: 'Le pont est très ancien.' } },
      { id: 'a2l16-fuehrung-pron', german: 'die Führung', english: 'the guided tour', french: 'la visite guidée', gender: 'die', syllables: ['FÜH', 'rung'], pronunciation: 'dee FUE-roong', example: { de: 'Die Führung ist kostenlos.', en: 'The guided tour is free.', fr: 'La visite guidée est gratuite.' } },
      { id: 'a2l16-beruehmt-pron', german: 'berühmt', english: 'famous', french: 'célèbre', gender: null, syllables: ['be', 'RÜHMT'], pronunciation: 'be-RUEMT', example: { de: 'Der Dom ist weltberühmt.', en: 'The cathedral is world-famous.', fr: 'La cathédrale est mondialement célèbre.' } },
      { id: 'a2l16-schloss-pron', german: 'das Schloss', english: 'the castle', french: 'le château', gender: 'das', syllables: ['SCHLOSS'], pronunciation: 'dahs shloss', example: { de: 'Das Schloss ist geschlossen.', en: 'The castle is closed.', fr: 'Le château est fermé.' } },
    ] },

    { kind: 'wrapup', summary: 'You now know the adjective endings after **der/die/das and dieser**: **-e** in the nominative and the feminine/neuter accusative, **-en** everywhere else (den alten Turm, mit dem berühmten Schloss, in der kleinen Stadt). The summary note puts all three patterns side by side — come back to it whenever you hesitate. 🎉',
      summaryFr: 'Tu connais maintenant les terminaisons après **der/die/das et dieser** : **-e** au nominatif et à l’accusatif féminin/neutre, **-en** partout ailleurs (den alten Turm, mit dem berühmten Schloss, in der kleinen Stadt). La fiche de résumé met les trois schémas côte à côte — reviens-y dès que tu hésites. 🎉' },
  ],
};
