import type { Lesson } from '../types';

export const a2lektion17: Lesson = {
  id: 'a2-l17', level: 'A2', module: 2, number: 7,
  title: { de: 'Zeitangaben', en: 'Expressing time', fr: 'Exprimer le temps' },
  theme: 'Events and festivals: von … bis, von … an, seit, über, zwischen, dates and times of day',
  themeFr: 'Événements et festivals : von … bis, von … an, seit, über, zwischen, dates et moments de la journée',
  goals: ['Say when something starts, ends and how long it lasts (von … bis, von … an)', 'Say how long something has been going on (seit + Dativ)', 'Use über + Akkusativ and zwischen + Dativ for time', 'Read a festival programme and make plans'],
  goalsFr: ['Dire quand quelque chose commence, finit et combien de temps cela dure (von … bis, von … an)', 'Dire depuis combien de temps quelque chose dure (seit + datif)', 'Utiliser über + accusatif et zwischen + datif pour le temps', 'Lire un programme de festival et faire des projets'],
  steps: [
    { kind: 'intro', title: 'Das Festival beginnt! 🎪', titleFr: 'Le festival commence ! 🎪',
      scene: 'The city festival is on: concerts on the stage, an art exhibition, food stalls. You read the programme and need to know exactly when everything happens.', sceneFr: 'Le festival de la ville bat son plein : concerts sur scène, exposition d’art, stands de nourriture. Tu lis le programme et tu dois savoir exactement quand tout se passe.',
      goals: ['von … bis and von … an / ab', 'seit + dative: Seit wann?', 'über + accusative, zwischen + dative', 'Dates and times of day'],
      goalsFr: ['von … bis et von … an / ab', 'seit + datif : Seit wann ?', 'über + accusatif, zwischen + datif', 'Dates et moments de la journée'] },

    { kind: 'vocab', item: { id: 'a2l17-veranstaltung', german: 'die Veranstaltung', english: 'the event', french: 'l’événement / la manifestation', gender: 'die', syllables: ['ver', 'AN', 'stal', 'tung'], pronunciation: 'dee fer-AHN-shtahl-toong', example: { de: 'Die Veranstaltung ist am Samstag im Park.', en: 'The event is on Saturday in the park.', fr: 'L’événement a lieu samedi dans le parc.' } } },
    { kind: 'vocab', item: { id: 'a2l17-festival', german: 'das Festival', english: 'the festival', french: 'le festival', gender: 'das', syllables: ['FES', 'ti', 'val'], pronunciation: 'dahs FES-ti-vahl', example: { de: 'Das Festival ist jedes Jahr im August.', en: 'The festival takes place every August.', fr: 'Le festival a lieu chaque année en août.' } } },
    { kind: 'vocab', item: { id: 'a2l17-eintrittskarte', german: 'die Eintrittskarte', english: 'the ticket (admission)', french: 'le billet d’entrée', gender: 'die', syllables: ['EIN', 'tritts', 'kar', 'te'], pronunciation: 'dee INE-trits-kar-te', example: { de: 'Die Eintrittskarte kostet zwölf Euro.', en: 'The ticket costs twelve euros.', fr: 'Le billet d’entrée coûte douze euros.' } } },
    { kind: 'vocab', item: { id: 'a2l17-buehne', german: 'die Bühne', english: 'the stage', french: 'la scène', gender: 'die', syllables: ['BÜH', 'ne'], pronunciation: 'dee BUE-ne', example: { de: 'Die Band steht schon auf der Bühne.', en: 'The band is already on the stage.', fr: 'Le groupe est déjà sur scène.' } } },
    { kind: 'vocab', item: { id: 'a2l17-kuenstler', german: 'der Künstler', english: 'the artist', french: 'l’artiste', gender: 'der', syllables: ['KÜNST', 'ler'], pronunciation: 'dair KUENST-ler', example: { de: 'Viele Künstler zeigen ihre Bilder.', en: 'Many artists are showing their paintings.', fr: 'Beaucoup d’artistes montrent leurs tableaux.' } } },
    { kind: 'vocab', item: { id: 'a2l17-programm', german: 'das Programm', english: 'the programme', french: 'le programme', gender: 'das', syllables: ['pro', 'GRAMM'], pronunciation: 'dahs pro-GRAHM', example: { de: 'Im Programm steht ein Konzert um 20 Uhr.', en: 'The programme lists a concert at 8 p.m.', fr: 'Le programme indique un concert à 20 heures.' } } },
    { kind: 'vocab', item: { id: 'a2l17-ausstellung', german: 'die Ausstellung', english: 'the exhibition', french: 'l’exposition', gender: 'die', syllables: ['AUS', 'stel', 'lung'], pronunciation: 'dee OWS-shtel-loong', example: { de: 'Die Ausstellung ist täglich geöffnet.', en: 'The exhibition is open daily.', fr: 'L’exposition est ouverte tous les jours.' } } },
    { kind: 'vocab', item: { id: 'a2l17-termin', german: 'der Termin', english: 'the appointment / date', french: 'le rendez-vous / la date', gender: 'der', syllables: ['ter', 'MIN'], pronunciation: 'dair ter-MEEN', example: { de: 'Ich habe am Freitag einen Termin.', en: 'I have an appointment on Friday.', fr: 'J’ai un rendez-vous vendredi.' } } },
    { kind: 'vocab', item: { id: 'a2l17-vormittag', german: 'der Vormittag', english: 'the (late) morning', french: 'la matinée', gender: 'der', syllables: ['VOR', 'mit', 'tag'], pronunciation: 'dair FOHR-mit-tahk', example: { de: 'Am Vormittag ist es noch ruhig.', en: 'In the morning it is still quiet.', fr: 'Le matin, c’est encore calme.' } } },
    { kind: 'vocab', item: { id: 'a2l17-nachmittag', german: 'der Nachmittag', english: 'the afternoon', french: 'l’après-midi', gender: 'der', syllables: ['NACH', 'mit', 'tag'], pronunciation: 'dair NAHKH-mit-tahk', example: { de: 'Am Nachmittag spielt die Band.', en: 'In the afternoon the band plays.', fr: 'L’après-midi, le groupe joue.' } } },
    { kind: 'vocab', item: { id: 'a2l17-dauern', german: 'dauern', english: 'to last', french: 'durer', gender: null, syllables: ['DAU', 'ern'], pronunciation: 'DOW-ern', example: { de: 'Wie lange dauert das Konzert?', en: 'How long does the concert last?', fr: 'Combien de temps dure le concert ?' } } },
    { kind: 'vocab', item: { id: 'a2l17-seit', german: 'seit', english: 'since / for (up to now)', french: 'depuis', gender: null, syllables: ['SEIT'], pronunciation: 'zite', example: { de: 'Ich spiele seit zwei Jahren Gitarre.', en: 'I have been playing guitar for two years.', fr: 'Je joue de la guitare depuis deux ans.' } } },
    { kind: 'vocab', item: { id: 'a2l17-bis', german: 'bis', english: 'until / to', french: 'jusqu’à', gender: null, syllables: ['BIS'], pronunciation: 'biss', example: { de: 'Die Party dauert bis Mitternacht.', en: 'The party lasts until midnight.', fr: 'La fête dure jusqu’à minuit.' } } },
    { kind: 'vocab', item: { id: 'a2l17-zwischen', german: 'zwischen', english: 'between', french: 'entre', gender: null, syllables: ['ZWI', 'schen'], pronunciation: 'TSVISH-en', example: { de: 'Zwischen 14 und 16 Uhr ist Pause.', en: 'Between 2 and 4 p.m. there is a break.', fr: 'Entre 14 et 16 heures, il y a une pause.' } } },

    { kind: 'grammar', note: {
      id: 'a2l17-von-bis', title: 'von … bis and von … an (ab)', titleFr: 'von … bis et von … an (ab)',
      explanationMd: 'Use **von … bis** for a start and an end, and **von … an** (or **ab**) when only the start is given:\n\n- Das Festival dauert **von** Freitag **bis** Sonntag.\n- Die Ausstellung ist **von** 10 **bis** 18 Uhr geöffnet.\n- **Von** 18 Uhr **an** ist der Eintritt frei. (= **Ab** 18 Uhr)\n\nDates: **am** 3. Mai (say: am dritten Mai) · **vom** 3. **bis zum** 5. Mai (vom = von dem, zum = zu dem).\n\nQuestions: **Wann?** · **Von wann bis wann?** · **Ab wann?** · **Wie lange?**',
      explanationMdFr: 'Utilise **von … bis** pour un début et une fin, et **von … an** (ou **ab**) quand seul le début est donné :\n\n- Das Festival dauert **von** Freitag **bis** Sonntag.\n- Die Ausstellung ist **von** 10 **bis** 18 Uhr geöffnet.\n- **Von** 18 Uhr **an** ist der Eintritt frei. (= **Ab** 18 Uhr)\n\nDates : **am** 3. Mai (on dit : am dritten Mai) · **vom** 3. **bis zum** 5. Mai (vom = von dem, zum = zu dem).\n\nQuestions : **Wann ?** · **Von wann bis wann ?** · **Ab wann ?** · **Wie lange ?**',
      examples: [
        { de: 'Das Festival läuft vom 3. bis zum 5. Juli.', en: 'The festival runs from 3 to 5 July.', fr: 'Le festival a lieu du 3 au 5 juillet.' },
        { de: 'Ab wann ist der Eintritt frei? — Von 18 Uhr an.', en: 'From when is admission free? — From 6 p.m. on.', fr: 'À partir de quand l’entrée est-elle gratuite ? — À partir de 18 heures.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l17-seit', title: 'seit + dative: something that still goes on', titleFr: 'seit + datif : quelque chose qui dure encore',
      explanationMd: '**seit** (since / for) says that something **started in the past and is still true now**. It takes the **dative**, and the verb stays in the **present tense**:\n\n- Ich lerne **seit einem Jahr** Deutsch.\n- Er wohnt **seit der** Schulzeit hier. · **seit dem** 1. Mai\n- Wir warten **seit zwei Stunden**. (plural dative: noun + **-n**)\n\nQuestions: **Seit wann …?** (starting point) or **Wie lange …?** (duration): Seit wann lernst du Deutsch? — Seit einem Jahr.',
      explanationMdFr: '**seit** (« depuis ») indique que quelque chose a **commencé dans le passé et dure encore maintenant**. Il veut le **datif**, et le verbe reste au **présent** :\n\n- Ich lerne **seit einem Jahr** Deutsch.\n- Er wohnt **seit der** Schulzeit hier. · **seit dem** 1. Mai\n- Wir warten **seit zwei Stunden**. (datif pluriel : nom + **-n**)\n\nQuestions : **Seit wann …?** (point de départ) ou **Wie lange …?** (durée) : Seit wann lernst du Deutsch ? — Seit einem Jahr.',
      examples: [
        { de: 'Seit wann spielst du Gitarre? — Seit drei Jahren.', en: 'Since when have you been playing guitar? — For three years.', fr: 'Depuis quand joues-tu de la guitare ? — Depuis trois ans.' },
        { de: 'Es regnet seit einer Woche.', en: 'It has been raining for a week.', fr: 'Il pleut depuis une semaine.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l17-ueber-zwischen', title: 'über + accusative, zwischen + dative', titleFr: 'über + accusatif, zwischen + datif',
      explanationMd: '**über** + **accusative** names a longer stretch of time — "for more than" or "over":\n\n- Das Festival läuft **über** drei Wochen.\n- Die Führung dauert **über** eine Stunde.\n- Wir bleiben **über** das Wochenende in Wien.\n\n**zwischen** + **dative** marks a time window:\n\n- **Zwischen** 14 und 16 Uhr ist Pause.\n- **Zwischen dem** 5. und 7. Mai bin ich nicht da.\n\nTimes of day: **am** Vormittag · **am** Nachmittag · **am** Abend · **in der** Nacht.',
      explanationMdFr: '**über** + **accusatif** désigne une période plus longue — « plus de » ou « pendant » :\n\n- Das Festival läuft **über** drei Wochen.\n- Die Führung dauert **über** eine Stunde.\n- Wir bleiben **über** das Wochenende in Wien.\n\n**zwischen** + **datif** marque une fenêtre de temps :\n\n- **Zwischen** 14 und 16 Uhr ist Pause.\n- **Zwischen dem** 5. und 7. Mai bin ich nicht da.\n\nMoments de la journée : **am** Vormittag · **am** Nachmittag · **am** Abend · **in der** Nacht.',
      examples: [
        { de: 'Zwischen 14 und 16 Uhr spielt keine Band.', en: 'Between 2 and 4 p.m. no band plays.', fr: 'Entre 14 et 16 heures, aucun groupe ne joue.' },
        { de: 'Am Vormittag bleiben wir im Hotel, am Abend gehen wir zum Konzert.', en: 'In the morning we stay at the hotel, in the evening we go to the concert.', fr: 'Le matin, nous restons à l’hôtel, le soir nous allons au concert.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l17-e1', prompt: 'Das Festival dauert ___ Freitag bis Sonntag.', promptFr: 'Das Festival dauert ___ Freitag bis Sonntag.', answer: 'von', hint: 'von … bis', hintFr: 'von … bis' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l17-e2', prompt: 'Ich lerne ___ einem Jahr Deutsch. (since / for)', promptFr: 'Ich lerne ___ einem Jahr Deutsch. (depuis)', answer: 'seit', hint: 'Still going on now → seit + dative.', hintFr: 'Ça continue maintenant → seit + datif.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l17-e3', prompt: 'Which question asks for the duration?', promptFr: 'Quelle question demande la durée ?', options: ['Seit wann?', 'Wie lange?', 'Ab wann?'], answer: 1, explain: '"Wie lange?" = how long; "Ab wann?" asks for the start; "Seit wann?" for a starting point in the past.', explainFr: '« Wie lange ? » = combien de temps ; « Ab wann ? » demande le début ; « Seit wann ? » un point de départ dans le passé.', hint: 'Think "how long".', hintFr: 'Pense à « combien de temps ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l17-e4', prompt: 'Von 10 Uhr ___ ist die Ausstellung geöffnet. (from … onwards)', promptFr: 'Von 10 Uhr ___ ist die Ausstellung geöffnet. (à partir de)', answer: 'an', hint: 'von … an', hintFr: 'von … an' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l17-e5', prompt: 'Wir warten seit zwei Stunde__. (dative plural)', promptFr: 'Wir warten seit zwei Stunde__. (datif pluriel)', answer: 'n', hint: 'dative plural adds -n', hintFr: 'le datif pluriel ajoute -n' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l17-e6', pairs: [ { de: 'von … bis', en: 'from … to', fr: 'de … à' }, { de: 'seit', en: 'since / for', fr: 'depuis' }, { de: 'zwischen', en: 'between', fr: 'entre' }, { de: 'über', en: 'over / for more than', fr: 'pendant / plus de' } ], hint: 'Match each time word to its meaning.', hintFr: 'Associe chaque mot de temps à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l17-e7', tokens: ['bis', 'Das', 'von', 'dauert', 'Freitag', 'Festival', 'Sonntag'], answer: ['Das', 'Festival', 'dauert', 'von', 'Freitag', 'bis', 'Sonntag'], hint: 'Subject + verb, then "von … bis …".', hintFr: 'Sujet + verbe, puis « von … bis … ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l17-e8', prompt: 'Listen. On which day is the exhibition closed?', promptFr: 'Écoute. Quel jour l’exposition est-elle fermée ?', audio: { ttsText: 'Die Ausstellung ist von Dienstag bis Sonntag geöffnet. Montags ist sie geschlossen.' }, options: ['Monday', 'Sunday', 'Tuesday'], optionsFr: ['Lundi', 'Dimanche', 'Mardi'], answer: 0, hint: 'Listen for "geschlossen".', hintFr: 'Écoute « geschlossen ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l17-e9', prompt: 'Seit ___ Woche regnet es.', promptFr: 'Seit ___ Woche regnet es.', options: ['einer', 'eine', 'einem'], answer: 0, explain: '"seit" takes the dative; feminine dative: einer Woche.', explainFr: '« seit » veut le datif ; datif féminin : einer Woche.', hint: 'die Woche → dative feminine.', hintFr: 'die Woche → datif féminin.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l17-e10', prompt: 'Listen. How long does the tour last?', promptFr: 'Écoute. Combien de temps dure la visite ?', audio: { ttsText: 'Die Führung beginnt um 15 Uhr und dauert über eine Stunde.' }, options: ['More than an hour', 'Exactly fifteen minutes', 'Three hours'], optionsFr: ['Plus d’une heure', 'Exactement quinze minutes', 'Trois heures'], answer: 0, hint: 'Listen for "über".', hintFr: 'Écoute « über ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l17-e11', prompt: 'Wir bleiben ___ das Wochenende in Wien. (over)', promptFr: 'Wir bleiben ___ das Wochenende in Wien. (pendant)', answer: 'über', hint: 'über + accusative for a stretch of time', hintFr: 'über + accusatif pour une période' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l17-e12', prompt: 'Die Probe ist ___ 14 und 16 Uhr.', promptFr: 'Die Probe ist ___ 14 und 16 Uhr.', options: ['zwischen', 'seit', 'über'], answer: 0, explain: '"zwischen … und …" marks a time window.', explainFr: '« zwischen … und … » marque une fenêtre de temps.', hint: 'Two times, joined with "und".', hintFr: 'Deux heures, reliées par « und ».' } },

    { kind: 'pronunciation', focus: 'The umlaut ü (round lips, say "ee") in über, Bühne, Künstler — and "zw" = "tsv"', focusFr: 'Le tréma ü (lèvres arrondies, dis « i ») dans über, Bühne, Künstler — et « zw » = « tsv »', items: [
      { id: 'a2l17-ueber-pron', german: 'über', english: 'over / above', french: 'sur / pendant', gender: null, syllables: ['Ü', 'ber'], pronunciation: 'UE-ber', example: { de: 'Das Fest dauert über zwei Tage.', en: 'The party lasts over two days.', fr: 'La fête dure plus de deux jours.' } },
      { id: 'a2l17-buehne-pron', german: 'die Bühne', english: 'the stage', french: 'la scène', gender: 'die', syllables: ['BÜH', 'ne'], pronunciation: 'dee BUE-ne', example: { de: 'Die Bühne ist groß.', en: 'The stage is big.', fr: 'La scène est grande.' } },
      { id: 'a2l17-kuenstler-pron', german: 'der Künstler', english: 'the artist', french: 'l’artiste', gender: 'der', syllables: ['KÜNST', 'ler'], pronunciation: 'dair KUENST-ler', example: { de: 'Der Künstler malt ein Bild.', en: 'The artist is painting a picture.', fr: 'L’artiste peint un tableau.' } },
      { id: 'a2l17-zwischen-pron', german: 'zwischen', english: 'between', french: 'entre', gender: null, syllables: ['ZWI', 'schen'], pronunciation: 'TSVISH-en', example: { de: 'Zwischen Montag und Mittwoch.', en: 'Between Monday and Wednesday.', fr: 'Entre lundi et mercredi.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now talk about time precisely: **von … bis** (Freitag bis Sonntag), **von … an / ab** (from 6 p.m. on), **seit + dative** with the present tense (seit einem Jahr), **über + accusative** for a longer stretch (über das Wochenende) and **zwischen + dative** for a time window. Ask with **Wann? Ab wann? Seit wann? Wie lange?** 🎉',
      summaryFr: 'Tu sais maintenant parler du temps avec précision : **von … bis** (du vendredi au dimanche), **von … an / ab** (à partir de 18 h), **seit + datif** avec le présent (seit einem Jahr), **über + accusatif** pour une période plus longue (über das Wochenende) et **zwischen + datif** pour une fenêtre de temps. Pose tes questions avec **Wann ? Ab wann ? Seit wann ? Wie lange ?** 🎉' },
  ],
};
