import type { Lesson } from '../types';

export const a2lektion13: Lesson = {
  id: 'a2-l13', level: 'A2', module: 1, number: 3,
  title: { de: 'Familie, Beruf und Besitz', en: 'Family, work and belongings', fr: 'Famille, métier et possession' },
  theme: 'Family history, professions and possessive articles in all cases',
  themeFr: 'Histoire de famille, métiers et articles possessifs à tous les cas',
  goals: ['Use all possessive articles: mein, dein, sein, ihr, unser, euer, ihr, Ihr', 'Choose the right ending in Nominativ, Akkusativ and Dativ', 'Talk about relatives and their jobs', 'Tell a short family story with "war"'],
  goalsFr: ['Utiliser tous les articles possessifs : mein, dein, sein, ihr, unser, euer, ihr, Ihr', 'Choisir la bonne terminaison au nominatif, à l’accusatif et au datif', 'Parler des membres de la famille et de leurs métiers', 'Raconter une courte histoire de famille avec « war »'],
  steps: [
    { kind: 'intro', title: 'Das Familienalbum 📸', titleFr: 'L’album de famille 📸',
      scene: 'Clara shows her old family album: her grandfather in front of his bakery, her aunt at the office, her cousins at the beach. Whose bakery, whose office, whose house?', sceneFr: 'Clara montre son vieil album de famille : son grand-père devant sa boulangerie, sa tante au bureau, ses cousins à la plage. À qui la boulangerie, à qui le bureau, à qui la maison ?',
      goals: ['Say "Mein Opa war Bäcker."', 'Use unser / euer / ihr / Ihr', 'Know the endings: mein, meinen, meinem, meiner', 'Name relatives and workplaces'],
      goalsFr: ['Dire « Mein Opa war Bäcker. »', 'Utiliser unser / euer / ihr / Ihr', 'Connaître les terminaisons : mein, meinen, meinem, meiner', 'Nommer les membres de la famille et les lieux de travail'] },

    { kind: 'vocab', item: { id: 'a2l13-opa', german: 'der Opa', english: 'the grandpa', french: 'le papi / le grand-père', gender: 'der', syllables: ['O', 'pa'], pronunciation: 'dair OH-pah', example: { de: 'Mein Opa war Bäcker.', en: 'My grandpa was a baker.', fr: 'Mon grand-père était boulanger.' } } },
    { kind: 'vocab', item: { id: 'a2l13-onkel', german: 'der Onkel', english: 'the uncle', french: 'l’oncle', gender: 'der', syllables: ['ON', 'kel'], pronunciation: 'dair ON-kel', example: { de: 'Mein Onkel wohnt in Hamburg.', en: 'My uncle lives in Hamburg.', fr: 'Mon oncle habite à Hambourg.' } } },
    { kind: 'vocab', item: { id: 'a2l13-tante', german: 'die Tante', english: 'the aunt', french: 'la tante', gender: 'die', syllables: ['TAN', 'te'], pronunciation: 'dee TAHN-teh', example: { de: 'Meine Tante arbeitet im Krankenhaus.', en: 'My aunt works at the hospital.', fr: 'Ma tante travaille à l’hôpital.' } } },
    { kind: 'vocab', item: { id: 'a2l13-cousin', german: 'der Cousin / die Cousine', english: 'the cousin (male / female)', french: 'le cousin / la cousine', gender: 'der', syllables: ['cou', 'SIN'], pronunciation: 'dair koo-ZEN / dee koo-ZEE-neh', example: { de: 'Meine Cousine studiert in Wien.', en: 'My cousin studies in Vienna.', fr: 'Ma cousine étudie à Vienne.' } } },
    { kind: 'vocab', item: { id: 'a2l13-neffe', german: 'der Neffe', english: 'the nephew', french: 'le neveu', gender: 'der', syllables: ['NEF', 'fe'], pronunciation: 'dair NEF-feh', example: { de: 'Mein Neffe ist fünf Jahre alt.', en: 'My nephew is five years old.', fr: 'Mon neveu a cinq ans.' } } },
    { kind: 'vocab', item: { id: 'a2l13-nichte', german: 'die Nichte', english: 'the niece', french: 'la nièce', gender: 'die', syllables: ['NICH', 'te'], pronunciation: 'dee NIKH-teh', example: { de: 'Meine Nichte spielt gern Fußball.', en: 'My niece likes playing football.', fr: 'Ma nièce aime jouer au football.' } } },
    { kind: 'vocab', item: { id: 'a2l13-schwiegermutter', german: 'die Schwiegermutter', english: 'the mother-in-law', french: 'la belle-mère', gender: 'die', syllables: ['SCHWIE', 'ger', 'mut', 'ter'], pronunciation: 'dee SHVEE-ger-moot-ter', example: { de: 'Meine Schwiegermutter kocht sehr gut.', en: 'My mother-in-law cooks very well.', fr: 'Ma belle-mère cuisine très bien.' } } },
    { kind: 'vocab', item: { id: 'a2l13-baecker', german: 'der Bäcker / die Bäckerin', english: 'the baker', french: 'le boulanger / la boulangère', gender: 'der', syllables: ['BÄ', 'cker'], pronunciation: 'dair BEK-ker', example: { de: 'Der Bäcker steht um vier Uhr auf.', en: 'The baker gets up at four o’clock.', fr: 'Le boulanger se lève à quatre heures.' } } },
    { kind: 'vocab', item: { id: 'a2l13-ingenieur', german: 'der Ingenieur / die Ingenieurin', english: 'the engineer', french: 'l’ingénieur / l’ingénieure', gender: 'der', syllables: ['in', 'ge', 'NIEUR'], pronunciation: 'dair in-zhen-YUR', example: { de: 'Ihr Mann ist Ingenieur.', en: 'Her husband is an engineer.', fr: 'Son mari est ingénieur.' } } },
    { kind: 'vocab', item: { id: 'a2l13-verkaeufer', german: 'der Verkäufer / die Verkäuferin', english: 'the salesperson', french: 'le vendeur / la vendeuse', gender: 'der', syllables: ['ver', 'KÄU', 'fer'], pronunciation: 'dair fair-KOY-fer', example: { de: 'Sein Bruder ist Verkäufer.', en: 'His brother is a salesman.', fr: 'Son frère est vendeur.' } } },
    { kind: 'vocab', item: { id: 'a2l13-kollege', german: 'der Kollege / die Kollegin', english: 'the colleague', french: 'le collègue / la collègue', gender: 'der', syllables: ['kol', 'LE', 'ge'], pronunciation: 'dair kol-LAY-geh', example: { de: 'Mein Kollege heißt Jan.', en: 'My colleague is called Jan.', fr: 'Mon collègue s’appelle Jan.' } } },
    { kind: 'vocab', item: { id: 'a2l13-chef', german: 'der Chef / die Chefin', english: 'the boss', french: 'le chef / la cheffe', gender: 'der', syllables: ['CHEF'], pronunciation: 'dair shef', example: { de: 'Unsere Chefin ist sehr nett.', en: 'Our boss is very nice.', fr: 'Notre cheffe est très sympa.' } } },
    { kind: 'vocab', item: { id: 'a2l13-firma', german: 'die Firma', english: 'the company', french: 'l’entreprise', gender: 'die', syllables: ['FIR', 'ma'], pronunciation: 'dee FEER-mah', example: { de: 'Unsere Firma ist nicht groß.', en: 'Our company is not big.', fr: 'Notre entreprise n’est pas grande.' } } },
    { kind: 'vocab', item: { id: 'a2l13-buero', german: 'das Büro', english: 'the office', french: 'le bureau', gender: 'das', syllables: ['bü', 'RO'], pronunciation: 'dahs bew-ROH', example: { de: 'Mein Büro ist im dritten Stock.', en: 'My office is on the third floor.', fr: 'Mon bureau est au troisième étage.' } } },

    { kind: 'grammar', note: {
      id: 'a2l13-possessiv-alle', title: 'All possessive articles', titleFr: 'Tous les articles possessifs',
      explanationMd: 'Every person has its own possessive article. It depends on **who owns** something:\n\n- ich → **mein** · du → **dein**\n- er → **sein** · sie (she) → **ihr** · es → **sein**\n- wir → **unser** · ihr (you, plural) → **euer**\n- sie (they) → **ihr** · Sie (formal) → **Ihr**\n\nThe **ending**, however, depends on the **noun** that follows (gender, number, case): sein**e** Mutter, sein**en** Vater.\n\n⚠️ **euer** loses its second e when it gets an ending: **eure** Mutter, **euren** Vater. **unser** often keeps it: unsere Mutter.\n\n⚠️ **sein** = his/its, **ihr** = her/their, **Ihr** (capital) = formal "your".',
      explanationMdFr: 'Chaque personne a son propre article possessif. Il dépend de **qui possède** :\n\n- ich → **mein** · du → **dein**\n- er → **sein** · sie (elle) → **ihr** · es → **sein**\n- wir → **unser** · ihr (vous, pluriel) → **euer**\n- sie (ils/elles) → **ihr** · Sie (vouvoiement) → **Ihr**\n\nLa **terminaison**, elle, dépend du **nom** qui suit (genre, nombre, cas) : sein**e** Mutter, sein**en** Vater.\n\n⚠️ **euer** perd son deuxième e quand il prend une terminaison : **eure** Mutter, **euren** Vater. **unser** le garde souvent : unsere Mutter.\n\n⚠️ **sein** = son (à lui), **ihr** = son (à elle) / leur, **Ihr** (majuscule) = votre (vouvoiement).',
      examples: [
        { de: 'Anna liebt ihren Beruf.', en: 'Anna loves her job.', fr: 'Anna aime son métier.' },
        { de: 'Tom und Lea besuchen ihre Oma.', en: 'Tom and Lea visit their grandma.', fr: 'Tom et Lea rendent visite à leur grand-mère.' },
        { de: 'Wie heißt Ihr Chef, Frau Weber?', en: 'What is your boss’s name, Ms Weber?', fr: 'Comment s’appelle votre chef, madame Weber ?' },
        { de: 'Kinder, wo sind eure Jacken?', en: 'Children, where are your jackets?', fr: 'Les enfants, où sont vos vestes ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l13-possessiv-nom-akk', title: 'Endings in Nominativ and Akkusativ', titleFr: 'Les terminaisons au nominatif et à l’accusatif',
      explanationMd: 'Possessive articles take the **same endings as ein / kein**:\n\n- **Nominativ**: mein Vater (m) · meine Mutter (f) · mein Kind (n) · meine Eltern (pl)\n- **Akkusativ**: mein**en** Vater (m) · meine Mutter (f) · mein Kind (n) · meine Eltern (pl)\n\nOnly the **masculine** changes between Nominativ and Akkusativ (**-en**). Feminine and plural always end in **-e**, neuter never has an ending.\n\nUse the Nominativ after **sein / werden / heißen** and for the subject. Use the Akkusativ for the direct object (**besuchen, lieben, haben, kennen, brauchen** …).',
      explanationMdFr: 'Les articles possessifs prennent les **mêmes terminaisons que ein / kein** :\n\n- **Nominatif** : mein Vater (m) · meine Mutter (f) · mein Kind (n) · meine Eltern (pl)\n- **Accusatif** : mein**en** Vater (m) · meine Mutter (f) · mein Kind (n) · meine Eltern (pl)\n\nSeul le **masculin** change entre nominatif et accusatif (**-en**). Le féminin et le pluriel finissent toujours par **-e**, le neutre n’a jamais de terminaison.\n\nUtilise le nominatif pour le sujet et après **sein / werden / heißen**. Utilise l’accusatif pour le COD (**besuchen, lieben, haben, kennen, brauchen** …).',
      examples: [
        { de: 'Mein Onkel ist Ingenieur.', en: 'My uncle is an engineer.', fr: 'Mon oncle est ingénieur.' },
        { de: 'Ich besuche meinen Onkel in Hamburg.', en: 'I visit my uncle in Hamburg.', fr: 'Je rends visite à mon oncle à Hambourg.' },
        { de: 'Sie kennt unseren Chef nicht.', en: 'She does not know our boss.', fr: 'Elle ne connaît pas notre chef.' },
        { de: 'Wir haben unsere Firma 2019 gegründet.', en: 'We founded our company in 2019.', fr: 'Nous avons fondé notre entreprise en 2019.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l13-possessiv-dativ', title: 'Possessive articles in the Dativ', titleFr: 'Les articles possessifs au datif',
      explanationMd: 'In the **Dativ** the endings are: **-em** (m, n) · **-er** (f) · **-en** (plural, and the noun adds **-n**).\n\n- mit mein**em** Bruder (m) · mit mein**em** Kind (n)\n- mit mein**er** Schwester (f)\n- mit mein**en** Eltern (pl) — the plural noun ends in -n: Eltern, Kindern, Freunden\n\nYou need the Dativ after **mit, bei, von, zu, nach, aus** and for the indirect object (**geben, schenken, helfen, gehören** — see Dativ lesson).\n\n**Quick table** (with mein-):\n- Nom: mein · meine · mein · meine\n- Akk: meinen · meine · mein · meine\n- Dat: meinem · meiner · meinem · meinen',
      explanationMdFr: 'Au **datif**, les terminaisons sont : **-em** (m, n) · **-er** (f) · **-en** (pluriel, et le nom prend **-n**).\n\n- mit mein**em** Bruder (m) · mit mein**em** Kind (n)\n- mit mein**er** Schwester (f)\n- mit mein**en** Eltern (pl) — le nom au pluriel finit par -n : Eltern, Kindern, Freunden\n\nTu as besoin du datif après **mit, bei, von, zu, nach, aus** et pour le complément d’attribution (**geben, schenken, helfen, gehören** — voir la leçon sur le datif).\n\n**Tableau rapide** (avec mein-) :\n- Nom : mein · meine · mein · meine\n- Acc : meinen · meine · mein · meine\n- Dat : meinem · meiner · meinem · meinen',
      examples: [
        { de: 'Ich wohne bei meinen Eltern.', en: 'I live with my parents.', fr: 'J’habite chez mes parents.' },
        { de: 'Er telefoniert mit seiner Schwester.', en: 'He is talking on the phone with his sister.', fr: 'Il téléphone à sa sœur.' },
        { de: 'Wir gratulieren unserem Opa zum Geburtstag.', en: 'We congratulate our grandpa on his birthday.', fr: 'Nous souhaitons un bon anniversaire à notre grand-père.' },
        { de: 'Habt ihr euren Kollegen schon geholfen?', en: 'Have you already helped your colleagues?', fr: 'Avez-vous déjà aidé vos collègues ?' },
      ] } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l13-e1', prompt: 'Das ist ___ Haus. (wir)', promptFr: 'Das ist ___ Haus. (wir)', options: ['unser', 'unsere', 'unseren'], answer: 0, explain: '"das Haus" is neuter and Nominativ, so no ending: unser Haus.', explainFr: '« das Haus » est neutre au nominatif, donc pas de terminaison : unser Haus.', hint: 'Neuter in the Nominativ: no ending.', hintFr: 'Neutre au nominatif : pas de terminaison.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l13-e2', prompt: 'Wo arbeitet ___ Tante? (your, du — Nominativ)', promptFr: 'Wo arbeitet ___ Tante ? (ton, du — nominatif)', answer: 'deine', hint: '"die Tante" is feminine: dein + e', hintFr: '« die Tante » est féminin : dein + e' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l13-e3', prompt: 'Ich besuche ___ Onkel in Hamburg. (my — Akkusativ)', promptFr: 'Ich besuche ___ Onkel in Hamburg. (mon — accusatif)', answer: 'meinen', hint: 'Masculine in the Akkusativ: -en', hintFr: 'Masculin à l’accusatif : -en' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l13-e4', prompt: 'Anna kennt ___ Chef gut. (her)', promptFr: 'Anna kennt ___ Chef gut. (son, à elle)', options: ['ihr', 'ihren', 'ihrem'], answer: 1, explain: '"der Chef" is masculine, Akkusativ (object): ihren Chef.', explainFr: '« der Chef » est masculin à l’accusatif (COD) : ihren Chef.', hint: 'Direct object, masculine → -en.', hintFr: 'COD, masculin → -en.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l13-e5', prompt: 'Ich wohne bei ___ Eltern. (my — Dativ plural)', promptFr: 'Ich wohne bei ___ Eltern. (mes — datif pluriel)', answer: 'meinen', hint: 'Dativ plural always ends in -en.', hintFr: 'Datif pluriel : toujours -en.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l13-e6', prompt: 'Er telefoniert mit ___ Schwester. (his — Dativ)', promptFr: 'Er telefoniert mit ___ Schwester. (sa, à lui — datif)', answer: 'seiner', hint: 'Feminine in the Dativ: -er', hintFr: 'Féminin au datif : -er' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l13-e7', pairs: [ { de: 'wir', en: 'unser (our)', fr: 'unser (notre)' }, { de: 'ihr (you, plural)', en: 'euer (your)', fr: 'euer (votre)' }, { de: 'Sie (formal)', en: 'Ihr (your)', fr: 'Ihr (votre)' }, { de: 'sie (they)', en: 'ihr (their)', fr: 'ihr (leur)' } ], hint: 'Match each pronoun with its possessive article.', hintFr: 'Associe chaque pronom à son article possessif.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l13-e8', tokens: ['Opa', 'war', 'Mein', 'Bäcker'], answer: ['Mein', 'Opa', 'war', 'Bäcker'], hint: 'Possessive + noun first, then the verb.', hintFr: 'D’abord l’article possessif + nom, puis le verbe.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l13-e9', prompt: 'Listen. What is the uncle’s job?', promptFr: 'Écoute. Quel est le métier de l’oncle ?', audio: { ttsText: 'Meine Tante ist Ingenieurin und mein Onkel ist Bäcker.' }, options: ['Baker', 'Engineer', 'Teacher'], optionsFr: ['Boulanger', 'Ingénieur', 'Enseignant'], answer: 0, hint: 'Listen for "Onkel".', hintFr: 'Écoute « Onkel ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l13-e10', prompt: 'Listen. Who does the speaker live with?', promptFr: 'Écoute. Chez qui habite la personne ?', audio: { ttsText: 'Ich wohne bei meiner Tante.' }, options: ['Her aunt', 'Her parents', 'Her uncle'], optionsFr: ['Sa tante', 'Ses parents', 'Son oncle'], answer: 0, hint: '"meiner" is feminine singular in the Dativ.', hintFr: '« meiner » est le féminin singulier au datif.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l13-e11', prompt: 'Kinder, wo ist ___ Mutter?', promptFr: 'Les enfants, où est ___ Mutter ?', options: ['euer', 'eure', 'euere'], answer: 1, explain: '"euer" loses its second e before an ending: eure Mutter.', explainFr: '« euer » perd son deuxième e devant une terminaison : eure Mutter.', hint: 'Feminine ending -e, and the middle e disappears.', hintFr: 'Terminaison féminine -e, et le e du milieu disparaît.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l13-e12', word: 'Firma', answer: 'die', hint: 'Words ending in -a are often feminine.', hintFr: 'Les mots en -a sont souvent féminins.' } },

    { kind: 'pronunciation', focus: 'eu = "oy", and the sound of ü in Büro / Bäcker', focusFr: 'eu = « oy », et le son ü dans Büro / Bäcker', items: [
      { id: 'a2l13-euer-pron', german: 'euer', english: 'your (plural)', french: 'votre (pluriel)', gender: null, syllables: ['EU', 'er'], pronunciation: 'OY-er', example: { de: 'Wo ist euer Auto?', en: 'Where is your car?', fr: 'Où est votre voiture ?' } },
      { id: 'a2l13-unser-pron', german: 'unser', english: 'our', french: 'notre', gender: null, syllables: ['UN', 'ser'], pronunciation: 'OON-zer', example: { de: 'Unser Haus ist neu.', en: 'Our house is new.', fr: 'Notre maison est neuve.' } },
      { id: 'a2l13-schwiegermutter-pron', german: 'Schwiegermutter', english: 'mother-in-law', french: 'belle-mère', gender: 'die', syllables: ['SCHWIE', 'ger', 'mut', 'ter'], pronunciation: 'SHVEE-ger-moot-ter', example: { de: 'Ihre Schwiegermutter ist nett.', en: 'Her mother-in-law is nice.', fr: 'Sa belle-mère est gentille.' } },
      { id: 'a2l13-buero-pron', german: 'Büro', english: 'office', french: 'bureau', gender: 'das', syllables: ['bü', 'RO'], pronunciation: 'bew-ROH', example: { de: 'Mein Büro ist hell.', en: 'My office is bright.', fr: 'Mon bureau est lumineux.' } },
      { id: 'a2l13-ingenieur-pron', german: 'Ingenieur', english: 'engineer', french: 'ingénieur', gender: 'der', syllables: ['in', 'ge', 'NIEUR'], pronunciation: 'in-zhen-YUR', example: { de: 'Mein Vater ist Ingenieur.', en: 'My father is an engineer.', fr: 'Mon père est ingénieur.' } },
    ] },

    { kind: 'wrapup', summary: 'You now know **all possessive articles**: mein, dein, sein, ihr, unser, euer, ihr, Ihr. The owner chooses the stem, the noun chooses the ending — same as ein: **Nom** mein/meine/mein/meine, **Akk** meinen/meine/mein/meine, **Dat** meinem/meiner/meinem/meinen. Now tell your own family story: "Mein Opa war Bäcker …" 🎉',
      summaryFr: 'Tu connais maintenant **tous les articles possessifs** : mein, dein, sein, ihr, unser, euer, ihr, Ihr. Le possesseur choisit le radical, le nom choisit la terminaison — comme pour ein : **Nom** mein/meine/mein/meine, **Acc** meinen/meine/mein/meine, **Dat** meinem/meiner/meinem/meinen. Raconte maintenant ta propre histoire de famille : « Mein Opa war Bäcker … » 🎉' },
  ],
};
