import type { Lesson } from '../types';

export const a2lektion19: Lesson = {
  id: 'a2-l19', level: 'A2', module: 5, number: 20,
  title: { de: 'Wenn-Sätze im Alltag', en: 'Everyday "wenn" clauses', fr: 'Les phrases en « wenn » au quotidien' },
  theme: 'Habits and routines with "wenn" clauses: food, weather, seasons, and traditions',
  themeFr: 'Habitudes et routines avec les phrases en « wenn » : nourriture, météo, saisons et traditions',
  goals: ['Describe habits with "wenn" (when / whenever)', 'Put the verb at the end of the wenn-clause', 'Start the sentence with the wenn-clause (verb jumps to position 1)', 'Talk about eating habits and express surprise'],
  goalsFr: ['Décrire des habitudes avec « wenn » (quand / chaque fois que)', 'Mettre le verbe à la fin de la subordonnée en wenn', 'Commencer la phrase par la subordonnée (le verbe passe en position 1)', 'Parler des habitudes alimentaires et exprimer la surprise'],
  steps: [
    { kind: 'intro', title: 'Wenn es warm ist, essen wir Salat 🥗', titleFr: 'Quand il fait chaud, on mange de la salade 🥗',
      scene: 'Two exchange students compare what people eat and drink in different seasons and on different occasions — and they are often surprised!', sceneFr: 'Deux étudiants d’échange comparent ce que l’on mange et boit selon les saisons et les occasions — et ils sont souvent surpris !',
      goals: ['Explain what you do "when …"', 'Build wenn-clauses with the verb at the end', 'Invert the main clause after a wenn-clause', 'Say how often you do things'],
      goalsFr: ['Expliquer ce que tu fais « quand … »', 'Construire des subordonnées en wenn avec le verbe à la fin', 'Inverser la principale après une subordonnée en wenn', 'Dire à quelle fréquence tu fais les choses'] },

    { kind: 'vocab', item: { id: 'a2l19-wenn', german: 'wenn', english: 'when / whenever / if', french: 'quand / chaque fois que / si', gender: null, syllables: ['WENN'], pronunciation: 'venn', example: { de: 'Wenn es warm ist, essen wir Salat.', en: 'When it is warm, we eat salad.', fr: 'Quand il fait chaud, nous mangeons de la salade.' } } },
    { kind: 'vocab', item: { id: 'a2l19-gewohnheit', german: 'die Gewohnheit', english: 'the habit', french: 'l’habitude', gender: 'die', syllables: ['ge', 'WOHN', 'heit'], pronunciation: 'dee ge-VOHN-hite', example: { de: 'Kaffee am Morgen ist meine Gewohnheit.', en: 'Coffee in the morning is my habit.', fr: 'Le café du matin est mon habitude.' } } },
    { kind: 'vocab', item: { id: 'a2l19-meistens', german: 'meistens', english: 'mostly / usually', french: 'la plupart du temps', gender: null, syllables: ['MEIS', 'tens'], pronunciation: 'MICE-tens', example: { de: 'Meistens esse ich um eins.', en: 'I usually eat at one o’clock.', fr: 'Je mange la plupart du temps à treize heures.' } } },
    { kind: 'vocab', item: { id: 'a2l19-manchmal', german: 'manchmal', english: 'sometimes', french: 'parfois', gender: null, syllables: ['MANCH', 'mal'], pronunciation: 'MAHNKH-mahl', example: { de: 'Manchmal koche ich für Freunde.', en: 'Sometimes I cook for friends.', fr: 'Parfois, je cuisine pour des amis.' } } },
    { kind: 'vocab', item: { id: 'a2l19-selten', german: 'selten', english: 'rarely', french: 'rarement', gender: null, syllables: ['SEL', 'ten'], pronunciation: 'ZEL-ten', example: { de: 'Ich trinke selten Limonade.', en: 'I rarely drink lemonade.', fr: 'Je bois rarement de la limonade.' } } },
    { kind: 'vocab', item: { id: 'a2l19-salat', german: 'der Salat', english: 'the salad', french: 'la salade', gender: 'der', syllables: ['sa', 'LAT'], pronunciation: 'dair zah-LAHT', example: { de: 'Im Sommer esse ich viel Salat.', en: 'In summer I eat a lot of salad.', fr: 'En été, je mange beaucoup de salade.' } } },
    { kind: 'vocab', item: { id: 'a2l19-wurst', german: 'die Wurst', english: 'the sausage', french: 'la saucisse', gender: 'die', syllables: ['WURST'], pronunciation: 'dee voorst', example: { de: 'Zum Frühstück gibt es Brot mit Wurst.', en: 'For breakfast there is bread with sausage.', fr: 'Au petit-déjeuner, il y a du pain avec de la charcuterie.' } } },
    { kind: 'vocab', item: { id: 'a2l19-limonade', german: 'die Limonade', english: 'the lemonade / soft drink', french: 'la limonade / la boisson gazeuse', gender: 'die', syllables: ['li', 'mo', 'NA', 'de'], pronunciation: 'dee lee-moh-NAH-deh', example: { de: 'Die Kinder trinken gern Limonade.', en: 'The children like drinking lemonade.', fr: 'Les enfants aiment boire de la limonade.' } } },
    { kind: 'vocab', item: { id: 'a2l19-mineralwasser', german: 'das Mineralwasser', english: 'the mineral water', french: 'l’eau minérale', gender: 'das', syllables: ['mi', 'ne', 'RAL', 'was', 'ser'], pronunciation: 'dahs mi-neh-RAHL-vahs-ser', example: { de: 'Ein Mineralwasser, bitte.', en: 'A mineral water, please.', fr: 'Une eau minérale, s’il vous plaît.' } } },
    { kind: 'vocab', item: { id: 'a2l19-durst', german: 'der Durst', english: 'the thirst', french: 'la soif', gender: 'der', syllables: ['DURST'], pronunciation: 'dair doorst', example: { de: 'Wenn ich Durst habe, trinke ich Wasser.', en: 'When I am thirsty, I drink water.', fr: 'Quand j’ai soif, je bois de l’eau.' } } },
    { kind: 'vocab', item: { id: 'a2l19-obst', german: 'das Obst', english: 'the fruit (in general)', french: 'les fruits', gender: 'das', syllables: ['OBST'], pronunciation: 'dahs ohpst', example: { de: 'Zum Nachtisch gibt es Obst.', en: 'For dessert there is fruit.', fr: 'Au dessert, il y a des fruits.' } } },
    { kind: 'vocab', item: { id: 'a2l19-tradition', german: 'die Tradition', english: 'the tradition', french: 'la tradition', gender: 'die', syllables: ['tra', 'di', 'ZION'], pronunciation: 'dee trah-dee-TSYOHN', example: { de: 'In meiner Familie ist das Tradition.', en: 'In my family that is a tradition.', fr: 'Dans ma famille, c’est une tradition.' } } },
    { kind: 'vocab', item: { id: 'a2l19-ueberraschen', german: 'überraschen', english: 'to surprise', french: 'surprendre', gender: null, syllables: ['ü', 'ber', 'RA', 'schen'], pronunciation: 'ue-ber-RASH-en', example: { de: 'Das überrascht mich.', en: 'That surprises me.', fr: 'Cela me surprend.' } } },

    { kind: 'grammar', note: {
      id: 'a2l19-wenn-verbende', title: '"wenn" sends the verb to the end', titleFr: '« wenn » envoie le verbe à la fin',
      explanationMd: '**wenn** means **when / whenever** for habits and things that happen again and again. Like **weil** and **dass**, it starts a subordinate clause: the **conjugated verb goes to the very end**, and a **comma** separates the two clauses.\n\n- Ich esse Salat, **wenn** es warm **ist**.\n- Wir trinken Tee, **wenn** wir Besuch **haben**.\n\nSeparable verbs join up again at the end: **wenn** ich früh **aufstehe**. With the Perfekt the participle comes first, then the auxiliary last: **wenn** ich gekocht **habe**.',
      explanationMdFr: '**wenn** signifie **quand / chaque fois que** pour les habitudes et ce qui se répète. Comme **weil** et **dass**, il introduit une subordonnée : le **verbe conjugué va tout à la fin** et une **virgule** sépare les deux propositions.\n\n- Ich esse Salat, **wenn** es warm **ist**.\n- Wir trinken Tee, **wenn** wir Besuch **haben**.\n\nLes verbes séparables se recollent à la fin : **wenn** ich früh **aufstehe**. Au Perfekt, le participe vient d’abord, puis l’auxiliaire en dernier : **wenn** ich gekocht **habe**.',
      examples: [
        { de: 'Ich trinke Mineralwasser, wenn ich Durst habe.', en: 'I drink mineral water when I am thirsty.', fr: 'Je bois de l’eau minérale quand j’ai soif.' },
        { de: 'Wir essen Suppe, wenn es kalt ist.', en: 'We eat soup when it is cold.', fr: 'Nous mangeons de la soupe quand il fait froid.' },
        { de: 'Ich frühstücke nicht, wenn ich spät aufstehe.', en: 'I don’t have breakfast when I get up late.', fr: 'Je ne prends pas de petit-déjeuner quand je me lève tard.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l19-wenn-vorne', title: 'The wenn-clause first: verb in position 1', titleFr: 'La subordonnée en wenn d’abord : verbe en position 1',
      explanationMd: 'You can start the sentence with the **wenn-clause**. The whole clause counts as **position 1**, so the verb of the main clause comes right after the comma (it is the verb in position 2 of the whole sentence):\n\n- Ich esse Salat, wenn es warm ist.\n- **Wenn** es warm ist, **esse** ich Salat.\n\nThe main clause has the **verb first**, then the subject. You may add **dann**; it does not change anything: Wenn es kalt ist, **dann essen** wir Suppe.',
      explanationMdFr: 'Tu peux commencer la phrase par la **subordonnée en wenn**. Toute la subordonnée compte pour la **position 1**, donc le verbe de la principale vient juste après la virgule (c’est le verbe en position 2 de toute la phrase) :\n\n- Ich esse Salat, wenn es warm ist.\n- **Wenn** es warm ist, **esse** ich Salat.\n\nLa principale commence par le **verbe**, puis le sujet. Tu peux ajouter **dann** ; cela ne change rien : Wenn es kalt ist, **dann essen** wir Suppe.',
      examples: [
        { de: 'Wenn es regnet, bleiben wir zu Hause.', en: 'When it rains, we stay at home.', fr: 'Quand il pleut, nous restons à la maison.' },
        { de: 'Wenn ich wenig Zeit habe, koche ich nicht.', en: 'When I have little time, I don’t cook.', fr: 'Quand j’ai peu de temps, je ne cuisine pas.' },
        { de: 'Wenn wir Gäste haben, gibt es immer Fisch.', en: 'When we have guests, there is always fish.', fr: 'Quand nous avons des invités, il y a toujours du poisson.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l19-haeufigkeit', title: 'How often? And expressing surprise', titleFr: 'À quelle fréquence ? Et exprimer la surprise',
      explanationMd: 'Habits go with **frequency words**:\n\n**immer** (always) → **meistens** (mostly) → **oft** (often) → **manchmal** (sometimes) → **selten** (rarely) → **nie** (never)\n\nTo react with surprise, use **dass** (verb at the end again!):\n\n- **Es überrascht mich, dass** ihr so spät esst.\n- **Ich finde es überraschend, dass** man hier Kuchen zum Frühstück isst.\n\nShort reactions: **Wirklich?** · **Das wusste ich nicht!** · **Das ist ja interessant!**',
      explanationMdFr: 'Les habitudes vont avec des **mots de fréquence** :\n\n**immer** (toujours) → **meistens** (la plupart du temps) → **oft** (souvent) → **manchmal** (parfois) → **selten** (rarement) → **nie** (jamais)\n\nPour réagir avec surprise, utilise **dass** (verbe à la fin, encore !) :\n\n- **Es überrascht mich, dass** ihr so spät esst.\n- **Ich finde es überraschend, dass** man hier Kuchen zum Frühstück isst.\n\nRéactions courtes : **Wirklich ?** · **Das wusste ich nicht !** · **Das ist ja interessant !**',
      examples: [
        { de: 'Es überrascht mich, dass ihr so spät esst.', en: 'It surprises me that you eat so late.', fr: 'Cela me surprend que vous mangiez si tard.' },
        { de: 'Meistens trinke ich Tee, manchmal Kaffee.', en: 'I mostly drink tea, sometimes coffee.', fr: 'La plupart du temps je bois du thé, parfois du café.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l19-e1', prompt: 'Ich esse Salat, wenn es heiß ___. (sein)', promptFr: 'Ich esse Salat, wenn es heiß ___. (sein)', answer: 'ist', hint: 'The verb goes to the end of the wenn-clause.', hintFr: 'Le verbe va à la fin de la subordonnée en wenn.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l19-e2', prompt: 'Where does the conjugated verb go in a wenn-clause?', promptFr: 'Où va le verbe conjugué dans une subordonnée en wenn ?', options: ['Position 2', 'At the end', 'Position 1'], optionsFr: ['Position 2', 'À la fin', 'Position 1'], answer: 1, explain: 'wenn, weil and dass all send the conjugated verb to the end.', explainFr: 'wenn, weil et dass envoient tous le verbe conjugué à la fin.', hint: 'Same rule as weil and dass.', hintFr: 'Même règle que weil et dass.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l19-e3', tokens: ['essen', 'Wenn', 'es', 'wir', 'ist', 'Suppe', 'kalt'], answer: ['Wenn', 'es', 'kalt', 'ist', 'essen', 'wir', 'Suppe'], hint: 'wenn-clause first (verb last), then the verb, then the subject.', hintFr: 'D’abord la subordonnée en wenn (verbe à la fin), puis le verbe, puis le sujet.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l19-e4', pairs: [ { de: 'immer', en: 'always', fr: 'toujours' }, { de: 'meistens', en: 'mostly', fr: 'la plupart du temps' }, { de: 'manchmal', en: 'sometimes', fr: 'parfois' }, { de: 'selten', en: 'rarely', fr: 'rarement' } ], hint: 'These words tell you how often something happens.', hintFr: 'Ces mots disent à quelle fréquence quelque chose arrive.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l19-e5', prompt: 'Listen. What does she drink when it rains?', promptFr: 'Écoute. Que boit-elle quand il pleut ?', audio: { ttsText: 'Wenn die Sonne scheint, trinke ich Limonade, und wenn es regnet, trinke ich Tee.' }, options: ['Tea', 'Lemonade', 'Mineral water'], optionsFr: ['Du thé', 'De la limonade', 'De l’eau minérale'], answer: 0, hint: 'Listen to the second wenn-clause.', hintFr: 'Écoute la deuxième subordonnée en wenn.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l19-e6', prompt: 'Wenn ich Durst ___, trinke ich Mineralwasser. (haben)', promptFr: 'Wenn ich Durst ___, trinke ich Mineralwasser. (haben)', answer: 'habe', hint: 'ich-form of haben.', hintFr: 'Forme « ich » de haben.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l19-e7', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Wenn es regnet, wir bleiben zu Hause.', 'Wenn es regnet, bleiben wir zu Hause.', 'Wenn es regnet, wir zu Hause bleiben.'], optionsFr: ['Wenn es regnet, wir bleiben zu Hause.', 'Wenn es regnet, bleiben wir zu Hause.', 'Wenn es regnet, wir zu Hause bleiben.'], answer: 1, explain: 'After a wenn-clause, the main clause starts with its verb.', explainFr: 'Après une subordonnée en wenn, la principale commence par son verbe.', hint: 'The main clause starts with the verb.', hintFr: 'La principale commence par le verbe.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l19-e8', tokens: ['trinke', 'Ich', 'Mineralwasser', 'wenn', 'ich', 'habe', 'Durst'], answer: ['Ich', 'trinke', 'Mineralwasser', 'wenn', 'ich', 'Durst', 'habe'], hint: 'Main clause first, then "wenn" with the verb last.', hintFr: 'D’abord la principale, puis « wenn » avec le verbe à la fin.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l19-e9', word: 'Wurst', answer: 'die', hint: 'Feminine: die Wurst, die Würste.', hintFr: 'Féminin : die Wurst, die Würste.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l19-e10', word: 'Salat', answer: 'der', hint: 'Masculine: der Salat.', hintFr: 'Masculin : der Salat.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l19-e11', prompt: 'Listen. What does she eat when she has little time?', promptFr: 'Écoute. Que mange-t-elle quand elle a peu de temps ?', audio: { ttsText: 'Meistens esse ich abends warm, aber wenn ich wenig Zeit habe, esse ich nur ein Brot.' }, options: ['Only a piece of bread', 'A hot dinner', 'A big salad'], optionsFr: ['Seulement un morceau de pain', 'Un dîner chaud', 'Une grande salade'], answer: 0, hint: 'Listen after "wenn ich wenig Zeit habe".', hintFr: 'Écoute après « wenn ich wenig Zeit habe ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l19-e12', prompt: 'Es überrascht mich, ___ ihr so spät esst.', promptFr: 'Es überrascht mich, ___ ihr so spät esst.', answer: 'dass', hint: 'The conjunction "that" — the verb "esst" is at the end.', hintFr: 'La conjonction « que » — le verbe « esst » est à la fin.' } },

    { kind: 'pronunciation', focus: 'ü in überraschen, the sch sound, and the long o in Gewohnheit', focusFr: 'Le ü de überraschen, le son sch et le o long de Gewohnheit', items: [
      { id: 'a2l19-ueberraschen-pron', german: 'überraschen', english: 'to surprise', french: 'surprendre', gender: null, syllables: ['ü', 'ber', 'RA', 'schen'], pronunciation: 'ue-ber-RASH-en', example: { de: 'Das überrascht mich sehr.', en: 'That surprises me a lot.', fr: 'Cela me surprend beaucoup.' } },
      { id: 'a2l19-gewohnheit-pron', german: 'die Gewohnheit', english: 'the habit', french: 'l’habitude', gender: 'die', syllables: ['ge', 'WOHN', 'heit'], pronunciation: 'dee ge-VOHN-hite', example: { de: 'Das ist eine gute Gewohnheit.', en: 'That is a good habit.', fr: 'C’est une bonne habitude.' } },
      { id: 'a2l19-wurst-pron', german: 'die Wurst', english: 'the sausage', french: 'la saucisse', gender: 'die', syllables: ['WURST'], pronunciation: 'dee voorst', example: { de: 'Die Wurst schmeckt gut.', en: 'The sausage tastes good.', fr: 'La saucisse est bonne.' } },
      { id: 'a2l19-mineralwasser-pron', german: 'das Mineralwasser', english: 'the mineral water', french: 'l’eau minérale', gender: 'das', syllables: ['mi', 'ne', 'RAL', 'was', 'ser'], pronunciation: 'dahs mi-neh-RAHL-vahs-ser', example: { de: 'Ich möchte ein Mineralwasser.', en: 'I would like a mineral water.', fr: 'Je voudrais une eau minérale.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now talk about habits with **wenn**: the verb goes to the **end** of the wenn-clause, and when the wenn-clause comes first, the main clause starts with its **verb** (**Wenn es warm ist, essen wir Salat**). Use **immer, meistens, manchmal, selten, nie** for frequency and **Es überrascht mich, dass …** for surprise. 🥗',
      summaryFr: 'Tu sais maintenant parler de tes habitudes avec **wenn** : le verbe va à la **fin** de la subordonnée, et quand la subordonnée en wenn vient en premier, la principale commence par son **verbe** (**Wenn es warm ist, essen wir Salat**). Utilise **immer, meistens, manchmal, selten, nie** pour la fréquence et **Es überrascht mich, dass …** pour la surprise. 🥗' },
  ],
};
