import type { Lesson } from '../types';

export const a2lektion15: Lesson = {
  id: 'a2-l15', level: 'A2', module: 4, number: 14,
  title: { de: 'Adjektive mit unbestimmtem Artikel und ohne Artikel', en: 'Adjectives after ein- and with no article', fr: 'Adjectifs après l’article indéfini et sans article' },
  theme: 'Shopping at the market: adjective endings after ein-/kein-/mein- (incl. dative) and with no article',
  themeFr: 'Faire ses courses au marché : terminaisons des adjectifs après ein-/kein-/mein- (datif inclus) et sans article',
  goals: ['Use adjective endings after ein-/kein-/mein- in the dative', 'Use adjective endings with no article (frische Brötchen)', 'Say what matters to you: Mir ist … wichtig', 'Ask for quantities and packaging in a shop'],
  goalsFr: ['Utiliser les terminaisons après ein-/kein-/mein- au datif', 'Utiliser les terminaisons sans article (frische Brötchen)', 'Dire ce qui compte pour toi : Mir ist … wichtig', 'Demander des quantités et des conditionnements dans un magasin'],
  steps: [
    { kind: 'intro', title: 'Was darf es sein? 🧺', titleFr: 'Que désirez-vous ? 🧺',
      scene: 'Saturday morning at the market: fresh rolls, red apples, a bottle of milk — and a stallholder who wants to know exactly what you need.', sceneFr: 'Samedi matin au marché : des petits pains frais, des pommes rouges, une bouteille de lait — et un vendeur qui veut savoir exactement ce qu’il te faut.',
      goals: ['Dative endings: mit einem netten Verkäufer', 'No article: frisches Brot, frische Brötchen', 'Mir ist … wichtig', 'Kilo, Pfund, Flasche, Dose, Packung'],
      goalsFr: ['Terminaisons du datif : mit einem netten Verkäufer', 'Sans article : frisches Brot, frische Brötchen', 'Mir ist … wichtig', 'Kilo, Pfund, Flasche, Dose, Packung'] },

    { kind: 'vocab', item: { id: 'a2l15-markt', german: 'der Markt', english: 'the market', french: 'le marché', gender: 'der', syllables: ['MARKT'], pronunciation: 'dair mahrkt', example: { de: 'Am Samstag gehe ich auf den Markt.', en: 'On Saturday I go to the market.', fr: 'Le samedi, je vais au marché.' } } },
    { kind: 'vocab', item: { id: 'a2l15-stand', german: 'der Stand', english: 'the stall', french: 'l’étal / le stand', gender: 'der', syllables: ['STAND'], pronunciation: 'dair shtahnt', example: { de: 'Der Stand mit dem Käse ist links.', en: 'The cheese stall is on the left.', fr: 'L’étal de fromage est à gauche.' } } },
    { kind: 'vocab', item: { id: 'a2l15-obst', german: 'das Obst', english: 'the fruit', french: 'les fruits', gender: 'das', syllables: ['OBST'], pronunciation: 'dahs ohpst', example: { de: 'Das Obst ist heute besonders süß.', en: 'The fruit is especially sweet today.', fr: 'Les fruits sont particulièrement sucrés aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'a2l15-gemuese', german: 'das Gemüse', english: 'the vegetables', french: 'les légumes', gender: 'das', syllables: ['ge', 'MÜ', 'se'], pronunciation: 'dahs ge-MUE-ze', example: { de: 'Ich kaufe frisches Gemüse für die Suppe.', en: 'I am buying fresh vegetables for the soup.', fr: 'J’achète des légumes frais pour la soupe.' } } },
    { kind: 'vocab', item: { id: 'a2l15-broetchen', german: 'das Brötchen', english: 'the bread roll', french: 'le petit pain', gender: 'das', syllables: ['BRÖT', 'chen'], pronunciation: 'dahs BROET-khen', example: { de: 'Zum Frühstück esse ich zwei Brötchen.', en: 'For breakfast I eat two rolls.', fr: 'Au petit-déjeuner, je mange deux petits pains.' } } },
    { kind: 'vocab', item: { id: 'a2l15-pfund', german: 'das Pfund', english: 'the pound (500 g)', french: 'la livre (500 g)', gender: 'das', syllables: ['PFUND'], pronunciation: 'dahs pfoont', example: { de: 'Ich nehme ein Pfund Tomaten.', en: 'I’ll take a pound of tomatoes.', fr: 'Je prends une livre de tomates.' } } },
    { kind: 'vocab', item: { id: 'a2l15-flasche', german: 'die Flasche', english: 'the bottle', french: 'la bouteille', gender: 'die', syllables: ['FLA', 'sche'], pronunciation: 'dee FLAH-she', example: { de: 'Eine Flasche Wasser, bitte.', en: 'A bottle of water, please.', fr: 'Une bouteille d’eau, s’il vous plaît.' } } },
    { kind: 'vocab', item: { id: 'a2l15-dose', german: 'die Dose', english: 'the tin / can', french: 'la boîte de conserve', gender: 'die', syllables: ['DO', 'se'], pronunciation: 'dee DOH-ze', example: { de: 'Wir brauchen zwei Dosen Tomaten.', en: 'We need two tins of tomatoes.', fr: 'Il nous faut deux boîtes de tomates.' } } },
    { kind: 'vocab', item: { id: 'a2l15-packung', german: 'die Packung', english: 'the pack / packet', french: 'le paquet', gender: 'die', syllables: ['PA', 'ckung'], pronunciation: 'dee PAH-koong', example: { de: 'Eine Packung Nudeln kostet einen Euro.', en: 'A packet of pasta costs one euro.', fr: 'Un paquet de pâtes coûte un euro.' } } },
    { kind: 'vocab', item: { id: 'a2l15-frisch', german: 'frisch', english: 'fresh', french: 'frais', gender: null, syllables: ['FRISCH'], pronunciation: 'frish', example: { de: 'Das Brot ist ganz frisch.', en: 'The bread is really fresh.', fr: 'Le pain est tout frais.' } } },
    { kind: 'vocab', item: { id: 'a2l15-guenstig', german: 'günstig', english: 'cheap / good value', french: 'avantageux / bon marché', gender: null, syllables: ['GÜNS', 'tig'], pronunciation: 'GUENS-tikh', example: { de: 'Die Äpfel sind heute günstig.', en: 'The apples are good value today.', fr: 'Les pommes sont avantageuses aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'a2l15-wichtig', german: 'wichtig', english: 'important', french: 'important', gender: null, syllables: ['WICH', 'tig'], pronunciation: 'VIKH-tikh', example: { de: 'Mir ist ein guter Preis wichtig.', en: 'A good price is important to me.', fr: 'Un bon prix est important pour moi.' } } },
    { kind: 'vocab', item: { id: 'a2l15-wasdarf', german: 'Was darf es sein?', english: 'What can I get you?', french: 'Que désirez-vous ?', gender: null, syllables: ['WAS', 'DARF', 'es', 'SEIN'], pronunciation: 'vahs dahrf es zine', example: { de: 'Guten Tag! Was darf es sein?', en: 'Hello! What can I get you?', fr: 'Bonjour ! Que désirez-vous ?' } } },

    { kind: 'grammar', note: {
      id: 'a2l15-ein-dativ', title: 'After ein-/kein-/mein-: now with the dative', titleFr: 'Après ein-/kein-/mein- : maintenant avec le datif',
      explanationMd: 'You know the nominative and accusative (ein neuer Mantel, einen neuen Mantel). In the **dative**, the adjective is always **-en**:\n\n- mit **einem** neu**en** Mantel (masc) · mit **einem** neu**en** Auto (neut)\n- mit **einer** neu**en** Tasche (fem)\n- mit **keinen** neu**en** Autos (plural, noun +n)\n\nSo after ein-/kein-/mein- you only need to remember **three special forms**: **-er / -e / -es** in the nominative (the accusative keeps them, except masculine → **-en**) — and the dative and plural are always **-en**.',
      explanationMdFr: 'Tu connais le nominatif et l’accusatif (ein neuer Mantel, einen neuen Mantel). Au **datif**, l’adjectif est toujours en **-en** :\n\n- mit **einem** neu**en** Mantel (masc) · mit **einem** neu**en** Auto (neutre)\n- mit **einer** neu**en** Tasche (fém)\n- mit **keinen** neu**en** Autos (pluriel, nom +n)\n\nAprès ein-/kein-/mein-, il suffit donc de retenir **trois formes particulières** : **-er / -e / -es** au nominatif (l’accusatif les garde, sauf le masculin → **-en**) — et le datif et le pluriel sont toujours en **-en**.',
      examples: [
        { de: 'Ich spreche mit einem netten Verkäufer.', en: 'I am talking to a nice salesman.', fr: 'Je parle à un vendeur sympathique.' },
        { de: 'Wir kaufen bei einem kleinen Bäcker ein.', en: 'We shop at a small bakery.', fr: 'Nous faisons nos courses chez un petit boulanger.' },
        { de: 'Hast du keine frischen Brötchen?', en: 'Don’t you have any fresh rolls?', fr: 'Tu n’as pas de petits pains frais ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l15-nullartikel', title: 'No article: the adjective shows the case', titleFr: 'Sans article : l’adjectif montre le cas',
      explanationMd: 'With no article (plural, or foods and materials like Brot, Milch, Käse), the adjective takes the ending the article **would have had**:\n\n- Nom: frisch**er** Käse · frisch**e** Milch · frisch**es** Brot · frisch**e** Brötchen\n- Akk: frisch**en** Käse · frisch**e** Milch · frisch**es** Brot · frisch**e** Brötchen\n- Dat: mit frisch**em** Käse · frisch**er** Milch · frisch**em** Brot · frisch**en** Brötchen\n\nAfter **bei** and **mit** (dative): Bei gut**em** Wetter gehe ich auf den Markt.',
      explanationMdFr: 'Sans article (pluriel, ou aliments et matières comme Brot, Milch, Käse), l’adjectif prend la terminaison que l’article **aurait eue** :\n\n- Nom : frisch**er** Käse · frisch**e** Milch · frisch**es** Brot · frisch**e** Brötchen\n- Acc : frisch**en** Käse · frisch**e** Milch · frisch**es** Brot · frisch**e** Brötchen\n- Dat : mit frisch**em** Käse · frisch**er** Milch · frisch**em** Brot · frisch**en** Brötchen\n\nAprès **bei** et **mit** (datif) : Bei gut**em** Wetter gehe ich auf den Markt.',
      examples: [
        { de: 'Hier gibt es frisches Brot und frische Brötchen.', en: 'Here you can get fresh bread and fresh rolls.', fr: 'Ici, il y a du pain frais et des petits pains frais.' },
        { de: 'Ich esse gern frischen Käse.', en: 'I like eating fresh cheese.', fr: 'J’aime manger du fromage frais.' },
        { de: 'Bei gutem Wetter gehe ich auf den Markt.', en: 'When the weather is good, I go to the market.', fr: 'Quand il fait beau, je vais au marché.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l15-wichtig', title: 'What matters: Mir ist … wichtig · and quantities', titleFr: 'Ce qui compte : Mir ist … wichtig · et les quantités',
      explanationMd: 'To say what is important to you, use **Mir ist … wichtig**. The thing that matters is the **subject** (nominative), so the verb follows it: **ist** (singular) / **sind** (plural):\n\n- Mir **ist** ein guter Preis wichtig.\n- Mir **sind** frische Zutaten wichtig.\n\nFor quantities, the measure word comes first and the food **stays in the basic form** (no plural on the measure): ein **Kilo** Äpfel · ein **Pfund** Käse · zwei **Flaschen** Wasser · eine **Dose** Tomaten · eine **Packung** Nudeln. Kilo, Pfund and Gramm stay singular after a number: zwei Kilo, 500 Gramm.',
      explanationMdFr: 'Pour dire ce qui est important pour toi, utilise **Mir ist … wichtig**. Ce qui compte est le **sujet** (nominatif), le verbe s’accorde donc : **ist** (singulier) / **sind** (pluriel) :\n\n- Mir **ist** ein guter Preis wichtig.\n- Mir **sind** frische Zutaten wichtig.\n\nPour les quantités, l’unité de mesure vient d’abord et l’aliment **reste tel quel** : ein **Kilo** Äpfel · ein **Pfund** Käse · zwei **Flaschen** Wasser · eine **Dose** Tomaten · eine **Packung** Nudeln. Kilo, Pfund et Gramm restent au singulier après un nombre : zwei Kilo, 500 Gramm.',
      examples: [
        { de: 'Mir ist regionales Obst wichtig.', en: 'Local fruit is important to me.', fr: 'Les fruits locaux sont importants pour moi.' },
        { de: 'Ich nehme ein Kilo rote Äpfel und zwei Flaschen Milch.', en: 'I’ll take a kilo of red apples and two bottles of milk.', fr: 'Je prends un kilo de pommes rouges et deux bouteilles de lait.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l15-e1', prompt: 'Hier gibt es frisch__ Brötchen. (no article, plural)', promptFr: 'Hier gibt es frisch__ Brötchen. (sans article, pluriel)', answer: 'e', hint: 'plural, no article, nominative → -e', hintFr: 'pluriel, sans article, nominatif → -e' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l15-e2', prompt: 'Ich brauche ___ Käse. (no article, accusative, masculine)', promptFr: 'Ich brauche ___ Käse. (sans article, accusatif, masculin)', options: ['frische', 'frischen', 'frischer'], answer: 1, explain: 'Masculine accusative: the ending is -en, like "den".', explainFr: 'Accusatif masculin : la terminaison est -en, comme « den ».', hint: 'Käse is masculine; accusative → -en.', hintFr: 'Käse est masculin ; accusatif → -en.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l15-e3', prompt: 'Ich spreche mit einem nett__ Verkäufer. (dative)', promptFr: 'Ich spreche mit einem nett__ Verkäufer. (datif)', answer: 'en', hint: 'dative → always -en after ein-', hintFr: 'datif → toujours -en après ein-' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l15-e4', prompt: 'Mir ___ gute Preise wichtig.', promptFr: 'Mir ___ gute Preise wichtig.', options: ['ist', 'sind', 'bin'], answer: 1, explain: '"Preise" is plural, so the verb is "sind".', explainFr: '« Preise » est au pluriel, le verbe est donc « sind ».', hint: 'What is the subject — one price or several?', hintFr: 'Quel est le sujet : un prix ou plusieurs ?' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l15-e5', pairs: [ { de: 'die Dose', en: 'the tin / can', fr: 'la boîte de conserve' }, { de: 'die Flasche', en: 'the bottle', fr: 'la bouteille' }, { de: 'die Packung', en: 'the pack', fr: 'le paquet' }, { de: 'das Pfund', en: 'the pound (500 g)', fr: 'la livre (500 g)' } ], hint: 'Match each container or measure to its meaning.', hintFr: 'Associe chaque conditionnement ou mesure à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l15-e6', tokens: ['Kilo', 'nehme', 'Äpfel', 'Ich', 'rote', 'ein'], answer: ['Ich', 'nehme', 'ein', 'Kilo', 'rote', 'Äpfel'], hint: 'Quantity first ("ein Kilo"), then adjective + noun.', hintFr: 'D’abord la quantité (« ein Kilo »), puis adjectif + nom.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l15-e7', prompt: 'Listen. What does the customer buy?', promptFr: 'Écoute. Qu’achète le client ?', audio: { ttsText: 'Guten Tag! Ich möchte zwei Flaschen Wasser und ein frisches Brot, bitte.' }, options: ['Two bottles of water and a fresh loaf', 'One bottle of water and fresh rolls', 'Two tins of tomatoes and cheese'], optionsFr: ['Deux bouteilles d’eau et un pain frais', 'Une bouteille d’eau et des petits pains frais', 'Deux boîtes de tomates et du fromage'], answer: 0, hint: 'Listen for the number before "Flaschen".', hintFr: 'Écoute le nombre avant « Flaschen ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l15-e8', prompt: 'Bei gut__ Wetter gehe ich auf den Markt. (bei + dative, neuter, no article)', promptFr: 'Bei gut__ Wetter gehe ich auf den Markt. (bei + datif, neutre, sans article)', answer: 'em', hint: 'dative, neuter, no article → -em', hintFr: 'datif, neutre, sans article → -em' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l15-e9', prompt: 'Wir haben heute keine ___ Tomaten.', promptFr: 'Wir haben heute keine ___ Tomaten.', options: ['frische', 'frischen', 'frisches'], answer: 1, explain: 'After keine + plural, the adjective ends in -en.', explainFr: 'Après keine + pluriel, l’adjectif se termine en -en.', hint: 'After kein-/mein- in the plural: always -en.', hintFr: 'Après kein-/mein- au pluriel : toujours -en.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l15-e10', word: 'Brötchen', answer: 'das', hint: 'Nouns ending in -chen are always neuter.', hintFr: 'Les noms en -chen sont toujours neutres.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l15-e11', prompt: 'Listen. What is important to Lena?', promptFr: 'Écoute. Qu’est-ce qui est important pour Lena ?', audio: { ttsText: 'Mir ist regionales Obst wichtig, und ich kaufe gern bei einem kleinen Bauern.' }, options: ['Local fruit', 'A low price', 'Organic bread'], optionsFr: ['Les fruits locaux', 'Un prix bas', 'Le pain bio'], answer: 0, hint: 'Listen right after "Mir ist".', hintFr: 'Écoute juste après « Mir ist ».' } },

    { kind: 'pronunciation', focus: 'The soft ch after ö/ä/ü/i (Brötchen) — and the umlauts ö, ü, ä in market words', focusFr: 'Le ch doux après ö/ä/ü/i (Brötchen) — et les tréma ö, ü, ä dans les mots du marché', items: [
      { id: 'a2l15-broetchen-pron', german: 'das Brötchen', english: 'the bread roll', french: 'le petit pain', gender: 'das', syllables: ['BRÖT', 'chen'], pronunciation: 'dahs BROET-khen', example: { de: 'Ich möchte drei Brötchen.', en: 'I would like three rolls.', fr: 'Je voudrais trois petits pains.' } },
      { id: 'a2l15-gemuese-pron', german: 'das Gemüse', english: 'the vegetables', french: 'les légumes', gender: 'das', syllables: ['ge', 'MÜ', 'se'], pronunciation: 'dahs ge-MUE-ze', example: { de: 'Das Gemüse ist frisch.', en: 'The vegetables are fresh.', fr: 'Les légumes sont frais.' } },
      { id: 'a2l15-kaese-pron', german: 'der Käse', english: 'the cheese', french: 'le fromage', gender: 'der', syllables: ['KÄ', 'se'], pronunciation: 'dair KAY-ze', example: { de: 'Der Käse schmeckt super.', en: 'The cheese tastes great.', fr: 'Le fromage est délicieux.' } },
      { id: 'a2l15-pfund-pron', german: 'das Pfund', english: 'the pound', french: 'la livre', gender: 'das', syllables: ['PFUND'], pronunciation: 'dahs pfoont', example: { de: 'Ein Pfund Kaffee, bitte.', en: 'A pound of coffee, please.', fr: 'Une livre de café, s’il vous plaît.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now shop and say what matters to you. After **ein-/kein-/mein-** the dative adjective is always **-en** (mit einem netten Verkäufer). With **no article**, the adjective carries the ending: frisch**er** Käse, frisch**e** Milch, frisch**es** Brot, frisch**e** Brötchen, mit frisch**em** Brot. And: **Mir ist / sind … wichtig**. 🎉',
      summaryFr: 'Tu sais maintenant faire tes courses et dire ce qui compte pour toi. Après **ein-/kein-/mein-**, l’adjectif au datif est toujours en **-en** (mit einem netten Verkäufer). **Sans article**, l’adjectif porte la terminaison : frisch**er** Käse, frisch**e** Milch, frisch**es** Brot, frisch**e** Brötchen, mit frisch**em** Brot. Et : **Mir ist / sind … wichtig**. 🎉' },
  ],
};
