import type { Lesson } from '../types';

export const a2lektion14: Lesson = {
  id: 'a2-l14', level: 'A2', module: 1, number: 4,
  title: { de: 'Urlaub und Wortbildung', en: 'Holidays and word building', fr: 'Vacances et formation des mots' },
  theme: 'Holiday ads, hotel services, and building new words with -er and -ung',
  themeFr: 'Annonces de vacances, services d’hôtel et formation de mots avec -er et -ung',
  goals: ['Turn verbs into people with -er (wandern → Wanderer)', 'Turn verbs into nouns with -ung (beraten → Beratung)', 'Express wishes and offers with "würde" + infinitive', 'Understand and describe holiday places and hotel services'],
  goalsFr: ['Transformer des verbes en personnes avec -er (wandern → Wanderer)', 'Transformer des verbes en noms avec -ung (beraten → Beratung)', 'Exprimer des souhaits et des offres avec « würde » + infinitif', 'Comprendre et décrire des lieux de vacances et des services d’hôtel'],
  steps: [
    { kind: 'intro', title: 'Ruhe und Erholung 🏞️', titleFr: 'Calme et détente 🏞️',
      scene: 'You read a hotel brochure: "Wanderungen, Beratung, Erholung …" — and suddenly you can guess many new words.', sceneFr: 'Tu lis une brochure d’hôtel : « Wanderungen, Beratung, Erholung … » — et tu devines soudain beaucoup de mots nouveaux.',
      goals: ['Build persons with -er (and -in for women)', 'Build nouns with -ung (always "die")', 'Say what you would like to do: Ich würde gern …', 'Describe landscapes and hotel offers'],
      goalsFr: ['Former des personnes avec -er (et -in pour les femmes)', 'Former des noms avec -ung (toujours « die »)', 'Dire ce que tu aimerais faire : Ich würde gern …', 'Décrire des paysages et des offres d’hôtel'] },

    { kind: 'vocab', item: { id: 'a2l14-urlaub', german: 'der Urlaub', english: 'the holiday / vacation', french: 'les vacances', gender: 'der', syllables: ['UR', 'laub'], pronunciation: 'dair OOR-lowp', example: { de: 'Wir machen im Sommer Urlaub am Meer.', en: 'We take a holiday by the sea in summer.', fr: 'En été, nous partons en vacances à la mer.' } } },
    { kind: 'vocab', item: { id: 'a2l14-gast', german: 'der Gast', english: 'the guest', french: 'l’hôte / le client', gender: 'der', syllables: ['GAST'], pronunciation: 'dair gahst', example: { de: 'Die Gäste frühstücken auf der Terrasse.', en: 'The guests have breakfast on the terrace.', fr: 'Les clients prennent le petit-déjeuner sur la terrasse.' } } },
    { kind: 'vocab', item: { id: 'a2l14-wanderer', german: 'der Wanderer', english: 'the hiker', french: 'le randonneur', gender: 'der', syllables: ['WAN', 'de', 'rer'], pronunciation: 'dair VAHN-de-rer', example: { de: 'Der Wanderer macht eine Pause im Wald.', en: 'The hiker takes a break in the forest.', fr: 'Le randonneur fait une pause dans la forêt.' } } },
    { kind: 'vocab', item: { id: 'a2l14-wanderung', german: 'die Wanderung', english: 'the hike', french: 'la randonnée', gender: 'die', syllables: ['WAN', 'de', 'rung'], pronunciation: 'dee VAHN-de-roong', example: { de: 'Morgen machen wir eine lange Wanderung.', en: 'Tomorrow we are going on a long hike.', fr: 'Demain, nous faisons une longue randonnée.' } } },
    { kind: 'vocab', item: { id: 'a2l14-berater', german: 'der Berater', english: 'the advisor', french: 'le conseiller', gender: 'der', syllables: ['be', 'RA', 'ter'], pronunciation: 'dair be-RAH-ter', example: { de: 'Der Berater zeigt uns viele Angebote.', en: 'The advisor shows us many offers.', fr: 'Le conseiller nous montre beaucoup d’offres.' } } },
    { kind: 'vocab', item: { id: 'a2l14-beratung', german: 'die Beratung', english: 'the advice / consultation', french: 'le conseil / la consultation', gender: 'die', syllables: ['be', 'RA', 'tung'], pronunciation: 'dee be-RAH-toong', example: { de: 'An der Rezeption gibt es eine kostenlose Beratung.', en: 'There is free advice at the reception.', fr: 'À la réception, il y a un conseil gratuit.' } } },
    { kind: 'vocab', item: { id: 'a2l14-buchung', german: 'die Buchung', english: 'the booking', french: 'la réservation', gender: 'die', syllables: ['BU', 'chung'], pronunciation: 'dee BOO-khoong', example: { de: 'Ihre Buchung ist bestätigt.', en: 'Your booking is confirmed.', fr: 'Votre réservation est confirmée.' } } },
    { kind: 'vocab', item: { id: 'a2l14-uebernachtung', german: 'die Übernachtung', english: 'the overnight stay', french: 'la nuitée', gender: 'die', syllables: ['ü', 'ber', 'NACH', 'tung'], pronunciation: 'dee ue-ber-NAHKH-toong', example: { de: 'Die Übernachtung mit Frühstück kostet 80 Euro.', en: 'The overnight stay with breakfast costs 80 euros.', fr: 'La nuitée avec petit-déjeuner coûte 80 euros.' } } },
    { kind: 'vocab', item: { id: 'a2l14-angebot', german: 'das Angebot', english: 'the offer', french: 'l’offre', gender: 'das', syllables: ['AN', 'ge', 'bot'], pronunciation: 'dahs AHN-ge-boht', example: { de: 'Das Angebot für den Herbst ist günstig.', en: 'The autumn offer is cheap.', fr: 'L’offre pour l’automne est avantageuse.' } } },
    { kind: 'vocab', item: { id: 'a2l14-erholung', german: 'die Erholung', english: 'the relaxation / rest', french: 'le repos / la détente', gender: 'die', syllables: ['er', 'HO', 'lung'], pronunciation: 'dee er-HOH-loong', example: { de: 'Ich suche Ruhe und Erholung.', en: 'I am looking for peace and relaxation.', fr: 'Je cherche le calme et la détente.' } } },
    { kind: 'vocab', item: { id: 'a2l14-landschaft', german: 'die Landschaft', english: 'the landscape / scenery', french: 'le paysage', gender: 'die', syllables: ['LAND', 'schaft'], pronunciation: 'dee LAHNT-shahft', example: { de: 'Die Landschaft hier ist wunderschön.', en: 'The scenery here is beautiful.', fr: 'Le paysage ici est magnifique.' } } },
    { kind: 'vocab', item: { id: 'a2l14-wald', german: 'der Wald', english: 'the forest', french: 'la forêt', gender: 'der', syllables: ['WALD'], pronunciation: 'dair vahlt', example: { de: 'Hinter dem Hotel beginnt ein großer Wald.', en: 'A big forest begins behind the hotel.', fr: 'Derrière l’hôtel commence une grande forêt.' } } },
    { kind: 'vocab', item: { id: 'a2l14-wiese', german: 'die Wiese', english: 'the meadow', french: 'la prairie', gender: 'die', syllables: ['WIE', 'se'], pronunciation: 'dee VEE-ze', example: { de: 'Auf der Wiese stehen drei Kühe.', en: 'Three cows are standing in the meadow.', fr: 'Trois vaches se tiennent dans la prairie.' } } },
    { kind: 'vocab', item: { id: 'a2l14-ruhig', german: 'ruhig', english: 'quiet / calm', french: 'calme / tranquille', gender: null, syllables: ['RU', 'hig'], pronunciation: 'ROO-ikh', example: { de: 'Das Zimmer ist ruhig und hell.', en: 'The room is quiet and bright.', fr: 'La chambre est calme et lumineuse.' } } },

    { kind: 'grammar', note: {
      id: 'a2l14-er', title: 'Verb + -er = the person who does it', titleFr: 'Verbe + -er = la personne qui le fait',
      explanationMd: 'Take the verb stem and add **-er** to name the person (masculine, **der**). For a woman add **-in**:\n\n- wandern → **der Wanderer** / **die Wanderin**\n- beraten → **der Berater** / **die Beraterin**\n- fahren → **der Fahrer** · besuchen → **der Besucher**\n- verkaufen → **der Verkäufer** (often with an **umlaut**)\n\nThe plural of the -er nouns stays the same: die Wanderer, die Berater.',
      explanationMdFr: 'Prends le radical du verbe et ajoute **-er** pour nommer la personne (masculin, **der**). Pour une femme, ajoute **-in** :\n\n- wandern → **der Wanderer** / **die Wanderin**\n- beraten → **der Berater** / **die Beraterin**\n- fahren → **der Fahrer** · besuchen → **der Besucher**\n- verkaufen → **der Verkäufer** (souvent avec un **tréma**)\n\nLe pluriel des noms en -er reste identique : die Wanderer, die Berater.',
      examples: [
        { de: 'Wer wandert, ist ein Wanderer.', en: 'Someone who hikes is a hiker.', fr: 'Celui qui fait de la randonnée est un randonneur.' },
        { de: 'Die Beraterin hilft mir bei der Buchung.', en: 'The (female) advisor helps me with the booking.', fr: 'La conseillère m’aide pour la réservation.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l14-ung', title: 'Verb + -ung = a feminine noun', titleFr: 'Verbe + -ung = un nom féminin',
      explanationMd: 'Take the verb stem and add **-ung** to get a noun for the action or result. These nouns are **always "die"**; the plural ends in **-en**:\n\n- beraten → **die Beratung**\n- buchen → **die Buchung**\n- wandern → **die Wanderung**\n- übernachten → **die Übernachtung**\n- erholen (sich) → **die Erholung**\n\nHotel ads love these words: Wir bieten Beratung, Buchung und Erholung!',
      explanationMdFr: 'Prends le radical du verbe et ajoute **-ung** pour obtenir un nom d’action ou de résultat. Ces noms sont **toujours « die »** ; le pluriel se termine par **-en** :\n\n- beraten → **die Beratung**\n- buchen → **die Buchung**\n- wandern → **die Wanderung**\n- übernachten → **die Übernachtung**\n- erholen (sich) → **die Erholung**\n\nLes annonces d’hôtel adorent ces mots : Wir bieten Beratung, Buchung und Erholung !',
      examples: [
        { de: 'Wir buchen das Zimmer. Die Buchung ist einfach.', en: 'We book the room. The booking is easy.', fr: 'Nous réservons la chambre. La réservation est simple.' },
        { de: 'Die Wanderungen im Wald sind schön.', en: 'The hikes in the forest are lovely.', fr: 'Les randonnées dans la forêt sont belles.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l14-wuerde', title: 'Wishes and offers: würde + infinitive', titleFr: 'Souhaits et offres : würde + infinitif',
      explanationMd: 'To say what you **would like** to do, use **würde** + infinitive. The infinitive goes to the **end** of the sentence:\n\n- ich **würde** · du **würdest** · er/sie **würde**\n- wir **würden** · ihr **würdet** · sie/Sie **würden**\n\nAdd **gern** or **am liebsten** (most of all): Ich **würde** am liebsten im Wald **wandern**.\n\nHotels use it for polite offers: Wir **würden** Ihnen gern ein ruhiges Zimmer **anbieten**.',
      explanationMdFr: 'Pour dire ce que tu **aimerais** faire, utilise **würde** + infinitif. L’infinitif va **à la fin** de la phrase :\n\n- ich **würde** · du **würdest** · er/sie **würde**\n- wir **würden** · ihr **würdet** · sie/Sie **würden**\n\nAjoute **gern** ou **am liebsten** (surtout) : Ich **würde** am liebsten im Wald **wandern**.\n\nLes hôtels l’utilisent pour des offres polies : Wir **würden** Ihnen gern ein ruhiges Zimmer **anbieten**.',
      examples: [
        { de: 'Ich würde gern eine Woche am See bleiben.', en: 'I would like to stay at the lake for a week.', fr: 'J’aimerais rester une semaine au bord du lac.' },
        { de: 'Was würdest du am liebsten machen?', en: 'What would you like to do most of all?', fr: 'Qu’aimerais-tu faire par-dessus tout ?' },
      ] } },

    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l14-e1', word: 'Beratung', answer: 'die', hint: 'Nouns ending in -ung are always feminine.', hintFr: 'Les noms en -ung sont toujours féminins.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l14-e2', prompt: 'Someone who hikes (wandern) is a ___.', promptFr: 'Une personne qui fait de la randonnée (wandern) est un ___.', answer: 'Wanderer', hint: 'wander + er', hintFr: 'wander + er' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l14-e3', prompt: 'Which noun comes from the verb "buchen"?', promptFr: 'Quel nom vient du verbe « buchen » ?', options: ['die Buchung', 'der Bucher', 'das Buchen'], answer: 0, explain: 'buchen + -ung = die Buchung (the booking).', explainFr: 'buchen + -ung = die Buchung (la réservation).', hint: 'The action noun ends in -ung.', hintFr: 'Le nom d’action se termine en -ung.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l14-e4', pairs: [ { de: 'wandern', en: 'die Wanderung', fr: 'die Wanderung' }, { de: 'beraten', en: 'die Beratung', fr: 'die Beratung' }, { de: 'erholen', en: 'die Erholung', fr: 'die Erholung' } ], hint: 'Match each verb to its -ung noun.', hintFr: 'Associe chaque verbe à son nom en -ung.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l14-e5', tokens: ['wandern', 'Ich', 'würde', 'im', 'am', 'Wald', 'liebsten'], answer: ['Ich', 'würde', 'am', 'liebsten', 'im', 'Wald', 'wandern'], hint: 'The infinitive "wandern" goes to the very end.', hintFr: 'L’infinitif « wandern » va tout à la fin.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l14-e6', prompt: 'Listen. What would the couple like to do?', promptFr: 'Écoute. Qu’aimerait faire le couple ?', audio: { ttsText: 'Wir würden gern eine Woche am See bleiben und viel schlafen.' }, options: ['Stay a week at the lake', 'Spend a weekend in the city', 'Hike in the mountains'], optionsFr: ['Rester une semaine au bord du lac', 'Passer un week-end en ville', 'Faire de la randonnée en montagne'], answer: 0, hint: 'Listen for "eine Woche" and "am See".', hintFr: 'Écoute « eine Woche » et « am See ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l14-e7', prompt: 'Wir ___ gern ein ruhiges Zimmer buchen. (würde → wir)', promptFr: 'Wir ___ gern ein ruhiges Zimmer buchen. (würde → wir)', answer: 'würden', hint: 'wir → würden', hintFr: 'wir → würden' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l14-e8', prompt: 'Which word means "a man who advises"?', promptFr: 'Quel mot signifie « un homme qui conseille » ?', options: ['der Berater', 'die Beratung', 'das Beraten'], answer: 0, explain: 'The person ends in -er; the service ends in -ung.', explainFr: 'La personne se termine en -er ; le service se termine en -ung.', hint: 'A person: verb stem + -er.', hintFr: 'Une personne : radical + -er.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l14-e9', prompt: 'verkaufen → der ___ (the seller, with umlaut)', promptFr: 'verkaufen → der ___ (le vendeur, avec tréma)', answer: 'Verkäufer', hint: 'Ver-k-ä-ufer', hintFr: 'Ver-k-ä-ufer' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l14-e10', prompt: 'Listen to the hotel ad. What does the hotel offer?', promptFr: 'Écoute l’annonce de l’hôtel. Qu’offre-t-il ?', audio: { ttsText: 'Unser Hotel bietet Ruhe, Erholung und freundliche Beratung.' }, options: ['Peace, relaxation and friendly advice', 'A big swimming pool and a disco', 'Cheap flights and a rental car'], optionsFr: ['Du calme, de la détente et des conseils aimables', 'Une grande piscine et une discothèque', 'Des vols pas chers et une voiture de location'], answer: 0, hint: 'Listen for the three -ung / noun offers.', hintFr: 'Écoute les trois offres (noms).' } },

    { kind: 'pronunciation', focus: 'The ending -ung sounds like "oong" (short u + ng) — and -er is a soft, unstressed "uh".', focusFr: 'La terminaison -ung se prononce « oung » (u court + ng) — et -er est un « e » doux et non accentué.', items: [
      { id: 'a2l14-wanderung-pron', german: 'die Wanderung', english: 'the hike', french: 'la randonnée', gender: 'die', syllables: ['WAN', 'de', 'rung'], pronunciation: 'dee VAHN-de-roong', example: { de: 'Die Wanderung dauert drei Stunden.', en: 'The hike takes three hours.', fr: 'La randonnée dure trois heures.' } },
      { id: 'a2l14-beratung-pron', german: 'die Beratung', english: 'the advice', french: 'le conseil', gender: 'die', syllables: ['be', 'RA', 'tung'], pronunciation: 'dee be-RAH-toong', example: { de: 'Die Beratung ist kostenlos.', en: 'The advice is free.', fr: 'Le conseil est gratuit.' } },
      { id: 'a2l14-wanderer-pron', german: 'der Wanderer', english: 'the hiker', french: 'le randonneur', gender: 'der', syllables: ['WAN', 'de', 'rer'], pronunciation: 'dair VAHN-de-rer', example: { de: 'Der Wanderer trinkt Wasser.', en: 'The hiker drinks water.', fr: 'Le randonneur boit de l’eau.' } },
      { id: 'a2l14-uebernachtung-pron', german: 'die Übernachtung', english: 'the overnight stay', french: 'la nuitée', gender: 'die', syllables: ['ü', 'ber', 'NACH', 'tung'], pronunciation: 'dee ue-ber-NAHKH-toong', example: { de: 'Wir buchen zwei Übernachtungen.', en: 'We book two overnight stays.', fr: 'Nous réservons deux nuitées.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now read hotel ads and build words: verb + **-er** names the person (Wanderer, Berater; **-in** for women), verb + **-ung** gives a feminine noun (Wanderung, Beratung, Buchung). To express a wish, use **würde** + infinitive at the end: Ich **würde** am liebsten im Wald **wandern**. 🎉',
      summaryFr: 'Tu sais maintenant lire des annonces d’hôtel et former des mots : verbe + **-er** désigne la personne (Wanderer, Berater ; **-in** pour les femmes), verbe + **-ung** donne un nom féminin (Wanderung, Beratung, Buchung). Pour exprimer un souhait, utilise **würde** + infinitif à la fin : Ich **würde** am liebsten im Wald **wandern**. 🎉' },
  ],
};
