import type { Lesson } from '../types';

export const a2lektion22: Lesson = {
  id: 'a2-l22', level: 'A2', module: 3, number: 9,
  title: { de: 'Woher, wo, wohin?', en: 'Where from, where, where to?', fr: 'D’où, où, vers où ?' },
  theme: 'Places, people, cities and countries: aus / in / nach, von / bei / zu',
  themeFr: 'Lieux, personnes, villes et pays : aus / in / nach, von / bei / zu',
  goals: ['Ask and answer Woher? Wo? Wohin?', 'Use aus dem / im / ins for places', 'Use vom / beim / zum for people and errands', 'Use nach, in die and aus with cities and countries'],
  goalsFr: ['Poser et répondre à Woher ? Wo ? Wohin ?', 'Utiliser aus dem / im / ins pour les lieux', 'Utiliser vom / beim / zum pour les personnes et les courses', 'Utiliser nach, in die et aus avec les villes et les pays'],
  steps: [
    { kind: 'intro', title: 'Woher, wo, wohin? 🗺️', titleFr: 'D’où, où, vers où ? 🗺️',
      scene: 'A busy Saturday in town: Mia comes from the dentist, stops at the baker’s, and plans a trip to Switzerland.', sceneFr: 'Un samedi bien rempli en ville : Mia revient de chez le dentiste, passe chez le boulanger et prépare un voyage en Suisse.',
      goals: ['Choose aus / in / in for places', 'Choose von / bei / zu for people', 'Use the contractions vom, beim, zum, zur, im, ins', 'Say nach Spanien, in die Schweiz, in den Iran'],
      goalsFr: ['Choisir aus / in / in pour les lieux', 'Choisir von / bei / zu pour les personnes', 'Utiliser les contractions vom, beim, zum, zur, im, ins', 'Dire nach Spanien, in die Schweiz, in den Iran'] },

    { kind: 'vocab', item: { id: 'a2l22-zahnarzt', german: 'der Zahnarzt', english: 'the dentist', french: 'le dentiste', gender: 'der', syllables: ['ZAHN', 'arzt'], pronunciation: 'dair TSAHN-artst', example: { de: 'Ich gehe morgen zum Zahnarzt.', en: 'I’m going to the dentist tomorrow.', fr: 'Je vais chez le dentiste demain.' } } },
    { kind: 'vocab', item: { id: 'a2l22-baecker', german: 'der Bäcker', english: 'the baker', french: 'le boulanger', gender: 'der', syllables: ['BÄ', 'cker'], pronunciation: 'dair BECK-er', example: { de: 'Ich bin gerade beim Bäcker.', en: 'I’m at the baker’s right now.', fr: 'Je suis en ce moment chez le boulanger.' } } },
    { kind: 'vocab', item: { id: 'a2l22-friseur', german: 'der Friseur', english: 'the hairdresser', french: 'le coiffeur', gender: 'der', syllables: ['fri', 'SEUR'], pronunciation: 'dair free-ZOER', example: { de: 'Lina kommt gerade vom Friseur.', en: 'Lina is just back from the hairdresser’s.', fr: 'Lina revient tout juste de chez le coiffeur.' } } },
    { kind: 'vocab', item: { id: 'a2l22-apotheke', german: 'die Apotheke', english: 'the pharmacy', french: 'la pharmacie', gender: 'die', syllables: ['A', 'po', 'THE', 'ke'], pronunciation: 'dee ah-poh-TAY-keh', example: { de: 'Sie kommt aus der Apotheke.', en: 'She is coming out of the pharmacy.', fr: 'Elle sort de la pharmacie.' } } },
    { kind: 'vocab', item: { id: 'a2l22-post', german: 'die Post', english: 'the post office', french: 'la poste', gender: 'die', syllables: ['POST'], pronunciation: 'dee POST', example: { de: 'Ich gehe zur Post und hole ein Paket ab.', en: 'I’m going to the post office to pick up a parcel.', fr: 'Je vais à la poste chercher un colis.' } } },
    { kind: 'vocab', item: { id: 'a2l22-konzert', german: 'das Konzert', english: 'the concert', french: 'le concert', gender: 'das', syllables: ['kon', 'ZERT'], pronunciation: 'dahs kon-TSAIRT', example: { de: 'Wir gehen heute Abend ins Konzert.', en: 'We’re going to a concert this evening.', fr: 'Nous allons au concert ce soir.' } } },
    { kind: 'vocab', item: { id: 'a2l22-ausland', german: 'das Ausland', english: 'abroad / foreign countries', french: 'l’étranger', gender: 'das', syllables: ['AUS', 'land'], pronunciation: 'dahs OWSS-lahnt', example: { de: 'Mein Bruder lebt im Ausland.', en: 'My brother lives abroad.', fr: 'Mon frère vit à l’étranger.' } } },
    { kind: 'vocab', item: { id: 'a2l22-schweiz', german: 'die Schweiz', english: 'Switzerland', french: 'la Suisse', gender: 'die', syllables: ['SCHWEIZ'], pronunciation: 'dee shvites', example: { de: 'Im Winter fahren wir in die Schweiz.', en: 'In winter we go to Switzerland.', fr: 'En hiver, nous allons en Suisse.' } } },
    { kind: 'vocab', item: { id: 'a2l22-tuerkei', german: 'die Türkei', english: 'Turkey', french: 'la Turquie', gender: 'die', syllables: ['Tür', 'KEI'], pronunciation: 'dee tuer-KYE', example: { de: 'Meine Kollegin kommt aus der Türkei.', en: 'My colleague comes from Turkey.', fr: 'Ma collègue vient de Turquie.' } } },
    { kind: 'vocab', item: { id: 'a2l22-iran', german: 'der Iran', english: 'Iran', french: 'l’Iran', gender: 'der', syllables: ['i', 'RAN'], pronunciation: 'dair ee-RAHN', example: { de: 'Er fliegt im Mai in den Iran.', en: 'He flies to Iran in May.', fr: 'Il prend l’avion pour l’Iran en mai.' } } },
    { kind: 'vocab', item: { id: 'a2l22-spanien', german: 'Spanien', english: 'Spain', french: 'l’Espagne', gender: null, syllables: ['SPA', 'ni', 'en'], pronunciation: 'SHPAH-nee-en', example: { de: 'Im Sommer fahren wir nach Spanien.', en: 'In summer we’re going to Spain.', fr: 'En été, nous allons en Espagne.' } } },
    { kind: 'vocab', item: { id: 'a2l22-oma', german: 'die Oma', english: 'grandma', french: 'la grand-mère (mamie)', gender: 'die', syllables: ['O', 'ma'], pronunciation: 'dee OH-mah', example: { de: 'Am Sonntag sind wir bei meiner Oma.', en: 'On Sunday we’re at my grandma’s.', fr: 'Dimanche, nous sommes chez ma grand-mère.' } } },
    { kind: 'vocab', item: { id: 'a2l22-woher', german: 'woher', english: 'where from', french: 'd’où', gender: null, syllables: ['wo', 'HER'], pronunciation: 'voh-HAIR', example: { de: 'Woher kommst du?', en: 'Where are you from?', fr: 'D’où viens-tu ?' } } },
    { kind: 'vocab', item: { id: 'a2l22-wohin', german: 'wohin', english: 'where to', french: 'où (direction) / vers où', gender: null, syllables: ['wo', 'HIN'], pronunciation: 'voh-HIN', example: { de: 'Wohin gehst du heute?', en: 'Where are you going today?', fr: 'Où vas-tu aujourd’hui ?' } } },

    { kind: 'grammar', note: {
      id: 'a2l22-orte', title: 'Places: aus / in / in', titleFr: 'Les lieux : aus / in / in',
      explanationMd: 'For places you can go **into** (a building, a room, a shop), the pattern is:\n\n- **Woher?** → **aus** + dative: aus **dem** Kino, aus **der** Apotheke\n- **Wo?** → **in** + dative: **im** Kino (in + dem), in **der** Apotheke\n- **Wohin?** → **in** + accusative: **ins** Kino (in + das), in **die** Apotheke\n\nFor places you go **to** rather than enter, use **zu**: **zum** Bahnhof, **zur** Post, **zum** Flughafen. (zu + dem = **zum**, zu + der = **zur**)',
      explanationMdFr: 'Pour les lieux où l’on peut **entrer** (un bâtiment, une pièce, un magasin), le schéma est :\n\n- **Woher ?** → **aus** + datif : aus **dem** Kino, aus **der** Apotheke\n- **Wo ?** → **in** + datif : **im** Kino (in + dem), in **der** Apotheke\n- **Wohin ?** → **in** + accusatif : **ins** Kino (in + das), in **die** Apotheke\n\nPour les lieux où l’on va **vers** sans forcément entrer, utilise **zu** : **zum** Bahnhof, **zur** Post, **zum** Flughafen. (zu + dem = **zum**, zu + der = **zur**)',
      examples: [
        { de: 'Sie kommt aus der Apotheke.', en: 'She comes out of the pharmacy.', fr: 'Elle sort de la pharmacie.' },
        { de: 'Wir sind im Kino. Morgen gehen wir ins Konzert.', en: 'We are at the cinema. Tomorrow we go to a concert.', fr: 'Nous sommes au cinéma. Demain, nous allons au concert.' },
        { de: 'Ich fahre zum Bahnhof und dann zur Post.', en: 'I’m going to the station and then to the post office.', fr: 'Je vais à la gare, puis à la poste.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l22-personen', title: 'People and errands: von / bei / zu', titleFr: 'Les personnes et les courses : von / bei / zu',
      explanationMd: 'For **people** (and the professionals you visit) use **von / bei / zu** — always with the **dative**:\n\n- **Woher?** → **von**: **vom** Arzt, von der Ärztin, von Anna\n- **Wo?** → **bei**: **beim** Bäcker, bei meiner Oma, bei Anna\n- **Wohin?** → **zu**: **zum** Friseur, zu meiner Oma, zu Anna\n\nContractions: von + dem = **vom**, bei + dem = **beim**, zu + dem = **zum**, zu + der = **zur**.\n\nWatch out: never say "in den Arzt". For a person the answer to "Wohin?" is **zu** + dative, not in + accusative. In English you say "at the baker’s" — in German **beim Bäcker**.',
      explanationMdFr: 'Pour les **personnes** (et les professionnels chez qui on va), utilise **von / bei / zu** — toujours avec le **datif** :\n\n- **Woher ?** → **von** : **vom** Arzt, von der Ärztin, von Anna\n- **Wo ?** → **bei** : **beim** Bäcker, bei meiner Oma, bei Anna\n- **Wohin ?** → **zu** : **zum** Friseur, zu meiner Oma, zu Anna\n\nContractions : von + dem = **vom**, bei + dem = **beim**, zu + dem = **zum**, zu + der = **zur**.\n\nAttention : ne dis jamais « in den Arzt ». Pour une personne, la réponse à « Wohin ? » est **zu** + datif, pas in + accusatif. Le français dit « chez le boulanger » : en allemand, **beim Bäcker**.',
      examples: [
        { de: 'Lina kommt gerade vom Friseur.', en: 'Lina is just coming from the hairdresser’s.', fr: 'Lina arrive tout juste de chez le coiffeur.' },
        { de: 'Tom ist beim Zahnarzt.', en: 'Tom is at the dentist’s.', fr: 'Tom est chez le dentiste.' },
        { de: 'Am Sonntag fahren wir zu meiner Oma.', en: 'On Sunday we’re driving to my grandma’s.', fr: 'Dimanche, nous allons chez ma grand-mère.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l22-laender', title: 'Cities and countries: nach / in / aus', titleFr: 'Villes et pays : nach / in / aus',
      explanationMd: '**Cities and most countries have no article.** Then:\n\n- **Woher?** → **aus** Berlin, **aus** Spanien\n- **Wo?** → **in** Berlin, **in** Spanien\n- **Wohin?** → **nach** Berlin, **nach** Spanien\n\n**Countries with an article** (die Schweiz, die Türkei, der Iran, die USA) behave like ordinary places — **no "nach"**:\n\n- Wohin? → **in die** Schweiz · **in die** Türkei · **in den** Iran\n- Wo? → **in der** Schweiz · **in der** Türkei · **im** Iran\n- Woher? → **aus der** Schweiz · **aus der** Türkei · **aus dem** Iran',
      explanationMdFr: '**Les villes et la plupart des pays n’ont pas d’article.** Alors :\n\n- **Woher ?** → **aus** Berlin, **aus** Spanien\n- **Wo ?** → **in** Berlin, **in** Spanien\n- **Wohin ?** → **nach** Berlin, **nach** Spanien\n\n**Les pays avec article** (die Schweiz, die Türkei, der Iran, die USA) se comportent comme des lieux ordinaires — **pas de « nach »** :\n\n- Wohin ? → **in die** Schweiz · **in die** Türkei · **in den** Iran\n- Wo ? → **in der** Schweiz · **in der** Türkei · **im** Iran\n- Woher ? → **aus der** Schweiz · **aus der** Türkei · **aus dem** Iran',
      examples: [
        { de: 'Sie kommt aus Kamerun und wohnt jetzt in Hamburg.', en: 'She comes from Cameroon and now lives in Hamburg.', fr: 'Elle vient du Cameroun et habite maintenant à Hambourg.' },
        { de: 'Im Sommer fliegen wir nach Spanien.', en: 'In summer we fly to Spain.', fr: 'En été, nous prenons l’avion pour l’Espagne.' },
        { de: 'Meine Tante lebt in der Schweiz. Nächste Woche fahre ich in die Schweiz.', en: 'My aunt lives in Switzerland. Next week I’m going to Switzerland.', fr: 'Ma tante vit en Suisse. La semaine prochaine, je vais en Suisse.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l22-e1', prompt: 'Ich gehe ___ Zahnarzt. (zu + dem)', promptFr: 'Ich gehe ___ Zahnarzt. (zu + dem) — « Je vais chez le dentiste. »', answer: 'zum', hint: 'A person → zu; zu + dem = zum', hintFr: 'Une personne → zu ; zu + dem = zum' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l22-e2', prompt: 'Mia ist gerade ___ Bäcker. (bei + dem)', promptFr: 'Mia ist gerade ___ Bäcker. (bei + dem) — « Mia est chez le boulanger. »', answer: 'beim', hint: 'Wo? + a person → bei; bei + dem = beim', hintFr: 'Wo ? + une personne → bei ; bei + dem = beim' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l22-e3', prompt: 'Wir fliegen ___ Schweiz.', promptFr: 'Wir fliegen ___ Schweiz. (nous prenons l’avion pour la Suisse)', options: ['nach der', 'in die', 'in der'], answer: 1, explain: '"die Schweiz" has an article, so the direction is "in die". "nach" is only for places without an article.', explainFr: '« die Schweiz » a un article : la direction est donc « in die ». « nach » ne s’emploie que sans article.', hint: 'Countries with an article take in + accusative.', hintFr: 'Les pays avec article se construisent avec in + accusatif.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l22-e4', pairs: [ { de: 'beim Bäcker', en: 'at the baker’s', fr: 'chez le boulanger' }, { de: 'vom Arzt', en: 'from the doctor’s', fr: 'de chez le médecin' }, { de: 'zum Friseur', en: 'to the hairdresser’s', fr: 'aller chez le coiffeur' } ], hint: 'bei = at, von = from, zu = to.', hintFr: 'bei = chez (lieu), von = de chez, zu = vers / chez (direction).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l22-e5', prompt: 'Listen. Where is she going now?', promptFr: 'Écoute. Où va-t-elle maintenant ?', audio: { ttsText: 'Ich komme gerade vom Arzt und gehe jetzt zur Apotheke.' }, options: ['To the pharmacy', 'To the doctor', 'To the post office'], optionsFr: ['À la pharmacie', 'Chez le médecin', 'À la poste'], answer: 0, hint: '"vom" = from (where she was). "zur" = to (where she is going).', hintFr: '« vom » = d’où elle vient. « zur » = où elle va.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l22-e6', tokens: ['in', 'Ich', 'die', 'fahre', 'Türkei', 'im', 'Sommer'], answer: ['Ich', 'fahre', 'im', 'Sommer', 'in', 'die', 'Türkei'], hint: 'Start with "Ich fahre", then the time, then the place.', hintFr: 'Commence par « Ich fahre », puis le moment, puis le lieu.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l22-e7', prompt: 'Woher kommt Jan? — Er kommt aus ___ Schweiz. (die Schweiz, dative)', promptFr: 'D’où vient Jan ? — Er kommt aus ___ Schweiz. (die Schweiz, datif)', answer: 'der', hint: 'aus + dative: die → der', hintFr: 'aus + datif : die → der' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l22-e8', prompt: 'Am Samstag bin ich ___ meiner Oma.', promptFr: 'Am Samstag bin ich ___ meiner Oma. (samedi, je suis chez ma grand-mère)', options: ['zu', 'bei', 'in'], answer: 1, explain: 'Location with a person: bei + dative (Wo?). "zu" would be the direction.', explainFr: 'Lieu avec une personne : bei + datif (Wo ?). « zu » exprimerait la direction.', hint: 'You are already there: Wo? → bei.', hintFr: 'Tu y es déjà : Wo ? → bei.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l22-e9', prompt: 'Listen. Where do they go second?', promptFr: 'Écoute. Où vont-ils en deuxième ?', audio: { ttsText: 'Zuerst fahren wir nach Spanien, dann fliegen wir in die Türkei.' }, options: ['Turkey', 'Switzerland', 'Iran'], optionsFr: ['La Turquie', 'La Suisse', 'L’Iran'], answer: 0, hint: 'Listen after "dann".', hintFr: 'Écoute après « dann ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l22-e10', prompt: 'Wohin geht ihr heute Abend? — ___ Konzert! (in + das)', promptFr: 'Où allez-vous ce soir ? — ___ Konzert ! (in + das)', answer: 'ins', hint: 'Direction + das → ins (in + das)', hintFr: 'Direction + das → ins (in + das)' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l22-e11', prompt: 'Lina kommt gerade ___ Friseur.', promptFr: 'Lina kommt gerade ___ Friseur. (elle arrive de chez le coiffeur)', options: ['zum', 'beim', 'vom'], answer: 2, explain: 'Woher? + a person → von + dem = vom.', explainFr: 'Woher ? + une personne → von + dem = vom.', hint: '"Coming from" = von.', hintFr: '« Venir de » = von.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l22-e12', word: 'Türkei', answer: 'die', hint: 'Words ending in -ei are feminine.', hintFr: 'Les mots en -ei sont féminins.' } },

    { kind: 'pronunciation', focus: 'Contractions are said as one word (zum, beim, vom), and the ü in Türkei is a rounded "ee"', focusFr: 'Les contractions se prononcent d’un seul mot (zum, beim, vom), et le ü de Türkei est un « i » arrondi', items: [
      { id: 'a2l22-zum-pron', german: 'zum', english: 'to the (zu + dem)', french: 'vers le / chez le (zu + dem)', gender: null, syllables: ['ZUM'], pronunciation: 'tsoom', example: { de: 'Ich gehe zum Friseur.', en: 'I’m going to the hairdresser’s.', fr: 'Je vais chez le coiffeur.' } },
      { id: 'a2l22-beim-pron', german: 'beim', english: 'at the (bei + dem)', french: 'chez le (bei + dem)', gender: null, syllables: ['BEIM'], pronunciation: 'bime', example: { de: 'Er ist beim Bäcker.', en: 'He is at the baker’s.', fr: 'Il est chez le boulanger.' } },
      { id: 'a2l22-tuerkei-pron', german: 'die Türkei', english: 'Turkey', french: 'la Turquie', gender: 'die', syllables: ['Tür', 'KEI'], pronunciation: 'dee tuer-KYE', example: { de: 'Wir fliegen in die Türkei.', en: 'We fly to Turkey.', fr: 'Nous prenons l’avion pour la Turquie.' } },
      { id: 'a2l22-schweiz-pron', german: 'die Schweiz', english: 'Switzerland', french: 'la Suisse', gender: 'die', syllables: ['SCHWEIZ'], pronunciation: 'dee shvites', example: { de: 'Sie wohnt in der Schweiz.', en: 'She lives in Switzerland.', fr: 'Elle habite en Suisse.' } },
    ] },

    { kind: 'wrapup', summary: 'You now control the three questions: for **places**, **aus / in / in** (aus dem, im, ins); for **people and errands**, **von / bei / zu** (vom, beim, zum); for **cities and countries without article**, **aus / in / nach**. Countries with an article use **in die Schweiz, in den Iran** — never "nach". 🧭',
      summaryFr: 'Tu maîtrises maintenant les trois questions : pour les **lieux**, **aus / in / in** (aus dem, im, ins) ; pour les **personnes et les courses**, **von / bei / zu** (vom, beim, zum) ; pour les **villes et pays sans article**, **aus / in / nach**. Les pays avec article prennent **in die Schweiz, in den Iran** — jamais « nach ». 🧭' },
  ],
};
