import type { Lesson } from '../types';

export const a2lektion21: Lesson = {
  id: 'a2-l21', level: 'A2', module: 3, number: 11,
  title: { de: 'Geschenke und Verben mit Dativ und Akkusativ', en: 'Gifts and verbs with dative + accusative', fr: 'Cadeaux et verbes avec datif + accusatif' },
  theme: 'Verbs with two objects (dative + accusative), object order, and celebrations',
  themeFr: 'Verbes à deux compléments (datif + accusatif), ordre des compléments et fêtes',
  goals: ['Use verbs with two objects: schenken, geben, schicken, bringen, zeigen, empfehlen', 'Put the dative before the accusative with nouns', 'Put pronouns first: "Ich gebe es ihm"', 'Talk about presents, parties and birthdays'],
  goalsFr: ['Utiliser des verbes à deux compléments : schenken, geben, schicken, bringen, zeigen, empfehlen', 'Placer le datif avant l’accusatif avec des noms', 'Placer les pronoms en premier : « Ich gebe es ihm »', 'Parler de cadeaux, de fêtes et d’anniversaires'],
  steps: [
    { kind: 'intro', title: 'Was schenkst du wem? 🎂', titleFr: 'Que donnes-tu à qui ? 🎂',
      scene: 'Lena is turning 30! Her friends plan a surprise party, choose presents, send cards and decide who brings what.', sceneFr: 'Lena fête ses 30 ans ! Ses amis préparent une fête surprise, choisissent des cadeaux, envoient des cartes et décident qui apporte quoi.',
      goals: ['Name the receiver (dative) and the thing (accusative)', 'Order two nouns correctly', 'Replace nouns with pronouns', 'Congratulate and recommend'],
      goalsFr: ['Nommer celui qui reçoit (datif) et la chose (accusatif)', 'Ordonner correctement deux noms', 'Remplacer des noms par des pronoms', 'Féliciter et recommander'] },

    { kind: 'vocab', item: { id: 'a2l21-empfehlen', german: 'empfehlen', english: 'to recommend', french: 'recommander', gender: null, syllables: ['emp', 'FEH', 'len'], pronunciation: 'emp-FAY-len', example: { de: 'Kannst du mir ein Restaurant empfehlen?', en: 'Can you recommend a restaurant to me?', fr: 'Peux-tu me recommander un restaurant ?' } } },
    { kind: 'vocab', item: { id: 'a2l21-schicken', german: 'schicken', english: 'to send', french: 'envoyer', gender: null, syllables: ['SCHI', 'cken'], pronunciation: 'SHIK-en', example: { de: 'Ich schicke dir ein Foto.', en: 'I’m sending you a photo.', fr: 'Je t’envoie une photo.' } } },
    { kind: 'vocab', item: { id: 'a2l21-bringen', german: 'bringen', english: 'to bring', french: 'apporter', gender: null, syllables: ['BRIN', 'gen'], pronunciation: 'BRING-en', example: { de: 'Ich bringe dir morgen das Buch.', en: 'I’ll bring you the book tomorrow.', fr: 'Je t’apporte le livre demain.' } } },
    { kind: 'vocab', item: { id: 'a2l21-kaufen', german: 'kaufen', english: 'to buy', french: 'acheter', gender: null, syllables: ['KAU', 'fen'], pronunciation: 'KOW-fen', example: { de: 'Ich kaufe meiner Schwester eine Tasche.', en: 'I’m buying my sister a bag.', fr: 'J’achète un sac à ma sœur.' } } },
    { kind: 'vocab', item: { id: 'a2l21-leihen', german: 'leihen', english: 'to lend', french: 'prêter', gender: null, syllables: ['LEI', 'hen'], pronunciation: 'LY-en', example: { de: 'Kannst du mir dein Fahrrad leihen?', en: 'Can you lend me your bike?', fr: 'Peux-tu me prêter ton vélo ?' } } },
    { kind: 'vocab', item: { id: 'a2l21-feier', german: 'die Feier', english: 'the celebration / party', french: 'la fête', gender: 'die', syllables: ['FEI', 'er'], pronunciation: 'dee FY-er', example: { de: 'Die Feier beginnt um acht Uhr.', en: 'The party starts at eight o’clock.', fr: 'La fête commence à vingt heures.' } } },
    { kind: 'vocab', item: { id: 'a2l21-ueberraschung', german: 'die Überraschung', english: 'the surprise', french: 'la surprise', gender: 'die', syllables: ['ü', 'ber', 'RA', 'schung'], pronunciation: 'dee ue-ber-RASH-oong', example: { de: 'Die Party ist eine Überraschung für Lena.', en: 'The party is a surprise for Lena.', fr: 'La fête est une surprise pour Lena.' } } },
    { kind: 'vocab', item: { id: 'a2l21-gast', german: 'der Gast', english: 'the guest', french: 'l’invité', gender: 'der', syllables: ['GAST'], pronunciation: 'dair gahst', example: { de: 'Alle Gäste bringen etwas mit.', en: 'All the guests bring something.', fr: 'Tous les invités apportent quelque chose.' } } },
    { kind: 'vocab', item: { id: 'a2l21-torte', german: 'die Torte', english: 'the cake (layered)', french: 'le gâteau', gender: 'die', syllables: ['TOR', 'te'], pronunciation: 'dee TOR-teh', example: { de: 'Wer backt die Torte?', en: 'Who is baking the cake?', fr: 'Qui prépare le gâteau ?' } } },
    { kind: 'vocab', item: { id: 'a2l21-karte', german: 'die Karte', english: 'the card', french: 'la carte', gender: 'die', syllables: ['KAR', 'te'], pronunciation: 'dee KAR-teh', example: { de: 'Ich schreibe dir eine Karte.', en: 'I’ll write you a card.', fr: 'Je t’écrirai une carte.' } } },
    { kind: 'vocab', item: { id: 'a2l21-paket', german: 'das Paket', english: 'the parcel', french: 'le colis', gender: 'das', syllables: ['pa', 'KET'], pronunciation: 'dahs pa-KAYT', example: { de: 'Das Paket kommt morgen an.', en: 'The parcel arrives tomorrow.', fr: 'Le colis arrive demain.' } } },
    { kind: 'vocab', item: { id: 'a2l21-gratulieren', german: 'gratulieren', english: 'to congratulate (+ dative)', french: 'féliciter (+ datif)', gender: null, syllables: ['gra', 'tu', 'LIE', 'ren'], pronunciation: 'grah-too-LEE-ren', example: { de: 'Ich gratuliere dir zum Geburtstag.', en: 'Happy birthday to you! (lit. I congratulate you on your birthday.)', fr: 'Je te souhaite un joyeux anniversaire ! (litt. je te félicite pour ton anniversaire.)' } } },
    { kind: 'vocab', item: { id: 'a2l21-verpacken', german: 'verpacken', english: 'to wrap / pack', french: 'emballer', gender: null, syllables: ['ver', 'PA', 'cken'], pronunciation: 'fair-PAK-en', example: { de: 'Ich verpacke das Geschenk.', en: 'I’m wrapping the present.', fr: 'J’emballe le cadeau.' } } },

    { kind: 'grammar', note: {
      id: 'a2l21-zwei-objekte', title: 'Verbs with two objects', titleFr: 'Les verbes à deux compléments',
      explanationMd: 'Many verbs of giving, showing and telling have **two objects**:\n\n- the **person** who receives → **dative** (wem?)\n- the **thing** → **accusative** (was?)\n\n**geben, schenken, schicken, bringen, zeigen, empfehlen, kaufen, leihen, erklären**\n\n| | der | die | das | plural |\n|---|---|---|---|---|\n| Dativ (person) | dem | der | dem | den |\n| Akkusativ (thing) | den | die | das | die |\n\nIch schicke **der** Freundin **einen** Brief. (die Freundin → dative **der**; der Brief → accusative **einen**)',
      explanationMdFr: 'Beaucoup de verbes qui expriment donner, montrer ou dire ont **deux compléments** :\n\n- la **personne** qui reçoit → **datif** (wem ?)\n- la **chose** → **accusatif** (was ?)\n\n**geben, schenken, schicken, bringen, zeigen, empfehlen, kaufen, leihen, erklären**\n\n| | der | die | das | pluriel |\n|---|---|---|---|---|\n| Dativ (personne) | dem | der | dem | den |\n| Akkusativ (chose) | den | die | das | die |\n\nIch schicke **der** Freundin **einen** Brief. (die Freundin → datif **der** ; der Brief → accusatif **einen**)',
      examples: [
        { de: 'Ich schenke meiner Mutter einen Schal.', en: 'I’m giving my mother a scarf.', fr: 'J’offre une écharpe à ma mère.' },
        { de: 'Der Kellner empfiehlt den Gästen die Suppe.', en: 'The waiter recommends the soup to the guests.', fr: 'Le serveur recommande la soupe aux invités.' },
        { de: 'Sie zeigt ihrem Bruder das Zimmer.', en: 'She shows her brother the room.', fr: 'Elle montre la chambre à son frère.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l21-reihenfolge', title: 'Order of two nouns: dative first', titleFr: 'Ordre de deux noms : datif d’abord',
      explanationMd: 'When **both objects are nouns**, the usual order is **Dativ (person) → Akkusativ (thing)**:\n\n- Ich gebe **dem Kind** **den Ball**.\n- Er kauft **seiner Freundin** **Blumen**.\n\nThe verb stays in position 2, the objects follow the subject. With **time words**, they usually come before the objects: Ich schicke dir **morgen** ein Paket.\n\nAlternative for gifts: **für + accusative** — Ich kaufe **ein Geschenk für meine Mutter**.',
      explanationMdFr: 'Quand les **deux compléments sont des noms**, l’ordre habituel est **datif (personne) → accusatif (chose)** :\n\n- Ich gebe **dem Kind** **den Ball**.\n- Er kauft **seiner Freundin** **Blumen**.\n\nLe verbe reste en position 2, les compléments suivent le sujet. Les **indications de temps** viennent en général avant les compléments : Ich schicke dir **morgen** ein Paket.\n\nAlternative pour les cadeaux : **für + accusatif** — Ich kaufe **ein Geschenk für meine Mutter**.',
      examples: [
        { de: 'Wir schenken dem Geburtstagskind eine Torte.', en: 'We are giving the birthday child a cake.', fr: 'Nous offrons un gâteau à la personne dont c’est l’anniversaire.' },
        { de: 'Ich schicke meinem Freund eine Karte.', en: 'I’m sending my friend a card.', fr: 'J’envoie une carte à mon ami.' },
        { de: 'Er kauft ein Geschenk für seine Schwester.', en: 'He buys a present for his sister.', fr: 'Il achète un cadeau pour sa sœur.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l21-pronomen', title: 'With pronouns: Ich gebe es ihm', titleFr: 'Avec des pronoms : Ich gebe es ihm',
      explanationMd: '**Pronouns come before nouns.** When both objects are pronouns, the order flips: **Akkusativ → Dativ**.\n\n- Ich gebe dem Kind das Buch.\n- Ich gebe **es** dem Kind. (accusative pronoun first)\n- Ich gebe **ihm** das Buch. (dative pronoun first)\n- Ich gebe **es ihm**. (both pronouns: **Akk + Dat**)\n\nAccusative pronouns: der → **ihn** · die → **sie** · das → **es** · plural → **sie**.\nDative pronouns: **mir, dir, ihm, ihr, ihm, uns, euch, ihnen** (you know them from the dative lesson).',
      explanationMdFr: '**Les pronoms passent avant les noms.** Quand les deux compléments sont des pronoms, l’ordre s’inverse : **accusatif → datif**.\n\n- Ich gebe dem Kind das Buch.\n- Ich gebe **es** dem Kind. (pronom à l’accusatif d’abord)\n- Ich gebe **ihm** das Buch. (pronom au datif d’abord)\n- Ich gebe **es ihm**. (deux pronoms : **acc. + dat.**)\n\nPronoms à l’accusatif : der → **ihn** · die → **sie** · das → **es** · pluriel → **sie**.\nPronoms au datif : **mir, dir, ihm, ihr, ihm, uns, euch, ihnen** (tu les connais de la leçon sur le datif).',
      examples: [
        { de: 'Das Geschenk? Ich gebe es ihr morgen.', en: 'The present? I’ll give it to her tomorrow.', fr: 'Le cadeau ? Je le lui donne demain.' },
        { de: 'Die Karte? Ich schicke sie dir heute.', en: 'The card? I’m sending it to you today.', fr: 'La carte ? Je te l’envoie aujourd’hui.' },
        { de: 'Den Kuchen bringe ich euch am Samstag.', en: 'I’ll bring you the cake on Saturday.', fr: 'Je vous apporte le gâteau samedi.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l21-e1', prompt: 'Ich schenke ___ Mutter ein Buch. (die Mutter → dative, my)', promptFr: 'Ich schenke ___ Mutter ein Buch. (die Mutter → datif, mon/ma)', answer: 'meiner', hint: 'Feminine dative: meiner (like der).', hintFr: 'Datif féminin : meiner (comme der).' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l21-e2', prompt: 'Which sentence has the correct order of the two nouns?', promptFr: 'Quelle phrase a le bon ordre des deux noms ?', options: ['Ich schenke einen Schal meiner Mutter.', 'Ich schenke meiner Mutter einen Schal.', 'Ich schenke meine Mutter einen Schal.'], optionsFr: ['Ich schenke einen Schal meiner Mutter.', 'Ich schenke meiner Mutter einen Schal.', 'Ich schenke meine Mutter einen Schal.'], answer: 1, explain: 'Dative (person) first, then accusative (thing) — and "Mutter" needs the dative "meiner".', explainFr: 'Datif (personne) d’abord, puis accusatif (chose) — et « Mutter » demande le datif « meiner ».', hint: 'Person before thing.', hintFr: 'La personne avant la chose.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l21-e3', tokens: ['schicke', 'Ich', 'Freund', 'eine', 'meinem', 'Karte'], answer: ['Ich', 'schicke', 'meinem', 'Freund', 'eine', 'Karte'], hint: 'Subject, verb, dative (person), accusative (thing).', hintFr: 'Sujet, verbe, datif (personne), accusatif (chose).' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l21-e4', pairs: [ { de: 'empfehlen', en: 'to recommend', fr: 'recommander' }, { de: 'schicken', en: 'to send', fr: 'envoyer' }, { de: 'bringen', en: 'to bring', fr: 'apporter' }, { de: 'leihen', en: 'to lend', fr: 'prêter' } ], hint: 'All four take a dative and an accusative object.', hintFr: 'Les quatre prennent un complément au datif et un à l’accusatif.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l21-e5', prompt: 'Listen. What will the speaker do?', promptFr: 'Écoute. Que va faire le locuteur ?', audio: { ttsText: 'Ich bringe dir morgen das Paket.' }, options: ['Bring the parcel tomorrow', 'Send the parcel yesterday', 'Buy a parcel'], optionsFr: ['Apporter le colis demain', 'Envoyer le colis hier', 'Acheter un colis'], answer: 0, hint: 'Listen for "bringe" and "morgen".', hintFr: 'Écoute « bringe » et « morgen ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l21-e6', prompt: 'Ich gebe das Buch meinem Bruder. → Ich gebe ___ ihm. (das Buch → pronoun)', promptFr: 'Ich gebe das Buch meinem Bruder. → Ich gebe ___ ihm. (das Buch → pronom)', answer: 'es', hint: 'Accusative pronoun for das: es.', hintFr: 'Pronom à l’accusatif pour das : es.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l21-e7', prompt: 'Sie zeigt ___ das Foto. (to me)', promptFr: 'Sie zeigt ___ das Foto. (à moi)', answer: 'mir', hint: 'Dative pronoun for "ich".', hintFr: 'Pronom au datif pour « ich ».' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l21-e8', word: 'Torte', answer: 'die', hint: 'Feminine: die Torte, die Torten.', hintFr: 'Féminin : die Torte, die Torten.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l21-e9', prompt: 'Which verb takes only a dative object (no accusative)?', promptFr: 'Quel verbe ne prend qu’un complément au datif (pas d’accusatif) ?', options: ['gratulieren', 'schenken', 'bringen'], optionsFr: ['gratulieren', 'schenken', 'bringen'], answer: 0, explain: '"Ich gratuliere dir" — only a dative. schenken and bringen have two objects.', explainFr: '« Ich gratuliere dir » — seulement un datif. schenken et bringen ont deux compléments.', hint: 'Think of "Ich gratuliere dir zum Geburtstag."', hintFr: 'Pense à « Ich gratuliere dir zum Geburtstag. »' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l21-e10', tokens: ['es', 'Ich', 'ihr', 'schenke'], answer: ['Ich', 'schenke', 'es', 'ihr'], hint: 'Two pronouns: accusative (es) before dative (ihr).', hintFr: 'Deux pronoms : accusatif (es) avant datif (ihr).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l21-e11', prompt: 'Listen. What is the speaker asking for?', promptFr: 'Écoute. Que demande le locuteur ?', audio: { ttsText: 'Kannst du mir ein Buch empfehlen?' }, options: ['A book recommendation', 'To borrow a book', 'A book as a gift'], optionsFr: ['Une recommandation de livre', 'Emprunter un livre', 'Un livre en cadeau'], answer: 0, hint: 'Listen for the verb at the end.', hintFr: 'Écoute le verbe à la fin.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l21-e12', prompt: 'Ich schenke meiner Mutter ___ Schal. (der Schal → a, accusative)', promptFr: 'Ich schenke meiner Mutter ___ Schal. (der Schal → un, accusatif)', answer: 'einen', hint: 'Masculine accusative: ein → einen.', hintFr: 'Masculin à l’accusatif : ein → einen.' } },

    { kind: 'pronunciation', focus: 'Stress on the second syllable (empfehlen, verpacken, Paket) and the ü in Überraschung', focusFr: 'Accent sur la deuxième syllabe (empfehlen, verpacken, Paket) et le ü de Überraschung', items: [
      { id: 'a2l21-empfehlen-pron', german: 'empfehlen', english: 'to recommend', french: 'recommander', gender: null, syllables: ['emp', 'FEH', 'len'], pronunciation: 'emp-FAY-len', example: { de: 'Was kannst du empfehlen?', en: 'What can you recommend?', fr: 'Que peux-tu recommander ?' } },
      { id: 'a2l21-verpacken-pron', german: 'verpacken', english: 'to wrap', french: 'emballer', gender: null, syllables: ['ver', 'PA', 'cken'], pronunciation: 'fair-PAK-en', example: { de: 'Ich verpacke das Geschenk schön.', en: 'I wrap the present nicely.', fr: 'J’emballe joliment le cadeau.' } },
      { id: 'a2l21-paket-pron', german: 'das Paket', english: 'the parcel', french: 'le colis', gender: 'das', syllables: ['pa', 'KET'], pronunciation: 'dahs pa-KAYT', example: { de: 'Das Paket ist schwer.', en: 'The parcel is heavy.', fr: 'Le colis est lourd.' } },
      { id: 'a2l21-ueberraschung-pron', german: 'die Überraschung', english: 'the surprise', french: 'la surprise', gender: 'die', syllables: ['ü', 'ber', 'RA', 'schung'], pronunciation: 'dee ue-ber-RASH-oong', example: { de: 'Das ist eine tolle Überraschung!', en: 'That is a great surprise!', fr: 'Quelle belle surprise !' } },
    ] },

    { kind: 'wrapup', summary: 'You can now use verbs with **two objects**: the person takes the **dative**, the thing the **accusative** (**Ich schenke meiner Mutter einen Schal**). With two nouns the **dative comes first**; pronouns come before nouns, and with two pronouns it is **Akkusativ → Dativ** (**Ich gebe es ihm**). You also know the vocabulary for parties, presents and congratulations. 🎁',
      summaryFr: 'Tu sais maintenant utiliser des verbes à **deux compléments** : la personne est au **datif**, la chose à l’**accusatif** (**Ich schenke meiner Mutter einen Schal**). Avec deux noms, le **datif vient en premier** ; les pronoms passent avant les noms, et avec deux pronoms c’est **accusatif → datif** (**Ich gebe es ihm**). Tu connais aussi le vocabulaire des fêtes, des cadeaux et des félicitations. 🎁' },
  ],
};
