import type { Lesson } from '../types';

export const a2lektion18: Lesson = {
  id: 'a2-l18', level: 'A2', module: 2, number: 6,
  title: { de: 'Vorschläge machen', en: 'Making suggestions', fr: 'Faire des propositions' },
  theme: 'Suggestions and advice with könnte / sollte, sport and leisure, and time adverbs like "montags"',
  themeFr: 'Propositions et conseils avec könnte / sollte, sport et loisirs, et adverbes de temps comme « montags »',
  goals: ['Suggest something with "Wir könnten …"', 'Give advice with "Du solltest …"', 'Agree and disagree politely', 'Say when you do things with montags, abends, vormittags'],
  goalsFr: ['Proposer quelque chose avec « Wir könnten … »', 'Donner un conseil avec « Du solltest … »', 'Accepter et refuser poliment', 'Dire quand on fait les choses avec montags, abends, vormittags'],
  steps: [
    { kind: 'intro', title: 'Wir könnten joggen gehen! 🏃', titleFr: 'On pourrait aller courir ! 🏃',
      scene: 'Mia and Jonas want to get fit. They plan a weekly routine, swap ideas and give each other advice.', sceneFr: 'Mia et Jonas veulent se remettre en forme. Ils planifient leur semaine, échangent des idées et se donnent des conseils.',
      goals: ['Use könnte to suggest an activity', 'Use sollte to give friendly advice', 'React to a suggestion politely', 'Use montags / abends / vormittags for routines'],
      goalsFr: ['Utiliser könnte pour proposer une activité', 'Utiliser sollte pour donner un conseil amical', 'Réagir poliment à une proposition', 'Utiliser montags / abends / vormittags pour les habitudes'] },

    { kind: 'vocab', item: { id: 'a2l18-vorschlag', german: 'der Vorschlag', english: 'the suggestion', french: 'la proposition', gender: 'der', syllables: ['VOR', 'schlag'], pronunciation: 'dair FOR-shlahk', example: { de: 'Ich habe einen Vorschlag.', en: 'I have a suggestion.', fr: 'J’ai une proposition.' } } },
    { kind: 'vocab', item: { id: 'a2l18-rat', german: 'der Rat', english: 'the advice', french: 'le conseil', gender: 'der', syllables: ['RAT'], pronunciation: 'dair raht', example: { de: 'Ich brauche deinen Rat.', en: 'I need your advice.', fr: 'J’ai besoin de ton conseil.' } } },
    { kind: 'vocab', item: { id: 'a2l18-joggen', german: 'joggen', english: 'to jog', french: 'faire du jogging', gender: null, syllables: ['JOG', 'gen'], pronunciation: 'JOG-en', example: { de: 'Ich jogge gern im Park.', en: 'I like jogging in the park.', fr: 'J’aime faire du jogging dans le parc.' } } },
    { kind: 'vocab', item: { id: 'a2l18-trainieren', german: 'trainieren', english: 'to train / work out', french: 's’entraîner', gender: null, syllables: ['tra', 'NIE', 'ren'], pronunciation: 'trah-NEE-ren', example: { de: 'Wir trainieren zweimal pro Woche.', en: 'We work out twice a week.', fr: 'Nous nous entraînons deux fois par semaine.' } } },
    { kind: 'vocab', item: { id: 'a2l18-fitnessstudio', german: 'das Fitnessstudio', english: 'the gym', french: 'la salle de sport', gender: 'das', syllables: ['FIT', 'ness', 'STU', 'dio'], pronunciation: 'dahs FIT-ness-shtoo-dee-oh', example: { de: 'Das Fitnessstudio liegt neben dem Bahnhof.', en: 'The gym is next to the station.', fr: 'La salle de sport est à côté de la gare.' } } },
    { kind: 'vocab', item: { id: 'a2l18-verein', german: 'der Verein', english: 'the club (association)', french: 'le club / l’association', gender: 'der', syllables: ['ver', 'EIN'], pronunciation: 'dair fair-INE', example: { de: 'Mein Bruder ist im Sportverein.', en: 'My brother is in the sports club.', fr: 'Mon frère est dans le club de sport.' } } },
    { kind: 'vocab', item: { id: 'a2l18-gesund', german: 'gesund', english: 'healthy', french: 'sain / en bonne santé', gender: null, syllables: ['ge', 'SUND'], pronunciation: 'ge-ZOONT', example: { de: 'Obst und Gemüse sind gesund.', en: 'Fruit and vegetables are healthy.', fr: 'Les fruits et les légumes sont sains.' } } },
    { kind: 'vocab', item: { id: 'a2l18-regelmaessig', german: 'regelmäßig', english: 'regularly', french: 'régulièrement', gender: null, syllables: ['RE', 'gel', 'mä', 'ßig'], pronunciation: 'RAY-gel-may-sikh', example: { de: 'Ich trainiere regelmäßig.', en: 'I work out regularly.', fr: 'Je m’entraîne régulièrement.' } } },
    { kind: 'vocab', item: { id: 'a2l18-abnehmen', german: 'abnehmen', english: 'to lose weight', french: 'perdre du poids / maigrir', gender: null, syllables: ['AB', 'neh', 'men'], pronunciation: 'AHP-nay-men', example: { de: 'Er will zwei Kilo abnehmen.', en: 'He wants to lose two kilos.', fr: 'Il veut perdre deux kilos.' } } },
    { kind: 'vocab', item: { id: 'a2l18-montags', german: 'montags', english: 'on Mondays (every Monday)', french: 'le lundi (chaque lundi)', gender: null, syllables: ['MON', 'tags'], pronunciation: 'MOHN-tahks', example: { de: 'Montags gehe ich schwimmen.', en: 'On Mondays I go swimming.', fr: 'Le lundi, je vais nager.' } } },
    { kind: 'vocab', item: { id: 'a2l18-vormittags', german: 'vormittags', english: 'in the morning (before noon)', french: 'le matin (avant midi)', gender: null, syllables: ['VOR', 'mit', 'tags'], pronunciation: 'FOR-mit-tahks', example: { de: 'Vormittags arbeite ich, nachmittags trainiere ich.', en: 'In the morning I work, in the afternoon I work out.', fr: 'Le matin je travaille, l’après-midi je m’entraîne.' } } },
    { kind: 'vocab', item: { id: 'a2l18-einverstanden', german: 'einverstanden', english: 'agreed / fine by me', french: 'd’accord', gender: null, syllables: ['EIN', 'ver', 'stan', 'den'], pronunciation: 'INE-fair-shtahn-den', example: { de: 'Einverstanden! Dann bis Montag.', en: 'Agreed! See you Monday, then.', fr: 'D’accord ! Alors à lundi.' } } },
    { kind: 'vocab', item: { id: 'a2l18-wie-waere-es', german: 'Wie wäre es mit …?', english: 'How about …?', french: 'Et si on faisait … ? / Que dirais-tu de … ?', gender: null, syllables: ['wie', 'WÄ', 're', 'es', 'mit'], pronunciation: 'vee VAY-reh ess mit', example: { de: 'Wie wäre es mit einem Spaziergang?', en: 'How about a walk?', fr: 'Que dirais-tu d’une promenade ?' } } },

    { kind: 'grammar', note: {
      id: 'a2l18-koennte-sollte', title: 'Suggestions and advice: könnte / sollte', titleFr: 'Propositions et conseils : könnte / sollte',
      explanationMd: 'To make a **polite suggestion**, use **könnte** (could). For **friendly advice**, use **sollte** (should). Both are modal verbs, so the second verb goes to the **end** as an infinitive.\n\n- **ich**: könnte / sollte\n- **du**: könntest / solltest\n- **er/sie/es**: könnte / sollte\n- **wir**: könnten / sollten\n- **ihr**: könntet / solltet\n- **sie/Sie**: könnten / sollten\n\n- **Wir könnten** montags joggen **gehen**. — We could go jogging on Mondays.\n- **Du solltest** mehr Wasser **trinken**. — You should drink more water.\n\nWatch out: **konnte** (past) ≠ **könnte** (suggestion) — the umlaut matters! For **sollen**, the form **sollte** looks like the past tense, but in a suggestion it refers to the present or future.',
      explanationMdFr: 'Pour faire une **proposition polie**, utilise **könnte** (pourrait). Pour un **conseil amical**, utilise **sollte** (devrait). Ce sont des verbes modaux : le second verbe va à la **fin**, à l’infinitif.\n\n- **ich**: könnte / sollte\n- **du**: könntest / solltest\n- **er/sie/es**: könnte / sollte\n- **wir**: könnten / sollten\n- **ihr**: könntet / solltet\n- **sie/Sie**: könnten / sollten\n\n- **Wir könnten** montags joggen **gehen**. — On pourrait aller courir le lundi.\n- **Du solltest** mehr Wasser **trinken**. — Tu devrais boire plus d’eau.\n\nAttention : **konnte** (passé) ≠ **könnte** (proposition) — le tréma compte ! Pour **sollen**, la forme **sollte** ressemble au passé, mais dans une proposition elle renvoie au présent ou au futur.',
      examples: [
        { de: 'Wir könnten am Samstag schwimmen gehen.', en: 'We could go swimming on Saturday.', fr: 'Nous pourrions aller nager samedi.' },
        { de: 'Du solltest regelmäßig trainieren.', en: 'You should work out regularly.', fr: 'Tu devrais t’entraîner régulièrement.' },
        { de: 'Ihr solltet früher ins Bett gehen.', en: 'You should go to bed earlier.', fr: 'Vous devriez vous coucher plus tôt.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l18-reagieren', title: 'Suggesting, agreeing, disagreeing politely', titleFr: 'Proposer, accepter, refuser poliment',
      explanationMd: '**Making a suggestion:**\n- **Wir könnten** … + infinitive\n- **Wie wäre es mit** + dative noun: Wie wäre es **mit einem** Spaziergang? (mit always takes the dative)\n- **An deiner Stelle würde ich** … + infinitive — If I were you, I would …\n\n**Agreeing:** Gute Idee! · Einverstanden! · Das machen wir.\n\n**Disagreeing politely** — give a reason or an alternative:\n- Das passt mir leider nicht. Wie wäre es mit Dienstag?\n- Hm, ich würde lieber schwimmen gehen.\n- Das ist nicht so mein Ding, aber ich komme gern mit.',
      explanationMdFr: '**Faire une proposition :**\n- **Wir könnten** … + infinitif\n- **Wie wäre es mit** + nom au datif : Wie wäre es **mit einem** Spaziergang ? (mit prend toujours le datif)\n- **An deiner Stelle würde ich** … + infinitif — À ta place, je …\n\n**Accepter :** Gute Idee ! · Einverstanden ! · Das machen wir.\n\n**Refuser poliment** — donne une raison ou une alternative :\n- Das passt mir leider nicht. Wie wäre es mit Dienstag ?\n- Hm, ich würde lieber schwimmen gehen.\n- Das ist nicht so mein Ding, aber ich komme gern mit.',
      examples: [
        { de: 'Wie wäre es mit einem Kurs im Fitnessstudio?', en: 'How about a class at the gym?', fr: 'Que dirais-tu d’un cours à la salle de sport ?' },
        { de: 'An deiner Stelle würde ich mehr schlafen.', en: 'If I were you, I would sleep more.', fr: 'À ta place, je dormirais plus.' },
        { de: 'Sonntags passt mir leider nicht. Geht es auch samstags?', en: 'Sundays don’t suit me, unfortunately. Does Saturday work too?', fr: 'Le dimanche, ça ne me convient malheureusement pas. Samedi, ça marche aussi ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'a2l18-zeitadverbien', title: 'Routines: montags, morgens, abends …', titleFr: 'Habitudes : montags, morgens, abends …',
      explanationMd: 'Add **-s** to a day or part of the day to say it happens **regularly**:\n\n- **montags** = jeden Montag (every Monday) · **samstags** = every Saturday\n- **morgens** (in the morning) · **vormittags** · **mittags** · **nachmittags** · **abends** · **nachts**\n\nCompare: **am Montag** = this one Monday; **montags** = every Monday.\n\nYou can combine them: **montags abends**. For a time window use **zwischen** + dative: zwischen 18 und 19 Uhr.',
      explanationMdFr: 'Ajoute **-s** à un jour ou à un moment de la journée pour dire que cela arrive **régulièrement** :\n\n- **montags** = jeden Montag (chaque lundi) · **samstags** = chaque samedi\n- **morgens** (le matin) · **vormittags** · **mittags** · **nachmittags** · **abends** · **nachts**\n\nComparaison : **am Montag** = ce lundi précis ; **montags** = tous les lundis.\n\nTu peux les combiner : **montags abends**. Pour une plage horaire, utilise **zwischen** + datif : zwischen 18 und 19 Uhr.',
      examples: [
        { de: 'Dienstags und donnerstags gehe ich ins Fitnessstudio.', en: 'On Tuesdays and Thursdays I go to the gym.', fr: 'Le mardi et le jeudi, je vais à la salle de sport.' },
        { de: 'Morgens jogge ich, abends koche ich.', en: 'In the morning I jog, in the evening I cook.', fr: 'Le matin je fais du jogging, le soir je cuisine.' },
        { de: 'Wir treffen uns zwischen 18 und 19 Uhr.', en: 'We meet between 6 and 7 p.m.', fr: 'Nous nous retrouvons entre 18 h et 19 h.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l18-e1', prompt: 'Wir ___ montags joggen gehen. (können → suggestion, wir)', promptFr: 'Wir ___ montags joggen gehen. (können → proposition, wir)', answer: 'könnten', hint: 'könnte + -n for wir', hintFr: 'könnte + -n pour wir' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l18-e2', prompt: 'Which sentence is a suggestion?', promptFr: 'Quelle phrase est une proposition ?', options: ['Ich konnte gestern nicht kommen.', 'Wir könnten heute Abend schwimmen gehen.', 'Er kann sehr gut schwimmen.'], optionsFr: ['Ich konnte gestern nicht kommen.', 'Wir könnten heute Abend schwimmen gehen.', 'Er kann sehr gut schwimmen.'], answer: 1, explain: '"könnten" with the umlaut is the polite suggestion form; "konnte" is past.', explainFr: '« könnten » avec tréma est la forme de la proposition polie ; « konnte » est au passé.', hint: 'Look for the umlaut: könnte.', hintFr: 'Cherche le tréma : könnte.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l18-e3', tokens: ['abends', 'Wir', 'schwimmen', 'könnten', 'gehen'], answer: ['Wir', 'könnten', 'abends', 'schwimmen', 'gehen'], hint: 'The modal verb is in position 2, the infinitive at the end.', hintFr: 'Le verbe modal est en position 2, l’infinitif à la fin.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'a2l18-e4', pairs: [ { de: 'montags', en: 'every Monday', fr: 'chaque lundi' }, { de: 'morgens', en: 'in the morning', fr: 'le matin' }, { de: 'abends', en: 'in the evening', fr: 'le soir' }, { de: 'nachmittags', en: 'in the afternoon', fr: 'l’après-midi' } ], hint: 'Adverbs with -s describe regular routines.', hintFr: 'Les adverbes en -s décrivent des habitudes régulières.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l18-e5', prompt: 'Listen. When do they go jogging?', promptFr: 'Écoute. Quand vont-ils courir ?', audio: { ttsText: 'Wir könnten montags und donnerstags abends joggen gehen.' }, options: ['Mondays and Thursdays in the evening', 'Mondays and Tuesdays in the morning', 'Every day at noon'], optionsFr: ['Le lundi et le jeudi soir', 'Le lundi et le mardi matin', 'Tous les jours à midi'], answer: 0, hint: 'Listen for the two days and "abends".', hintFr: 'Écoute les deux jours et « abends ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l18-e6', prompt: 'Du ___ mehr Wasser trinken. (sollen → advice, du)', promptFr: 'Du ___ mehr Wasser trinken. (sollen → conseil, du)', answer: 'solltest', hint: 'sollte + -st for du', hintFr: 'sollte + -st pour du' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'a2l18-e7', prompt: 'A friend says: "Wir könnten sonntags joggen gehen." You prefer another day. Which is the politest answer?', promptFr: 'Un ami dit : « Wir könnten sonntags joggen gehen. » Tu préfères un autre jour. Quelle réponse est la plus polie ?', options: ['Nein, das ist dumm.', 'Sonntags passt mir leider nicht. Wie wäre es mit samstags?', 'Ich gehe nie joggen!'], optionsFr: ['Non, c’est bête.', 'Le dimanche, ça ne me convient malheureusement pas. Et si on faisait samedi ?', 'Je ne fais jamais de jogging !'], answer: 1, explain: 'Give a reason and offer an alternative.', explainFr: 'Donne une raison et propose une alternative.', hint: 'Polite = reason + alternative.', hintFr: 'Poli = raison + alternative.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l18-e8', word: 'Fitnessstudio', answer: 'das', hint: 'Words ending in -studio are neuter.', hintFr: 'Les mots en -studio sont neutres.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'a2l18-e9', word: 'Verein', answer: 'der', hint: 'Many nouns with ver- are masculine: der Verein.', hintFr: 'Beaucoup de noms en ver- sont masculins : der Verein.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'a2l18-e10', tokens: ['solltest', 'Du', 'trainieren', 'regelmäßig'], answer: ['Du', 'solltest', 'regelmäßig', 'trainieren'], hint: 'Subject, sollte-form, adverb, infinitive at the end.', hintFr: 'Sujet, forme de sollte, adverbe, infinitif à la fin.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'a2l18-e11', prompt: 'Listen. What does the trainer advise?', promptFr: 'Écoute. Que conseille l’entraîneur ?', audio: { ttsText: 'Du solltest weniger Kaffee und mehr Wasser trinken.' }, options: ['Drink less coffee and more water', 'Drink more coffee', 'Sleep longer in the morning'], optionsFr: ['Boire moins de café et plus d’eau', 'Boire plus de café', 'Dormir plus longtemps le matin'], answer: 0, hint: 'Listen to "weniger" and "mehr".', hintFr: 'Écoute « weniger » et « mehr ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'a2l18-e12', prompt: 'Wie wäre es ___ einem Spaziergang?', promptFr: 'Wie wäre es ___ einem Spaziergang ?', answer: 'mit', hint: 'This preposition takes the dative: "einem".', hintFr: 'Cette préposition prend le datif : « einem ».' } },

    { kind: 'pronunciation', focus: 'The umlaut in könnte makes a rounded ö; "sollte" has a short o; -ch after i is soft (regelmäßig)', focusFr: 'Le tréma de könnte donne un ö arrondi ; « sollte » a un o bref ; -ch après i est doux (regelmäßig)', items: [
      { id: 'a2l18-koennte-pron', german: 'könnte', english: 'could (suggestion)', french: 'pourrait (proposition)', gender: null, syllables: ['KÖNN', 'te'], pronunciation: 'KOEN-teh', example: { de: 'Wir könnten joggen gehen.', en: 'We could go jogging.', fr: 'Nous pourrions aller courir.' } },
      { id: 'a2l18-koennten-pron', german: 'könnten', english: 'could (wir / sie)', french: 'pourrions / pourraient', gender: null, syllables: ['KÖNN', 'ten'], pronunciation: 'KOEN-ten', example: { de: 'Sie könnten mitkommen.', en: 'They could come along.', fr: 'Ils pourraient venir avec nous.' } },
      { id: 'a2l18-sollte-pron', german: 'sollte', english: 'should', french: 'devrait', gender: null, syllables: ['SOLL', 'te'], pronunciation: 'ZOL-teh', example: { de: 'Du solltest mehr schlafen.', en: 'You should sleep more.', fr: 'Tu devrais dormir plus.' } },
      { id: 'a2l18-montags-pron', german: 'montags', english: 'on Mondays', french: 'le lundi', gender: null, syllables: ['MON', 'tags'], pronunciation: 'MOHN-tahks', example: { de: 'Montags trainiere ich.', en: 'On Mondays I work out.', fr: 'Le lundi, je m’entraîne.' } },
      { id: 'a2l18-regelmaessig-pron', german: 'regelmäßig', english: 'regularly', french: 'régulièrement', gender: null, syllables: ['RE', 'gel', 'mä', 'ßig'], pronunciation: 'RAY-gel-may-sikh', example: { de: 'Er isst regelmäßig Obst.', en: 'He eats fruit regularly.', fr: 'Il mange régulièrement des fruits.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now make suggestions and give advice: **Wir könnten …** for ideas, **Du solltest …** for advice, and **Wie wäre es mit …?** for offers — with the infinitive at the end. You can agree (**Einverstanden!**) or decline politely with a reason and an alternative, and you can describe routines with **montags, morgens, abends**. 🏃',
      summaryFr: 'Tu sais maintenant faire des propositions et donner des conseils : **Wir könnten …** pour les idées, **Du solltest …** pour les conseils, et **Wie wäre es mit …?** pour proposer — avec l’infinitif à la fin. Tu peux accepter (**Einverstanden !**) ou refuser poliment avec une raison et une alternative, et décrire tes habitudes avec **montags, morgens, abends**. 🏃' },
  ],
};
