import type { Lesson } from '../types';

export const b1lektion26: Lesson = {
  id: 'b1-l26', level: 'B1', module: 7, number: 25,
  title: { de: 'Damit, um … zu und als ob', en: 'Purpose clauses and "als ob"', fr: 'But, « um … zu » et « als ob »' },
  theme: 'Purpose with "damit" and "um … zu", unreal comparisons with "als ob", solving problems together',
  themeFr: 'Le but avec « damit » et « um … zu », les comparaisons irréelles avec « als ob », résoudre des problèmes ensemble',
  goals: ['Choose between "damit" and "um … zu"', 'Give reasons for plans and visions of the future', 'Make unreal comparisons with "als ob" + Konjunktiv II', 'Express conviction and describe solutions'],
  goalsFr: ['Choisir entre « damit » et « um … zu »', 'Justifier des projets et des visions de l’avenir', 'Faire des comparaisons irréelles avec « als ob » + Konjunktiv II', 'Exprimer une conviction et décrire des solutions'],
  steps: [
    { kind: 'intro', title: 'Mehrere Probleme auf einmal lösen 🌱', titleFr: 'Résoudre plusieurs problèmes à la fois 🌱',
      scene: 'A village plans a shared garden with a café and a repair workshop. Why are they doing it? To bring people together, so that nobody is lonely, to save money — and some neighbours act as if they had known the answer all along.',
      sceneFr: 'Un village projette un jardin partagé avec un café et un atelier de réparation. Pourquoi ? Pour rapprocher les gens, pour que personne ne soit seul, pour économiser — et certains voisins font comme s’ils avaient toujours connu la solution.',
      goals: ['Decide: same subject → um … zu, different subject → damit', 'Use negative purpose (um nicht zu …, damit … nicht)', 'Build "als ob" + Konjunktiv II', 'Talk about visions of the future'],
      goalsFr: ['Décider : même sujet → um … zu, sujet différent → damit', 'Utiliser le but négatif (um nicht zu …, damit … nicht)', 'Construire « als ob » + Konjunktiv II', 'Parler de visions de l’avenir'] },

    { kind: 'vocab', item: { id: 'b1l26-umzu', german: 'um … zu', english: 'in order to', french: 'pour (+ infinitif)', gender: null, syllables: ['UM', 'ZU'], pronunciation: 'oom … tsoo', example: { de: 'Wir gründen einen Verein, um Geld zu sparen.', en: 'We are founding a club in order to save money.', fr: 'Nous fondons une association pour économiser de l’argent.' } } },
    { kind: 'vocab', item: { id: 'b1l26-damit', german: 'damit', english: 'so that', french: 'pour que', gender: null, syllables: ['da', 'MIT'], pronunciation: 'dah-MIT', example: { de: 'Wir kochen zusammen, damit niemand allein isst.', en: 'We cook together so that nobody eats alone.', fr: 'Nous cuisinons ensemble pour que personne ne mange seul.' } } },
    { kind: 'vocab', item: { id: 'b1l26-alsob', german: 'als ob', english: 'as if', french: 'comme si', gender: null, syllables: ['ALS', 'OB'], pronunciation: 'ahls ohp', example: { de: 'Er tut so, als ob er alles wüsste.', en: 'He acts as if he knew everything.', fr: 'Il fait comme s’il savait tout.' } } },
    { kind: 'vocab', item: { id: 'b1l26-sotun', german: 'so tun, als ob', english: 'to pretend that', french: 'faire semblant de', gender: null, syllables: ['SO', 'TUN'], pronunciation: 'zoh toon ahls ohp', example: { de: 'Sie tut so, als ob sie schlafen würde.', en: 'She pretends to be asleep.', fr: 'Elle fait semblant de dormir.' } } },
    { kind: 'vocab', item: { id: 'b1l26-problem', german: 'das Problem', english: 'the problem', french: 'le problème', gender: 'das', syllables: ['pro', 'BLEM'], pronunciation: 'dahs pro-BLAYM', example: { de: 'Wir haben ein Problem mit dem Verkehr.', en: 'We have a problem with traffic.', fr: 'Nous avons un problème de circulation.' } } },
    { kind: 'vocab', item: { id: 'b1l26-loesen', german: 'lösen', english: 'to solve', french: 'résoudre', gender: null, syllables: ['LÖ', 'sen'], pronunciation: 'LOE-zen', example: { de: 'Gemeinsam lösen wir das Problem.', en: 'Together we solve the problem.', fr: 'Ensemble, nous résolvons le problème.' } } },
    { kind: 'vocab', item: { id: 'b1l26-loesung', german: 'die Lösung', english: 'the solution', french: 'la solution', gender: 'die', syllables: ['LÖ', 'sung'], pronunciation: 'dee LOE-zoong', example: { de: 'Das ist eine clevere Lösung.', en: 'That is a clever solution.', fr: 'C’est une solution astucieuse.' } } },
    { kind: 'vocab', item: { id: 'b1l26-gleichzeitig', german: 'gleichzeitig', english: 'at the same time', french: 'en même temps', gender: null, syllables: ['GLEICH', 'zei', 'tig'], pronunciation: 'GLYKH-tsy-tikh', example: { de: 'Man kann nicht alles gleichzeitig machen.', en: 'You can’t do everything at the same time.', fr: 'On ne peut pas tout faire en même temps.' } } },
    { kind: 'vocab', item: { id: 'b1l26-zukunft', german: 'die Zukunft', english: 'the future', french: 'l’avenir', gender: 'die', syllables: ['ZU', 'kunft'], pronunciation: 'dee TSOO-koonft', example: { de: 'Die Zukunft beginnt heute.', en: 'The future starts today.', fr: 'L’avenir commence aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'b1l26-gemeinschaft', german: 'die Gemeinschaft', english: 'the community', french: 'la communauté', gender: 'die', syllables: ['ge', 'MEIN', 'schaft'], pronunciation: 'dee ge-MINE-shahft', example: { de: 'In einer Gemeinschaft hilft man sich.', en: 'In a community people help each other.', fr: 'Dans une communauté, on s’entraide.' } } },
    { kind: 'vocab', item: { id: 'b1l26-zusammenarbeiten', german: 'zusammenarbeiten', english: 'to cooperate / work together', french: 'collaborer', gender: null, syllables: ['zu', 'SAM', 'men', 'ar', 'bei', 'ten'], pronunciation: 'tsoo-ZAHM-men-ar-by-ten', example: { de: 'Alle Generationen arbeiten zusammen.', en: 'All generations work together.', fr: 'Toutes les générations travaillent ensemble.' } } },
    { kind: 'vocab', item: { id: 'b1l26-vermeiden', german: 'vermeiden', english: 'to avoid', french: 'éviter', gender: null, syllables: ['ver', 'MEI', 'den'], pronunciation: 'fair-MY-den', example: { de: 'So vermeiden wir viel Müll.', en: 'This way we avoid a lot of waste.', fr: 'Ainsi, nous évitons beaucoup de déchets.' } } },
    { kind: 'vocab', item: { id: 'b1l26-ueberzeugt', german: 'überzeugt', english: 'convinced', french: 'convaincu', gender: null, syllables: ['ü', 'ber', 'ZEUGT'], pronunciation: 'ue-ber-TSOYKT', example: { de: 'Ich bin überzeugt, dass es klappt.', en: 'I am convinced that it will work.', fr: 'Je suis convaincu que ça marchera.' } } },

    { kind: 'grammar', note: {
      id: 'b1l26-damit-umzu', title: 'damit or um … zu?', titleFr: 'damit ou um … zu ?',
      explanationMd: 'Both give a **purpose** and answer **"Wozu?"** (What for?). You met them earlier in this course. Now choose:\n\n- **Same subject** → **um … zu** + infinitive: Ich stehe früh auf, **um** pünktlich **zu sein**.\n- **Different subjects** → **damit** + full clause (verb at the end): Ich stehe früh auf, **damit** die Kinder pünktlich **sind**.\n\nNegative purpose: **um nicht … zu** / **damit … nicht**:\n- Ich stehe früh auf, **um nicht** zu spät **zu kommen**.\n- Ich schreibe es auf, **damit** ich es **nicht** vergesse.\n\nWith a **modal verb** in the purpose, **damit** is also used for the same subject: Ich spare, **damit** ich reisen **kann**.',
      explanationMdFr: 'Les deux expriment un **but** et répondent à **« Wozu ? »** (pour quoi faire ?). Tu les as déjà rencontrés plus haut dans le cours. Maintenant, choisis :\n\n- **Même sujet** → **um … zu** + infinitif : Ich stehe früh auf, **um** pünktlich **zu sein**.\n- **Sujets différents** → **damit** + proposition complète (verbe à la fin) : Ich stehe früh auf, **damit** die Kinder pünktlich **sind**.\n\nBut négatif : **um nicht … zu** / **damit … nicht** :\n- Ich stehe früh auf, **um nicht** zu spät **zu kommen**.\n- Ich schreibe es auf, **damit** ich es **nicht** vergesse.\n\nAvec un **verbe modal** dans le but, on utilise aussi **damit** pour le même sujet : Ich spare, **damit** ich reisen **kann**.',
      examples: [
        { de: 'Wir bauen einen Garten, um Lebensmittel selbst anzubauen.', en: 'We are building a garden to grow our own food.', fr: 'Nous aménageons un jardin pour cultiver nous-mêmes notre nourriture.' },
        { de: 'Die Gemeinde baut ein Café, damit sich die Nachbarn treffen können.', en: 'The municipality is building a café so that the neighbours can meet.', fr: 'La commune construit un café pour que les voisins puissent se rencontrer.' },
        { de: 'Sie fährt Rad, um nicht im Stau zu stehen.', en: 'She cycles so as not to stand in traffic.', fr: 'Elle roule à vélo pour ne pas rester dans les embouteillages.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l26-alsob-note', title: '"als ob" + Konjunktiv II: unreal comparisons', titleFr: '« als ob » + Konjunktiv II : comparaisons irréelles',
      explanationMd: '**als ob** ("as if") compares reality with something **unreal** or only pretended. The verb goes to the **end** and stands in **Konjunktiv II**:\n\n- Er tut so, **als ob** er alles **wüsste**. (wissen → wüsste)\n- Sie spricht, **als ob** sie Deutsche **wäre**.\n- Es sieht aus, **als ob** es gleich regnen **würde**.\n\nIn **spoken** German you also hear **als** + verb in position 2: Er tut so, **als wüsste** er alles.\n\nFor the past use **hätte / wäre** + participle: Er tut so, als ob er alles **gewusst hätte**.',
      explanationMdFr: '**als ob** (« comme si ») compare la réalité à quelque chose d’**irréel** ou de simplement feint. Le verbe va à la **fin** et se met au **Konjunktiv II** :\n\n- Er tut so, **als ob** er alles **wüsste**. (wissen → wüsste)\n- Sie spricht, **als ob** sie Deutsche **wäre**.\n- Es sieht aus, **als ob** es gleich regnen **würde**.\n\nÀ l’**oral**, on entend aussi **als** + verbe en position 2 : Er tut so, **als wüsste** er alles.\n\nPour le passé, utilise **hätte / wäre** + participe : Er tut so, als ob er alles **gewusst hätte**.',
      examples: [
        { de: 'Du tust so, als ob du keine Zeit hättest.', en: 'You act as if you had no time.', fr: 'Tu fais comme si tu n’avais pas le temps.' },
        { de: 'Er lacht, als ob er nie Sorgen gehabt hätte.', en: 'He laughs as if he had never had worries.', fr: 'Il rit comme s’il n’avait jamais eu de soucis.' },
        { de: 'Sie kocht, als wäre sie Profi-Köchin.', en: 'She cooks as if she were a professional chef.', fr: 'Elle cuisine comme si elle était cuisinière professionnelle.' },
      ],
      diagram: 'satzklammer' } },

    { kind: 'grammar', note: {
      id: 'b1l26-ueberzeugung', title: 'Expressing conviction and solutions', titleFr: 'Exprimer une conviction et des solutions',
      explanationMd: 'To say what you are sure about, and why an idea works:\n\n- Ich bin **überzeugt**, dass … — I am convinced that …\n- Ich bin sicher, dass … / Ich glaube fest daran, dass …\n- Das löst **mehrere Probleme auf einmal**. — That solves several problems at once.\n- Dadurch **entsteht** … / So **vermeiden** wir … — Because of that … / This way we avoid …\n\nCombine with **damit / um … zu** to give the aim of a plan: Ich bin überzeugt, dass Gemeinschaftsgärten entstehen, damit die Menschen zusammenkommen.',
      explanationMdFr: 'Pour dire de quoi tu es sûr, et pourquoi une idée fonctionne :\n\n- Ich bin **überzeugt**, dass … — Je suis convaincu que …\n- Ich bin sicher, dass … / Ich glaube fest daran, dass …\n- Das löst **mehrere Probleme auf einmal**. — Cela résout plusieurs problèmes à la fois.\n- Dadurch **entsteht** … / So **vermeiden** wir … — Grâce à cela … / Ainsi, nous évitons …\n\nCombine avec **damit / um … zu** pour donner le but d’un projet : Ich bin überzeugt, dass Gemeinschaftsgärten entstehen, damit die Menschen zusammenkommen.',
      examples: [
        { de: 'Ich bin überzeugt, dass ein gemeinsames Auto mehrere Probleme auf einmal löst.', en: 'I am convinced that a shared car solves several problems at once.', fr: 'Je suis convaincu qu’une voiture partagée résout plusieurs problèmes à la fois.' },
        { de: 'So vermeiden wir Müll und sparen gleichzeitig Geld.', en: 'This way we avoid waste and save money at the same time.', fr: 'Ainsi, nous évitons les déchets et économisons de l’argent en même temps.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l26-e1', prompt: 'Ich lerne Deutsch, ___ in Wien zu arbeiten. (same subject)', promptFr: 'Ich lerne Deutsch, ___ in Wien zu arbeiten. (même sujet)', answer: 'um', hint: 'same subject → um … zu', hintFr: 'même sujet → um … zu' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l26-e2', prompt: 'Sie erklärt es langsam, ___ wir es verstehen. (different subjects)', promptFr: 'Sie erklärt es langsam, ___ wir es verstehen. (sujets différents)', answer: 'damit', hint: 'sie / wir — two subjects', hintFr: 'sie / wir — deux sujets' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l26-e3', prompt: 'Der Lehrer wiederholt den Satz, ___ die Schüler ihn verstehen.', promptFr: 'Der Lehrer wiederholt den Satz, ___ die Schüler ihn verstehen.', options: ['um … zu', 'damit', 'als ob'], answer: 1, explain: 'Different subjects (Lehrer / Schüler) → "damit" with the verb at the end.', explainFr: 'Sujets différents (Lehrer / Schüler) → « damit » avec le verbe à la fin.', hint: 'Count the subjects.', hintFr: 'Compte les sujets.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l26-e4', tokens: ['sein', 'früh', 'Ich', 'um', 'zu', 'stehe', 'pünktlich', 'auf'], answer: ['Ich', 'stehe', 'früh', 'auf', 'um', 'pünktlich', 'zu', 'sein'], hint: 'Main clause (with the separable verb), then "um … zu" + infinitive.', hintFr: 'Proposition principale (avec le verbe séparable), puis « um … zu » + infinitif.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l26-e5', prompt: 'Er tut so, als ob er alles ___. (wissen → Konjunktiv II)', promptFr: 'Er tut so, als ob er alles ___. (wissen → Konjunktiv II)', answer: 'wüsste', hint: 'wissen → wüsste', hintFr: 'wissen → wüsste' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l26-e6', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Sie spricht, als ob sie Deutsche wäre.', 'Sie spricht, als ob sie Deutsche ist.', 'Sie spricht, als ob wäre sie Deutsche.'], optionsFr: ['Sie spricht, als ob sie Deutsche wäre.', 'Sie spricht, als ob sie Deutsche ist.', 'Sie spricht, als ob wäre sie Deutsche.'], answer: 0, explain: 'Unreal comparison → Konjunktiv II, and the verb goes to the end after "als ob".', explainFr: 'Comparaison irréelle → Konjunktiv II, et le verbe va à la fin après « als ob ».', hint: 'Konjunktiv II at the end of the clause.', hintFr: 'Konjunktiv II à la fin de la proposition.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l26-e7', tokens: ['wüsste', 'als ob', 'alles', 'er'], answer: ['als ob', 'er', 'alles', 'wüsste'], hint: 'Conjunction, subject, object, Konjunktiv II at the end.', hintFr: 'Conjonction, sujet, objet, Konjunktiv II à la fin.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l26-e8', pairs: [ { de: 'um … zu', en: 'purpose, same subject', fr: 'but, même sujet' }, { de: 'damit', en: 'purpose, different subject', fr: 'but, sujet différent' }, { de: 'als ob', en: 'unreal comparison', fr: 'comparaison irréelle' }, { de: 'gleichzeitig', en: 'at the same time', fr: 'en même temps' } ], hint: 'Match each word to its function or meaning.', hintFr: 'Associe chaque mot à sa fonction ou à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l26-e9', prompt: 'Listen. What is the situation really like?', promptFr: 'Écoute. Quelle est la situation réelle ?', audio: { ttsText: 'Er tut so, als ob er keine Zeit hätte, aber er hat eigentlich viel Zeit.' }, options: ['He has plenty of time', 'He really has no time', 'He has too much work'], optionsFr: ['Il a largement le temps', 'Il n’a vraiment pas le temps', 'Il a trop de travail'], answer: 0, hint: 'Listen to the word after "aber".', hintFr: 'Écoute le mot après « aber ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l26-e10', prompt: 'Es sieht aus, als ob es gleich ___.', promptFr: 'Es sieht aus, als ob es gleich ___.', options: ['regnen würde', 'regnen wird', 'geregnet hat'], answer: 0, explain: '"als ob" takes Konjunktiv II: würde + infinitive.', explainFr: '« als ob » demande le Konjunktiv II : würde + infinitif.', hint: 'Which option is Konjunktiv II?', hintFr: 'Quelle option est au Konjunktiv II ?' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l26-e11', word: 'Problem', answer: 'das', hint: 'Problem is neuter (das Problem).', hintFr: 'Problem est neutre (das Problem).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l26-e12', prompt: 'Listen. Why do they build the garden?', promptFr: 'Écoute. Pourquoi construisent-ils le jardin ?', audio: { ttsText: 'Wir bauen einen Gemeinschaftsgarten, damit sich die Nachbarn öfter treffen.' }, options: ['So that neighbours meet more often', 'To save money', 'To sell vegetables'], optionsFr: ['Pour que les voisins se rencontrent plus souvent', 'Pour économiser de l’argent', 'Pour vendre des légumes'], answer: 0, hint: 'Listen to the clause after "damit".', hintFr: 'Écoute la proposition après « damit ».' } },

    { kind: 'pronunciation', focus: 'Umlauts in Konjunktiv II: wüsste (ü), hätte (ä), könnte (ö), wäre (ä)', focusFr: 'Les trémas au Konjunktiv II : wüsste (ü), hätte (ä), könnte (ö), wäre (ä)', items: [
      { id: 'b1l26-wuesste-pron', german: 'wüsste', english: 'would know', french: 'saurait', gender: null, syllables: ['WÜSS', 'te'], pronunciation: 'VUESS-teh', example: { de: 'Ich wüsste gern mehr.', en: 'I would like to know more.', fr: 'J’aimerais en savoir plus.' } },
      { id: 'b1l26-haette-pron', german: 'hätte', english: 'would have', french: 'aurait', gender: null, syllables: ['HÄT', 'te'], pronunciation: 'HET-teh', example: { de: 'Er tut so, als hätte er Zeit.', en: 'He acts as if he had time.', fr: 'Il fait comme s’il avait le temps.' } },
      { id: 'b1l26-koennte-pron', german: 'könnte', english: 'could', french: 'pourrait', gender: null, syllables: ['KÖNN', 'te'], pronunciation: 'KOEN-teh', example: { de: 'Das könnte die Lösung sein.', en: 'That could be the solution.', fr: 'Ce pourrait être la solution.' } },
      { id: 'b1l26-waere-pron', german: 'wäre', english: 'would be', french: 'serait', gender: null, syllables: ['WÄ', 're'], pronunciation: 'VAIR-eh', example: { de: 'Sie tut, als wäre alles gut.', en: 'She acts as if everything were fine.', fr: 'Elle fait comme si tout allait bien.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now give purposes precisely: **um … zu** for the same subject, **damit** for different subjects (and **um nicht … zu** for negative aims). With **als ob** + **Konjunktiv II** you compare reality with something unreal: **Er tut so, als ob er alles wüsste.** 🎉',
      summaryFr: 'Tu sais maintenant exprimer précisément un but : **um … zu** pour le même sujet, **damit** pour des sujets différents (et **um nicht … zu** pour un but négatif). Avec **als ob** + **Konjunktiv II**, tu compares la réalité à quelque chose d’irréel : **Er tut so, als ob er alles wüsste.** 🎉' },
  ],
};
