import type { Lesson } from '../types';

export const b1lektion23: Lesson = {
  id: 'b1-l23', level: 'B1', module: 5, number: 19,
  title: { de: 'Passiv mit Modalverben und Ortsangaben', en: 'Passive with modal verbs and place/time expressions', fr: 'Passif avec verbes modaux et compléments de lieu/temps' },
  theme: 'Organising an event: passive with modal verbs, innerhalb/außerhalb, um … herum, am … entlang',
  themeFr: 'Organiser un événement : passif avec verbes modaux, innerhalb/außerhalb, um … herum, am … entlang',
  goals: ['Form the passive with a modal verb (muss … werden)', 'Say what has to be done before an event', 'Use innerhalb and außerhalb with the genitive', 'Describe routes with um … herum and am … entlang'],
  goalsFr: ['Former le passif avec un verbe modal (muss … werden)', 'Dire ce qui doit être fait avant un événement', 'Utiliser innerhalb et außerhalb avec le génitif', 'Décrire des trajets avec um … herum et am … entlang'],
  steps: [
    { kind: 'intro', title: 'Vorher muss viel gemacht werden 🎸', titleFr: 'Il y a beaucoup à faire avant 🎸',
      scene: 'A student band plays its first open-air concert. Stage, posters, tickets, buses — so much has to be organised, and nobody says exactly who does it. The passive with modal verbs is perfect for that.',
      sceneFr: 'Un groupe d’étudiants donne son premier concert en plein air. Scène, affiches, billets, bus : il y a tant à organiser, et personne ne dit qui s’en charge. Le passif avec verbes modaux est parfait pour cela.',
      goals: ['Build "modal + participle + werden"', 'Plan an event with the passive', 'Place things with innerhalb / außerhalb + genitive', 'Give directions with um … herum / am … entlang'],
      goalsFr: ['Construire « modal + participe + werden »', 'Planifier un événement au passif', 'Situer avec innerhalb / außerhalb + génitif', 'Indiquer un trajet avec um … herum / am … entlang'] },

    { kind: 'vocab', item: { id: 'b1l23-veranstaltung', german: 'die Veranstaltung', english: 'the event', french: 'l’événement', gender: 'die', syllables: ['ver', 'AN', 'stal', 'tung'], pronunciation: 'dee fair-AHN-shtahl-toong', example: { de: 'Die Veranstaltung beginnt um sieben Uhr.', en: 'The event starts at seven o’clock.', fr: 'L’événement commence à sept heures.' } } },
    { kind: 'vocab', item: { id: 'b1l23-auftritt', german: 'der Auftritt', english: 'the performance / gig', french: 'la prestation / le concert', gender: 'der', syllables: ['AUF', 'tritt'], pronunciation: 'dair OWF-trit', example: { de: 'Der Auftritt der Band war ein Erfolg.', en: 'The band’s gig was a success.', fr: 'Le concert du groupe a été un succès.' } } },
    { kind: 'vocab', item: { id: 'b1l23-probe', german: 'die Probe', english: 'the rehearsal', french: 'la répétition', gender: 'die', syllables: ['PRO', 'be'], pronunciation: 'dee PROH-beh', example: { de: 'Die Probe dauert zwei Stunden.', en: 'The rehearsal lasts two hours.', fr: 'La répétition dure deux heures.' } } },
    { kind: 'vocab', item: { id: 'b1l23-lampenfieber', german: 'das Lampenfieber', english: 'stage fright', french: 'le trac', gender: 'das', syllables: ['LAM', 'pen', 'fie', 'ber'], pronunciation: 'dahs LAHM-pen-fee-ber', example: { de: 'Vor jedem Auftritt hat sie Lampenfieber.', en: 'She gets stage fright before every performance.', fr: 'Avant chaque concert, elle a le trac.' } } },
    { kind: 'vocab', item: { id: 'b1l23-buehne', german: 'die Bühne', english: 'the stage', french: 'la scène', gender: 'die', syllables: ['BÜH', 'ne'], pronunciation: 'dee BUE-neh', example: { de: 'Die Bühne steht mitten auf dem Platz.', en: 'The stage stands in the middle of the square.', fr: 'La scène se trouve au milieu de la place.' } } },
    { kind: 'vocab', item: { id: 'b1l23-publikum', german: 'das Publikum', english: 'the audience', french: 'le public', gender: 'das', syllables: ['PU', 'bli', 'kum'], pronunciation: 'dahs POO-blee-koom', example: { de: 'Das Publikum klatscht laut.', en: 'The audience applauds loudly.', fr: 'Le public applaudit fort.' } } },
    { kind: 'vocab', item: { id: 'b1l23-tournee', german: 'die Tournee', english: 'the tour', french: 'la tournée', gender: 'die', syllables: ['tour', 'NEE'], pronunciation: 'dee toor-NAY', example: { de: 'Die Band geht im Herbst auf Tournee.', en: 'The band goes on tour in autumn.', fr: 'Le groupe part en tournée en automne.' } } },
    { kind: 'vocab', item: { id: 'b1l23-aufbauen', german: 'aufbauen', english: 'to set up / build up', french: 'monter / installer', gender: null, syllables: ['AUF', 'bau', 'en'], pronunciation: 'OWF-bow-en', example: { de: 'Die Technik muss früh aufgebaut werden.', en: 'The equipment has to be set up early.', fr: 'Le matériel doit être installé tôt.' } } },
    { kind: 'vocab', item: { id: 'b1l23-organisieren', german: 'organisieren', english: 'to organise', french: 'organiser', gender: null, syllables: ['or', 'ga', 'ni', 'SIE', 'ren'], pronunciation: 'or-gah-nee-ZEE-ren', example: { de: 'Wer organisiert die Busse?', en: 'Who is organising the buses?', fr: 'Qui organise les bus ?' } } },
    { kind: 'vocab', item: { id: 'b1l23-werbung', german: 'die Werbung', english: 'advertising', french: 'la publicité', gender: 'die', syllables: ['WER', 'bung'], pronunciation: 'dee VAIR-boong', example: { de: 'Für das Konzert wird viel Werbung gemacht.', en: 'A lot of advertising is done for the concert.', fr: 'On fait beaucoup de publicité pour le concert.' } } },
    { kind: 'vocab', item: { id: 'b1l23-innerhalb', german: 'innerhalb', english: 'within / inside (+ gen.)', french: 'à l’intérieur de / dans un délai de', gender: null, syllables: ['IN', 'ner', 'halb'], pronunciation: 'IN-ner-hahlp', example: { de: 'Innerhalb der Stadt gibt es viele Bühnen.', en: 'Within the city there are many stages.', fr: 'Dans la ville, il y a beaucoup de scènes.' } } },
    { kind: 'vocab', item: { id: 'b1l23-ausserhalb', german: 'außerhalb', english: 'outside of (+ gen.)', french: 'en dehors de', gender: null, syllables: ['AU', 'ßer', 'halb'], pronunciation: 'OW-ser-hahlp', example: { de: 'Das Festival findet außerhalb der Stadt statt.', en: 'The festival takes place outside the city.', fr: 'Le festival a lieu en dehors de la ville.' } } },
    { kind: 'vocab', item: { id: 'b1l23-entlang', german: 'entlang', english: 'along', french: 'le long de', gender: null, syllables: ['ent', 'LANG'], pronunciation: 'ent-LAHNG', example: { de: 'Wir gehen am Fluss entlang.', en: 'We walk along the river.', fr: 'Nous marchons le long de la rivière.' } } },

    { kind: 'grammar', note: {
      id: 'b1l23-passiv-modal', title: 'Passive with modal verbs', titleFr: 'Le passif avec verbes modaux',
      explanationMd: 'You know the present passive (**wird/werden + participle**). With a **modal verb** (müssen, können, dürfen, sollen, wollen) the modal is **conjugated**; the **participle** and the infinitive **werden** go to the end:\n\n**modal** + … + **participle** + **werden**\n\n- Die Bühne **muss** aufgebaut **werden**.\n- Die Plakate **müssen** gedruckt **werden**.\n- Das **darf** nicht vergessen **werden**.\n\nIn a **subordinate clause** the modal is the very last word: …, weil noch viel geübt werden **muss**.\n\nActive → passive: Man **muss** die Tickets verkaufen. → Die Tickets **müssen** verkauft **werden**.',
      explanationMdFr: 'Tu connais le passif présent (**wird/werden + participe**). Avec un **verbe modal** (müssen, können, dürfen, sollen, wollen), c’est le modal qui est **conjugué** ; le **participe** et l’infinitif **werden** vont à la fin :\n\n**modal** + … + **participe** + **werden**\n\n- Die Bühne **muss** aufgebaut **werden**.\n- Die Plakate **müssen** gedruckt **werden**.\n- Das **darf** nicht vergessen **werden**.\n\nDans une **subordonnée**, le modal est le tout dernier mot : …, weil noch viel geübt werden **muss**.\n\nActif → passif : Man **muss** die Tickets verkaufen. → Die Tickets **müssen** verkauft **werden**.',
      examples: [
        { de: 'Es muss noch viel geübt werden.', en: 'A lot still has to be practised.', fr: 'Il faut encore beaucoup s’entraîner.' },
        { de: 'Die Karten können online gekauft werden.', en: 'The tickets can be bought online.', fr: 'Les billets peuvent être achetés en ligne.' },
        { de: 'Wir sind nervös, weil noch vieles organisiert werden muss.', en: 'We are nervous because a lot still has to be organised.', fr: 'Nous sommes nerveux parce qu’il y a encore beaucoup à organiser.' },
      ],
      diagram: 'satzklammer' } },

    { kind: 'grammar', note: {
      id: 'b1l23-innerhalb-note', title: 'innerhalb / außerhalb + genitive', titleFr: 'innerhalb / außerhalb + génitif',
      explanationMd: 'Both prepositions take the **genitive** and work for **place** and **time**:\n\n- **innerhalb** der Stadt — inside the city / **innerhalb** einer Woche — within a week\n- **außerhalb** des Zentrums — outside the centre / **außerhalb** der Öffnungszeiten — outside opening hours\n\nMasculine and neuter nouns get **-(e)s**: des Zentrum**s**, des Gebäude**s**. With a bare plural noun, people often use **von** + dative: innerhalb **von** zwei Tagen.',
      explanationMdFr: 'Les deux prépositions se construisent avec le **génitif** et valent pour le **lieu** et le **temps** :\n\n- **innerhalb** der Stadt — à l’intérieur de la ville / **innerhalb** einer Woche — dans un délai d’une semaine\n- **außerhalb** des Zentrums — en dehors du centre / **außerhalb** der Öffnungszeiten — en dehors des heures d’ouverture\n\nLes noms masculins et neutres prennent **-(e)s** : des Zentrum**s**, des Gebäude**s**. Avec un pluriel sans article, on utilise souvent **von** + datif : innerhalb **von** zwei Tagen.',
      examples: [
        { de: 'Innerhalb des Gebäudes darf nicht geraucht werden.', en: 'Smoking is not allowed inside the building.', fr: 'Il est interdit de fumer à l’intérieur du bâtiment.' },
        { de: 'Die Tickets müssen innerhalb einer Woche bezahlt werden.', en: 'The tickets must be paid for within a week.', fr: 'Les billets doivent être payés dans un délai d’une semaine.' },
        { de: 'Das Stadion liegt außerhalb der Stadt.', en: 'The stadium is outside the city.', fr: 'Le stade se trouve en dehors de la ville.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l23-herum-entlang', title: 'um … herum and an … entlang', titleFr: 'um … herum et an … entlang',
      explanationMd: 'Two-part expressions for routes and positions:\n\n- **um** + **accusative** + **herum** — around: **Um den See herum** stehen Stände.\n- **an** + **dative** + **entlang** — along: Wir gehen **am Fluss entlang**.\n\nIf the noun comes **first**, **entlang** follows it with the accusative: Wir gehen **den Fluss entlang**. Nice places and events are often praised with the superlative: Das ist der **schönste** Platz der Stadt!',
      explanationMdFr: 'Deux expressions en deux parties pour les trajets et les positions :\n\n- **um** + **accusatif** + **herum** — autour de : **Um den See herum** stehen des stands.\n- **an** + **datif** + **entlang** — le long de : Wir gehen **am Fluss entlang**.\n\nSi le nom vient **en premier**, **entlang** le suit avec l’accusatif : Wir gehen **den Fluss entlang**. On loue souvent les beaux lieux avec le superlatif : Das ist der **schönste** Platz der Stadt !',
      examples: [
        { de: 'Um die Halle herum warten schon viele Fans.', en: 'Lots of fans are already waiting around the hall.', fr: 'Beaucoup de fans attendent déjà autour de la salle.' },
        { de: 'Am Ufer entlang stehen Lichter und Stände.', en: 'Lights and stalls stand along the bank.', fr: 'Des lumières et des stands bordent la rive.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l23-e1', prompt: 'Die Tickets müssen noch verkauft ___. (passive infinitive)', promptFr: 'Die Tickets müssen noch verkauft ___. (infinitif passif)', answer: 'werden', hint: 'modal + participle + werden', hintFr: 'modal + participe + werden' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l23-e2', prompt: 'Which sentence is a passive with a modal verb?', promptFr: 'Quelle phrase est un passif avec verbe modal ?', options: ['Wir müssen noch viel üben.', 'Es muss noch viel geübt werden.', 'Es wird noch viel geübt.'], optionsFr: ['Wir müssen noch viel üben.', 'Es muss noch viel geübt werden.', 'Es wird noch viel geübt.'], answer: 1, explain: 'Modal (muss) + participle (geübt) + werden.', explainFr: 'Modal (muss) + participe (geübt) + werden.', hint: 'Look for the participle followed by "werden".', hintFr: 'Cherche le participe suivi de « werden ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l23-e3', tokens: ['aufgebaut', 'Die Bühne', 'werden', 'muss'], answer: ['Die Bühne', 'muss', 'aufgebaut', 'werden'], hint: 'Modal in position 2, participle + werden at the end.', hintFr: 'Modal en position 2, participe + werden à la fin.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l23-e4', prompt: 'Die Plakate ___ bald gedruckt werden. (müssen — plural)', promptFr: 'Die Plakate ___ bald gedruckt werden. (müssen — pluriel)', answer: 'müssen', hint: 'plural subject → plural modal', hintFr: 'sujet pluriel → modal au pluriel' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l23-e5', prompt: 'Which subordinate clause is correct?', promptFr: 'Quelle subordonnée est correcte ?', options: ['…, weil noch viel geprobt werden muss.', '…, weil noch viel muss geprobt werden.', '…, weil noch viel geprobt muss werden.'], optionsFr: ['…, weil noch viel geprobt werden muss.', '…, weil noch viel muss geprobt werden.', '…, weil noch viel geprobt muss werden.'], answer: 0, explain: 'In a subordinate clause the conjugated modal stands last.', explainFr: 'Dans une subordonnée, le modal conjugué est en dernière position.', hint: 'Which verb is conjugated — and where does it go?', hintFr: 'Quel verbe est conjugué — et où va-t-il ?' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l23-e6', pairs: [ { de: 'innerhalb', en: 'within / inside of', fr: 'à l’intérieur de' }, { de: 'außerhalb', en: 'outside of', fr: 'en dehors de' }, { de: 'um … herum', en: 'around', fr: 'autour de' }, { de: 'am … entlang', en: 'along', fr: 'le long de' } ], hint: 'Match each expression to its meaning.', hintFr: 'Associe chaque expression à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l23-e7', prompt: 'Das Konzert findet innerhalb ___ Stadt statt. (die Stadt → genitive article)', promptFr: 'Das Konzert findet innerhalb ___ Stadt statt. (die Stadt → article au génitif)', answer: 'der', hint: 'feminine genitive: der', hintFr: 'génitif féminin : der' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l23-e8', prompt: 'Listen. What has to be organised?', promptFr: 'Écoute. Qu’est-ce qui doit être organisé ?', audio: { ttsText: 'Die Halle liegt außerhalb der Stadt, deshalb müssen Busse organisiert werden.' }, options: ['Buses', 'Tickets', 'Posters'], optionsFr: ['Des bus', 'Des billets', 'Des affiches'], answer: 0, hint: 'Listen for the noun before "organisiert werden".', hintFr: 'Écoute le nom avant « organisiert werden ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l23-e9', prompt: 'Wir spazieren ___ Fluss entlang.', promptFr: 'Wir spazieren ___ Fluss entlang.', options: ['um', 'am', 'im'], answer: 1, explain: '"an dem" = "am": am Fluss entlang (along the river).', explainFr: '« an dem » = « am » : am Fluss entlang (le long de la rivière).', hint: 'an + dative + entlang', hintFr: 'an + datif + entlang' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l23-e10', prompt: 'Die Fans stehen um die Halle ___. (around)', promptFr: 'Die Fans stehen um die Halle ___. (autour)', answer: 'herum', hint: 'um … herum', hintFr: 'um … herum' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l23-e11', word: 'Publikum', answer: 'das', hint: 'Publikum is neuter (das Publikum).', hintFr: 'Publikum est neutre (das Publikum).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l23-e12', prompt: 'Listen. When must the tickets be paid?', promptFr: 'Écoute. Quand faut-il payer les billets ?', audio: { ttsText: 'Die Karten müssen innerhalb einer Woche bezahlt werden.' }, options: ['Within a week', 'After a month', 'Tomorrow'], optionsFr: ['Dans un délai d’une semaine', 'Après un mois', 'Demain'], answer: 0, hint: 'Listen to the time expression after "innerhalb".', hintFr: 'Écoute l’expression de temps après « innerhalb ».' } },

    { kind: 'pronunciation', focus: 'Long ü in Bühne vs. short ü in müssen — and stress on the last syllable of Tournee', focusFr: 'ü long dans Bühne vs ü bref dans müssen — et accent sur la dernière syllabe de Tournee', items: [
      { id: 'b1l23-buehne-pron', german: 'die Bühne', english: 'the stage', french: 'la scène', gender: 'die', syllables: ['BÜH', 'ne'], pronunciation: 'dee BUE-neh', example: { de: 'Die Bühne ist bereit.', en: 'The stage is ready.', fr: 'La scène est prête.' } },
      { id: 'b1l23-muessen-pron', german: 'müssen', english: 'must / have to', french: 'devoir', gender: null, syllables: ['MÜS', 'sen'], pronunciation: 'MUESS-en', example: { de: 'Wir müssen noch proben.', en: 'We still have to rehearse.', fr: 'Nous devons encore répéter.' } },
      { id: 'b1l23-ausserhalb-pron', german: 'außerhalb', english: 'outside of', french: 'en dehors de', gender: null, syllables: ['AU', 'ßer', 'halb'], pronunciation: 'OW-ser-hahlp', example: { de: 'Außerhalb der Stadt ist es ruhig.', en: 'It is quiet outside the city.', fr: 'C’est calme en dehors de la ville.' } },
      { id: 'b1l23-tournee-pron', german: 'die Tournee', english: 'the tour', french: 'la tournée', gender: 'die', syllables: ['tour', 'NEE'], pronunciation: 'dee toor-NAY', example: { de: 'Die Tournee beginnt im Mai.', en: 'The tour starts in May.', fr: 'La tournée commence en mai.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now talk about what has to be done before an event: **modal + participle + werden** (Die Bühne muss aufgebaut werden). You also know **innerhalb / außerhalb** + genitive for place and time, and **um … herum** / **am … entlang** for routes. 🎉',
      summaryFr: 'Tu sais maintenant parler de ce qui doit être fait avant un événement : **modal + participe + werden** (Die Bühne muss aufgebaut werden). Tu connais aussi **innerhalb / außerhalb** + génitif pour le lieu et le temps, et **um … herum** / **am … entlang** pour les trajets. 🎉' },
  ],
};
