import type { Lesson } from '../types';

export const b1lektion15: Lesson = {
  id: 'b1-l15', level: 'B1', module: 3, number: 10,
  title: { de: 'Relativsätze mit Präposition und Dativ', en: 'Relative clauses with prepositions and dative', fr: 'Propositions relatives avec préposition et datif' },
  theme: 'Talking about jobs, colleagues and passions with dative and prepositional relative clauses',
  themeFr: 'Parler de métiers, de collègues et de passions avec des relatives au datif et avec préposition',
  goals: ['Use the dative relative pronouns dem / der / denen', 'Build relative clauses with prepositions (für den, mit dem)', 'Choose accusative or dative after the preposition', 'Describe jobs, teams and passions in one flowing sentence'],
  goalsFr: ['Utiliser les pronoms relatifs au datif dem / der / denen', 'Construire des relatives avec préposition (für den, mit dem)', 'Choisir l’accusatif ou le datif après la préposition', 'Décrire métiers, équipes et passions en une seule phrase fluide'],
  steps: [
    { kind: 'intro', title: 'Mein Beruf ist meine Leidenschaft 🔥', titleFr: 'Mon métier est ma passion 🔥',
      scene: 'At a networking evening, people describe the job they love, the team they work with and the boss they trust.', sceneFr: 'Lors d’une soirée de réseautage, chacun décrit le métier qu’il adore, l’équipe avec laquelle il travaille et le chef en qui il a confiance.',
      goals: ['Use dem, der and denen as relative pronouns', 'Put the preposition in front of the pronoun', 'Decide the case with the preposition or the verb', 'Talk about your dream job'],
      goalsFr: ['Utiliser dem, der et denen comme pronoms relatifs', 'Placer la préposition devant le pronom', 'Décider du cas selon la préposition ou le verbe', 'Parler de ton métier de rêve'] },

    { kind: 'vocab', item: { id: 'b1l15-leidenschaft', german: 'die Leidenschaft', english: 'the passion', french: 'la passion', gender: 'die', syllables: ['LEI', 'den', 'schaft'], pronunciation: 'dee LY-den-shahft', example: { de: 'Kochen ist eine Leidenschaft, der ich jeden Tag nachgehe.', en: 'Cooking is a passion I pursue every day.', fr: 'La cuisine est une passion que je poursuis tous les jours.' } } },
    { kind: 'vocab', item: { id: 'b1l15-traumberuf', german: 'der Traumberuf', english: 'the dream job', french: 'le métier de rêve', gender: 'der', syllables: ['TRAUM', 'be', 'ruf'], pronunciation: 'dair TROWM-be-roof', example: { de: 'Pilotin ist der Traumberuf, von dem sie schon als Kind träumte.', en: 'Pilot is the dream job she already dreamed of as a child.', fr: 'Pilote est le métier de rêve dont elle rêvait déjà enfant.' } } },
    { kind: 'vocab', item: { id: 'b1l15-team', german: 'das Team', english: 'the team', french: 'l’équipe', gender: 'das', syllables: ['TEAM'], pronunciation: 'dahs TEEM', example: { de: 'Das Team, mit dem ich arbeite, ist sehr kreativ.', en: 'The team I work with is very creative.', fr: 'L’équipe avec laquelle je travaille est très créative.' } } },
    { kind: 'vocab', item: { id: 'b1l15-kunde', german: 'der Kunde', english: 'the customer', french: 'le client', gender: 'der', syllables: ['KUN', 'de'], pronunciation: 'dair KOON-duh', example: { de: 'Der Kunde, dem wir helfen, wartet schon.', en: 'The customer we are helping is already waiting.', fr: 'Le client que nous aidons attend déjà.' } } },
    { kind: 'vocab', item: { id: 'b1l15-abteilung', german: 'die Abteilung', english: 'the department', french: 'le service / le département', gender: 'die', syllables: ['ab', 'TEI', 'lung'], pronunciation: 'dee ahp-TY-loong', example: { de: 'Die Abteilung, in der ich arbeite, ist neu.', en: 'The department I work in is new.', fr: 'Le service dans lequel je travaille est nouveau.' } } },
    { kind: 'vocab', item: { id: 'b1l15-arbeitgeber', german: 'der Arbeitgeber', english: 'the employer', french: 'l’employeur', gender: 'der', syllables: ['AR', 'beit', 'ge', 'ber'], pronunciation: 'dair AR-bite-gay-ber', example: { de: 'Der Arbeitgeber, bei dem ich mich bewerbe, sitzt in Hamburg.', en: 'The employer I am applying to is based in Hamburg.', fr: 'L’employeur chez qui je postule est à Hambourg.' } } },
    { kind: 'vocab', item: { id: 'b1l15-herausforderung', german: 'die Herausforderung', english: 'the challenge', french: 'le défi', gender: 'die', syllables: ['he', 'RAUS', 'for', 'de', 'rung'], pronunciation: 'dee heh-ROWSS-for-de-roong', example: { de: 'Das ist eine Herausforderung, vor der ich keine Angst habe.', en: 'That is a challenge I am not afraid of.', fr: 'C’est un défi qui ne me fait pas peur.' } } },
    { kind: 'vocab', item: { id: 'b1l15-vorbild', german: 'das Vorbild', english: 'the role model', french: 'le modèle', gender: 'das', syllables: ['VOR', 'bild'], pronunciation: 'dahs FOR-bilt', example: { de: 'Meine Chefin ist ein Vorbild, zu dem ich aufschaue.', en: 'My boss is a role model I look up to.', fr: 'Ma cheffe est un modèle que j’admire.' } } },
    { kind: 'vocab', item: { id: 'b1l15-verantwortung', german: 'die Verantwortung', english: 'the responsibility', french: 'la responsabilité', gender: 'die', syllables: ['ver', 'ANT', 'wor', 'tung'], pronunciation: 'dee fer-ANT-vor-toong', example: { de: 'Das ist eine Verantwortung, für die ich bereit bin.', en: 'That is a responsibility I am ready for.', fr: 'C’est une responsabilité pour laquelle je suis prêt.' } } },
    { kind: 'vocab', item: { id: 'b1l15-begeistern', german: 'sich begeistern (für)', english: 'to be enthusiastic (about)', french: 's’enthousiasmer (pour)', gender: null, syllables: ['be', 'GEIS', 'tern'], pronunciation: 'zikh be-GUY-stern', example: { de: 'Er begeistert sich für Projekte, die etwas bewegen.', en: 'He is enthusiastic about projects that make a difference.', fr: 'Il s’enthousiasme pour les projets qui font bouger les choses.' } } },
    { kind: 'vocab', item: { id: 'b1l15-vertrauen', german: 'vertrauen', english: 'to trust', french: 'faire confiance', gender: null, syllables: ['ver', 'TRAU', 'en'], pronunciation: 'fer-TROW-en', example: { de: 'Ich vertraue einem Chef, der ehrlich ist.', en: 'I trust a boss who is honest.', fr: 'Je fais confiance à un chef qui est honnête.' } } },
    { kind: 'vocab', item: { id: 'b1l15-zusammenarbeiten', german: 'zusammenarbeiten', english: 'to work together', french: 'travailler ensemble', gender: null, syllables: ['zu', 'SAM', 'men', 'ar', 'bei', 'ten'], pronunciation: 'tsoo-ZAHM-men-ar-by-ten', example: { de: 'Die Kollegen, mit denen ich zusammenarbeite, sind hilfsbereit.', en: 'The colleagues I work together with are helpful.', fr: 'Les collègues avec qui je travaille sont serviables.' } } },
    { kind: 'vocab', item: { id: 'b1l15-fortbildung', german: 'die Fortbildung', english: 'the further training', french: 'la formation continue', gender: 'die', syllables: ['FORT', 'bil', 'dung'], pronunciation: 'dee FORT-bil-doong', example: { de: 'Die Fortbildung, an der ich teilnehme, dauert drei Tage.', en: 'The training I am taking part in lasts three days.', fr: 'La formation à laquelle je participe dure trois jours.' } } },

    { kind: 'grammar', note: {
      id: 'b1l15-dativ', title: 'Dative relative pronouns: dem / der / denen', titleFr: 'Les pronoms relatifs au datif : dem / der / denen',
      explanationMd: 'You already know **der/die/das** (nominative) and **den** (accusative). When the relative pronoun is an **indirect object** or follows a **dative verb** (helfen, gehören, vertrauen, gefallen, danken), use the **dative**:\n\n- masculine: **dem** — Der Kollege, **dem** ich helfe, …\n- feminine: **der** — Die Chefin, **der** ich vertraue, …\n- neuter: **dem** — Das Kind, **dem** wir helfen, …\n- plural: **denen** — Die Kunden, **denen** wir helfen, …\n\nThe verb still goes to the **end**, and the clause is set off by commas.\n\nOverview (Nom / Akk / Dat): m **der / den / dem** · f **die / die / der** · n **das / das / dem** · pl **die / die / denen**.',
      explanationMdFr: 'Tu connais déjà **der/die/das** (nominatif) et **den** (accusatif). Quand le pronom relatif est un **complément d’objet indirect** ou suit un **verbe à datif** (helfen, gehören, vertrauen, gefallen, danken), on utilise le **datif** :\n\n- masculin : **dem** — Der Kollege, **dem** ich helfe, …\n- féminin : **der** — Die Chefin, **der** ich vertraue, …\n- neutre : **dem** — Das Kind, **dem** wir helfen, …\n- pluriel : **denen** — Die Kunden, **denen** wir helfen, …\n\nLe verbe va toujours à la **fin**, et la relative est entourée de virgules.\n\nVue d’ensemble (Nom / Acc / Dat) : m **der / den / dem** · f **die / die / der** · n **das / das / dem** · pl **die / die / denen**.',
      examples: [
        { de: 'Der Kollege, dem ich helfe, ist neu im Team.', en: 'The colleague I am helping is new in the team.', fr: 'Le collègue que j’aide est nouveau dans l’équipe.' },
        { de: 'Die Chefin, der ich vertraue, ist sehr fair.', en: 'The boss I trust is very fair.', fr: 'La cheffe en qui j’ai confiance est très juste.' },
        { de: 'Die Kunden, denen wir geholfen haben, schrieben uns einen Brief.', en: 'The customers we helped wrote us a letter.', fr: 'Les clients que nous avons aidés nous ont écrit une lettre.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l15-praeposition', title: 'Relative clauses with a preposition', titleFr: 'Les relatives avec préposition',
      explanationMd: 'The **preposition** moves to the **front** of the relative clause, **right before the pronoun**. The preposition decides the **case** of the pronoun:\n\n- **für, durch, gegen, um, ohne** + accusative: Der Beruf, **für den** ich brenne, … · Die Aufgabe, **für die** ich zuständig bin, …\n- **mit, bei, von, aus, nach, zu** + dative: Das Team, **mit dem** ich arbeite, … · Die Firma, **bei der** ich arbeite, …\n- **über, auf, an** (accusative after a verb like *sich freuen auf*, *sprechen über*): Das Thema, **über das** wir sprechen, …\n- plural dative: **mit denen**, **von denen**, **bei denen**.\n\nThe preposition does not come back at the end: *das Team, mit dem ich arbeite* (not: *das Team, dem ich mit arbeite*).',
      explanationMdFr: 'La **préposition** passe **en tête** de la relative, **juste avant le pronom**. C’est la préposition qui décide du **cas** du pronom :\n\n- **für, durch, gegen, um, ohne** + accusatif : Der Beruf, **für den** ich brenne, … · Die Aufgabe, **für die** ich zuständig bin, …\n- **mit, bei, von, aus, nach, zu** + datif : Das Team, **mit dem** ich arbeite, … · Die Firma, **bei der** ich arbeite, …\n- **über, auf, an** (accusatif après un verbe comme *sich freuen auf*, *sprechen über*) : Das Thema, **über das** wir sprechen, …\n- datif pluriel : **mit denen**, **von denen**, **bei denen**.\n\nLa préposition ne revient pas à la fin : *das Team, mit dem ich arbeite* (et non : *das Team, dem ich mit arbeite*).',
      examples: [
        { de: 'Das ist der Beruf, für den ich mich begeistere.', en: 'That is the profession I am enthusiastic about.', fr: 'C’est le métier pour lequel je m’enthousiasme.' },
        { de: 'Das Team, mit dem ich arbeite, hilft mir immer.', en: 'The team I work with always helps me.', fr: 'L’équipe avec laquelle je travaille m’aide toujours.' },
        { de: 'Die Kollegen, von denen ich viel lerne, sind sehr erfahren.', en: 'The colleagues I learn a lot from are very experienced.', fr: 'Les collègues dont j’apprends beaucoup sont très expérimentés.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l15-wechsel', title: 'Wo? or Wohin? — two-way prepositions', titleFr: 'Wo ? ou Wohin ? — prépositions mixtes',
      explanationMd: 'With **in, an, auf, neben, vor, unter, über, zwischen, hinter** the **verb and the meaning** decide:\n\n- **Wo?** (position) → **dative**: Das Büro, **in dem** ich arbeite, … · Die Abteilung, **in der** sie sitzt, …\n- **Wohin?** (direction) → **accusative**: Das Büro, **in das** ich jeden Morgen gehe, …\n- Verbs with fixed prepositions decide too: sich interessieren **für** + Akk → *das Thema, **für das** ich mich interessiere*; träumen **von** + Dat → *der Beruf, **von dem** ich träume*.\n\nTip: say the pronoun’s gender first, then check the case.',
      explanationMdFr: 'Avec **in, an, auf, neben, vor, unter, über, zwischen, hinter**, ce sont **le verbe et le sens** qui décident :\n\n- **Wo ?** (position) → **datif** : Das Büro, **in dem** ich arbeite, … · Die Abteilung, **in der** sie sitzt, …\n- **Wohin ?** (direction) → **accusatif** : Das Büro, **in das** ich jeden Morgen gehe, …\n- Les verbes à préposition fixe décident aussi : sich interessieren **für** + acc → *das Thema, **für das** ich mich interessiere* ; träumen **von** + dat → *der Beruf, **von dem** ich träume*.\n\nAstuce : trouve d’abord le genre du pronom, puis vérifie le cas.',
      examples: [
        { de: 'Das Büro, in dem ich arbeite, liegt im dritten Stock.', en: 'The office I work in is on the third floor.', fr: 'Le bureau dans lequel je travaille est au troisième étage.' },
        { de: 'Das Projekt, auf das ich mich freue, beginnt im Herbst.', en: 'The project I am looking forward to starts in the autumn.', fr: 'Le projet dont je me réjouis commence à l’automne.' },
        { de: 'Sie hat einen Beruf, von dem viele träumen.', en: 'She has a profession that many people dream of.', fr: 'Elle a un métier dont beaucoup rêvent.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l15-e1', prompt: 'Die Chefin, ___ ich vertraue, ist sehr fair. (f, dative)', promptFr: 'Die Chefin, ___ ich vertraue, ist sehr fair. (f, datif)', answer: 'der', hint: 'feminine dative → der', hintFr: 'féminin datif → der' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l15-e2', prompt: 'Die Kunden, ___ wir helfen, sind zufrieden. (plural, dative)', promptFr: 'Die Kunden, ___ wir helfen, sind zufrieden. (pluriel, datif)', answer: 'denen', hint: 'plural dative relative pronoun', hintFr: 'pronom relatif au datif pluriel' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l15-e3', prompt: 'Das Team, mit ___ ich arbeite, ist super. (n, dative after "mit")', promptFr: 'Das Team, mit ___ ich arbeite, ist super. (n, datif après « mit »)', answer: 'dem', hint: '"mit" + dative; Team is neuter', hintFr: '« mit » + datif ; Team est neutre' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l15-e4', prompt: 'Choose: "Der Beruf, für ___ ich mich interessiere, ist Lehrer."', promptFr: 'Choisis : « Der Beruf, für ___ ich mich interessiere, ist Lehrer. »', options: ['dem', 'den', 'der'], answer: 1, explain: '"für" takes the accusative; Beruf is masculine → den.', explainFr: '« für » demande l’accusatif ; Beruf est masculin → den.', hint: '"für" is always accusative.', hintFr: '« für » est toujours suivi de l’accusatif.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l15-e5', prompt: 'Choose: "Das Büro, in ___ ich arbeite, ist hell." (Wo?)', promptFr: 'Choisis : « Das Büro, in ___ ich arbeite, ist hell. » (Wo ?)', options: ['das', 'dem', 'den'], answer: 1, explain: 'Position (Wo?) → dative; Büro is neuter → dem.', explainFr: 'Position (Wo ?) → datif ; Büro est neutre → dem.', hint: 'You work in the office: position, not direction.', hintFr: 'Tu travailles dans le bureau : position, pas direction.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l15-e6', prompt: 'Listen. Who does Mia trust?', promptFr: 'Écoute. À qui Mia fait-elle confiance ?', audio: { ttsText: 'Mia hat eine Chefin, der sie voll vertraut.' }, options: ['Her boss', 'Her colleague', 'Her customer'], optionsFr: ['Sa cheffe', 'Sa collègue', 'Sa cliente'], answer: 0, hint: 'Listen to the noun before "der sie".', hintFr: 'Écoute le nom avant « der sie ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l15-e7', tokens: ['mit', 'zusammenarbeite', 'Das', 'dem', 'Kollege', 'ich', 'ist', 'der'], answer: ['Das', 'ist', 'der', 'Kollege', 'mit', 'dem', 'ich', 'zusammenarbeite'], hint: 'Preposition + pronoun first in the relative clause; the verb goes last.', hintFr: 'Préposition + pronom en tête de la relative ; le verbe à la fin.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l15-e8', pairs: [ { de: 'die Firma (bei)', en: 'bei der', fr: 'bei der' }, { de: 'der Beruf (für)', en: 'für den', fr: 'für den' }, { de: 'das Thema (über)', en: 'über das', fr: 'über das' }, { de: 'die Kollegen (mit)', en: 'mit denen', fr: 'mit denen' } ], hint: 'Find the gender, then the case required by the preposition.', hintFr: 'Trouve le genre, puis le cas exigé par la préposition.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l15-e9', prompt: 'Listen. What is the dream job?', promptFr: 'Écoute. Quel est le métier de rêve ?', audio: { ttsText: 'Journalist ist der Beruf, von dem ich schon lange träume.' }, options: ['Journalist', 'Teacher', 'Doctor'], optionsFr: ['Journaliste', 'Enseignant', 'Médecin'], answer: 0, hint: 'The job comes before "der Beruf, von dem".', hintFr: 'Le métier est nommé au début de la phrase.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l15-e10', prompt: 'Die Firma, bei ___ ich arbeite, ist klein. (f, dative after "bei")', promptFr: 'Die Firma, bei ___ ich arbeite, ist klein. (f, datif après « bei »)', answer: 'der', hint: '"bei" + dative; Firma is feminine', hintFr: '« bei » + datif ; Firma est féminin' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l15-e11', word: 'Traumberuf', answer: 'der', hint: 'the last part is "Beruf" (m)', hintFr: 'la dernière partie est « Beruf » (m)' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l15-e12', word: 'Leidenschaft', answer: 'die', hint: 'nouns ending in -schaft are feminine', hintFr: 'les noms en -schaft sont féminins' } },

    { kind: 'pronunciation', focus: 'Stress falls on the noun, not on the pronoun; "ei" sounds like English "eye", "eu" like "oy"', focusFr: 'L’accent tombe sur le nom, pas sur le pronom ; « ei » se prononce comme « aïe », « eu » comme « oï »', items: [
      { id: 'b1l15-denen-pron', german: 'denen', english: 'whom / which (plural, dative)', french: 'à qui / auxquels (pluriel, datif)', gender: null, syllables: ['DE', 'nen'], pronunciation: 'DAY-nen', example: { de: 'Die Kollegen, denen ich helfe.', en: 'The colleagues I help.', fr: 'Les collègues que j’aide.' } },
      { id: 'b1l15-leidenschaft-pron', german: 'Leidenschaft', english: 'passion', french: 'passion', gender: 'die', syllables: ['LEI', 'den', 'schaft'], pronunciation: 'LY-den-shahft', example: { de: 'Sie arbeitet mit Leidenschaft.', en: 'She works with passion.', fr: 'Elle travaille avec passion.' } },
      { id: 'b1l15-verantwortung-pron', german: 'Verantwortung', english: 'responsibility', french: 'responsabilité', gender: 'die', syllables: ['ver', 'ANT', 'wor', 'tung'], pronunciation: 'fer-ANT-vor-toong', example: { de: 'Er übernimmt Verantwortung.', en: 'He takes on responsibility.', fr: 'Il prend des responsabilités.' } },
      { id: 'b1l15-herausforderung-pron', german: 'Herausforderung', english: 'challenge', french: 'défi', gender: 'die', syllables: ['he', 'RAUS', 'for', 'de', 'rung'], pronunciation: 'heh-ROWSS-for-de-roong', example: { de: 'Eine neue Herausforderung wartet.', en: 'A new challenge is waiting.', fr: 'Un nouveau défi m’attend.' } },
      { id: 'b1l15-begeistern-pron', german: 'begeistern', english: 'to inspire / enthuse', french: 'enthousiasmer', gender: null, syllables: ['be', 'GEIS', 'tern'], pronunciation: 'be-GUY-stern', example: { de: 'Der Beruf begeistert mich.', en: 'The job inspires me.', fr: 'Ce métier m’enthousiasme.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now build richer relative clauses. The **dative** pronouns are **dem** (m/n), **der** (f) and **denen** (pl). With a preposition, put it **before the pronoun**: **für den** Beruf (acc), **mit dem** Team (dat), **bei der** Firma (dat), **in dem** Büro (Wo?) vs. **in das** Büro (Wohin?). The verb stays at the end. 🎉',
      summaryFr: 'Tu sais maintenant construire des relatives plus riches. Les pronoms au **datif** sont **dem** (m/n), **der** (f) et **denen** (pl). Avec une préposition, place-la **devant le pronom** : **für den** Beruf (acc), **mit dem** Team (dat), **bei der** Firma (dat), **in dem** Büro (Wo ?) contre **in das** Büro (Wohin ?). Le verbe reste à la fin. 🎉' },
  ],
};
