import type { Lesson } from '../types';

export const b1lektion13: Lesson = {
  id: 'b1-l13', level: 'B1', module: 1, number: 2,
  title: { de: 'Adjektive als Nomen', en: 'Adjectives as nouns', fr: 'Adjectifs employés comme noms' },
  theme: 'Adjectives and participles used as nouns, and the n-declension',
  themeFr: 'Adjectifs et participes employés comme noms, et la déclinaison en -n',
  goals: ['Use adjectives as nouns (der Deutsche, ein Bekannter, das Beste)', 'Decline participles used as nouns (der Angestellte, die Reisenden)', 'Recognise and decline n-declension nouns (den Kollegen, dem Nachbarn)', 'Describe people and character, and soften or strengthen statements'],
  goalsFr: ['Employer des adjectifs comme noms (der Deutsche, ein Bekannter, das Beste)', 'Décliner des participes employés comme noms (der Angestellte, die Reisenden)', 'Reconnaître et décliner les noms en déclinaison en -n (den Kollegen, dem Nachbarn)', 'Décrire des personnes et leur caractère, et nuancer ou renforcer une affirmation'],
  steps: [
    { kind: 'intro', title: 'Ihr seid die Besten! 🤝', titleFr: 'Vous êtes les meilleurs ! 🤝',
      scene: 'A farewell party for a colleague: friends, acquaintances and neighbours tell how they know each other and what impression they make.', sceneFr: 'Une fête d’adieu pour un collègue : amis, connaissances et voisins racontent comment ils se connaissent et quelle impression ils font.',
      goals: ['Turn adjectives into nouns', 'Decline them like adjectives', 'Spot the n-declension nouns', 'Say how someone is: ziemlich hilfsbereit, gar nicht nervös'],
      goalsFr: ['Transformer des adjectifs en noms', 'Les décliner comme des adjectifs', 'Repérer les noms de la déclinaison en -n', 'Dire comment est quelqu’un : ziemlich hilfsbereit, gar nicht nervös'] },

    { kind: 'vocab', item: { id: 'b1l13-bekannte', german: 'der Bekannte', english: 'the acquaintance (m)', french: 'la connaissance (m)', gender: 'der', syllables: ['Be', 'KANN', 'te'], pronunciation: 'dair be-KAHN-teh', example: { de: 'Ein Bekannter hat mir den Job empfohlen.', en: 'An acquaintance recommended the job to me.', fr: 'Une connaissance m’a recommandé ce poste.' } } },
    { kind: 'vocab', item: { id: 'b1l13-angestellte', german: 'der Angestellte', english: 'the employee (m)', french: 'l’employé', gender: 'der', syllables: ['AN', 'ge', 'stell', 'te'], pronunciation: 'dair AHN-ge-shtell-teh', example: { de: 'Der Angestellte erklärt uns den Vertrag.', en: 'The employee explains the contract to us.', fr: 'L’employé nous explique le contrat.' } } },
    { kind: 'vocab', item: { id: 'b1l13-deutsche', german: 'der Deutsche', english: 'the German (m)', french: 'l’Allemand', gender: 'der', syllables: ['DEUT', 'sche'], pronunciation: 'dair DOY-cheh', example: { de: 'Ein Deutscher wohnt neben mir.', en: 'A German lives next door to me.', fr: 'Un Allemand habite à côté de chez moi.' } } },
    { kind: 'vocab', item: { id: 'b1l13-erwachsene', german: 'der Erwachsene', english: 'the adult (m)', french: 'l’adulte', gender: 'der', syllables: ['Er', 'WACH', 'se', 'ne'], pronunciation: 'dair air-VAHK-seh-neh', example: { de: 'Kinder und Erwachsene sind willkommen.', en: 'Children and adults are welcome.', fr: 'Enfants et adultes sont les bienvenus.' } } },
    { kind: 'vocab', item: { id: 'b1l13-jugendliche', german: 'der Jugendliche', english: 'the teenager (m)', french: 'l’adolescent', gender: 'der', syllables: ['JU', 'gend', 'li', 'che'], pronunciation: 'dair YOO-gent-lee-kheh', example: { de: 'Die Jugendlichen treffen sich im Park.', en: 'The teenagers meet in the park.', fr: 'Les adolescents se retrouvent au parc.' } } },
    { kind: 'vocab', item: { id: 'b1l13-verwandte', german: 'der Verwandte', english: 'the relative (m)', french: 'le parent (membre de la famille)', gender: 'der', syllables: ['Ver', 'WAND', 'te'], pronunciation: 'dair fair-VAHN-teh', example: { de: 'Meine Verwandten wohnen in Hamburg.', en: 'My relatives live in Hamburg.', fr: 'Mes parents (ma famille) habitent à Hambourg.' } } },
    { kind: 'vocab', item: { id: 'b1l13-kollege', german: 'der Kollege', english: 'the colleague (m)', french: 'le collègue', gender: 'der', syllables: ['Kol', 'LE', 'ge'], pronunciation: 'dair koh-LAY-geh', example: { de: 'Ich kenne den neuen Kollegen noch nicht.', en: 'I don’t know the new colleague yet.', fr: 'Je ne connais pas encore le nouveau collègue.' } } },
    { kind: 'vocab', item: { id: 'b1l13-nachbar', german: 'der Nachbar', english: 'the neighbour (m)', french: 'le voisin', gender: 'der', syllables: ['NACH', 'bar'], pronunciation: 'dair NAHKH-bar', example: { de: 'Wir helfen unserem Nachbarn oft.', en: 'We often help our neighbour.', fr: 'Nous aidons souvent notre voisin.' } } },
    { kind: 'vocab', item: { id: 'b1l13-mensch', german: 'der Mensch', english: 'the human being / person', french: 'l’être humain / la personne', gender: 'der', syllables: ['MENSCH'], pronunciation: 'dair mench', example: { de: 'Sie ist ein sehr offener Mensch.', en: 'She is a very open person.', fr: 'C’est une personne très ouverte.' } } },
    { kind: 'vocab', item: { id: 'b1l13-praktikant', german: 'der Praktikant', english: 'the intern (m)', french: 'le stagiaire', gender: 'der', syllables: ['Prak', 'ti', 'KANT'], pronunciation: 'dair prahk-tee-KAHNT', example: { de: 'Wir fragen den Praktikanten um Hilfe.', en: 'We ask the intern for help.', fr: 'Nous demandons de l’aide au stagiaire.' } } },
    { kind: 'vocab', item: { id: 'b1l13-hilfsbereit', german: 'hilfsbereit', english: 'helpful / ready to help', french: 'serviable', gender: null, syllables: ['HILFS', 'be', 'reit'], pronunciation: 'HILFS-beh-rite', example: { de: 'Unser Team ist total hilfsbereit.', en: 'Our team is totally helpful.', fr: 'Notre équipe est vraiment serviable.' } } },
    { kind: 'vocab', item: { id: 'b1l13-zuverlaessig', german: 'zuverlässig', english: 'reliable', french: 'fiable', gender: null, syllables: ['ZU', 'ver', 'läs', 'sig'], pronunciation: 'TSOO-fair-less-ikh', example: { de: 'Er ist ehrlich und zuverlässig.', en: 'He is honest and reliable.', fr: 'Il est honnête et fiable.' } } },
    { kind: 'vocab', item: { id: 'b1l13-ziemlich', german: 'ziemlich', english: 'quite / fairly', french: 'assez / plutôt', gender: null, syllables: ['ZIEM', 'lich'], pronunciation: 'TSEEM-likh', example: { de: 'Die Präsentation war ziemlich gut.', en: 'The presentation was quite good.', fr: 'La présentation était plutôt bonne.' } } },
    { kind: 'vocab', item: { id: 'b1l13-gar-nicht', german: 'gar nicht', english: 'not at all', french: 'pas du tout', gender: null, syllables: ['GAR', 'nicht'], pronunciation: 'gar nikht', example: { de: 'Sie ist gar nicht nervös.', en: 'She is not nervous at all.', fr: 'Elle n’est pas du tout nerveuse.' } } },
    { kind: 'vocab', item: { id: 'b1l13-beste', german: 'der / die / das Beste', english: 'the best (one)', french: 'le meilleur / la meilleure / le mieux', gender: null, syllables: ['BES', 'te'], pronunciation: 'BESS-teh', example: { de: 'Ihr seid die Besten!', en: 'You are the best!', fr: 'Vous êtes les meilleurs !' } } },

    { kind: 'grammar', note: {
      id: 'b1l13-adjektiv-nomen', title: 'Adjectives as nouns', titleFr: 'Les adjectifs employés comme noms',
      explanationMd: 'Many adjectives can be used as **nouns**: capitalise them, but keep the **normal adjective endings** (the ending shows case and gender):\n\n- masc: **der** Deutsche · **ein** Deutsch**er** | acc: **den** Deutsch**en** · **einen** Deutsch**en** | dat: **dem** Deutsch**en** · **einem** Deutsch**en**\n- fem: **die** Deutsche · **eine** Deutsche | dat: **der** Deutsch**en** · **einer** Deutsch**en**\n- plural: **die** Deutsch**en** · (viele) Deutsch**e** | dat: **den** Deutsch**en**\n\nThe same works for **der Bekannte, der Kranke, der Fremde, der Verwandte, der Jugendliche**.\n\n**Neuter, abstract:** das Beste, das Neue, das Wichtige. After **etwas, nichts, viel, alles**: etwas Neu**es**, nichts Besonder**es**, viel Gut**es**, alles Gut**e**.\n\n**Superlative as noun:** der Beste, die Beste, die Besten — **Ihr seid die Besten!**',
      explanationMdFr: 'Beaucoup d’adjectifs peuvent être employés comme **noms** : on leur met une majuscule, mais ils gardent les **terminaisons habituelles de l’adjectif** (la terminaison indique le cas et le genre) :\n\n- masc : **der** Deutsche · **ein** Deutsch**er** | acc : **den** Deutsch**en** · **einen** Deutsch**en** | dat : **dem** Deutsch**en** · **einem** Deutsch**en**\n- fém : **die** Deutsche · **eine** Deutsche | dat : **der** Deutsch**en** · **einer** Deutsch**en**\n- pluriel : **die** Deutsch**en** · (viele) Deutsch**e** | dat : **den** Deutsch**en**\n\nMême chose pour **der Bekannte, der Kranke, der Fremde, der Verwandte, der Jugendliche**.\n\n**Neutre, abstrait :** das Beste, das Neue, das Wichtige. Après **etwas, nichts, viel, alles** : etwas Neu**es**, nichts Besonder**es**, viel Gut**es**, alles Gut**e**.\n\n**Superlatif employé comme nom :** der Beste, die Beste, die Besten — **Ihr seid die Besten !**',
      examples: [
        { de: 'Ein Bekannter von mir arbeitet bei Siemens.', en: 'An acquaintance of mine works at Siemens.', fr: 'Une de mes connaissances travaille chez Siemens.' },
        { de: 'Ich spreche gerade mit einer Bekannten.', en: 'I’m just talking to a (female) acquaintance.', fr: 'Je parle justement avec une connaissance (une femme).' },
        { de: 'Das Beste kommt noch. — Hast du etwas Neues gehört?', en: 'The best is yet to come. — Have you heard anything new?', fr: 'Le meilleur reste à venir. — As-tu entendu quelque chose de nouveau ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l13-partizip-nomen', title: 'Participles as nouns', titleFr: 'Les participes employés comme noms',
      explanationMd: 'Participles behave the same way. The **past participle** and the **present participle** (verb + **-d**) can become nouns with adjective endings:\n\n- angestellt → **der Angestellte** · **die Angestellte** · **die Angestellten**\n- reisen → reisend → **der Reisende** · **die Reisenden**\n- studieren → **der / die Studierende** · vorgesetzt → **der Vorgesetzte** (boss)\n\nEndings follow the article: **der** Angestellte, **ein** Angestellt**er**, **den** Angestellten, **mit dem** Angestellten. Plural without article: **drei neue Angestellte**.\n\nFor the feminine, the noun is the **same word** — only the article shows the gender: der Angestellte / **die** Angestellte.',
      explanationMdFr: 'Les participes se comportent de la même façon. Le **participe passé** et le **participe présent** (verbe + **-d**) peuvent devenir des noms avec les terminaisons de l’adjectif :\n\n- angestellt → **der Angestellte** · **die Angestellte** · **die Angestellten**\n- reisen → reisend → **der Reisende** · **die Reisenden**\n- studieren → **der / die Studierende** · vorgesetzt → **der Vorgesetzte** (le supérieur)\n\nLes terminaisons suivent l’article : **der** Angestellte, **ein** Angestellt**er**, **den** Angestellten, **mit dem** Angestellten. Pluriel sans article : **drei neue Angestellte**.\n\nAu féminin, le nom est le **même mot** — seul l’article indique le genre : der Angestellte / **die** Angestellte.',
      examples: [
        { de: 'Der Angestellte öffnet die Tür.', en: 'The employee opens the door.', fr: 'L’employé ouvre la porte.' },
        { de: 'Ich frage einen Angestellten nach dem Weg.', en: 'I ask an employee for directions.', fr: 'Je demande mon chemin à un employé.' },
        { de: 'Die Reisenden warten am Gleis. Wir haben drei neue Angestellte.', en: 'The travellers are waiting on the platform. We have three new employees.', fr: 'Les voyageurs attendent sur le quai. Nous avons trois nouveaux employés.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l13-n-deklination', title: 'The n-declension', titleFr: 'La déclinaison en -n',
      explanationMd: 'A group of **masculine** nouns takes **-(e)n in every case except the nominative singular**:\n\n- der Kollege → **den Kollegen** → **dem Kollegen**\n- der Mensch → **den Menschen** → **dem Menschen**\n- der Nachbar → **den Nachbarn** → **dem Nachbarn**\n- der Praktikant → **den Praktikanten** → **dem Praktikanten**\n\nWho belongs to the group? Masculine nouns for **people and animals** ending in **-e** (der Kunde, der Junge, der Löwe), in **-ent / -ant / -ist** (der Student, der Praktikant, der Polizist), plus **der Mensch, der Nachbar, der Herr** (den Herrn).\n\nWatch out for look-alikes: **ein Kollege** (n-declension, no -r) but **ein Angestellter** (adjective noun, with -r).',
      explanationMdFr: 'Un groupe de noms **masculins** prend **-(e)n à tous les cas sauf au nominatif singulier** :\n\n- der Kollege → **den Kollegen** → **dem Kollegen**\n- der Mensch → **den Menschen** → **dem Menschen**\n- der Nachbar → **den Nachbarn** → **dem Nachbarn**\n- der Praktikant → **den Praktikanten** → **dem Praktikanten**\n\nQui en fait partie ? Les noms masculins de **personnes et d’animaux** en **-e** (der Kunde, der Junge, der Löwe), en **-ent / -ant / -ist** (der Student, der Praktikant, der Polizist), ainsi que **der Mensch, der Nachbar, der Herr** (den Herrn).\n\nAttention aux faux amis : **ein Kollege** (déclinaison en -n, sans -r) mais **ein Angestellter** (nom issu d’un adjectif, avec -r).',
      examples: [
        { de: 'Ich kenne den neuen Kollegen schon.', en: 'I already know the new colleague.', fr: 'Je connais déjà le nouveau collègue.' },
        { de: 'Wir helfen unserem Nachbarn. Die Firma sucht einen Praktikanten.', en: 'We help our neighbour. The company is looking for an intern.', fr: 'Nous aidons notre voisin. L’entreprise cherche un stagiaire.' },
        { de: 'Jeder Mensch braucht gute Freunde. — Sie ist der netteste Mensch im Team.', en: 'Everyone needs good friends. — She is the nicest person on the team.', fr: 'Chacun a besoin de bons amis. — C’est la personne la plus sympathique de l’équipe.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l13-e1', prompt: 'Das ist Jonas, ein ___ von mir. (bekannt → noun, nominative)', promptFr: 'Das ist Jonas, ein ___ von mir. (bekannt → nom, nominatif)', answer: 'Bekannter', hint: 'After "ein", masculine nominative: -er', hintFr: 'Après « ein », masculin au nominatif : -er' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l13-e2', prompt: 'Ich kenne den neuen ___ nicht. (der Angestellte, accusative)', promptFr: 'Ich kenne den neuen ___ nicht. (der Angestellte, accusatif)', answer: 'Angestellten', hint: 'After "den … neuen": -en', hintFr: 'Après « den … neuen » : -en' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l13-e3', prompt: 'Er spricht mit einem ___.', promptFr: 'Er spricht mit einem ___. (un Allemand)', options: ['Deutsche', 'Deutschen', 'Deutscher'], answer: 1, explain: 'mit + dative, masculine after "einem": Deutschen.', explainFr: 'mit + datif, masculin après « einem » : Deutschen.', hint: 'Dative masculine singular ends in -en.', hintFr: 'Le datif masculin singulier se termine en -en.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l13-e4', prompt: 'Ich rufe meinen ___ an. (der Kollege, accusative)', promptFr: 'Ich rufe meinen ___ an. (der Kollege, accusatif)', answer: 'Kollegen', hint: 'n-declension: der Kollege → den Kollegen', hintFr: 'Déclinaison en -n : der Kollege → den Kollegen' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l13-e5', pairs: [ { de: 'der Jugendliche', en: 'the teenager', fr: 'l’adolescent' }, { de: 'der Verwandte', en: 'the relative', fr: 'le parent' }, { de: 'der Erwachsene', en: 'the adult', fr: 'l’adulte' }, { de: 'der Angestellte', en: 'the employee', fr: 'l’employé' } ], hint: 'Match each person noun to its meaning.', hintFr: 'Associe chaque nom de personne à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l13-e6', prompt: 'Listen. What is the acquaintance like?', promptFr: 'Écoute. Comment est la connaissance ?', audio: { ttsText: 'Ich habe gestern einen Bekannten getroffen. Er ist ziemlich hilfsbereit.' }, options: ['Quite helpful', 'Not helpful at all', 'Very funny'], optionsFr: ['Plutôt serviable', 'Pas du tout serviable', 'Très drôle'], answer: 0, hint: '"ziemlich" = quite.', hintFr: '« ziemlich » = plutôt.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l13-e7', tokens: ['kenne', 'den', 'Ich', 'neuen', 'Kollegen', 'nicht'], answer: ['Ich', 'kenne', 'den', 'neuen', 'Kollegen', 'nicht'], hint: 'Subject, verb, object with article + adjective + noun, then "nicht".', hintFr: 'Sujet, verbe, complément (article + adjectif + nom), puis « nicht ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l13-e8', prompt: 'Which noun follows the n-declension?', promptFr: 'Quel nom suit la déclinaison en -n ?', options: ['der Tisch', 'der Mensch', 'der Apfel'], answer: 1, explain: 'der Mensch → den Menschen → dem Menschen. Tisch and Apfel are normal masculine nouns.', explainFr: 'der Mensch → den Menschen → dem Menschen. Tisch et Apfel sont des noms masculins ordinaires.', hint: 'Think of people.', hintFr: 'Pense aux personnes.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l13-e9', prompt: 'Er hilft dem alten ___. (der Nachbar, dative)', promptFr: 'Er hilft dem alten ___. (der Nachbar, datif)', answer: 'Nachbarn', hint: 'n-declension: dem Nachbarn', hintFr: 'Déclinaison en -n : dem Nachbarn' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l13-e10', prompt: 'Listen. What is the best thing about the team?', promptFr: 'Écoute. Quel est le meilleur aspect de l’équipe ?', audio: { ttsText: 'Das Beste an unserem Team ist: Wir helfen uns immer.' }, options: ['They always help each other', 'The high salary', 'The modern office'], optionsFr: ['Ils s’entraident toujours', 'Le salaire élevé', 'Le bureau moderne'], answer: 0, hint: 'Listen after the colon.', hintFr: 'Écoute ce qui vient après les deux-points.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l13-e11', prompt: 'Ihr seid die ___! (gut → superlative noun, plural)', promptFr: 'Ihr seid die ___ ! (gut → superlatif employé comme nom, pluriel)', answer: 'Besten', hint: 'After "die" in the plural: -en', hintFr: 'Après « die » au pluriel : -en' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l13-e12', prompt: 'Die ___ warten am Gleis. (reisend → noun, plural)', promptFr: 'Die ___ warten am Gleis. (reisend → nom, pluriel)', options: ['Reisende', 'Reisenden', 'Reisender'], answer: 1, explain: 'After "die" in the plural, the ending is -en: die Reisenden.', explainFr: 'Après « die » au pluriel, la terminaison est -en : die Reisenden.', hint: 'Plural with article → -en.', hintFr: 'Pluriel avec article → -en.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l13-e13', word: 'Praktikant', answer: 'der', hint: 'Nouns in -ant for people are masculine.', hintFr: 'Les noms de personnes en -ant sont masculins.' } },

    { kind: 'pronunciation', focus: '"eu" sounds like "oy" (Deutsche), "chs" sounds like "ks" (Erwachsene), and the soft "ch" in Mensch', focusFr: '« eu » se prononce « oy » (Deutsche), « chs » se prononce « ks » (Erwachsene), et le « ch » doux de Mensch', items: [
      { id: 'b1l13-deutsche-pron', german: 'der Deutsche', english: 'the German (m)', french: 'l’Allemand', gender: 'der', syllables: ['DEUT', 'sche'], pronunciation: 'dair DOY-cheh', example: { de: 'Der Deutsche spricht Französisch.', en: 'The German speaks French.', fr: 'L’Allemand parle français.' } },
      { id: 'b1l13-erwachsene-pron', german: 'der Erwachsene', english: 'the adult (m)', french: 'l’adulte', gender: 'der', syllables: ['Er', 'WACH', 'se', 'ne'], pronunciation: 'dair air-VAHK-seh-neh', example: { de: 'Ein Erwachsener zahlt zehn Euro.', en: 'An adult pays ten euros.', fr: 'Un adulte paie dix euros.' } },
      { id: 'b1l13-mensch-pron', german: 'der Mensch', english: 'the person', french: 'la personne', gender: 'der', syllables: ['MENSCH'], pronunciation: 'dair mench', example: { de: 'Sie ist ein netter Mensch.', en: 'She is a nice person.', fr: 'C’est une personne sympathique.' } },
      { id: 'b1l13-kollege-pron', german: 'der Kollege', english: 'the colleague (m)', french: 'le collègue', gender: 'der', syllables: ['Kol', 'LE', 'ge'], pronunciation: 'dair koh-LAY-geh', example: { de: 'Mein Kollege ist zuverlässig.', en: 'My colleague is reliable.', fr: 'Mon collègue est fiable.' } },
    ] },

    { kind: 'wrapup', summary: 'Adjectives and participles can become nouns — capitalise them and keep the **adjective endings**: **der Deutsche / ein Deutscher / den Deutschen**, **der Angestellte**, **das Beste**, **die Besten**. Masculine nouns of the **n-declension** add **-(e)n** everywhere except the nominative: **der Kollege → den Kollegen**, **der Mensch → dem Menschen**. Add colour with **ziemlich**, **total**, **gar nicht**. 🤝',
      summaryFr: 'Adjectifs et participes peuvent devenir des noms — majuscule et **terminaisons de l’adjectif** : **der Deutsche / ein Deutscher / den Deutschen**, **der Angestellte**, **das Beste**, **die Besten**. Les noms masculins de la **déclinaison en -n** ajoutent **-(e)n** partout sauf au nominatif : **der Kollege → den Kollegen**, **der Mensch → dem Menschen**. Nuance avec **ziemlich**, **total**, **gar nicht**. 🤝' },
  ],
};
