import type { Lesson } from '../types';

export const b1lektion19: Lesson = {
  id: 'b1-l19', level: 'B1', module: 5, number: 17,
  title: { de: 'Partizip als Adjektiv', en: 'Participles as adjectives', fr: 'Participes employés comme adjectifs' },
  theme: 'Participles as adjectives: laufend, spannend, geschlossen, gebucht — signs, warnings and activities',
  themeFr: 'Les participes comme adjectifs : laufend, spannend, geschlossen, gebucht — panneaux, avertissements et activités',
  goals: ['Form the Partizip Präsens (Infinitiv + d) and use it as an adjective', 'Use the Partizip Perfekt as an adjective (die gebuchte Reise)', 'Read and understand signs, rules and warnings', 'Talk about courses, leisure and adventure activities'],
  goalsFr: ['Former le participe présent (infinitif + d) et l’employer comme adjectif', 'Employer le participe passé comme adjectif (die gebuchte Reise)', 'Lire et comprendre des panneaux, règles et avertissements', 'Parler de cours, de loisirs et d’activités d’aventure'],
  steps: [
    { kind: 'intro', title: 'Auf eigene Gefahr ⚠️', titleFr: 'À vos risques et périls ⚠️',
      scene: 'Ida and her brother Felix browse the programme of a leisure centre: a climbing course, a rafting day and a photography workshop. Every page comes with signs, warnings and small print.',
      sceneFr: 'Ida et son frère Felix feuillettent le programme d’un centre de loisirs : un cours d’escalade, une journée de rafting et un atelier photo. Chaque page est pleine de panneaux, d’avertissements et de petits caractères.',
      goals: ['Turn verbs into adjectives: laufen → laufend, buchen → gebucht', 'Add the normal adjective endings', 'Decode typical notices and warnings', 'Describe a course or an adventure'],
      goalsFr: ['Transformer des verbes en adjectifs : laufen → laufend, buchen → gebucht', 'Ajouter les terminaisons d’adjectif habituelles', 'Décoder des avis et avertissements typiques', 'Décrire un cours ou une aventure'] },

    { kind: 'vocab', item: { id: 'b1l19-gefahr', german: 'die Gefahr', english: 'the danger / risk', french: 'le danger / le risque', gender: 'die', syllables: ['ge', 'FAHR'], pronunciation: 'dee geh-FAHR', example: { de: 'Bei Nebel besteht Gefahr für Wanderer.', en: 'In fog there is danger for hikers.', fr: 'Par temps de brouillard, les randonneurs courent un danger.' } } },
    { kind: 'vocab', item: { id: 'b1l19-teilnahme', german: 'die Teilnahme', english: 'the participation', french: 'la participation', gender: 'die', syllables: ['TEIL', 'nah', 'me'], pronunciation: 'dee TILE-nah-meh', example: { de: 'Die Teilnahme ist kostenlos.', en: 'Participation is free of charge.', fr: 'La participation est gratuite.' } } },
    { kind: 'vocab', item: { id: 'b1l19-hinweis', german: 'der Hinweis', english: 'the notice / tip', french: 'l’avis / l’indication', gender: 'der', syllables: ['HIN', 'weis'], pronunciation: 'dair HIN-vice', example: { de: 'Bitte beachten Sie die Hinweise am Eingang.', en: 'Please note the notices at the entrance.', fr: 'Veuillez tenir compte des avis à l’entrée.' } } },
    { kind: 'vocab', item: { id: 'b1l19-abenteuer', german: 'das Abenteuer', english: 'the adventure', french: 'l’aventure', gender: 'das', syllables: ['A', 'ben', 'teu', 'er'], pronunciation: 'dahss AH-ben-toy-er', example: { de: 'Das Rafting war ein echtes Abenteuer.', en: 'The rafting was a real adventure.', fr: 'Le rafting a été une vraie aventure.' } } },
    { kind: 'vocab', item: { id: 'b1l19-ausruestung', german: 'die Ausrüstung', english: 'the equipment / gear', french: 'l’équipement', gender: 'die', syllables: ['AUS', 'rüs', 'tung'], pronunciation: 'dee OWS-rues-toong', example: { de: 'Die Ausrüstung bekommst du vor Ort.', en: 'You get the equipment on site.', fr: 'Tu reçois l’équipement sur place.' } } },
    { kind: 'vocab', item: { id: 'b1l19-anmeldung', german: 'die Anmeldung', english: 'the registration', french: 'l’inscription', gender: 'die', syllables: ['AN', 'mel', 'dung'], pronunciation: 'dee AHN-mel-doong', example: { de: 'Die Anmeldung ist bis Freitag möglich.', en: 'Registration is possible until Friday.', fr: 'L’inscription est possible jusqu’à vendredi.' } } },
    { kind: 'vocab', item: { id: 'b1l19-spannend', german: 'spannend', english: 'exciting / thrilling', french: 'passionnant / palpitant', gender: null, syllables: ['SPAN', 'nend'], pronunciation: 'SHPAH-nent', example: { de: 'Der Kletterkurs klingt sehr spannend.', en: 'The climbing course sounds very exciting.', fr: 'Le cours d’escalade a l’air très palpitant.' } } },
    { kind: 'vocab', item: { id: 'b1l19-geschlossen', german: 'geschlossen', english: 'closed', french: 'fermé', gender: null, syllables: ['ge', 'SCHLOS', 'sen'], pronunciation: 'geh-SHLOSS-en', example: { de: 'Die Halle ist heute geschlossen.', en: 'The hall is closed today.', fr: 'La salle est fermée aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'b1l19-gebucht', german: 'gebucht', english: 'booked', french: 'réservé', gender: null, syllables: ['ge', 'BUCHT'], pronunciation: 'geh-BOOKHT', example: { de: 'Die gebuchte Reise beginnt im Mai.', en: 'The booked trip starts in May.', fr: 'Le voyage réservé commence en mai.' } } },
    { kind: 'vocab', item: { id: 'b1l19-ausgebucht', german: 'ausgebucht', english: 'fully booked', french: 'complet', gender: null, syllables: ['AUS', 'ge', 'bucht'], pronunciation: 'OWSS-geh-bookht', example: { de: 'Der Fotokurs ist leider ausgebucht.', en: 'The photography course is unfortunately fully booked.', fr: 'Le cours de photo est malheureusement complet.' } } },
    { kind: 'vocab', item: { id: 'b1l19-begrenzt', german: 'begrenzt', english: 'limited', french: 'limité', gender: null, syllables: ['be', 'GRENZT'], pronunciation: 'beh-GRENTST', example: { de: 'Die Teilnehmerzahl ist begrenzt.', en: 'The number of participants is limited.', fr: 'Le nombre de participants est limité.' } } },
    { kind: 'vocab', item: { id: 'b1l19-verboten', german: 'verboten', english: 'forbidden', french: 'interdit', gender: null, syllables: ['ver', 'BO', 'ten'], pronunciation: 'fair-BOH-ten', example: { de: 'Das Betreten der Baustelle ist verboten.', en: 'Entering the building site is forbidden.', fr: 'L’accès au chantier est interdit.' } } },
    { kind: 'vocab', item: { id: 'b1l19-erforderlich', german: 'erforderlich', english: 'required / necessary', french: 'nécessaire / obligatoire', gender: null, syllables: ['er', 'FOR', 'der', 'lich'], pronunciation: 'air-FOR-der-lish', example: { de: 'Für den Kurs ist eine Anmeldung erforderlich.', en: 'Registration is required for the course.', fr: 'Une inscription est obligatoire pour le cours.' } } },

    { kind: 'grammar', note: {
      id: 'b1l19-partizip-praesens', title: 'Partizip Präsens: Infinitiv + d', titleFr: 'Participe présent : infinitif + d',
      explanationMd: 'Add **-d** to the infinitive and you get the **Partizip Präsens**: lachen → **lachend**, steigen → **steigend**, laufen → **laufend**. As an adjective it gets the **normal adjective ending**.\n\nIt describes something that is **happening right now** (active meaning, "…ing"):\n\n- Das Wasser **kocht**. → das **kochende** Wasser (the boiling water)\n- Die Preise **steigen**. → die **steigenden** Preise (the rising prices)\n- Die Geschichte **fesselt** uns. → eine **fesselnde** Geschichte (a gripping story)\n\nEndings work as always: **ein** lachend**es** Kind (n), **der** lachend**e** Mann (m), **die** lachend**en** Kinder (pl).\n\nIrregular: sein → **seiend** and tun → **tuend** are rare; ignore them for now.',
      explanationMdFr: 'Ajoute **-d** à l’infinitif et tu obtiens le **Partizip Präsens** : lachen → **lachend**, steigen → **steigend**, laufen → **laufend**. Comme adjectif, il prend la **terminaison d’adjectif habituelle**.\n\nIl décrit quelque chose qui **se passe en ce moment** (sens actif, « …ant ») :\n\n- Das Wasser **kocht**. → das **kochende** Wasser (l’eau qui bout)\n- Die Preise **steigen**. → die **steigenden** Preise (les prix qui montent)\n- Die Geschichte **fesselt** uns. → eine **fesselnde** Geschichte (une histoire captivante)\n\nLes terminaisons sont celles de toujours : **ein** lachend**es** Kind (n), **der** lachend**e** Mann (m), **die** lachend**en** Kinder (pl).\n\nIrréguliers : sein → **seiend** et tun → **tuend** sont rares ; oublie-les pour l’instant.',
      examples: [
        { de: 'Ein lachendes Kind rennt durch den Park.', en: 'A laughing child runs through the park.', fr: 'Un enfant qui rit court à travers le parc.' },
        { de: 'Die steigenden Preise machen vielen Familien Sorgen.', en: 'The rising prices worry many families.', fr: 'La hausse des prix inquiète beaucoup de familles.' },
        { de: 'Vorsicht! Das kochende Wasser ist sehr heiß.', en: 'Careful! The boiling water is very hot.', fr: 'Attention ! L’eau bouillante est très chaude.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l19-partizip-perfekt', title: 'Partizip Perfekt as an adjective', titleFr: 'Le participe passé comme adjectif',
      explanationMd: 'You already know the Partizip Perfekt from the Perfekt (gebucht, geschlossen, verloren). Put it **before a noun** with an adjective ending and it describes the **result or state** — usually with a **passive** meaning:\n\n- Die Tür **wurde** geschlossen. → die **geschlossene** Tür (the closed door)\n- Ich habe die Reise gebucht. → die **gebuchte** Reise (the booked trip)\n- Ich suche den **verlorenen** Schlüssel. (the lost key)\n\nVerbs with **sein** in the Perfekt give an **active** sense: Die Blätter **sind gefallen**. → die **gefallenen** Blätter (the fallen leaves).\n\nWithout an article, the ending shows case: **Geänderte** Öffnungszeiten (changed opening hours), **Geschlossene** Gesellschaft (private party).',
      explanationMdFr: 'Tu connais déjà le participe passé grâce au Perfekt (gebucht, geschlossen, verloren). Place-le **devant un nom** avec une terminaison d’adjectif et il décrit le **résultat ou l’état** — le plus souvent avec un sens **passif** :\n\n- Die Tür **wurde** geschlossen. → die **geschlossene** Tür (la porte fermée)\n- Ich habe die Reise gebucht. → die **gebuchte** Reise (le voyage réservé)\n- Ich suche den **verlorenen** Schlüssel. (la clé perdue)\n\nLes verbes avec **sein** au Perfekt donnent un sens **actif** : Die Blätter **sind gefallen**. → die **gefallenen** Blätter (les feuilles tombées).\n\nSans article, la terminaison montre le cas : **Geänderte** Öffnungszeiten (horaires modifiés), **Geschlossene** Gesellschaft (réception privée).',
      examples: [
        { de: 'Die gebuchte Reise war günstig und perfekt organisiert.', en: 'The booked trip was cheap and perfectly organised.', fr: 'Le voyage réservé était bon marché et parfaitement organisé.' },
        { de: 'Bitte schließen Sie die geöffnete Tür wieder.', en: 'Please close the opened door again.', fr: 'Veuillez refermer la porte ouverte.' },
        { de: 'Ein gebrauchtes Fahrrad kostet weniger als ein neues.', en: 'A used bike costs less than a new one.', fr: 'Un vélo d’occasion coûte moins cher qu’un neuf.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l19-schilder', title: 'Signs, rules and warnings', titleFr: 'Panneaux, règles et avertissements',
      explanationMd: 'Notices love participles because they are short and formal. After **sein** or **bleiben**, the participle is a state and takes **no ending**:\n\n- Der Kurs ist **ausgebucht**. · Das Museum bleibt **geschlossen**.\n- Rauchen ist **verboten**. · Eine Anmeldung ist **erforderlich**.\n- Die Teilnehmerzahl ist **begrenzt**.\n\nBefore a noun, add the ending: **begrenzte** Teilnehmerzahl, **geänderte** Öffnungszeiten, **reservierter** Tisch.\n\nTypical warning phrase: **Die Teilnahme erfolgt auf eigene Gefahr.** — participation is at your own risk. Also: **Eltern haften für ihre Kinder.**',
      explanationMdFr: 'Les avis adorent les participes car ils sont courts et formels. Après **sein** ou **bleiben**, le participe est un état et ne prend **aucune terminaison** :\n\n- Der Kurs ist **ausgebucht**. · Das Museum bleibt **geschlossen**.\n- Rauchen ist **verboten**. · Eine Anmeldung ist **erforderlich**.\n- Die Teilnehmerzahl ist **begrenzt**.\n\nDevant un nom, ajoute la terminaison : **begrenzte** Teilnehmerzahl, **geänderte** Öffnungszeiten, **reservierter** Tisch.\n\nPhrase d’avertissement typique : **Die Teilnahme erfolgt auf eigene Gefahr.** — la participation se fait à vos risques et périls. Aussi : **Eltern haften für ihre Kinder.**',
      examples: [
        { de: 'Der Klettersteig ist heute wegen des Regens gesperrt.', en: 'The via ferrata is closed today because of rain.', fr: 'La via ferrata est fermée aujourd’hui à cause de la pluie.' },
        { de: 'Die Teilnahme am Rafting erfolgt auf eigene Gefahr.', en: 'Participation in the rafting is at your own risk.', fr: 'La participation au rafting se fait à vos risques et périls.' },
        { de: 'Begrenzte Teilnehmerzahl – Anmeldung erforderlich!', en: 'Limited number of participants – registration required!', fr: 'Nombre de participants limité – inscription obligatoire !' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l19-e1', prompt: 'Das Wasser kocht. → das ___ Wasser (Partizip Präsens + ending)', promptFr: 'Das Wasser kocht. → das ___ Wasser (participe présent + terminaison)', answer: 'kochende', hint: 'kochen + d + e', hintFr: 'kochen + d + e' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l19-e2', prompt: 'Choose the correct form: die ___ Tür (schließen, result)', promptFr: 'Choisis la bonne forme : die ___ Tür (schließen, résultat)', options: ['geschlossene', 'schließende', 'geschlossen'], answer: 0, explain: 'A closed door = Partizip Perfekt + ending -e (feminine, nominative).', explainFr: 'Une porte fermée = participe passé + terminaison -e (féminin, nominatif).', hint: 'The door was closed — a result, with an ending.', hintFr: 'La porte a été fermée — un résultat, avec terminaison.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l19-e3', tokens: ['beginnt', 'Der', 'um', 'Film', 'acht', 'spannende', 'Uhr'], answer: ['Der', 'spannende', 'Film', 'beginnt', 'um', 'acht', 'Uhr'], hint: 'The participle-adjective stands between article and noun.', hintFr: 'L’adjectif-participe se place entre l’article et le nom.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l19-e4', pairs: [ { de: 'die gebuchte Reise', en: 'the booked trip', fr: 'le voyage réservé' }, { de: 'der spannende Film', en: 'the exciting film', fr: 'le film palpitant' }, { de: 'die geschlossene Tür', en: 'the closed door', fr: 'la porte fermée' }, { de: 'die steigenden Preise', en: 'the rising prices', fr: 'les prix qui montent' } ], hint: 'Match each phrase to its meaning.', hintFr: 'Associe chaque expression à son sens.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l19-e5', prompt: 'Listen to the sign. What does it mean?', promptFr: 'Écoute le panneau. Que signifie-t-il ?', audio: { ttsText: 'Achtung! Die Teilnahme an der Wanderung erfolgt auf eigene Gefahr.' }, options: ['You take part at your own risk', 'The hike is cancelled', 'The hike is free'], optionsFr: ['Tu participes à tes risques et périls', 'La randonnée est annulée', 'La randonnée est gratuite'], answer: 0, hint: 'Listen for "auf eigene Gefahr".', hintFr: 'Écoute « auf eigene Gefahr ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l19-e6', prompt: 'Which one is a Partizip Präsens?', promptFr: 'Lequel est un participe présent ?', options: ['gelaufen', 'laufend', 'zu laufen'], answer: 1, explain: 'Infinitive + d = Partizip Präsens: laufen → laufend.', explainFr: 'Infinitif + d = participe présent : laufen → laufend.', hint: 'Look for the -d ending.', hintFr: 'Cherche la terminaison -d.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l19-e7', prompt: 'Ich habe die Reise gebucht. Die ___ Reise war günstig.', promptFr: 'Ich habe die Reise gebucht. Die ___ Reise war günstig.', answer: 'gebuchte', hint: 'gebucht + e', hintFr: 'gebucht + e' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l19-e8', prompt: 'Ein ___ Kind spielt im Garten. (lachen)', promptFr: 'Ein ___ Kind spielt im Garten. (lachen)', options: ['lachendes', 'lachende', 'gelachtes'], answer: 0, explain: '"Kind" is neuter; after "ein" the nominative ending is -es.', explainFr: '« Kind » est neutre ; après « ein », la terminaison du nominatif est -es.', hint: 'ein + neuter noun → -es', hintFr: 'ein + nom neutre → -es' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l19-e9', prompt: 'Der Kletterkurs ist leider ___. (fully booked)', promptFr: 'Der Kletterkurs ist leider ___. (complet)', answer: 'ausgebucht', hint: 'after "sein" the participle takes no ending', hintFr: 'après « sein », le participe ne prend pas de terminaison' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l19-e10', prompt: 'Listen. What must you bring?', promptFr: 'Écoute. Que faut-il apporter ?', audio: { ttsText: 'Bitte bringen Sie feste Schuhe und wetterfeste Kleidung mit.' }, options: ['Sturdy shoes and weatherproof clothes', 'A swimsuit and a towel', 'A laptop and a notebook'], optionsFr: ['Des chaussures solides et des vêtements imperméables', 'Un maillot de bain et une serviette', 'Un ordinateur et un cahier'], answer: 0, hint: 'Think of a hiking or climbing course.', hintFr: 'Pense à un cours de randonnée ou d’escalade.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l19-e11', tokens: ['Reise', 'war', 'Die', 'wirklich', 'gebuchte', 'günstig'], answer: ['Die', 'gebuchte', 'Reise', 'war', 'wirklich', 'günstig'], hint: 'Article, participle-adjective, noun, then verb.', hintFr: 'Article, adjectif-participe, nom, puis verbe.' } },

    { kind: 'pronunciation', focus: 'The ending -end is pronounced "-ent": laufend, steigend — stress the verb stem, not the ending', focusFr: 'La terminaison -end se prononce « -ent » : laufend, steigend — accentue le radical, pas la terminaison', items: [
      { id: 'b1l19-laufend-pron', german: 'laufend', english: 'running / ongoing', french: 'en cours / qui court', gender: null, syllables: ['LAU', 'fend'], pronunciation: 'LOW-fent', example: { de: 'Das laufende Jahr ist fast vorbei.', en: 'The current year is almost over.', fr: 'L’année en cours est presque terminée.' } },
      { id: 'b1l19-steigend-pron', german: 'steigend', english: 'rising', french: 'croissant', gender: null, syllables: ['STEI', 'gend'], pronunciation: 'SHTY-gent', example: { de: 'Die steigenden Preise sind ein Problem.', en: 'The rising prices are a problem.', fr: 'La hausse des prix est un problème.' } },
      { id: 'b1l19-lachend-pron', german: 'lachend', english: 'laughing', french: 'riant', gender: null, syllables: ['LA', 'chend'], pronunciation: 'LAH-khent', example: { de: 'Sie kam lachend aus dem Kurs.', en: 'She came out of the course laughing.', fr: 'Elle est sortie du cours en riant.' } },
      { id: 'b1l19-ueberraschend-pron', german: 'überraschend', english: 'surprising', french: 'surprenant', gender: null, syllables: ['ü', 'ber', 'RA', 'schend'], pronunciation: 'ew-ber-RAH-shent', example: { de: 'Das Ende war überraschend.', en: 'The ending was surprising.', fr: 'La fin était surprenante.' } },
      { id: 'b1l19-fesselnd-pron', german: 'fesselnd', english: 'gripping', french: 'captivant', gender: null, syllables: ['FES', 'selnd'], pronunciation: 'FESS-elnt', example: { de: 'Das Buch ist fesselnd.', en: 'The book is gripping.', fr: 'Le livre est captivant.' } },
    ] },

    { kind: 'wrapup', summary: 'Participles can work as adjectives. The **Partizip Präsens** (Infinitiv + **d**) describes what is happening: **kochendes** Wasser, **steigende** Preise. The **Partizip Perfekt** describes a result or state: **geschlossene** Tür, **gebuchte** Reise. Both take normal adjective endings before a noun; after **sein** the participle stays bare (**ausgebucht**, **verboten**). Now you can read signs and warnings like a local. 🎉',
      summaryFr: 'Les participes peuvent servir d’adjectifs. Le **Partizip Präsens** (infinitif + **d**) décrit ce qui se passe : **kochendes** Wasser, **steigende** Preise. Le **Partizip Perfekt** décrit un résultat ou un état : **geschlossene** Tür, **gebuchte** Reise. Les deux prennent les terminaisons d’adjectif habituelles devant un nom ; après **sein**, le participe reste nu (**ausgebucht**, **verboten**). Tu peux maintenant lire panneaux et avertissements comme un habitant. 🎉' },
  ],
};
