import type { Lesson } from '../types';

export const b1lektion17: Lesson = {
  id: 'b1-l17', level: 'B1', module: 4, number: 16,
  title: { de: 'Adjektive im Komparativ und Superlativ', en: 'Attributive comparatives and superlatives', fr: 'Comparatifs et superlatifs devant le nom' },
  theme: 'Using comparatives and superlatives in front of a noun, with health, sport and well-being',
  themeFr: 'Utiliser le comparatif et le superlatif devant un nom, autour de la santé, du sport et du bien-être',
  goals: ['Put comparatives in front of nouns (ein größeres Haus)', 'Use superlatives with an article (der schnellste Läufer)', 'Add the right adjective ending in every case', 'Talk about sport, health and fitness habits'],
  goalsFr: ['Placer des comparatifs devant des noms (ein größeres Haus)', 'Utiliser des superlatifs avec un article (der schnellste Läufer)', 'Ajouter la bonne terminaison d’adjectif à chaque cas', 'Parler de sport, de santé et d’habitudes de forme'],
  steps: [
    { kind: 'intro', title: 'Fitter, gesünder, besser 🏃', titleFr: 'Plus en forme, plus sain, meilleur 🏃',
      scene: 'A health programme at the office: colleagues compare their fitness habits, choose a bigger gym and present the healthiest routines.', sceneFr: 'Un programme santé au bureau : les collègues comparent leurs habitudes sportives, choisissent une salle plus grande et présentent les routines les plus saines.',
      goals: ['Combine comparative + adjective ending', 'Combine superlative + adjective ending', 'Choose the correct case ending', 'Learn the irregular forms (besser, höher, nächst-)'],
      goalsFr: ['Combiner comparatif + terminaison d’adjectif', 'Combiner superlatif + terminaison d’adjectif', 'Choisir la bonne terminaison selon le cas', 'Apprendre les formes irrégulières (besser, höher, nächst-)'] },

    { kind: 'vocab', item: { id: 'b1l17-wohlbefinden', german: 'das Wohlbefinden', english: 'the well-being', french: 'le bien-être', gender: 'das', syllables: ['WOHL', 'be', 'fin', 'den'], pronunciation: 'dahs VOHL-be-fin-den', example: { de: 'Bewegung steigert das Wohlbefinden.', en: 'Exercise increases well-being.', fr: 'Le mouvement augmente le bien-être.' } } },
    { kind: 'vocab', item: { id: 'b1l17-gesundheit', german: 'die Gesundheit', english: 'the health', french: 'la santé', gender: 'die', syllables: ['ge', 'SUND', 'heit'], pronunciation: 'dee ge-ZOONT-hite', example: { de: 'Gesundheit ist das größte Gut.', en: 'Health is the greatest asset.', fr: 'La santé est le bien le plus précieux.' } } },
    { kind: 'vocab', item: { id: 'b1l17-bewegung', german: 'die Bewegung', english: 'the movement / exercise', french: 'le mouvement / l’activité physique', gender: 'die', syllables: ['be', 'WE', 'gung'], pronunciation: 'dee be-VAY-goong', example: { de: 'Mehr Bewegung im Alltag tut gut.', en: 'More exercise in everyday life does you good.', fr: 'Plus de mouvement au quotidien fait du bien.' } } },
    { kind: 'vocab', item: { id: 'b1l17-ausdauer', german: 'die Ausdauer', english: 'the stamina / endurance', french: 'l’endurance', gender: 'die', syllables: ['AUS', 'dau', 'er'], pronunciation: 'dee OWS-dow-er', example: { de: 'Für mehr Ausdauer laufe ich dreimal pro Woche.', en: 'For more stamina I run three times a week.', fr: 'Pour plus d’endurance, je cours trois fois par semaine.' } } },
    { kind: 'vocab', item: { id: 'b1l17-kraft', german: 'die Kraft', english: 'the strength', french: 'la force', gender: 'die', syllables: ['KRAFT'], pronunciation: 'dee krahft', example: { de: 'Nach dem Krafttraining fühle ich mich stärker.', en: 'After strength training I feel stronger.', fr: 'Après la musculation, je me sens plus fort.' } } },
    { kind: 'vocab', item: { id: 'b1l17-entspannung', german: 'die Entspannung', english: 'the relaxation', french: 'la détente', gender: 'die', syllables: ['ent', 'SPAN', 'nung'], pronunciation: 'dee ent-SHPAH-noong', example: { de: 'Yoga ist eine gute Entspannung nach der Arbeit.', en: 'Yoga is a good way to relax after work.', fr: 'Le yoga est une bonne détente après le travail.' } } },
    { kind: 'vocab', item: { id: 'b1l17-ernaehrung', german: 'die Ernährung', english: 'the nutrition / diet', french: 'l’alimentation', gender: 'die', syllables: ['er', 'NÄH', 'rung'], pronunciation: 'dee er-NAIR-roong', example: { de: 'Eine gesündere Ernährung beginnt beim Einkaufen.', en: 'A healthier diet starts at the supermarket.', fr: 'Une alimentation plus saine commence aux courses.' } } },
    { kind: 'vocab', item: { id: 'b1l17-stress', german: 'der Stress', english: 'the stress', french: 'le stress', gender: 'der', syllables: ['STRESS'], pronunciation: 'dair shtress', example: { de: 'Stress im Büro macht müde.', en: 'Stress at the office makes you tired.', fr: 'Le stress au bureau fatigue.' } } },
    { kind: 'vocab', item: { id: 'b1l17-gewohnheit', german: 'die Gewohnheit', english: 'the habit', french: 'l’habitude', gender: 'die', syllables: ['ge', 'WOHN', 'heit'], pronunciation: 'dee ge-VOHN-hite', example: { de: 'Jeden Morgen zu laufen ist eine gute Gewohnheit.', en: 'Running every morning is a good habit.', fr: 'Courir tous les matins est une bonne habitude.' } } },
    { kind: 'vocab', item: { id: 'b1l17-fitnessstudio', german: 'das Fitnessstudio', english: 'the gym', french: 'la salle de sport', gender: 'das', syllables: ['FIT', 'ness', 'stu', 'di', 'o'], pronunciation: 'dahs FIT-ness-shtoo-dee-oh', example: { de: 'Das neue Fitnessstudio hat längere Öffnungszeiten.', en: 'The new gym has longer opening hours.', fr: 'La nouvelle salle de sport a des horaires d’ouverture plus longs.' } } },
    { kind: 'vocab', item: { id: 'b1l17-beitragen', german: 'beitragen (zu)', english: 'to contribute (to)', french: 'contribuer (à)', gender: null, syllables: ['BEI', 'tra', 'gen'], pronunciation: 'BY-trah-gen', example: { de: 'Sport trägt zu einem größeren Wohlbefinden bei.', en: 'Sport contributes to greater well-being.', fr: 'Le sport contribue à un plus grand bien-être.' } } },
    { kind: 'vocab', item: { id: 'b1l17-laeufer', german: 'der Läufer', english: 'the runner', french: 'le coureur', gender: 'der', syllables: ['LÄU', 'fer'], pronunciation: 'dair LOY-fer', example: { de: 'Der schnellste Läufer gewinnt das Rennen.', en: 'The fastest runner wins the race.', fr: 'Le coureur le plus rapide gagne la course.' } } },
    { kind: 'vocab', item: { id: 'b1l17-gesund', german: 'gesund', english: 'healthy', french: 'sain / en bonne santé', gender: null, syllables: ['ge', 'SUND'], pronunciation: 'ge-ZOONT', example: { de: 'Ich möchte einen gesünderen Lebensstil.', en: 'I would like a healthier lifestyle.', fr: 'Je voudrais un mode de vie plus sain.' } } },

    { kind: 'grammar', note: {
      id: 'b1l17-komparativ-attr', title: 'Comparative in front of a noun', titleFr: 'Le comparatif devant un nom',
      explanationMd: 'In front of a noun, the **comparative** (**-er**) keeps its **-er** and then takes the **normal adjective ending**:\n\n- schnell → schnell**er** + ending: ein schnell**erer** Läufer (m), eine schnell**ere** Läuferin (f), ein schnell**eres** Tempo (n)\n- groß → größ**er**: ein **größeres** Haus · gesund → ges**ünder**: eine **gesündere** Ernährung\n\nAfter **der/die/das**: -e / -en (*der größere Raum*, *mit dem größeren Raum*). After **ein-**: -er / -e / -es (nominative), -en / -e / -es (accusative), -en (dative).\n\nAdjectives in **-el** and **-er** drop the **e**: dunkel → ein **dunkleres** Zimmer, teuer → ein **teureres** Auto.\n\nThere is **no "am"** in front of a noun, and **mehr / weniger** take **no ending**: mehr Bewegung, weniger Stress.',
      explanationMdFr: 'Devant un nom, le **comparatif** (**-er**) garde son **-er** puis prend la **terminaison normale de l’adjectif** :\n\n- schnell → schnell**er** + terminaison : ein schnell**erer** Läufer (m), eine schnell**ere** Läuferin (f), ein schnell**eres** Tempo (n)\n- groß → größ**er** : ein **größeres** Haus · gesund → ges**ünder** : eine **gesündere** Ernährung\n\nAprès **der/die/das** : -e / -en (*der größere Raum*, *mit dem größeren Raum*). Après **ein-** : -er / -e / -es (nominatif), -en / -e / -es (accusatif), -en (datif).\n\nLes adjectifs en **-el** et **-er** perdent le **e** : dunkel → ein **dunkleres** Zimmer, teuer → ein **teureres** Auto.\n\nIl n’y a **pas de « am »** devant un nom, et **mehr / weniger** ne prennent **aucune terminaison** : mehr Bewegung, weniger Stress.',
      examples: [
        { de: 'Wir suchen ein größeres Fitnessstudio.', en: 'We are looking for a bigger gym.', fr: 'Nous cherchons une salle de sport plus grande.' },
        { de: 'Sie wünscht sich eine gesündere Ernährung.', en: 'She wishes for a healthier diet.', fr: 'Elle souhaite une alimentation plus saine.' },
        { de: 'Er hat einen längeren Weg zur Arbeit als ich.', en: 'He has a longer way to work than I do.', fr: 'Il a un trajet plus long que moi pour aller au travail.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l17-superlativ-attr', title: 'Superlative in front of a noun', titleFr: 'Le superlatif devant un nom',
      explanationMd: 'In front of a noun the superlative ends in **-st** plus the adjective ending, and is almost always used with a **definite article** (or a possessive):\n\n- der schnell**ste** Läufer · die schnell**ste** Läuferin · das schnell**ste** Auto\n- Akk: Ich kenne **den** schnell**sten** Läufer. · Dat: Ich trainiere mit **dem** schnell**sten** Läufer.\n\nAfter **d, t, s, ß, z, sch** add **-est**: alt → der **ältest**e, gesund → der **gesündest**e, heiß → der **heißest**e. Exception: groß → der **größte**.\n\nCompare the **predicative** form from A2: *Er läuft **am schnellsten**.* — but with a noun: *Er ist **der schnellste** Läufer.*',
      explanationMdFr: 'Devant un nom, le superlatif se termine par **-st** plus la terminaison de l’adjectif, et s’emploie presque toujours avec un **article défini** (ou un possessif) :\n\n- der schnell**ste** Läufer · die schnell**ste** Läuferin · das schnell**ste** Auto\n- Acc : Ich kenne **den** schnell**sten** Läufer. · Dat : Ich trainiere mit **dem** schnell**sten** Läufer.\n\nAprès **d, t, s, ß, z, sch**, on ajoute **-est** : alt → der **ältest**e, gesund → der **gesündest**e, heiß → der **heißest**e. Exception : groß → der **größte**.\n\nCompare avec la forme **attribut** vue en A2 : *Er läuft **am schnellsten**.* — mais devant un nom : *Er ist **der schnellste** Läufer.*',
      examples: [
        { de: 'Das ist das größte Fitnessstudio der Stadt.', en: 'That is the biggest gym in the city.', fr: 'C’est la plus grande salle de sport de la ville.' },
        { de: 'Ich gehe mit meinem besten Freund joggen.', en: 'I go jogging with my best friend.', fr: 'Je vais courir avec mon meilleur ami.' },
        { de: 'Die gesündeste Gewohnheit ist ein regelmäßiger Spaziergang.', en: 'The healthiest habit is a regular walk.', fr: 'L’habitude la plus saine est une promenade régulière.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l17-alle-faelle', title: 'All cases and irregular forms', titleFr: 'Tous les cas et formes irrégulières',
      explanationMd: 'Comparative and superlative endings follow the **usual pattern** — **dative is always -en** (singular and plural):\n\n- Nom: der beste Plan · ein besserer Plan\n- Akk: den besten Plan · einen besseren Plan\n- Dat: mit dem besten Plan · mit einem besseren Plan · mit der besseren Idee\n- Plural: die besten Ideen · mit besseren Ideen\n\nMemorise these irregular stems:\n\n- gut → **besser** → der **best-**\n- hoch → **höher** → der **höchst-** (*ein höherer Preis*, *der höchste Berg*)\n- nah → **näher** → der **nächst-** (*das nächste Fitnessstudio*)\n- viel → **mehr** → die **meist-** (*die meisten Menschen*)\n\n**Sport trägt zu einem größeren Wohlbefinden bei.** — *zu* + dative → *einem* (n) → *größeren*.',
      explanationMdFr: 'Les terminaisons du comparatif et du superlatif suivent le **schéma habituel** — le **datif est toujours en -en** (singulier et pluriel) :\n\n- Nom : der beste Plan · ein besserer Plan\n- Acc : den besten Plan · einen besseren Plan\n- Dat : mit dem besten Plan · mit einem besseren Plan · mit der besseren Idee\n- Pluriel : die besten Ideen · mit besseren Ideen\n\nRetiens ces radicaux irréguliers :\n\n- gut → **besser** → der **best-**\n- hoch → **höher** → der **höchst-** (*ein höherer Preis*, *der höchste Berg*)\n- nah → **näher** → der **nächst-** (*das nächste Fitnessstudio*)\n- viel → **mehr** → die **meist-** (*die meisten Menschen*)\n\n**Sport trägt zu einem größeren Wohlbefinden bei.** — *zu* + datif → *einem* (n) → *größeren*.',
      examples: [
        { de: 'Sie hat ein besseres Gefühl als früher.', en: 'She has a better feeling than before.', fr: 'Elle se sent mieux qu’avant.' },
        { de: 'Das nächste Schwimmbad ist zehn Minuten entfernt.', en: 'The nearest swimming pool is ten minutes away.', fr: 'La piscine la plus proche est à dix minutes.' },
        { de: 'Mit einem intensiveren Training steigt auch die Kraft.', en: 'With more intense training, strength also rises.', fr: 'Avec un entraînement plus intensif, la force augmente aussi.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l17-e1', prompt: 'Wir suchen ein ___ Fitnessstudio. (groß → comparative, n accusative)', promptFr: 'Wir suchen ein ___ Fitnessstudio. (groß → comparatif, n accusatif)', answer: 'größeres', hint: 'größer + -es after "ein" (neuter)', hintFr: 'größer + -es après « ein » (neutre)' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l17-e2', prompt: 'Das ist der ___ Läufer im Verein. (schnell → superlative)', promptFr: 'Das ist der ___ Läufer im Verein. (schnell → superlatif)', answer: 'schnellste', hint: 'schnell + st + e', hintFr: 'schnell + st + e' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l17-e3', prompt: 'Choose: "Heute hatte ich ein ___ Training als gestern."', promptFr: 'Choisis : « Heute hatte ich ein ___ Training als gestern. »', options: ['besser', 'besseres', 'bessere'], answer: 1, explain: 'Neuter accusative after "ein": comparative besser + -es.', explainFr: 'Neutre accusatif après « ein » : comparatif besser + -es.', hint: 'Training is neuter; "ein" → -es.', hintFr: 'Training est neutre ; « ein » → -es.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l17-e4', prompt: 'Ich gehe mit meinem ___ Freund joggen. (gut → superlative)', promptFr: 'Ich gehe mit meinem ___ Freund joggen. (gut → superlatif)', answer: 'besten', hint: 'dative after "mit": ending -en', hintFr: 'datif après « mit » : terminaison -en' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l17-e5', prompt: 'Sie wünscht sich eine ___ Ernährung. (gesund → comparative, f accusative)', promptFr: 'Sie wünscht sich eine ___ Ernährung. (gesund → comparatif, f accusatif)', answer: 'gesündere', hint: 'umlaut + -er + ending -e', hintFr: 'tréma + -er + terminaison -e' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l17-e6', prompt: 'Choose: "Sport trägt zu einem ___ Wohlbefinden bei."', promptFr: 'Choisis : « Sport trägt zu einem ___ Wohlbefinden bei. »', options: ['größeren', 'größere', 'größeres'], answer: 0, explain: '"zu" takes the dative; after "einem" the ending is -en.', explainFr: '« zu » demande le datif ; après « einem » la terminaison est -en.', hint: 'Dative singular → -en.', hintFr: 'Datif singulier → -en.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l17-e7', tokens: ['gewinnt', 'Der', 'Läufer', 'das', 'schnellste', 'Rennen'], answer: ['Der', 'schnellste', 'Läufer', 'gewinnt', 'das', 'Rennen'], hint: 'Article, superlative with ending, noun, then verb.', hintFr: 'Article, superlatif avec terminaison, nom, puis verbe.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l17-e8', pairs: [ { de: 'gut', en: 'der beste', fr: 'der beste' }, { de: 'hoch', en: 'der höchste', fr: 'der höchste' }, { de: 'nah', en: 'der nächste', fr: 'der nächste' }, { de: 'groß', en: 'der größte', fr: 'der größte' } ], hint: 'Match each adjective with its superlative (masculine nominative).', hintFr: 'Associe chaque adjectif à son superlatif (masculin nominatif).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l17-e9', prompt: 'Listen. Who lives healthier?', promptFr: 'Écoute. Qui vit plus sainement ?', audio: { ttsText: 'Meine Schwester hat einen gesünderen Lebensstil als ich.' }, options: ['The sister', 'The speaker', 'Both the same'], optionsFr: ['La sœur', 'La personne qui parle', 'Les deux pareil'], answer: 0, hint: 'Listen for "gesünderen … als ich".', hintFr: 'Écoute « gesünderen … als ich ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l17-e10', prompt: 'Listen. What is special about the gym?', promptFr: 'Écoute. Qu’a de spécial la salle de sport ?', audio: { ttsText: 'Das ist das größte Fitnessstudio der Stadt.' }, options: ['It is the biggest in the city', 'It is the cheapest', 'It is the newest'], optionsFr: ['C’est la plus grande de la ville', 'C’est la moins chère', 'C’est la plus récente'], answer: 0, hint: 'Listen to the adjective before "Fitnessstudio".', hintFr: 'Écoute l’adjectif avant « Fitnessstudio ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l17-e11', prompt: 'Which form is correct in front of the noun?', promptFr: 'Quelle forme est correcte devant le nom ?', options: ['der schnellste Läufer', 'der am schnellsten Läufer', 'der schnellster Läufer'], answer: 0, explain: 'Superlative + -ste after the definite article; no "am" in front of a noun.', explainFr: 'Superlatif + -ste après l’article défini ; pas de « am » devant un nom.', hint: 'No "am" before a noun; der → -e ending.', hintFr: 'Pas de « am » devant un nom ; der → terminaison -e.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l17-e12', word: 'Wohlbefinden', answer: 'das', hint: 'a nominalised verb (befinden) is neuter', hintFr: 'un verbe substantivé (befinden) est neutre' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l17-e13', word: 'Ausdauer', answer: 'die', hint: 'a feminine noun', hintFr: 'un nom féminin' } },

    { kind: 'pronunciation', focus: 'The umlauts ä, ö, ü in comparatives: größer, gesünder, längere (rounded and fronted vowels)', focusFr: 'Les trémas ä, ö, ü dans les comparatifs : größer, gesünder, längere (voyelles arrondies et antérieures)', items: [
      { id: 'b1l17-groesseres-pron', german: 'größeres', english: 'bigger (n)', french: 'plus grand (n)', gender: null, syllables: ['GRÖ', 'se', 'res'], pronunciation: 'GROE-se-res', example: { de: 'Ein größeres Zimmer, bitte.', en: 'A bigger room, please.', fr: 'Une chambre plus grande, s’il vous plaît.' } },
      { id: 'b1l17-gesuender-pron', german: 'gesünder', english: 'healthier', french: 'plus sain', gender: null, syllables: ['ge', 'SÜN', 'der'], pronunciation: 'ge-ZUEN-der', example: { de: 'Obst ist gesünder als Kuchen.', en: 'Fruit is healthier than cake.', fr: 'Les fruits sont plus sains que le gâteau.' } },
      { id: 'b1l17-laengere-pron', german: 'längere', english: 'longer', french: 'plus longue', gender: null, syllables: ['LÄN', 'ge', 're'], pronunciation: 'LENG-e-re', example: { de: 'Eine längere Pause tut gut.', en: 'A longer break does you good.', fr: 'Une pause plus longue fait du bien.' } },
      { id: 'b1l17-wohlbefinden-pron', german: 'Wohlbefinden', english: 'well-being', french: 'bien-être', gender: 'das', syllables: ['WOHL', 'be', 'fin', 'den'], pronunciation: 'VOHL-be-fin-den', example: { de: 'Mein Wohlbefinden ist wichtig.', en: 'My well-being is important.', fr: 'Mon bien-être est important.' } },
      { id: 'b1l17-entspannung-pron', german: 'Entspannung', english: 'relaxation', french: 'détente', gender: 'die', syllables: ['ent', 'SPAN', 'nung'], pronunciation: 'ent-SHPAH-noong', example: { de: 'Ich brauche Entspannung.', en: 'I need some relaxation.', fr: 'J’ai besoin de détente.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now use comparatives and superlatives **in front of a noun**: comparative **-er + ending** (*ein größeres Haus*), superlative **-st + ending** with an article (*der schnellste Läufer*). The dative always ends in **-en** (*mit dem besten Freund*, *zu einem größeren Wohlbefinden*). Remember the irregulars **besser / beste, höher / höchste, näher / nächste, mehr / meiste**. 🎉',
      summaryFr: 'Tu sais maintenant employer le comparatif et le superlatif **devant un nom** : comparatif **-er + terminaison** (*ein größeres Haus*), superlatif **-st + terminaison** avec un article (*der schnellste Läufer*). Le datif se termine toujours en **-en** (*mit dem besten Freund*, *zu einem größeren Wohlbefinden*). N’oublie pas les irréguliers **besser / beste, höher / höchste, näher / nächste, mehr / meiste**. 🎉' },
  ],
};
