import type { Lesson } from '../types';

export const b1lektion22: Lesson = {
  id: 'b1-l22', level: 'B1', module: 6, number: 23,
  title: { de: 'Indem und sodass', en: '"indem" and "sodass"', fr: '« indem » et « sodass »' },
  theme: 'Means and result with "indem" and "sodass": thanking, helping, reaching goals',
  themeFr: 'Le moyen et la conséquence avec « indem » et « sodass » : remercier, aider, atteindre ses objectifs',
  goals: ['Explain how you do something with "indem"', 'Express a result with "sodass"', 'Thank people and offer advice', 'Choose between indem, weil, damit and sodass'],
  goalsFr: ['Expliquer comment on fait quelque chose avec « indem »', 'Exprimer une conséquence avec « sodass »', 'Remercier et donner des conseils', 'Choisir entre indem, weil, damit et sodass'],
  steps: [
    { kind: 'intro', title: 'Wie schafft man das? 🤝', titleFr: 'Comment y arriver ? 🤝',
      scene: 'Your neighbour watered your plants for two weeks. How do you say thank you — and how do you reach your own goals? Two little conjunctions answer "how?" and "with what result?".',
      sceneFr: 'Ta voisine a arrosé tes plantes pendant deux semaines. Comment la remercier — et comment atteindre tes propres objectifs ? Deux petites conjonctions répondent à « comment ? » et « avec quel résultat ? ».',
      goals: ['Use "indem" for the means (how?)', 'Use "sodass" for the result', 'Put the verb at the end of both clauses', 'Tell indem / weil / damit / sodass apart'],
      goalsFr: ['Utiliser « indem » pour le moyen (comment ?)', 'Utiliser « sodass » pour le résultat', 'Mettre le verbe à la fin dans les deux cas', 'Distinguer indem / weil / damit / sodass'] },

    { kind: 'vocab', item: { id: 'b1l22-indem', german: 'indem', english: 'by (doing) …', french: 'en (faisant) …', gender: null, syllables: ['in', 'DEM'], pronunciation: 'in-DEM', example: { de: 'Man lernt Vokabeln, indem man sie oft wiederholt.', en: 'You learn vocabulary by repeating it often.', fr: 'On apprend le vocabulaire en le répétant souvent.' } } },
    { kind: 'vocab', item: { id: 'b1l22-sodass', german: 'sodass', english: 'so that / with the result that', french: 'de sorte que / si bien que', gender: null, syllables: ['so', 'DASS'], pronunciation: 'zo-DAHSS', example: { de: 'Es schneite die ganze Nacht, sodass die Straße gesperrt war.', en: 'It snowed all night, so the road was closed.', fr: 'Il a neigé toute la nuit, si bien que la route était fermée.' } } },
    { kind: 'vocab', item: { id: 'b1l22-bedanken', german: 'sich bedanken', english: 'to say thank you', french: 'remercier', gender: null, syllables: ['sich', 'be', 'DAN', 'ken'], pronunciation: 'zikh be-DAHN-ken', example: { de: 'Ich bedanke mich bei dir für deine Hilfe.', en: 'I thank you for your help.', fr: 'Je te remercie pour ton aide.' } } },
    { kind: 'vocab', item: { id: 'b1l22-dankbarkeit', german: 'die Dankbarkeit', english: 'gratitude', french: 'la gratitude', gender: 'die', syllables: ['DANK', 'bar', 'keit'], pronunciation: 'dee DAHNK-bar-kite', example: { de: 'Sie zeigt ihre Dankbarkeit mit einem Brief.', en: 'She shows her gratitude with a letter.', fr: 'Elle montre sa gratitude par une lettre.' } } },
    { kind: 'vocab', item: { id: 'b1l22-unterstuetzen', german: 'unterstützen', english: 'to support', french: 'soutenir', gender: null, syllables: ['un', 'ter', 'STÜT', 'zen'], pronunciation: 'oon-ter-SHTUET-sen', example: { de: 'Meine Eltern unterstützen mich beim Studium.', en: 'My parents support me during my studies.', fr: 'Mes parents me soutiennent pendant mes études.' } } },
    { kind: 'vocab', item: { id: 'b1l22-ziel', german: 'das Ziel', english: 'the goal', french: 'l’objectif', gender: 'das', syllables: ['ZIEL'], pronunciation: 'dahs tseel', example: { de: 'Mein Ziel ist es, bis Juni die Prüfung zu bestehen.', en: 'My goal is to pass the exam by June.', fr: 'Mon objectif est de réussir l’examen d’ici juin.' } } },
    { kind: 'vocab', item: { id: 'b1l22-erreichen', german: 'erreichen', english: 'to reach / achieve', french: 'atteindre', gender: null, syllables: ['er', 'REI', 'chen'], pronunciation: 'air-RY-khen', example: { de: 'Sie hat ihr Ziel erreicht.', en: 'She has reached her goal.', fr: 'Elle a atteint son objectif.' } } },
    { kind: 'vocab', item: { id: 'b1l22-ratschlag', german: 'der Ratschlag', english: 'the piece of advice', french: 'le conseil', gender: 'der', syllables: ['RAT', 'schlag'], pronunciation: 'dair RAHT-shlahk', example: { de: 'Der Ratschlag meiner Oma war Gold wert.', en: 'My grandma’s advice was worth its weight in gold.', fr: 'Le conseil de ma grand-mère valait de l’or.' } } },
    { kind: 'vocab', item: { id: 'b1l22-muehe', german: 'die Mühe', english: 'the effort / trouble', french: 'l’effort / la peine', gender: 'die', syllables: ['MÜ', 'he'], pronunciation: 'dee MUE-eh', example: { de: 'Er gibt sich viel Mühe mit dem Essen.', en: 'He puts a lot of effort into the meal.', fr: 'Il se donne beaucoup de mal pour le repas.' } } },
    { kind: 'vocab', item: { id: 'b1l22-vertrauen', german: 'das Vertrauen', english: 'trust', french: 'la confiance', gender: 'das', syllables: ['ver', 'TRAU', 'en'], pronunciation: 'dahs fair-TROW-en', example: { de: 'Vertrauen wächst, indem man ehrlich ist.', en: 'Trust grows by being honest.', fr: 'La confiance grandit quand on est honnête.' } } },
    { kind: 'vocab', item: { id: 'b1l22-hilfsbereit', german: 'hilfsbereit', english: 'helpful / ready to help', french: 'serviable', gender: null, syllables: ['HILFS', 'be', 'reit'], pronunciation: 'HILFS-be-rite', example: { de: 'Unsere Nachbarn sind sehr hilfsbereit.', en: 'Our neighbours are very helpful.', fr: 'Nos voisins sont très serviables.' } } },
    { kind: 'vocab', item: { id: 'b1l22-zuverlaessig', german: 'zuverlässig', english: 'reliable', french: 'fiable', gender: null, syllables: ['ZU', 'ver', 'läs', 'sig'], pronunciation: 'TSOO-fair-less-ikh', example: { de: 'Ein zuverlässiger Freund ruft zurück.', en: 'A reliable friend calls back.', fr: 'Un ami fiable rappelle.' } } },

    { kind: 'grammar', note: {
      id: 'b1l22-indem-note', title: '"indem": the means (How?)', titleFr: '« indem » : le moyen (Comment ?)',
      explanationMd: '**indem** answers the question **"Wie?"** — it names the **means** or **method** ("by doing …"). It is a subordinating conjunction, so the **conjugated verb goes to the end**:\n\n- Man lernt Deutsch, **indem** man jeden Tag **übt**.\n- Sie dankt ihm, **indem** sie ihm einen Kuchen **backt**.\n\nThe subject is normally the **same** in both clauses. You can also start with the **indem**-clause; then the main verb comes right after the comma:\n\n- **Indem** man jeden Tag übt, **lernt** man schneller.',
      explanationMdFr: '**indem** répond à la question **« Wie ? »** (comment ?) — il nomme le **moyen** ou la **méthode** (« en faisant … »). C’est une conjonction de subordination : le **verbe conjugué va à la fin** :\n\n- Man lernt Deutsch, **indem** man jeden Tag **übt**.\n- Sie dankt ihm, **indem** sie ihm einen Kuchen **backt**.\n\nLe sujet est normalement **le même** dans les deux propositions. On peut aussi commencer par la proposition en **indem** ; le verbe principal suit alors directement la virgule :\n\n- **Indem** man jeden Tag übt, **lernt** man schneller.',
      examples: [
        { de: 'Ich halte mich fit, indem ich jeden Morgen laufe.', en: 'I keep fit by running every morning.', fr: 'Je reste en forme en courant tous les matins.' },
        { de: 'Er hilft mir, indem er meine Taschen trägt.', en: 'He helps me by carrying my bags.', fr: 'Il m’aide en portant mes sacs.' },
        { de: 'Indem sie zuhört, gewinnt sie Vertrauen.', en: 'By listening, she gains trust.', fr: 'En écoutant, elle gagne la confiance.' },
      ],
      diagram: 'satzklammer' } },

    { kind: 'grammar', note: {
      id: 'b1l22-sodass-note', title: '"sodass": the result', titleFr: '« sodass » : la conséquence',
      explanationMd: '**sodass** introduces a **result** that really happened ("so that / with the result that"). It follows the main clause and sends the verb to the **end**:\n\n- Sie hat mir sehr geholfen, **sodass** ich rechtzeitig fertig **wurde**.\n- Es regnete stark, **sodass** das Konzert **ausfiel**.\n\nYou may also see it written in two words: **so dass**. Compare with **deshalb**: the meaning is similar, but **deshalb** keeps the verb in **position 2** (…, deshalb fiel das Konzert aus).',
      explanationMdFr: '**sodass** introduit une **conséquence** qui s’est réellement produite (« de sorte que / si bien que »). Il suit la proposition principale et envoie le verbe à la **fin** :\n\n- Sie hat mir sehr geholfen, **sodass** ich rechtzeitig fertig **wurde**.\n- Es regnete stark, **sodass** das Konzert **ausfiel**.\n\nOn trouve aussi l’écriture en deux mots : **so dass**. Compare avec **deshalb** : le sens est proche, mais **deshalb** garde le verbe en **position 2** (…, deshalb fiel das Konzert aus).',
      examples: [
        { de: 'Der Zug hatte Verspätung, sodass wir den Anschluss verpassten.', en: 'The train was late, so we missed the connection.', fr: 'Le train avait du retard, si bien que nous avons raté la correspondance.' },
        { de: 'Er war so hilfsbereit, dass alle ihn mochten.', en: 'He was so helpful that everyone liked him.', fr: 'Il était si serviable que tout le monde l’aimait.' },
      ],
      diagram: 'verb-second' } },

    { kind: 'grammar', note: {
      id: 'b1l22-vier-note', title: 'Means, reason, purpose or result?', titleFr: 'Moyen, cause, but ou résultat ?',
      explanationMd: 'Ask yourself which question the second clause answers:\n\n- **Wie?** (by what means) → **indem**\n- **Warum?** (reason) → **weil**\n- **Wozu?** (intended purpose) → **damit** / **um … zu**\n- **Mit welchem Ergebnis?** (real result) → **sodass**\n\nAll four send the verb to the **end**.\n\n- Ich danke dir, **indem** ich koche. (how)\n- Ich koche, **weil** ich dir danken will. (why)\n- Ich koche, **damit** du dich freust. (for what purpose)\n- Ich habe gekocht, **sodass** du nicht hungern musst. (result)',
      explanationMdFr: 'Demande-toi à quelle question répond la seconde proposition :\n\n- **Wie ?** (par quel moyen) → **indem**\n- **Warum ?** (cause) → **weil**\n- **Wozu ?** (but visé) → **damit** / **um … zu**\n- **Mit welchem Ergebnis ?** (résultat réel) → **sodass**\n\nLes quatre envoient le verbe à la **fin**.\n\n- Ich danke dir, **indem** ich koche. (comment)\n- Ich koche, **weil** ich dir danken will. (pourquoi)\n- Ich koche, **damit** du dich freust. (dans quel but)\n- Ich habe gekocht, **sodass** du nicht hungern musst. (résultat)',
      examples: [
        { de: 'Sie zeigt Dankbarkeit, indem sie „Danke“ sagt.', en: 'She shows gratitude by saying “thank you”.', fr: 'Elle montre sa gratitude en disant « merci ».' },
        { de: 'Sie spricht langsam, damit alle sie verstehen.', en: 'She speaks slowly so that everyone understands her.', fr: 'Elle parle lentement pour que tout le monde la comprenne.' },
        { de: 'Sie sprach langsam, sodass alle sie verstanden.', en: 'She spoke slowly, so everyone understood her.', fr: 'Elle parlait lentement, si bien que tout le monde la comprenait.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l22-e1', prompt: 'Man lernt Vokabeln, ___ man jeden Tag übt. (by …-ing)', promptFr: 'Man lernt Vokabeln, ___ man jeden Tag übt. (en …-ant)', answer: 'indem', hint: 'the conjunction for the means / method', hintFr: 'la conjonction du moyen / de la méthode' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l22-e2', prompt: 'Which question does "indem" answer?', promptFr: 'À quelle question répond « indem » ?', options: ['Warum? (reason)', 'Wie? (by what means)', 'Wozu? (purpose)'], optionsFr: ['Warum ? (cause)', 'Wie ? (par quel moyen)', 'Wozu ? (but)'], answer: 1, explain: '"indem" names the means or method: how something is done.', explainFr: '« indem » nomme le moyen ou la méthode : comment on fait quelque chose.', hint: 'Think "by doing …".', hintFr: 'Pense à « en faisant … ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l22-e3', prompt: 'Er hat mir sehr geholfen, ___ ich die Prüfung bestanden habe. (with the result that)', promptFr: 'Er hat mir sehr geholfen, ___ ich die Prüfung bestanden habe. (de sorte que)', answer: 'sodass', hint: 'the conjunction for a real result', hintFr: 'la conjonction du résultat réel' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l22-e4', tokens: ['Deutsch', 'indem', 'man', 'spricht', 'jeden', 'Tag'], answer: ['indem', 'man', 'jeden', 'Tag', 'Deutsch', 'spricht'], hint: 'Conjunction first, verb at the very end.', hintFr: 'Conjonction en premier, verbe tout à la fin.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l22-e5', pairs: [ { de: 'indem', en: 'by …-ing (means)', fr: 'en …-ant (moyen)' }, { de: 'sodass', en: 'so that (result)', fr: 'de sorte que (résultat)' }, { de: 'damit', en: 'so that (purpose)', fr: 'pour que (but)' }, { de: 'weil', en: 'because (reason)', fr: 'parce que (cause)' } ], hint: 'Match each conjunction to the idea it expresses.', hintFr: 'Associe chaque conjonction à l’idée qu’elle exprime.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l22-e6', prompt: 'Listen. How does she say thank you to her neighbour?', promptFr: 'Écoute. Comment remercie-t-elle sa voisine ?', audio: { ttsText: 'Ich bedanke mich bei meiner Nachbarin, indem ich ihr Blumen schenke.' }, options: ['By giving her flowers', 'By baking a cake', 'By calling her'], optionsFr: ['En lui offrant des fleurs', 'En lui faisant un gâteau', 'En lui téléphonant'], answer: 0, hint: 'Listen after "indem".', hintFr: 'Écoute ce qui suit « indem ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l22-e7', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Sie hilft mir, indem sie mir das Formular erklärt.', 'Sie hilft mir, indem sie erklärt mir das Formular.', 'Sie hilft mir, indem erklärt sie mir das Formular.'], optionsFr: ['Sie hilft mir, indem sie mir das Formular erklärt.', 'Sie hilft mir, indem sie erklärt mir das Formular.', 'Sie hilft mir, indem erklärt sie mir das Formular.'], answer: 0, explain: 'After "indem" the conjugated verb goes to the very end.', explainFr: 'Après « indem », le verbe conjugué va tout à la fin.', hint: 'Where does the verb belong in a subordinate clause?', hintFr: 'Où se place le verbe dans une subordonnée ?' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l22-e8', prompt: 'Es regnete stark, ___ das Fest ausfiel.', promptFr: 'Es regnete stark, ___ das Fest ausfiel.', options: ['indem', 'sodass', 'damit'], answer: 1, explain: 'The cancelled party is a real result, so "sodass".', explainFr: 'La fête annulée est un résultat réel, donc « sodass ».', hint: 'Is it a method, a purpose or a result?', hintFr: 'Est-ce une méthode, un but ou un résultat ?' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l22-e9', word: 'Ratschlag', answer: 'der', hint: 'Ratschlag is masculine (der Ratschlag).', hintFr: 'Ratschlag est masculin (der Ratschlag).' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l22-e10', word: 'Ziel', answer: 'das', hint: 'Ziel is neuter (das Ziel).', hintFr: 'Ziel est neutre (das Ziel).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l22-e11', prompt: 'Listen. What was the result of her effort?', promptFr: 'Écoute. Quel a été le résultat de son effort ?', audio: { ttsText: 'Sie hat sich so viel Mühe gegeben, sodass alle begeistert waren.' }, options: ['Everyone was thrilled', 'Nobody noticed', 'She got tired and left'], optionsFr: ['Tout le monde était enthousiaste', 'Personne n’a rien remarqué', 'Elle s’est fatiguée et est partie'], answer: 0, hint: 'Listen to the clause after "sodass".', hintFr: 'Écoute la proposition après « sodass ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l22-e12', prompt: 'Sie spricht langsam, ___ alle sie verstehen. (so that — intended purpose)', promptFr: 'Sie spricht langsam, ___ alle sie verstehen. (pour que — but visé)', answer: 'damit', hint: 'a purpose you want to reach, not a fact', hintFr: 'un but que l’on veut atteindre, pas un fait' } },

    { kind: 'pronunciation', focus: 'Stress the conjunction’s last syllable: inDEM, soDASS — and say the ending -keit as "kite"', focusFr: 'Accentue la dernière syllabe de la conjonction : inDEM, soDASS — et prononce la finale -keit comme « kaïte »', items: [
      { id: 'b1l22-indem-pron', german: 'indem', english: 'by (doing) …', french: 'en (faisant) …', gender: null, syllables: ['in', 'DEM'], pronunciation: 'in-DEM', example: { de: 'Man lernt, indem man übt.', en: 'You learn by practising.', fr: 'On apprend en s’entraînant.' } },
      { id: 'b1l22-sodass-pron', german: 'sodass', english: 'so that (result)', french: 'de sorte que', gender: null, syllables: ['so', 'DASS'], pronunciation: 'zo-DAHSS', example: { de: 'Es war laut, sodass ich nichts hörte.', en: 'It was loud, so I heard nothing.', fr: 'Il y avait du bruit, si bien que je n’entendais rien.' } },
      { id: 'b1l22-dankbarkeit-pron', german: 'die Dankbarkeit', english: 'gratitude', french: 'la gratitude', gender: 'die', syllables: ['DANK', 'bar', 'keit'], pronunciation: 'dee DAHNK-bar-kite', example: { de: 'Ich spüre große Dankbarkeit.', en: 'I feel great gratitude.', fr: 'Je ressens une grande gratitude.' } },
      { id: 'b1l22-zuverlaessig-pron', german: 'zuverlässig', english: 'reliable', french: 'fiable', gender: null, syllables: ['ZU', 'ver', 'läs', 'sig'], pronunciation: 'TSOO-fair-less-ikh', example: { de: 'Sie ist immer zuverlässig.', en: 'She is always reliable.', fr: 'Elle est toujours fiable.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now explain **how** you do something with **indem** (Man lernt, indem man übt) and state a **result** with **sodass** (…, sodass ich bestanden habe). Both send the verb to the **end**. Ask yourself: how? → **indem**, why? → **weil**, for what purpose? → **damit**, with what result? → **sodass**. 🎉',
      summaryFr: 'Tu sais maintenant expliquer **comment** on fait quelque chose avec **indem** (Man lernt, indem man übt) et énoncer un **résultat** avec **sodass** (…, sodass ich bestanden habe). Les deux envoient le verbe à la **fin**. Demande-toi : comment ? → **indem**, pourquoi ? → **weil**, dans quel but ? → **damit**, avec quel résultat ? → **sodass**. 🎉' },
  ],
};
