import type { Lesson } from '../types';

export const b1lektion14: Lesson = {
  id: 'b1-l14', level: 'B1', module: 1, number: 3,
  title: { de: 'Lebenslauf und Präteritum', en: 'CV and the simple past', fr: 'CV et prétérit' },
  theme: 'Describing a work history with the Präteritum (regular, irregular and mixed verbs)',
  themeFr: 'Décrire un parcours professionnel avec le prétérit (verbes réguliers, irréguliers et mixtes)',
  goals: ['Form the Präteritum of regular verbs (arbeitete)', 'Use irregular verbs with a vowel change (ging, schrieb)', 'Use mixed verbs (brachte, wusste, kannte)', 'Describe a career in formal written German'],
  goalsFr: ['Former le prétérit des verbes réguliers (arbeitete)', 'Utiliser les verbes irréguliers à changement de voyelle (ging, schrieb)', 'Utiliser les verbes mixtes (brachte, wusste, kannte)', 'Décrire un parcours en allemand écrit formel'],
  steps: [
    { kind: 'intro', title: 'Mein Weg ins Berufsleben 💼', titleFr: 'Mon chemin vers la vie professionnelle 💼',
      scene: 'You are updating your CV, writing an application and reading a reference letter from a former boss.', sceneFr: 'Tu mets à jour ton CV, tu rédiges une candidature et tu lis la lettre de recommandation d’un ancien chef.',
      goals: ['Tell a work history in the Präteritum', 'Conjugate regular, irregular and mixed verbs in all persons', 'Use CV and application vocabulary', 'Recognise the formal style of references'],
      goalsFr: ['Raconter un parcours professionnel au prétérit', 'Conjuguer les verbes réguliers, irréguliers et mixtes à toutes les personnes', 'Utiliser le vocabulaire du CV et de la candidature', 'Reconnaître le style formel des lettres de recommandation'] },

    { kind: 'vocab', item: { id: 'b1l14-lebenslauf', german: 'der Lebenslauf', english: 'the CV / résumé', french: 'le CV', gender: 'der', syllables: ['LE', 'bens', 'lauf'], pronunciation: 'dair LAY-bens-lowf', example: { de: 'Mein Lebenslauf ist zwei Seiten lang.', en: 'My CV is two pages long.', fr: 'Mon CV fait deux pages.' } } },
    { kind: 'vocab', item: { id: 'b1l14-bewerbung', german: 'die Bewerbung', english: 'the application', french: 'la candidature', gender: 'die', syllables: ['be', 'WER', 'bung'], pronunciation: 'dee be-VAIR-boong', example: { de: 'Ich schicke meine Bewerbung heute ab.', en: 'I am sending off my application today.', fr: 'J’envoie ma candidature aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'b1l14-berufserfahrung', german: 'die Berufserfahrung', english: 'the work experience', french: 'l’expérience professionnelle', gender: 'die', syllables: ['be', 'RUFS', 'er', 'fah', 'rung'], pronunciation: 'dee be-ROOFS-er-fah-roong', example: { de: 'Sie hat zehn Jahre Berufserfahrung.', en: 'She has ten years of work experience.', fr: 'Elle a dix ans d’expérience professionnelle.' } } },
    { kind: 'vocab', item: { id: 'b1l14-praktikum', german: 'das Praktikum', english: 'the internship', french: 'le stage', gender: 'das', syllables: ['PRAK', 'ti', 'kum'], pronunciation: 'dahs PRAHK-tee-koom', example: { de: 'Er machte ein Praktikum bei einer Bank.', en: 'He did an internship at a bank.', fr: 'Il a fait un stage dans une banque.' } } },
    { kind: 'vocab', item: { id: 'b1l14-ausbildung', german: 'die Ausbildung', english: 'the vocational training', french: 'la formation professionnelle', gender: 'die', syllables: ['AUS', 'bil', 'dung'], pronunciation: 'dee OWS-bil-doong', example: { de: 'Nach der Schule begann sie eine Ausbildung.', en: 'After school she began a vocational training.', fr: 'Après l’école, elle a commencé une formation professionnelle.' } } },
    { kind: 'vocab', item: { id: 'b1l14-zeugnis', german: 'das Arbeitszeugnis', english: 'the reference letter (from an employer)', french: 'le certificat de travail', gender: 'das', syllables: ['AR', 'beits', 'zeug', 'nis'], pronunciation: 'dahs AR-bites-tsoyg-niss', example: { de: 'Im Arbeitszeugnis stand: Er war immer pünktlich.', en: 'The reference said: He was always punctual.', fr: 'Le certificat disait : il était toujours ponctuel.' } } },
    { kind: 'vocab', item: { id: 'b1l14-aufgabe', german: 'die Aufgabe', english: 'the task / duty', french: 'la tâche', gender: 'die', syllables: ['AUF', 'ga', 'be'], pronunciation: 'dee OWF-gah-buh', example: { de: 'Zu ihren Aufgaben gehörte der Kundenkontakt.', en: 'Her duties included customer contact.', fr: 'Le contact avec la clientèle faisait partie de ses tâches.' } } },
    { kind: 'vocab', item: { id: 'b1l14-erledigen', german: 'erledigen', english: 'to take care of / to get done', french: 's’occuper de / régler', gender: null, syllables: ['er', 'LE', 'di', 'gen'], pronunciation: 'er-LAY-dee-gen', example: { de: 'Sie erledigte alle Aufträge pünktlich.', en: 'She took care of all orders on time.', fr: 'Elle a traité toutes les commandes à temps.' } } },
    { kind: 'vocab', item: { id: 'b1l14-zuverlaessig', german: 'zuverlässig', english: 'reliable', french: 'fiable', gender: null, syllables: ['ZU', 'ver', 'läs', 'sig'], pronunciation: 'TSOO-fer-less-ikh', example: { de: 'Er arbeitete immer zuverlässig.', en: 'He always worked reliably.', fr: 'Il travaillait toujours de façon fiable.' } } },
    { kind: 'vocab', item: { id: 'b1l14-bewerben', german: 'sich bewerben (um)', english: 'to apply (for)', french: 'postuler (à)', gender: null, syllables: ['be', 'WER', 'ben'], pronunciation: 'zikh be-VAIR-ben', example: { de: 'Ich bewarb mich im Mai um die Stelle.', en: 'I applied for the position in May.', fr: 'J’ai postulé à ce poste en mai.' } } },
    { kind: 'vocab', item: { id: 'b1l14-kuendigen', german: 'kündigen', english: 'to quit / to give notice', french: 'démissionner / résilier', gender: null, syllables: ['KÜN', 'di', 'gen'], pronunciation: 'KUEN-dee-gen', example: { de: 'Er kündigte seine Stelle zum Jahresende.', en: 'He gave notice on his job for the end of the year.', fr: 'Il a démissionné de son poste pour la fin de l’année.' } } },
    { kind: 'vocab', item: { id: 'b1l14-einstellen', german: 'einstellen', english: 'to hire', french: 'embaucher', gender: null, syllables: ['EIN', 'stel', 'len'], pronunciation: 'INE-shtel-len', example: { de: 'Die Firma stellte drei neue Mitarbeiter ein.', en: 'The company hired three new employees.', fr: 'L’entreprise a embauché trois nouveaux employés.' } } },
    { kind: 'vocab', item: { id: 'b1l14-kenntnisse', german: 'die Kenntnisse (Pl.)', english: 'the skills / knowledge', french: 'les connaissances / compétences', gender: 'die', syllables: ['KENNT', 'nis', 'se'], pronunciation: 'dee KENT-niss-uh', example: { de: 'Ich habe gute Sprachkenntnisse.', en: 'I have good language skills.', fr: 'J’ai de bonnes connaissances linguistiques.' } } },
    { kind: 'vocab', item: { id: 'b1l14-referenz', german: 'die Referenz', english: 'the reference', french: 'la référence', gender: 'die', syllables: ['re', 'fe', 'RENZ'], pronunciation: 'dee ray-fay-RENTS', example: { de: 'Als Referenz nannte er seinen früheren Chef.', en: 'As a reference he named his former boss.', fr: 'Comme référence, il a cité son ancien chef.' } } },

    { kind: 'grammar', note: {
      id: 'b1l14-regelmaessig', title: 'Präteritum of regular verbs: stem + -te', titleFr: 'Le prétérit des verbes réguliers : radical + -te',
      explanationMd: 'Regular ("weak") verbs add **-te** to the stem, then the personal ending. In the **ich** and **er/sie/es** forms there is **no extra ending**:\n\n- ich arbeit**ete**\n- du arbeit**etest**\n- er/sie/es arbeit**ete**\n- wir arbeit**eten**\n- ihr arbeit**etet**\n- sie/Sie arbeit**eten**\n\nStems ending in **-t** or **-d** insert an **-e-** (arbeit**e**te, bad**e**te). Otherwise it is simply **-te**: machen → mach**te**, erledigen → erledig**te**, kündigen → kündig**te**.\n\nSeparable verbs split as in the present: Die Firma **stellte** ihn **ein**.',
      explanationMdFr: 'Les verbes réguliers (« faibles ») ajoutent **-te** au radical, puis la terminaison personnelle. Aux formes **ich** et **er/sie/es**, il n’y a **aucune terminaison supplémentaire** :\n\n- ich arbeit**ete**\n- du arbeit**etest**\n- er/sie/es arbeit**ete**\n- wir arbeit**eten**\n- ihr arbeit**etet**\n- sie/Sie arbeit**eten**\n\nLes radicaux en **-t** ou **-d** insèrent un **-e-** (arbeit**e**te, bad**e**te). Sinon c’est simplement **-te** : machen → mach**te**, erledigen → erledig**te**, kündigen → kündig**te**.\n\nLes verbes séparables se séparent comme au présent : Die Firma **stellte** ihn **ein**.',
      diagram: 'conjugation-table',
      examples: [
        { de: 'Ich arbeitete drei Jahre in einem Hotel.', en: 'I worked in a hotel for three years.', fr: 'J’ai travaillé trois ans dans un hôtel.' },
        { de: 'Sie erledigte ihre Aufgaben zuverlässig.', en: 'She carried out her tasks reliably.', fr: 'Elle accomplissait ses tâches de manière fiable.' },
        { de: 'Wir kündigten im Dezember.', en: 'We gave notice in December.', fr: 'Nous avons démissionné en décembre.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l14-unregelmaessig', title: 'Irregular and mixed verbs', titleFr: 'Verbes irréguliers et verbes mixtes',
      explanationMd: '**Irregular ("strong") verbs** change their **stem vowel** and take **no -te**. Endings: ich –, du **-st**, er/sie/es –, wir **-en**, ihr **-t**, sie **-en**:\n\n- gehen → ich **ging**, du gingst, er **ging**, wir gingen\n- schreiben → **schrieb** · finden → **fand** · kommen → **kam**\n- bleiben → **blieb** · bekommen → **bekam** · sich bewerben → **bewarb sich**\n\n**Mixed verbs** change the stem **and** add **-te**:\n\n- bringen → **brachte** · denken → **dachte**\n- kennen → **kannte** · wissen → **wusste** · nennen → **nannte**\n\nIrregular verbs must be learned — always memorise the three forms: *gehen – ging – ist gegangen*.',
      explanationMdFr: 'Les **verbes irréguliers (« forts »)** changent leur **voyelle du radical** et ne prennent **pas de -te**. Terminaisons : ich –, du **-st**, er/sie/es –, wir **-en**, ihr **-t**, sie **-en** :\n\n- gehen → ich **ging**, du gingst, er **ging**, wir gingen\n- schreiben → **schrieb** · finden → **fand** · kommen → **kam**\n- bleiben → **blieb** · bekommen → **bekam** · sich bewerben → **bewarb sich**\n\nLes **verbes mixtes** changent le radical **et** ajoutent **-te** :\n\n- bringen → **brachte** · denken → **dachte**\n- kennen → **kannte** · wissen → **wusste** · nennen → **nannte**\n\nLes verbes irréguliers s’apprennent par cœur — retiens toujours les trois formes : *gehen – ging – ist gegangen*.',
      examples: [
        { de: 'Nach dem Studium fand er schnell eine Stelle.', en: 'After university he quickly found a job.', fr: 'Après ses études, il a vite trouvé un poste.' },
        { de: 'Ich schrieb zehn Bewerbungen und bekam zwei Einladungen.', en: 'I wrote ten applications and received two invitations.', fr: 'J’ai écrit dix candidatures et reçu deux invitations.' },
        { de: 'Er kannte die Firma und wusste, was sie suchte.', en: 'He knew the company and knew what it was looking for.', fr: 'Il connaissait l’entreprise et savait ce qu’elle cherchait.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l14-schriftlich', title: 'Telling a career: the written style', titleFr: 'Raconter un parcours : le style écrit',
      explanationMd: 'In **writing** (CV cover letters, reports, references, biographies) German prefers the **Präteritum**. In **conversation** you usually say the **Perfekt** (*Ich habe drei Jahre in Köln gearbeitet*). Only **sein, haben** and the **modal verbs** are also common in the Präteritum when speaking.\n\nTime markers give the story a structure:\n\n- **2018 bis 2021** · **von … bis …** · **seit 2021** (still true)\n- **zuerst**, **danach**, **anschließend**, **später**, **zuletzt**\n- **nach** + dative · **vor** + dative · **im Jahr 2019**\n\nReference letters use a formal style: *Er erledigte seine Aufgaben stets zuverlässig und zu unserer vollen Zufriedenheit.*',
      explanationMdFr: 'À l’**écrit** (lettres de motivation, rapports, certificats, biographies), l’allemand préfère le **prétérit**. À l’**oral**, on emploie en général le **Perfekt** (*Ich habe drei Jahre in Köln gearbeitet*). Seuls **sein, haben** et les **verbes modaux** sont aussi courants au prétérit à l’oral.\n\nLes marqueurs de temps structurent le récit :\n\n- **2018 bis 2021** · **von … bis …** · **seit 2021** (toujours vrai)\n- **zuerst**, **danach**, **anschließend**, **später**, **zuletzt**\n- **nach** + datif · **vor** + datif · **im Jahr 2019**\n\nLes certificats de travail ont un style formel : *Er erledigte seine Aufgaben stets zuverlässig und zu unserer vollen Zufriedenheit.*',
      examples: [
        { de: 'Von 2019 bis 2022 arbeitete sie als Verkäuferin, danach leitete sie eine Filiale.', en: 'From 2019 to 2022 she worked as a sales assistant, then she managed a branch.', fr: 'De 2019 à 2022, elle a travaillé comme vendeuse, puis elle a dirigé une succursale.' },
        { de: 'Zuerst machte ich ein Praktikum, anschließend bewarb ich mich um eine Ausbildung.', en: 'First I did an internship, then I applied for a vocational training.', fr: 'D’abord j’ai fait un stage, ensuite j’ai postulé à une formation professionnelle.' },
        { de: 'Seit 2023 arbeite ich bei einer Softwarefirma.', en: 'Since 2023 I have been working at a software company.', fr: 'Depuis 2023, je travaille dans une entreprise de logiciels.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l14-e1', prompt: 'Letztes Jahr ___ ich in einer Bäckerei. (arbeiten → Präteritum)', promptFr: 'L’année dernière, je ___ dans une boulangerie. (arbeiten → prétérit)', answer: 'arbeitete', hint: 'stem ends in -t → arbeit + e + te', hintFr: 'radical en -t → arbeit + e + te' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l14-e2', prompt: 'What is the Präteritum of "gehen" (er …)?', promptFr: 'Quel est le prétérit de « gehen » (er …) ?', options: ['gehte', 'ging', 'gegangen'], answer: 1, explain: '"gehen" is irregular: gehen – ging – ist gegangen.', explainFr: '« gehen » est irrégulier : gehen – ging – ist gegangen.', hint: 'Irregular verbs change the vowel and take no -te.', hintFr: 'Les verbes irréguliers changent de voyelle et n’ont pas de -te.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l14-e3', prompt: 'Sie ___ drei Bewerbungen. (schreiben → Präteritum, sie = they)', promptFr: 'Elles ___ trois candidatures. (schreiben → prétérit)', answer: 'schrieben', hint: 'schrieb + -en for wir/sie', hintFr: 'schrieb + -en pour wir/sie' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l14-e4', pairs: [ { de: 'bringen', en: 'brachte', fr: 'brachte' }, { de: 'wissen', en: 'wusste', fr: 'wusste' }, { de: 'finden', en: 'fand', fr: 'fand' }, { de: 'bleiben', en: 'blieb', fr: 'blieb' } ], hint: 'Match each infinitive with its Präteritum (3rd person singular).', hintFr: 'Associe chaque infinitif à son prétérit (3e personne du singulier).' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l14-e5', prompt: 'Listen. Where did Anna apply?', promptFr: 'Écoute. Où Anna a-t-elle postulé ?', audio: { ttsText: 'Anna bewarb sich im Mai bei einer Bank. Im Juni bekam sie die Stelle.' }, options: ['At a bank', 'At a hotel', 'At a school'], optionsFr: ['Dans une banque', 'Dans un hôtel', 'Dans une école'], answer: 0, hint: 'Listen for the place after "bei".', hintFr: 'Écoute le lieu après « bei ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l14-e6', prompt: 'Er ___ die Firma schon. (kennen → Präteritum, mixed verb)', promptFr: 'Il ___ déjà l’entreprise. (kennen → prétérit, verbe mixte)', answer: 'kannte', hint: 'mixed verb: new vowel (a) + -te', hintFr: 'verbe mixte : nouvelle voyelle (a) + -te' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l14-e7', tokens: ['bewarb', 'Danach', 'bei', 'sie', 'einer', 'Firma', 'sich'], answer: ['Danach', 'bewarb', 'sie', 'sich', 'bei', 'einer', 'Firma'], hint: 'Verb second after "Danach", then subject and reflexive pronoun.', hintFr: 'Verbe en deuxième position après « Danach », puis sujet et pronom réfléchi.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l14-e8', prompt: 'Which sentence fits a formal reference letter?', promptFr: 'Quelle phrase convient à un certificat de travail formel ?', options: ['Er hat seine Aufgaben zuverlässig erledigt, glaube ich.', 'Er erledigte seine Aufgaben stets zuverlässig.', 'Der war echt zuverlässig.'], answer: 1, explain: 'Written, formal style uses the Präteritum and neutral wording.', explainFr: 'Le style écrit formel utilise le prétérit et un vocabulaire neutre.', hint: 'Look for the Präteritum and no casual words.', hintFr: 'Cherche le prétérit et aucun mot familier.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l14-e9', prompt: 'Listen. What happened in 2022?', promptFr: 'Écoute. Que s’est-il passé en 2022 ?', audio: { ttsText: 'Von 2019 bis 2022 arbeitete Jonas als Koch. Dann kündigte er und ging nach Wien.' }, options: ['He quit and moved to Vienna', 'He started as a cook', 'He was hired as a manager'], optionsFr: ['Il a démissionné et est parti à Vienne', 'Il a débuté comme cuisinier', 'Il a été embauché comme directeur'], answer: 0, hint: 'Listen for "kündigte" and "ging".', hintFr: 'Écoute « kündigte » et « ging ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l14-e10', prompt: 'Wir ___ zwei Jahre in Lyon. (bleiben → Präteritum)', promptFr: 'Nous ___ deux ans à Lyon. (bleiben → prétérit)', answer: 'blieben', hint: 'blieb + -en', hintFr: 'blieb + -en' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l14-e11', word: 'Lebenslauf', answer: 'der', hint: 'a compound: the last part is "Lauf" (m)', hintFr: 'un mot composé : la dernière partie est « Lauf » (m)' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l14-e12', word: 'Berufserfahrung', answer: 'die', hint: 'nouns ending in -ung are feminine', hintFr: 'les noms en -ung sont féminins' } },

    { kind: 'pronunciation', focus: 'The Präteritum ending -te is short and clear (arbeitete); "ch" after a, o, u is a throaty sound (brachte, dachte)', focusFr: 'La terminaison -te du prétérit est courte et nette (arbeitete) ; « ch » après a, o, u est un son guttural (brachte, dachte)', items: [
      { id: 'b1l14-arbeitete-pron', german: 'arbeitete', english: 'worked', french: 'travaillait', gender: null, syllables: ['AR', 'bei', 'te', 'te'], pronunciation: 'AR-by-te-tuh', example: { de: 'Er arbeitete in Zürich.', en: 'He worked in Zurich.', fr: 'Il travaillait à Zurich.' } },
      { id: 'b1l14-brachte-pron', german: 'brachte', english: 'brought', french: 'apportait', gender: null, syllables: ['BRACH', 'te'], pronunciation: 'BRAHKH-tuh', example: { de: 'Sie brachte Erfahrung mit.', en: 'She brought experience with her.', fr: 'Elle apportait de l’expérience.' } },
      { id: 'b1l14-wusste-pron', german: 'wusste', english: 'knew', french: 'savait', gender: null, syllables: ['WUSS', 'te'], pronunciation: 'VOOSS-tuh', example: { de: 'Ich wusste die Antwort.', en: 'I knew the answer.', fr: 'Je connaissais la réponse.' } },
      { id: 'b1l14-schrieb-pron', german: 'schrieb', english: 'wrote', french: 'écrivait', gender: null, syllables: ['SCHRIEB'], pronunciation: 'shreep', example: { de: 'Er schrieb einen Lebenslauf.', en: 'He wrote a CV.', fr: 'Il a écrit un CV.' } },
      { id: 'b1l14-fand-pron', german: 'fand', english: 'found', french: 'trouvait', gender: null, syllables: ['FAND'], pronunciation: 'fahnt', example: { de: 'Sie fand eine gute Stelle.', en: 'She found a good job.', fr: 'Elle a trouvé un bon poste.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now tell a work history in the **Präteritum**: regular verbs add **-te** (arbeitete), irregular verbs change their vowel (**ging, schrieb, fand**), and mixed verbs do both (**brachte, wusste, kannte**). Use it for written reports and references, and structure your story with **von … bis …, danach, anschließend, seit**. 🎉',
      summaryFr: 'Tu sais maintenant raconter un parcours professionnel au **prétérit** : les verbes réguliers ajoutent **-te** (arbeitete), les verbes irréguliers changent de voyelle (**ging, schrieb, fand**) et les verbes mixtes font les deux (**brachte, wusste, kannte**). Utilise-le pour les rapports et certificats écrits, et structure ton récit avec **von … bis …, danach, anschließend, seit**. 🎉' },
  ],
};
