import type { Lesson } from '../types';

export const b1lektion24: Lesson = {
  id: 'b1-l24', level: 'B1', module: 5, number: 20,
  title: { de: 'Passiv im Präteritum und Perfekt', en: 'Passive in the past tenses', fr: 'Le passif au passé' },
  theme: 'Telling history: passive in the Präteritum and Perfekt, plus wishes about the past',
  themeFr: 'Raconter l’histoire : le passif au prétérit et au parfait, et les souhaits sur le passé',
  goals: ['Form the passive Präteritum (wurde … gebaut)', 'Form the passive Perfekt (ist … gebaut worden)', 'Summarise historical events and inventions', 'Say you wish you had been there (wäre … gewesen)'],
  goalsFr: ['Former le passif au prétérit (wurde … gebaut)', 'Former le passif au parfait (ist … gebaut worden)', 'Résumer des événements historiques et des inventions', 'Dire qu’on aurait aimé y être (wäre … gewesen)'],
  steps: [
    { kind: 'intro', title: 'Was wurde wann gemacht? 🕰️', titleFr: 'Qu’a-t-on fait, et quand ? 🕰️',
      scene: 'A museum audio guide walks you along a timeline of German history: a state is founded, a wall is built, a wall is opened, a new currency is introduced. History is full of things that "were done" — a perfect job for the past passive.',
      sceneFr: 'Un audioguide de musée te fait parcourir une frise de l’histoire allemande : un État est fondé, un mur est construit, un mur est ouvert, une nouvelle monnaie est introduite. L’histoire est pleine de choses « qui ont été faites » — un terrain idéal pour le passif au passé.',
      goals: ['Use wurde / wurden + participle in texts', 'Use ist / sind + participle + worden in conversation', 'Read and write a short timeline', 'Express a wish about a past event'],
      goalsFr: ['Utiliser wurde / wurden + participe dans les textes', 'Utiliser ist / sind + participe + worden à l’oral', 'Lire et écrire une courte frise chronologique', 'Exprimer un souhait sur un événement passé'] },

    { kind: 'vocab', item: { id: 'b1l24-geschichte', german: 'die Geschichte', english: 'history / story', french: 'l’histoire', gender: 'die', syllables: ['ge', 'SCHICH', 'te'], pronunciation: 'dee ge-SHIKH-teh', example: { de: 'Ich interessiere mich für Geschichte.', en: 'I am interested in history.', fr: 'Je m’intéresse à l’histoire.' } } },
    { kind: 'vocab', item: { id: 'b1l24-ereignis', german: 'das Ereignis', english: 'the event / occurrence', french: 'l’événement', gender: 'das', syllables: ['er', 'EIG', 'nis'], pronunciation: 'dahs air-EYEG-niss', example: { de: 'Der Mauerfall war ein historisches Ereignis.', en: 'The fall of the Wall was a historic event.', fr: 'La chute du Mur a été un événement historique.' } } },
    { kind: 'vocab', item: { id: 'b1l24-demokratie', german: 'die Demokratie', english: 'democracy', french: 'la démocratie', gender: 'die', syllables: ['de', 'mo', 'kra', 'TIE'], pronunciation: 'dee de-mo-krah-TEE', example: { de: 'In einer Demokratie dürfen alle wählen.', en: 'In a democracy everyone may vote.', fr: 'Dans une démocratie, tout le monde peut voter.' } } },
    { kind: 'vocab', item: { id: 'b1l24-mauer', german: 'die Mauer', english: 'the wall', french: 'le mur', gender: 'die', syllables: ['MAU', 'er'], pronunciation: 'dee MOW-er', example: { de: 'Die Berliner Mauer stand fast dreißig Jahre.', en: 'The Berlin Wall stood for almost thirty years.', fr: 'Le mur de Berlin est resté debout presque trente ans.' } } },
    { kind: 'vocab', item: { id: 'b1l24-grenze', german: 'die Grenze', english: 'the border', french: 'la frontière', gender: 'die', syllables: ['GREN', 'ze'], pronunciation: 'dee GREN-tseh', example: { de: 'Die Grenze wurde geöffnet.', en: 'The border was opened.', fr: 'La frontière a été ouverte.' } } },
    { kind: 'vocab', item: { id: 'b1l24-teilung', german: 'die Teilung', english: 'the division', french: 'la division', gender: 'die', syllables: ['TEI', 'lung'], pronunciation: 'dee TY-loong', example: { de: 'Die Teilung Deutschlands dauerte 41 Jahre.', en: 'The division of Germany lasted 41 years.', fr: 'La division de l’Allemagne a duré 41 ans.' } } },
    { kind: 'vocab', item: { id: 'b1l24-wiedervereinigung', german: 'die Wiedervereinigung', english: 'the reunification', french: 'la réunification', gender: 'die', syllables: ['WIE', 'der', 'ver', 'ei', 'ni', 'gung'], pronunciation: 'dee VEE-der-fair-EYE-nee-goong', example: { de: 'Die Wiedervereinigung wurde 1990 gefeiert.', en: 'The reunification was celebrated in 1990.', fr: 'La réunification a été célébrée en 1990.' } } },
    { kind: 'vocab', item: { id: 'b1l24-freiheit', german: 'die Freiheit', english: 'freedom', french: 'la liberté', gender: 'die', syllables: ['FREI', 'heit'], pronunciation: 'dee FRY-hite', example: { de: 'Meinungsfreiheit ist ein wichtiges Recht.', en: 'Freedom of speech is an important right.', fr: 'La liberté d’expression est un droit important.' } } },
    { kind: 'vocab', item: { id: 'b1l24-gruenden', german: 'gründen', english: 'to found', french: 'fonder', gender: null, syllables: ['GRÜN', 'den'], pronunciation: 'GRUEN-den', example: { de: 'Die Partei wurde 1980 gegründet.', en: 'The party was founded in 1980.', fr: 'Le parti a été fondé en 1980.' } } },
    { kind: 'vocab', item: { id: 'b1l24-einfuehren', german: 'einführen', english: 'to introduce', french: 'introduire', gender: null, syllables: ['EIN', 'füh', 'ren'], pronunciation: 'INE-fue-ren', example: { de: 'Der Euro wurde 2002 eingeführt.', en: 'The euro was introduced in 2002.', fr: 'L’euro a été introduit en 2002.' } } },
    { kind: 'vocab', item: { id: 'b1l24-erfinden', german: 'erfinden', english: 'to invent', french: 'inventer', gender: null, syllables: ['er', 'FIN', 'den'], pronunciation: 'air-FIN-den', example: { de: 'Der Buchdruck wurde von Gutenberg erfunden.', en: 'The printing press was invented by Gutenberg.', fr: 'L’imprimerie a été inventée par Gutenberg.' } } },
    { kind: 'vocab', item: { id: 'b1l24-abschaffen', german: 'abschaffen', english: 'to abolish', french: 'abolir', gender: null, syllables: ['AB', 'schaf', 'fen'], pronunciation: 'AHP-shahf-fen', example: { de: 'Die Sklaverei wurde abgeschafft.', en: 'Slavery was abolished.', fr: 'L’esclavage a été aboli.' } } },
    { kind: 'vocab', item: { id: 'b1l24-erfindung', german: 'die Erfindung', english: 'the invention', french: 'l’invention', gender: 'die', syllables: ['er', 'FIN', 'dung'], pronunciation: 'dee air-FIN-doong', example: { de: 'Das Fahrrad ist eine Erfindung des 19. Jahrhunderts.', en: 'The bicycle is an invention of the 19th century.', fr: 'La bicyclette est une invention du XIXe siècle.' } } },

    { kind: 'grammar', note: {
      id: 'b1l24-praeteritum', title: 'Passive Präteritum: wurde / wurden + participle', titleFr: 'Passif au prétérit : wurde / wurden + participe',
      explanationMd: 'For the past passive in **texts** (history, news, reports) use **wurde** (singular) or **wurden** (plural) + **participle** at the end:\n\n- Die Mauer **wurde** 1961 **gebaut**.\n- Die Grenzen **wurden** 1989 **geöffnet**.\n\nName the doer with **von** + dative: Der Buchdruck **wurde von** Gutenberg **erfunden**.\n\nActive → passive: Man **führte** 2002 den Euro **ein**. → 2002 **wurde** der Euro **eingeführt**.',
      explanationMdFr: 'Pour le passif au passé dans les **textes** (histoire, presse, rapports), utilise **wurde** (singulier) ou **wurden** (pluriel) + **participe** à la fin :\n\n- Die Mauer **wurde** 1961 **gebaut**.\n- Die Grenzen **wurden** 1989 **geöffnet**.\n\nNomme l’auteur avec **von** + datif : Der Buchdruck **wurde von** Gutenberg **erfunden**.\n\nActif → passif : Man **führte** 2002 den Euro **ein**. → 2002 **wurde** der Euro **eingeführt**.',
      examples: [
        { de: 'Die BRD wurde 1949 gegründet.', en: 'The Federal Republic was founded in 1949.', fr: 'La République fédérale a été fondée en 1949.' },
        { de: '1990 wurde Deutschland wiedervereinigt.', en: 'Germany was reunified in 1990.', fr: 'L’Allemagne a été réunifiée en 1990.' },
        { de: 'Viele Menschen wurden von der Nachricht überrascht.', en: 'Many people were surprised by the news.', fr: 'Beaucoup de gens ont été surpris par la nouvelle.' },
      ],
      diagram: 'satzklammer' } },

    { kind: 'grammar', note: {
      id: 'b1l24-perfekt', title: 'Passive Perfekt: ist / sind + participle + worden', titleFr: 'Passif au parfait : ist / sind + participe + worden',
      explanationMd: 'In **conversation** the passive usually takes the **Perfekt**: **ist / sind** + **participle** + **worden**:\n\n- Die Mauer **ist** gebaut **worden**.\n- Die Grenzen **sind** geöffnet **worden**.\n\nCareful: the passive uses **worden**, not **geworden** (that is the participle of "werden" = to become).\n\nIn a **subordinate clause** the auxiliary stands last: …, weil die Mauer gebaut **worden ist**.\n\nPräsens: wird gebaut → Präteritum: wurde gebaut → Perfekt: ist gebaut worden',
      explanationMdFr: 'À l’**oral**, le passif au passé utilise généralement le **parfait** : **ist / sind** + **participe** + **worden** :\n\n- Die Mauer **ist** gebaut **worden**.\n- Die Grenzen **sind** geöffnet **worden**.\n\nAttention : le passif utilise **worden**, pas **geworden** (participe de « werden » = devenir).\n\nDans une **subordonnée**, l’auxiliaire est en dernière position : …, weil die Mauer gebaut **worden ist**.\n\nPräsens : wird gebaut → Präteritum : wurde gebaut → Perfekt : ist gebaut worden',
      examples: [
        { de: 'Der Euro ist 2002 eingeführt worden.', en: 'The euro was introduced in 2002.', fr: 'L’euro a été introduit en 2002.' },
        { de: 'Wusstest du, dass die Stadt im Krieg zerstört worden ist?', en: 'Did you know the city was destroyed in the war?', fr: 'Savais-tu que la ville avait été détruite pendant la guerre ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l24-wunsch', title: 'Wishes about the past: wäre … gewesen, hätte … gesehen', titleFr: 'Souhaits sur le passé : wäre … gewesen, hätte … gesehen',
      explanationMd: 'You already know the past Konjunktiv II: **hätte / wäre** + participle. It is perfect for wishing you had **been there**:\n\n- Ich **wäre** gern dabei **gewesen**, als die Mauer geöffnet **wurde**.\n- Ich **hätte** gern **gesehen**, wie der Euro eingeführt **wurde**.\n\nThe second clause (**als …** / **wie …**) tells the event — very often in the **passive Präteritum**.',
      explanationMdFr: 'Tu connais déjà le Konjunktiv II du passé : **hätte / wäre** + participe. Il est parfait pour dire qu’on aurait aimé **y être** :\n\n- Ich **wäre** gern dabei **gewesen**, als die Mauer geöffnet **wurde**.\n- Ich **hätte** gern **gesehen**, wie der Euro eingeführt **wurde**.\n\nLa seconde proposition (**als …** / **wie …**) raconte l’événement — très souvent au **passif prétérit**.',
      examples: [
        { de: 'Ich wäre gern bei der Wiedervereinigung dabei gewesen.', en: 'I would have liked to be there at the reunification.', fr: 'J’aurais aimé être là lors de la réunification.' },
        { de: 'Mein Opa hätte gern erlebt, wie die Grenze geöffnet wurde.', en: 'My grandpa would have liked to see the border being opened.', fr: 'Mon grand-père aurait aimé voir la frontière s’ouvrir.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l24-e1', prompt: 'Die Mauer ___ 1961 gebaut. (passive Präteritum, singular)', promptFr: 'Die Mauer ___ 1961 gebaut. (passif au prétérit, singulier)', answer: 'wurde', hint: 'singular → wurde', hintFr: 'singulier → wurde' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l24-e2', prompt: 'Die Grenzen ___ 1989 geöffnet. (passive Präteritum, plural)', promptFr: 'Die Grenzen ___ 1989 geöffnet. (passif au prétérit, pluriel)', answer: 'wurden', hint: 'plural → wurden', hintFr: 'pluriel → wurden' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l24-e3', prompt: 'Which sentence is the passive Perfekt?', promptFr: 'Quelle phrase est au passif parfait ?', options: ['Der Euro wurde eingeführt.', 'Der Euro ist eingeführt worden.', 'Der Euro ist eingeführt geworden.'], optionsFr: ['Der Euro wurde eingeführt.', 'Der Euro ist eingeführt worden.', 'Der Euro ist eingeführt geworden.'], answer: 1, explain: 'Passive Perfekt = ist + participle + worden.', explainFr: 'Passif parfait = ist + participe + worden.', hint: 'Look for "worden" at the end.', hintFr: 'Cherche « worden » à la fin.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l24-e4', prompt: 'Die Stadt ist im Krieg zerstört ___. (passive Perfekt)', promptFr: 'Die Stadt ist im Krieg zerstört ___. (passif parfait)', answer: 'worden', hint: 'not "geworden"', hintFr: 'pas « geworden »' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l24-e5', tokens: ['gegründet', 'wurde', 'Die BRD', '1949'], answer: ['Die BRD', 'wurde', '1949', 'gegründet'], hint: 'Start with the subject; participle at the end.', hintFr: 'Commence par le sujet ; participe à la fin.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l24-e6', pairs: [ { de: '1961', en: 'The Wall was built', fr: 'Le Mur a été construit' }, { de: '1989', en: 'The border was opened', fr: 'La frontière a été ouverte' }, { de: '1990', en: 'Germany was reunified', fr: 'L’Allemagne a été réunifiée' }, { de: '2002', en: 'Euro cash was introduced', fr: 'L’euro fiduciaire a été introduit' } ], hint: 'Match each year to the event.', hintFr: 'Associe chaque année à l’événement.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l24-e7', prompt: 'Listen. When was Germany reunified?', promptFr: 'Écoute. Quand l’Allemagne a-t-elle été réunifiée ?', audio: { ttsText: 'Im Jahr 1990 wurde Deutschland wiedervereinigt.' }, options: ['1990', '1961', '2002'], answer: 0, hint: 'Listen for the year.', hintFr: 'Écoute l’année.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l24-e8', prompt: 'Ich ___ gern dabei gewesen.', promptFr: 'Ich ___ gern dabei gewesen.', options: ['hätte', 'wäre', 'würde'], answer: 1, explain: '"gewesen" belongs to "sein", so the auxiliary is "wäre".', explainFr: '« gewesen » appartient à « sein », donc l’auxiliaire est « wäre ».', hint: 'Which auxiliary goes with "gewesen"?', hintFr: 'Quel auxiliaire va avec « gewesen » ?' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l24-e9', prompt: 'Which subordinate clause is correct?', promptFr: 'Quelle subordonnée est correcte ?', options: ['…, weil die Mauer gebaut worden ist.', '…, weil die Mauer ist gebaut worden.', '…, weil die Mauer gebaut geworden ist.'], optionsFr: ['…, weil die Mauer gebaut worden ist.', '…, weil die Mauer ist gebaut worden.', '…, weil die Mauer gebaut geworden ist.'], answer: 0, explain: 'The conjugated auxiliary “ist” stands last, after “worden”.', explainFr: 'L’auxiliaire conjugué « ist » est en dernière position, après « worden ».', hint: 'The conjugated verb goes last.', hintFr: 'Le verbe conjugué va en dernier.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l24-e10', word: 'Ereignis', answer: 'das', hint: 'Words ending in -nis are usually neuter.', hintFr: 'Les mots en -nis sont le plus souvent neutres.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l24-e11', prompt: 'Der Buchdruck wurde ___ Gutenberg erfunden. (by)', promptFr: 'Der Buchdruck wurde ___ Gutenberg erfunden. (par)', answer: 'von', hint: 'the doer in a passive sentence', hintFr: 'l’auteur dans une phrase passive' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l24-e12', prompt: 'Listen. What does the speaker wish?', promptFr: 'Écoute. Que souhaite la personne ?', audio: { ttsText: 'Ich wäre gern dabei gewesen, als die Mauer geöffnet wurde.' }, options: ['To have been there when the Wall opened', 'To have watched the Wall being built', 'To visit Berlin next year'], optionsFr: ['Avoir été là à l’ouverture du Mur', 'Avoir assisté à la construction du Mur', 'Visiter Berlin l’année prochaine'], answer: 0, hint: 'Listen to the clause after "als".', hintFr: 'Écoute la proposition après « als ».' } },

    { kind: 'pronunciation', focus: '"w" sounds like English "v": wurde, worden, Wiedervereinigung — and ei = "eye", ie = "ee"', focusFr: '« w » se prononce comme « v » : wurde, worden, Wiedervereinigung — et ei = « aïe », ie = « i long »', items: [
      { id: 'b1l24-wurde-pron', german: 'wurde', english: 'was (passive auxiliary)', french: 'a été (auxiliaire du passif)', gender: null, syllables: ['WUR', 'de'], pronunciation: 'VOOR-deh', example: { de: 'Die Mauer wurde gebaut.', en: 'The wall was built.', fr: 'Le mur a été construit.' } },
      { id: 'b1l24-worden-pron', german: 'worden', english: 'been (passive Perfekt)', french: 'été (passif parfait)', gender: null, syllables: ['WOR', 'den'], pronunciation: 'VOR-den', example: { de: 'Es ist viel gebaut worden.', en: 'A lot has been built.', fr: 'On a beaucoup construit.' } },
      { id: 'b1l24-mauer-pron', german: 'die Mauer', english: 'the wall', french: 'le mur', gender: 'die', syllables: ['MAU', 'er'], pronunciation: 'dee MOW-er', example: { de: 'Die Mauer fiel 1989.', en: 'The Wall fell in 1989.', fr: 'Le Mur est tombé en 1989.' } },
      { id: 'b1l24-freiheit-pron', german: 'die Freiheit', english: 'freedom', french: 'la liberté', gender: 'die', syllables: ['FREI', 'heit'], pronunciation: 'dee FRY-hite', example: { de: 'Freiheit ist wichtig.', en: 'Freedom is important.', fr: 'La liberté est importante.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now tell history with the past passive: **wurde / wurden + participle** in texts (Die Mauer wurde gebaut), **ist / sind + participle + worden** in conversation (Der Euro ist eingeführt worden). You can also voice a wish about the past: **Ich wäre gern dabei gewesen, als …** 🎉',
      summaryFr: 'Tu sais maintenant raconter l’histoire avec le passif au passé : **wurde / wurden + participe** dans les textes (Die Mauer wurde gebaut), **ist / sind + participe + worden** à l’oral (Der Euro ist eingeführt worden). Tu peux aussi formuler un souhait sur le passé : **Ich wäre gern dabei gewesen, als …** 🎉' },
  ],
};
