import type { Lesson } from '../types';

export const b1lektion18: Lesson = {
  id: 'b1-l18', level: 'B1', module: 2, number: 6,
  title: { de: 'Darum, deswegen, daher', en: 'Reasons and consequences', fr: 'Causes et conséquences' },
  theme: 'Giving reasons and consequences: darum, deswegen, daher, aus diesem Grund, nämlich, außerdem',
  themeFr: 'Donner des causes et des conséquences : darum, deswegen, daher, aus diesem Grund, nämlich, außerdem',
  goals: ['Express a consequence with darum / deswegen / daher / aus diesem Grund', 'Give the reason afterwards with "nämlich"', 'Add another argument with "außerdem"', 'Explain a misunderstanding and apologise politely, also in an email'],
  goalsFr: ['Exprimer une conséquence avec darum / deswegen / daher / aus diesem Grund', 'Donner la raison après coup avec « nämlich »', 'Ajouter un argument avec « außerdem »', 'Expliquer un malentendu et s’excuser poliment, aussi dans un e-mail'],
  steps: [
    { kind: 'intro', title: 'Darum war es ein Missverständnis 🤝', titleFr: 'C’est pourquoi il y a eu un malentendu 🤝',
      scene: 'Mara waited an hour at the wrong café. Now she and Jonas sort out what went wrong, apologise, and write a friendly email to clear it up.',
      sceneFr: 'Mara a attendu une heure dans le mauvais café. Maintenant, elle et Jonas démêlent ce qui s’est passé, s’excusent et écrivent un e-mail amical pour clarifier les choses.',
      goals: ['Say why something happened, and what followed from it', 'Use five near-synonyms for "therefore"', 'Add a reason with "nämlich" and an extra point with "außerdem"', 'Write a short, polite explanation email'],
      goalsFr: ['Dire pourquoi quelque chose est arrivé et ce qui en a découlé', 'Utiliser cinq quasi-synonymes de « c’est pourquoi »', 'Ajouter une raison avec « nämlich » et un point supplémentaire avec « außerdem »', 'Écrire un court e-mail d’explication poli'] },

    { kind: 'vocab', item: { id: 'b1l18-missverstaendnis', german: 'das Missverständnis', english: 'the misunderstanding', french: 'le malentendu', gender: 'das', syllables: ['MISS', 'ver', 'ständ', 'nis'], pronunciation: 'dahss MISS-fair-shtent-nis', example: { de: 'Das war nur ein kleines Missverständnis.', en: 'That was just a small misunderstanding.', fr: 'Ce n’était qu’un petit malentendu.' } } },
    { kind: 'vocab', item: { id: 'b1l18-grund', german: 'der Grund', english: 'the reason', french: 'la raison', gender: 'der', syllables: ['GRUND'], pronunciation: 'dair groont', example: { de: 'Was war der Grund für die Verspätung?', en: 'What was the reason for the delay?', fr: 'Quelle était la raison du retard ?' } } },
    { kind: 'vocab', item: { id: 'b1l18-folge', german: 'die Folge', english: 'the consequence', french: 'la conséquence', gender: 'die', syllables: ['FOL', 'ge'], pronunciation: 'dee FOL-geh', example: { de: 'Die Folge war ein langes Warten.', en: 'The consequence was a long wait.', fr: 'La conséquence a été une longue attente.' } } },
    { kind: 'vocab', item: { id: 'b1l18-entschuldigung', german: 'die Entschuldigung', english: 'the apology / excuse', french: 'l’excuse', gender: 'die', syllables: ['ent', 'SCHUL', 'di', 'gung'], pronunciation: 'dee ent-SHOOL-dih-goong', example: { de: 'Bitte nimm meine Entschuldigung an.', en: 'Please accept my apology.', fr: 'Accepte mes excuses, s’il te plaît.' } } },
    { kind: 'vocab', item: { id: 'b1l18-erklaerung', german: 'die Erklärung', english: 'the explanation', french: 'l’explication', gender: 'die', syllables: ['er', 'KLÄ', 'rung'], pronunciation: 'dee air-KLAY-roong', example: { de: 'Ich schulde dir eine Erklärung.', en: 'I owe you an explanation.', fr: 'Je te dois une explication.' } } },
    { kind: 'vocab', item: { id: 'b1l18-verspaetung', german: 'die Verspätung', english: 'the delay', french: 'le retard', gender: 'die', syllables: ['ver', 'SPÄ', 'tung'], pronunciation: 'dee fair-SHPAY-toong', example: { de: 'Der Zug hat zwanzig Minuten Verspätung.', en: 'The train is twenty minutes late.', fr: 'Le train a vingt minutes de retard.' } } },
    { kind: 'vocab', item: { id: 'b1l18-darum', german: 'darum', english: 'that’s why', french: 'c’est pourquoi', gender: null, syllables: ['DA', 'rum'], pronunciation: 'DAH-room', example: { de: 'Ich habe den Termin vergessen, darum bin ich nicht gekommen.', en: 'I forgot the appointment, that’s why I didn’t come.', fr: 'J’ai oublié le rendez-vous, c’est pourquoi je ne suis pas venu.' } } },
    { kind: 'vocab', item: { id: 'b1l18-deswegen', german: 'deswegen', english: 'because of that', french: 'à cause de cela', gender: null, syllables: ['DES', 've', 'gen'], pronunciation: 'DESS-vay-gen', example: { de: 'Mein Akku war leer, deswegen habe ich nicht geantwortet.', en: 'My battery was dead, so I didn’t reply.', fr: 'Ma batterie était vide, donc je n’ai pas répondu.' } } },
    { kind: 'vocab', item: { id: 'b1l18-daher', german: 'daher', english: 'hence / for that reason', french: 'de ce fait', gender: null, syllables: ['DA', 'her'], pronunciation: 'DAH-hair', example: { de: 'Die Straße war gesperrt, daher kamen wir zu spät.', en: 'The road was closed, hence we arrived late.', fr: 'La rue était barrée, de ce fait nous sommes arrivés en retard.' } } },
    { kind: 'vocab', item: { id: 'b1l18-aus-diesem-grund', german: 'aus diesem Grund', english: 'for this reason', french: 'pour cette raison', gender: null, syllables: ['aus', 'DIE', 'sem', 'GRUND'], pronunciation: 'ows DEE-zem groont', example: { de: 'Aus diesem Grund möchte ich mich entschuldigen.', en: 'For this reason I would like to apologise.', fr: 'Pour cette raison, je voudrais m’excuser.' } } },
    { kind: 'vocab', item: { id: 'b1l18-naemlich', german: 'nämlich', english: 'you see / namely (gives the reason)', french: 'en effet / c’est que', gender: null, syllables: ['NÄM', 'lich'], pronunciation: 'NAYM-lish', example: { de: 'Ich war zu spät. Mein Bus ist nämlich ausgefallen.', en: 'I was late. You see, my bus was cancelled.', fr: 'J’étais en retard. C’est que mon bus a été supprimé.' } } },
    { kind: 'vocab', item: { id: 'b1l18-ausserdem', german: 'außerdem', english: 'besides / in addition', french: 'en outre / de plus', gender: null, syllables: ['AU', 'ßer', 'dem'], pronunciation: 'OW-ser-dem', example: { de: 'Das Café ist gemütlich. Außerdem gibt es tollen Kuchen.', en: 'The café is cosy. Besides, they have great cake.', fr: 'Le café est agréable. En plus, il y a un super gâteau.' } } },
    { kind: 'vocab', item: { id: 'b1l18-missverstehen', german: 'etwas falsch verstehen', english: 'to misunderstand something', french: 'mal comprendre quelque chose', gender: null, syllables: ['ET', 'was', 'FALSCH', 'ver', 'STE', 'hen'], pronunciation: 'ET-vahss fahlsh fair-SHTAY-en', example: { de: 'Ich habe die Uhrzeit falsch verstanden.', en: 'I misunderstood the time.', fr: 'J’ai mal compris l’heure.' } } },

    { kind: 'grammar', note: {
      id: 'b1l18-folge-adverbien', title: 'Five ways to say "therefore"', titleFr: 'Cinq façons de dire « c’est pourquoi »',
      explanationMd: 'You already know **deshalb**. **Darum**, **deswegen**, **daher** and **aus diesem Grund** work exactly the same way: they name the **consequence** of what you just said.\n\n- **Darum**, **deswegen** and **deshalb** are the everyday choices — they are practically interchangeable.\n- **Daher** and **aus diesem Grund** sound a bit more formal, good for emails and announcements.\n\nThey are **adverbs**: they take **position 1**, so the **verb comes second**. After a comma, they also start a new main clause.\n\n- Ich habe den Zug verpasst. **Darum komme** ich zu spät.\n- Es gab einen Fehler. **Aus diesem Grund bitten** wir um Entschuldigung.\n\nThey can also move into the middle: Ich komme **deswegen** zu spät.',
      explanationMdFr: 'Tu connais déjà **deshalb**. **Darum**, **deswegen**, **daher** et **aus diesem Grund** fonctionnent exactement pareil : ils nomment la **conséquence** de ce qu’on vient de dire.\n\n- **Darum**, **deswegen** et **deshalb** sont les choix courants — presque interchangeables.\n- **Daher** et **aus diesem Grund** sonnent un peu plus formels, bien pour les e-mails et les annonces.\n\nCe sont des **adverbes** : ils prennent la **position 1**, donc le **verbe vient en deuxième**. Après une virgule, ils ouvrent aussi une nouvelle principale.\n\n- Ich habe den Zug verpasst. **Darum komme** ich zu spät.\n- Es gab einen Fehler. **Aus diesem Grund bitten** wir um Entschuldigung.\n\nIls peuvent aussi glisser au milieu : Ich komme **deswegen** zu spät.',
      examples: [
        { de: 'Ich habe deine Nachricht falsch verstanden, darum war ich im falschen Café.', en: 'I misread your message, that’s why I was in the wrong café.', fr: 'J’ai mal lu ton message, c’est pourquoi j’étais dans le mauvais café.' },
        { de: 'Wir hatten kein Netz. Deswegen konnten wir nicht anrufen.', en: 'We had no signal. Because of that we couldn’t call.', fr: 'Nous n’avions pas de réseau. À cause de cela, nous n’avons pas pu appeler.' },
        { de: 'Der Flug wurde gestrichen. Daher fahren wir mit dem Zug.', en: 'The flight was cancelled. Hence we are taking the train.', fr: 'Le vol a été annulé. De ce fait, nous prenons le train.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l18-naemlich-note', title: '"nämlich": the reason comes second', titleFr: '« nämlich » : la raison vient après',
      explanationMd: '**Nämlich** turns the order around: first the **result**, then the **reason**. It says "you see, the thing is…".\n\n- Ich bin zu spät. Der Bus ist **nämlich** ausgefallen.\n\nRules:\n- **Nämlich** never stands in position 1 — it sits **in the middle**, right after the verb (and often after the pronoun subject).\n- The verb stays in **position 2**.\n- It replaces "weil": Ich bin zu spät, **weil** der Bus ausgefallen ist. (here the verb goes to the end!)\n\nCompare: **weil** = subordinate clause, verb last. **nämlich** = main clause, verb second.',
      explanationMdFr: '**Nämlich** inverse l’ordre : d’abord le **résultat**, ensuite la **raison**. Il dit « tu vois, c’est que… ».\n\n- Ich bin zu spät. Der Bus ist **nämlich** ausgefallen.\n\nRègles :\n- **Nämlich** n’est jamais en position 1 — il se place **au milieu**, juste après le verbe (et souvent après le sujet pronom).\n- Le verbe reste en **position 2**.\n- Il remplace « weil » : Ich bin zu spät, **weil** der Bus ausgefallen ist. (ici le verbe va à la fin !)\n\nÀ comparer : **weil** = subordonnée, verbe à la fin. **nämlich** = principale, verbe en deuxième.',
      examples: [
        { de: 'Ich konnte nicht kommen. Ich hatte nämlich Fieber.', en: 'I couldn’t come. You see, I had a fever.', fr: 'Je n’ai pas pu venir. J’avais de la fièvre, voyez-vous.' },
        { de: 'Jonas hat gewartet. Er wusste nämlich nicht, dass ich im anderen Café war.', en: 'Jonas waited. He didn’t know, you see, that I was in the other café.', fr: 'Jonas a attendu. C’est qu’il ne savait pas que j’étais dans l’autre café.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l18-ausserdem-note', title: '"außerdem" and apologising in writing', titleFr: '« außerdem » et s’excuser par écrit',
      explanationMd: '**Außerdem** adds **one more argument** to what you just said ("besides"). Like darum, it is an adverb: position 1, **verb second**.\n\n- Das Café war überfüllt. **Außerdem war** es laut.\n\nA clear, polite explanation email often follows this pattern:\n1. **Apologise**: Es tut mir leid, dass … / Entschuldige bitte.\n2. **Explain the cause**: Ich habe die Adresse … nämlich falsch verstanden.\n3. **Give the consequence**: **Daher** / **Aus diesem Grund** …\n4. **Offer a solution**: Wollen wir es noch einmal versuchen?\n\nWith a noun you can also use **wegen** + genitive: **Wegen des Regens** kamen wir zu spät.',
      explanationMdFr: '**Außerdem** ajoute **un argument de plus** à ce qu’on vient de dire (« en outre »). Comme darum, c’est un adverbe : position 1, **verbe en deuxième**.\n\n- Das Café war überfüllt. **Außerdem war** es laut.\n\nUn e-mail d’explication clair et poli suit souvent ce schéma :\n1. **S’excuser** : Es tut mir leid, dass … / Entschuldige bitte.\n2. **Expliquer la cause** : Ich habe die Adresse … nämlich falsch verstanden.\n3. **Donner la conséquence** : **Daher** / **Aus diesem Grund** …\n4. **Proposer une solution** : Wollen wir es noch einmal versuchen ?\n\nAvec un nom, on peut aussi employer **wegen** + génitif : **Wegen des Regens** kamen wir zu spät.',
      examples: [
        { de: 'Es tut mir leid. Ich habe nämlich die Adresse falsch verstanden. Daher war ich im falschen Café.', en: 'I’m sorry. You see, I misunderstood the address. Hence I was in the wrong café.', fr: 'Je suis désolée. C’est que j’ai mal compris l’adresse. De ce fait, j’étais dans le mauvais café.' },
        { de: 'Die Wohnung ist hell und ruhig. Außerdem ist sie nicht teuer.', en: 'The flat is bright and quiet. Besides, it isn’t expensive.', fr: 'L’appartement est clair et calme. En plus, il n’est pas cher.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l18-e1', prompt: 'Which sentence has the correct word order?', promptFr: 'Quelle phrase a le bon ordre des mots ?', options: ['Darum ich bin müde.', 'Darum bin ich müde.', 'Darum müde bin ich.'], answer: 1, explain: '"darum" is position 1, so the verb comes second.', explainFr: '« darum » est en position 1, donc le verbe vient en deuxième.', hint: 'Verb second after "darum".', hintFr: 'Verbe en deuxième après « darum ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l18-e2', prompt: 'Ich bin müde. Ich habe ___ schlecht geschlafen. (you see)', promptFr: 'Ich bin müde. Ich habe ___ schlecht geschlafen. (en effet)', answer: 'nämlich', hint: 'gives the reason, sits in the middle', hintFr: 'donne la raison, se place au milieu' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l18-e3', tokens: ['habe', 'Deswegen', 'angerufen', 'ich', 'dich'], answer: ['Deswegen', 'habe', 'ich', 'dich', 'angerufen'], hint: 'Deswegen is position 1, then the auxiliary verb, then the subject.', hintFr: 'Deswegen en position 1, puis l’auxiliaire, puis le sujet.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l18-e4', pairs: [ { de: 'darum', en: 'that’s why', fr: 'c’est pourquoi' }, { de: 'nämlich', en: 'you see (reason)', fr: 'en effet (raison)' }, { de: 'außerdem', en: 'besides', fr: 'en outre' }, { de: 'das Missverständnis', en: 'the misunderstanding', fr: 'le malentendu' } ], hint: 'Match each word to its meaning.', hintFr: 'Associe chaque mot à son sens.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l18-e5', prompt: 'Listen. Why was Mara late?', promptFr: 'Écoute. Pourquoi Mara était-elle en retard ?', audio: { ttsText: 'Es tut mir leid, dass ich zu spät bin. Mein Bus ist nämlich ausgefallen.' }, options: ['Her bus was cancelled', 'She forgot the time', 'She was ill'], optionsFr: ['Son bus a été supprimé', 'Elle a oublié l’heure', 'Elle était malade'], answer: 0, hint: 'Listen to the sentence with "nämlich".', hintFr: 'Écoute la phrase avec « nämlich ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l18-e6', prompt: 'Where does "nämlich" normally stand?', promptFr: 'Où se place normalement « nämlich » ?', options: ['In position 1, before the verb', 'In the middle, after the verb', 'At the very end after a comma'], optionsFr: ['En position 1, avant le verbe', 'Au milieu, après le verbe', 'Tout à la fin après une virgule'], answer: 1, explain: 'Nämlich sits in the middle field: Er hatte nämlich Fieber.', explainFr: 'Nämlich se place au milieu : Er hatte nämlich Fieber.', hint: 'It never opens the sentence.', hintFr: 'Il n’ouvre jamais la phrase.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l18-e7', tokens: ['nämlich', 'Ich', 'den', 'Bus', 'habe', 'verpasst'], answer: ['Ich', 'habe', 'nämlich', 'den', 'Bus', 'verpasst'], hint: 'Subject, auxiliary, nämlich, then the rest; the participle goes last.', hintFr: 'Sujet, auxiliaire, nämlich, puis le reste ; le participe en dernier.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l18-e8', prompt: 'Die Wohnung ist schön. ___ ist sie günstig. (adds another point)', promptFr: 'Die Wohnung ist schön. ___ ist sie günstig. (ajoute un point)', options: ['Deshalb', 'Außerdem', 'Nämlich'], answer: 1, explain: '"außerdem" adds a second argument.', explainFr: '« außerdem » ajoute un second argument.', hint: 'You are adding a second good thing, not a consequence.', hintFr: 'Tu ajoutes un second point positif, pas une conséquence.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l18-e9', prompt: 'Listen. What is the consequence?', promptFr: 'Écoute. Quelle est la conséquence ?', audio: { ttsText: 'Die Straße war gesperrt. Daher sind wir zu Fuß gegangen.' }, options: ['They walked', 'They took a taxi', 'They stayed home'], optionsFr: ['Ils sont allés à pied', 'Ils ont pris un taxi', 'Ils sont restés chez eux'], answer: 0, hint: 'The consequence follows "Daher".', hintFr: 'La conséquence suit « Daher ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l18-e10', prompt: 'Es gab einen Fehler. Aus diesem ___ bitten wir um Entschuldigung.', promptFr: 'Es gab einen Fehler. Aus diesem ___ bitten wir um Entschuldigung.', answer: 'Grund', hint: 'aus diesem … = for this reason', hintFr: 'aus diesem … = pour cette raison' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l18-e11', prompt: '"Er ist krank. Daher kommt er nicht." What is the reason?', promptFr: '« Er ist krank. Daher kommt er nicht. » Quelle est la raison ?', options: ['He is ill', 'He doesn’t come'], optionsFr: ['Il est malade', 'Il ne vient pas'], answer: 0, explain: 'The sentence before "daher" is the reason; the one after is the consequence.', explainFr: 'La phrase avant « daher » est la raison ; celle d’après est la conséquence.', hint: 'The consequence comes after daher.', hintFr: 'La conséquence vient après daher.' } },

    { kind: 'pronunciation', focus: 'Two "ch" sounds: the soft ich-sound after e, i, ä, ö, ü (nämlich) and the back ach-sound after a, o, u, au (auch)', focusFr: 'Deux sons « ch » : le son doux « ich » après e, i, ä, ö, ü (nämlich) et le son guttural « ach » après a, o, u, au (auch)', items: [
      { id: 'b1l18-vielleicht-pron', german: 'vielleicht', english: 'maybe', french: 'peut-être', gender: null, syllables: ['viel', 'LEICHT'], pronunciation: 'fee-LYESHT', example: { de: 'Vielleicht war es ein Missverständnis.', en: 'Maybe it was a misunderstanding.', fr: 'C’était peut-être un malentendu.' } },
      { id: 'b1l18-hoeflich-pron', german: 'höflich', english: 'polite', french: 'poli', gender: null, syllables: ['HÖF', 'lich'], pronunciation: 'HOEF-lish', example: { de: 'Er hat sich höflich entschuldigt.', en: 'He apologised politely.', fr: 'Il s’est excusé poliment.' } },
      { id: 'b1l18-sprache-pron', german: 'die Sprache', english: 'the language', french: 'la langue', gender: 'die', syllables: ['SPRA', 'che'], pronunciation: 'dee SHPRAH-khe', example: { de: 'Die Sprache war das Problem.', en: 'The language was the problem.', fr: 'La langue était le problème.' } },
      { id: 'b1l18-auch-pron', german: 'auch', english: 'also / too', french: 'aussi', gender: null, syllables: ['AUCH'], pronunciation: 'owkh', example: { de: 'Ich habe auch gewartet.', en: 'I waited too.', fr: 'J’ai attendu aussi.' } },
      { id: 'b1l18-rechtzeitig-pron', german: 'rechtzeitig', english: 'on time / in good time', french: 'à temps', gender: null, syllables: ['RECHT', 'zei', 'tig'], pronunciation: 'RESHT-tsy-tish', example: { de: 'Wir waren rechtzeitig da.', en: 'We were there on time.', fr: 'Nous étions là à temps.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now link cause and effect in a richer way: **darum / deswegen / daher / aus diesem Grund** all put the **verb second** after them. **Nämlich** gives the reason afterwards from the middle of the sentence, and **außerdem** adds one more argument. Put it together in a short email: apologise, explain, name the consequence, and suggest a fix. 🎉',
      summaryFr: 'Tu sais maintenant relier cause et effet de façon plus riche : **darum / deswegen / daher / aus diesem Grund** placent tous le **verbe en deuxième**. **Nämlich** donne la raison après coup, depuis le milieu de la phrase, et **außerdem** ajoute un argument de plus. Assemble le tout dans un court e-mail : excuse-toi, explique, nomme la conséquence et propose une solution. 🎉' },
  ],
};
