import type { Lesson } from '../types';

export const b1lektion20: Lesson = {
  id: 'b1-l20', level: 'B1', module: 2, number: 8,
  title: { de: 'Es-Ausdrücke und „brauchen … zu“', en: '"es" expressions and "brauchen … zu"', fr: 'Expressions avec « es » et « brauchen … zu »' },
  theme: 'Not having to (brauchen + zu), the many jobs of "es", and telling stories in the present tense',
  themeFr: 'Ne pas avoir à (brauchen + zu), les nombreux emplois de « es » et raconter au présent',
  goals: ['Say what is not necessary with "brauchen nicht/nur/kein … zu"', 'Use "es" in fixed phrases, weather, time and well-being', 'Recognise "es" as a placeholder subject', 'Tell stories and jokes in the narrative present'],
  goalsFr: ['Dire ce qui n’est pas nécessaire avec « brauchen nicht/nur/kein … zu »', 'Employer « es » dans des expressions figées, la météo, l’heure et le bien-être', 'Reconnaître « es » comme sujet de remplacement', 'Raconter des histoires et des blagues au présent de narration'],
  steps: [
    { kind: 'intro', title: 'Früher, als wir jung waren 🎞️', titleFr: 'Autrefois, quand nous étions jeunes 🎞️',
      scene: 'At a family party, grandma Hanne and her grandson Leo swap stories: her strict childhood chores, his school pranks, and one very good joke. Somebody is always ringing the doorbell.',
      sceneFr: 'Lors d’une fête de famille, grand-mère Hanne et son petit-fils Leo échangent des histoires : les corvées de son enfance stricte, les blagues de Leo à l’école et une très bonne plaisanterie. Quelqu’un sonne toujours à la porte.',
      goals: ['Talk about duties that were or were not necessary', 'Use "es" correctly in everyday phrases', 'Understand when "es" disappears', 'Tell a lively anecdote in the present tense'],
      goalsFr: ['Parler des tâches qui étaient ou n’étaient pas nécessaires', 'Employer correctement « es » dans les phrases du quotidien', 'Comprendre quand « es » disparaît', 'Raconter une anecdote vivante au présent'] },

    { kind: 'vocab', item: { id: 'b1l20-brauchen', german: 'brauchen … zu', english: 'to need to / to have to (only negated)', french: 'avoir besoin de / devoir (surtout nié)', gender: null, syllables: ['BRAU', 'chen', 'TSU'], pronunciation: 'BROW-khen tsoo', example: { de: 'Du brauchst nicht zu warten.', en: 'You don’t need to wait.', fr: 'Tu n’as pas besoin d’attendre.' } } },
    { kind: 'vocab', item: { id: 'b1l20-kuemmern', german: 'sich kümmern um', english: 'to take care of', french: 's’occuper de', gender: null, syllables: ['sich', 'KÜM', 'mern', 'um'], pronunciation: 'zish KEWM-ern oom', example: { de: 'Mein Bruder kümmert sich um den Garten.', en: 'My brother takes care of the garden.', fr: 'Mon frère s’occupe du jardin.' } } },
    { kind: 'vocab', item: { id: 'b1l20-jugend', german: 'die Jugend', english: 'the youth', french: 'la jeunesse', gender: 'die', syllables: ['JU', 'gend'], pronunciation: 'dee YOO-gent', example: { de: 'In meiner Jugend gab es noch keine Handys.', en: 'In my youth there were no mobile phones yet.', fr: 'Dans ma jeunesse, il n’y avait pas encore de portables.' } } },
    { kind: 'vocab', item: { id: 'b1l20-erinnerung', german: 'die Erinnerung', english: 'the memory', french: 'le souvenir', gender: 'die', syllables: ['er', 'IN', 'ne', 'rung'], pronunciation: 'dee air-IN-eh-roong', example: { de: 'Das ist meine schönste Erinnerung an den Sommer.', en: 'That is my nicest memory of the summer.', fr: 'C’est mon plus beau souvenir de l’été.' } } },
    { kind: 'vocab', item: { id: 'b1l20-pflicht', german: 'die Pflicht', english: 'the duty', french: 'le devoir / l’obligation', gender: 'die', syllables: ['PFLICHT'], pronunciation: 'dee pflisht', example: { de: 'Hausaufgaben waren früher Pflicht.', en: 'Homework used to be compulsory.', fr: 'Les devoirs étaient autrefois obligatoires.' } } },
    { kind: 'vocab', item: { id: 'b1l20-erlaubnis', german: 'die Erlaubnis', english: 'the permission', french: 'la permission', gender: 'die', syllables: ['er', 'LAUB', 'nis'], pronunciation: 'dee air-LOWB-niss', example: { de: 'Ohne Erlaubnis durften wir nicht ausgehen.', en: 'We weren’t allowed to go out without permission.', fr: 'Sans permission, nous n’avions pas le droit de sortir.' } } },
    { kind: 'vocab', item: { id: 'b1l20-haushalt', german: 'der Haushalt', english: 'the household / housework', french: 'le ménage / les tâches ménagères', gender: 'der', syllables: ['HAUS', 'halt'], pronunciation: 'dair HOWSS-hahlt', example: { de: 'Jeder hilft im Haushalt mit.', en: 'Everyone helps with the housework.', fr: 'Chacun aide aux tâches ménagères.' } } },
    { kind: 'vocab', item: { id: 'b1l20-witz', german: 'der Witz', english: 'the joke', french: 'la blague', gender: 'der', syllables: ['WITZ'], pronunciation: 'dair vitss', example: { de: 'Opa erzählt immer denselben Witz.', en: 'Grandpa always tells the same joke.', fr: 'Papi raconte toujours la même blague.' } } },
    { kind: 'vocab', item: { id: 'b1l20-anekdote', german: 'die Anekdote', english: 'the anecdote', french: 'l’anecdote', gender: 'die', syllables: ['a', 'nek', 'DO', 'te'], pronunciation: 'dee ah-nek-DOH-teh', example: { de: 'Sie erzählt eine lustige Anekdote aus ihrer Schulzeit.', en: 'She tells a funny anecdote from her school days.', fr: 'Elle raconte une anecdote amusante de sa scolarité.' } } },
    { kind: 'vocab', item: { id: 'b1l20-damals', german: 'damals', english: 'back then', french: 'à l’époque', gender: null, syllables: ['DA', 'mals'], pronunciation: 'DAH-mahls', example: { de: 'Damals gab es nur drei Fernsehprogramme.', en: 'Back then there were only three TV channels.', fr: 'À l’époque, il n’y avait que trois chaînes de télévision.' } } },
    { kind: 'vocab', item: { id: 'b1l20-ploetzlich', german: 'plötzlich', english: 'suddenly', french: 'soudain', gender: null, syllables: ['PLÖTZ', 'lich'], pronunciation: 'PLOETS-lish', example: { de: 'Plötzlich klingelt das Telefon.', en: 'Suddenly the phone rings.', fr: 'Soudain, le téléphone sonne.' } } },
    { kind: 'vocab', item: { id: 'b1l20-klingeln', german: 'klingeln', english: 'to ring (a bell / phone)', french: 'sonner', gender: null, syllables: ['KLIN', 'geln'], pronunciation: 'KLING-eln', example: { de: 'Es klingelt an der Tür.', en: 'Someone is ringing the doorbell.', fr: 'On sonne à la porte.' } } },
    { kind: 'vocab', item: { id: 'b1l20-stell-dir-vor', german: 'Stell dir vor: …', english: 'Imagine this: … (opens a story)', french: 'Imagine-toi : … (ouvre une histoire)', gender: null, syllables: ['STELL', 'dir', 'VOR'], pronunciation: 'shtell deer fohr', example: { de: 'Stell dir vor: Ich öffne die Tür, und da steht Oma!', en: 'Imagine this: I open the door and there stands Grandma!', fr: 'Imagine : j’ouvre la porte et voilà Mamie !' } } },

    { kind: 'grammar', note: {
      id: 'b1l20-brauchen-zu', title: '"brauchen … zu": it is not necessary', titleFr: '« brauchen … zu » : ce n’est pas nécessaire',
      explanationMd: 'With **brauchen** + **zu** + infinitive you say something is **not necessary**. It works only with a **negation** or a limiting word: **nicht**, **kein-**, **nichts**, **niemand**, **nur**.\n\n- Du **brauchst nicht zu kommen**. (you don’t have to come)\n- Wir **brauchten** uns um nichts **zu kümmern**. (we didn’t have to worry about anything)\n- Du **brauchst nur anzurufen**. (you only have to call)\n- Ich **brauche keine Angst zu haben**.\n\nThe **zu** goes right before the infinitive; with a **separable verb** it sits inside: **anzu**rufen, **aufzu**räumen.\n\nCompare: **nicht müssen** ≈ **nicht brauchen zu** (not necessary), but **nicht dürfen** = forbidden.\n\nBy itself, **brauchen** + accusative means "need": Ich brauche Hilfe. A sentence like "Du brauchst zu kommen" (no negation) is wrong — use **müssen**.',
      explanationMdFr: 'Avec **brauchen** + **zu** + infinitif, tu dis que quelque chose **n’est pas nécessaire**. Cela ne marche qu’avec une **négation** ou un mot restrictif : **nicht**, **kein-**, **nichts**, **niemand**, **nur**.\n\n- Du **brauchst nicht zu kommen**. (tu n’as pas besoin de venir)\n- Wir **brauchten** uns um nichts **zu kümmern**. (nous n’avions à nous soucier de rien)\n- Du **brauchst nur anzurufen**. (il te suffit d’appeler)\n- Ich **brauche keine Angst zu haben**.\n\nLe **zu** se place juste avant l’infinitif ; avec un **verbe séparable**, il s’insère dedans : **anzu**rufen, **aufzu**räumen.\n\nÀ comparer : **nicht müssen** ≈ **nicht brauchen zu** (pas nécessaire), mais **nicht dürfen** = interdit.\n\nSeul, **brauchen** + accusatif veut dire « avoir besoin de » : Ich brauche Hilfe. Une phrase comme « Du brauchst zu kommen » (sans négation) est fausse — utilise **müssen**.',
      examples: [
        { de: 'Früher brauchten wir am Sonntag nicht zu lernen.', en: 'We didn’t have to study on Sundays back then.', fr: 'Autrefois, nous n’avions pas à étudier le dimanche.' },
        { de: 'Du brauchst nur kurz Bescheid zu sagen.', en: 'You only need to let me know briefly.', fr: 'Il te suffit de me prévenir rapidement.' },
        { de: 'Heute brauche ich nicht aufzuräumen, das macht Leo.', en: 'Today I don’t need to tidy up, Leo does it.', fr: 'Aujourd’hui, je n’ai pas besoin de ranger, c’est Leo qui le fait.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l20-es-ausdruecke', title: '"es": fixed phrases and placeholder', titleFr: '« es » : expressions figées et sujet de remplacement',
      explanationMd: 'In German, many sentences need **es** as a formal subject — it does not stand for any thing.\n\n- **Es gibt** + accusative: Es gibt hier einen Spielplatz.\n- **Weather:** Es regnet. Es ist kalt. Es schneit.\n- **Time / seasons:** Es ist Abend. Es ist halb acht. Im Sommer ist es lange hell.\n- **Well-being:** Wie geht es dir? — Es geht mir gut. / Mir ist kalt. (no es!)\n- **Sounds:** Es klingelt. Es klopft.\n- **Feelings:** Es tut mir leid. Es gefällt mir hier.\n- **Topic:** Es geht um einen Witz.\n\n**Placeholder es:** it may fill position 1 when the real subject comes later — and it **disappears** as soon as something else stands in position 1:\n\n- **Es** kommen viele Gäste. → Heute kommen viele Gäste.\n- **Es** wurde viel gelacht. → Gestern wurde viel gelacht.\n\nThe verb agrees with the **real subject** (kommen = plural Gäste), not with es.',
      explanationMdFr: 'En allemand, beaucoup de phrases ont besoin de **es** comme sujet formel — il ne remplace aucune chose.\n\n- **Es gibt** + accusatif : Es gibt hier einen Spielplatz.\n- **Météo :** Es regnet. Es ist kalt. Es schneit.\n- **Heure / saisons :** Es ist Abend. Es ist halb acht. Im Sommer ist es lange hell.\n- **Bien-être :** Wie geht es dir ? — Es geht mir gut. / Mir ist kalt. (no es!)\n- **Bruits :** Es klingelt. Es klopft.\n- **Sentiments :** Es tut mir leid. Es gefällt mir hier.\n- **Sujet :** Es geht um einen Witz.\n\n**Es de remplacement :** il peut occuper la position 1 quand le vrai sujet vient plus tard — et il **disparaît** dès qu’autre chose est en position 1 :\n\n- **Es** kommen viele Gäste. → Heute kommen viele Gäste.\n- **Es** wurde viel gelacht. → Gestern wurde viel gelacht.\n\nLe verbe s’accorde avec le **vrai sujet** (kommen = pluriel Gäste), pas avec es.',
      examples: [
        { de: 'Es ist kalt, aber es regnet nicht.', en: 'It is cold, but it isn’t raining.', fr: 'Il fait froid, mais il ne pleut pas.' },
        { de: 'Wie geht es dir? – Danke, es geht mir gut.', en: 'How are you? – Thanks, I’m fine.', fr: 'Comment vas-tu ? – Merci, ça va bien.' },
        { de: 'Es kommen viele Gäste. / Heute kommen viele Gäste.', en: 'Many guests are coming. / Today many guests are coming.', fr: 'Beaucoup d’invités viennent. / Aujourd’hui, beaucoup d’invités viennent.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l20-erzaehlpraesens', title: 'Telling stories in the present tense', titleFr: 'Raconter une histoire au présent',
      explanationMd: 'Jokes, anecdotes and lively stories are often told in the **present tense**, even when they happened in the past. It makes the story feel close, as if it is happening now.\n\nHandy story signals:\n- **Stell dir vor: …** · **Weißt du, was passiert ist?**\n- **Plötzlich …** · **Da …** · **Und dann …**\n- **Guck mal!** / **Schau mal!** — look! (to pull attention)\n\nExample: **Stell dir vor:** Ich sitze im Café, da klingelt plötzlich mein Handy. Ich gehe ran — und **wer** ist es? Meine Oma!\n\nUse **Präteritum/Perfekt** for plain reports, and the **present** to make a story vivid.',
      explanationMdFr: 'Les blagues, anecdotes et récits vivants se racontent souvent au **présent**, même s’ils se sont passés autrefois. Cela rapproche l’histoire, comme si elle se déroulait maintenant.\n\nSignaux utiles :\n- **Stell dir vor: …** · **Weißt du, was passiert ist?**\n- **Plötzlich …** · **Da …** · **Und dann …**\n- **Guck mal!** / **Schau mal!** — regarde ! (pour attirer l’attention)\n\nExemple : **Stell dir vor:** Ich sitze im Café, da klingelt plötzlich mein Handy. Ich gehe ran — und **wer** ist es ? Meine Oma !\n\nUtilise **Präteritum/Perfekt** pour un simple compte rendu, et le **présent** pour rendre un récit vivant.',
      examples: [
        { de: 'Stell dir vor: Ich öffne die Tür, und da steht mein Onkel aus Hamburg!', en: 'Imagine this: I open the door and there stands my uncle from Hamburg!', fr: 'Imagine : j’ouvre la porte et voilà mon oncle de Hambourg !' },
        { de: 'Guck mal! Da kommt plötzlich ein Hund ins Zimmer.', en: 'Look! Suddenly a dog comes into the room.', fr: 'Regarde ! Soudain, un chien entre dans la pièce.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l20-e1', prompt: 'How do you say "You don’t have to come"?', promptFr: 'Comment dit-on « Tu n’as pas besoin de venir » ?', options: ['Du darfst nicht kommen.', 'Du brauchst nicht zu kommen.', 'Du brauchst nicht kommen zu.'], answer: 1, explain: '"nicht brauchen zu" + infinitive = not necessary; "nicht dürfen" = forbidden.', explainFr: '« nicht brauchen zu » + infinitif = pas nécessaire ; « nicht dürfen » = interdit.', hint: 'zu goes right before the infinitive.', hintFr: 'zu se place juste avant l’infinitif.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l20-e2', prompt: 'Du brauchst nicht ___ warten.', promptFr: 'Du brauchst nicht ___ warten.', answer: 'zu', hint: 'brauchen + nicht + zu + infinitive', hintFr: 'brauchen + nicht + zu + infinitif' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l20-e3', tokens: ['nur', 'Du', 'anzurufen', 'brauchst'], answer: ['Du', 'brauchst', 'nur', 'anzurufen'], hint: 'The separable verb keeps "zu" inside: anzurufen.', hintFr: 'Le verbe séparable garde « zu » à l’intérieur : anzurufen.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l20-e4', prompt: 'Wie geht ___ dir?', promptFr: 'Wie geht ___ dir ?', answer: 'es', hint: 'formal subject of well-being', hintFr: 'sujet formel du bien-être' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l20-e5', pairs: [ { de: 'Es regnet.', en: 'It is raining.', fr: 'Il pleut.' }, { de: 'Es klingelt.', en: 'The bell is ringing.', fr: 'On sonne.' }, { de: 'Es tut mir leid.', en: 'I am sorry.', fr: 'Je suis désolé(e).' }, { de: 'Es gibt einen Park.', en: 'There is a park.', fr: 'Il y a un parc.' } ], hint: 'Match each "es" phrase to its meaning.', hintFr: 'Associe chaque expression avec « es » à son sens.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l20-e6', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Heute es kommen viele Gäste.', 'Heute kommen viele Gäste.', 'Heute kommen es viele Gäste.'], answer: 1, explain: 'When another element stands in position 1, the placeholder "es" disappears.', explainFr: 'Quand un autre élément est en position 1, le « es » de remplacement disparaît.', hint: 'Only one "es" spot exists: position 1.', hintFr: 'Il n’y a qu’une place pour « es » : la position 1.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l20-e7', prompt: 'Listen. Who did not have to clean?', promptFr: 'Écoute. Qui n’avait pas à nettoyer ?', audio: { ttsText: 'Früher musste ich jeden Samstag das Bad putzen. Mein Bruder brauchte das nie zu tun, er war ja der Jüngste.' }, options: ['The brother', 'The speaker', 'The mother'], optionsFr: ['Le frère', 'Le narrateur', 'La mère'], answer: 0, hint: 'Listen for "brauchte … nie zu tun".', hintFr: 'Écoute « brauchte … nie zu tun ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l20-e8', prompt: 'Which sentence tells a story in the narrative present?', promptFr: 'Quelle phrase raconte au présent de narration ?', options: ['Gestern saß ich im Zug.', 'Ich sitze im Zug, da klingelt plötzlich mein Handy.', 'Ich werde im Zug sitzen.'], answer: 1, explain: 'The present tense with "da" / "plötzlich" makes a past story lively.', explainFr: 'Le présent avec « da » / « plötzlich » rend un récit passé vivant.', hint: 'Look for present tense plus a story signal.', hintFr: 'Cherche le présent plus un signal de récit.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l20-e9', prompt: 'Im Winter ist ___ früh dunkel.', promptFr: 'Im Winter ist ___ früh dunkel.', answer: 'es', hint: 'formal subject for time and light', hintFr: 'sujet formel pour le temps et la lumière' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l20-e10', tokens: ['nicht', 'Wir', 'aufzuräumen', 'brauchten'], answer: ['Wir', 'brauchten', 'nicht', 'aufzuräumen'], hint: 'Subject, brauchten, nicht, then the infinitive with zu inside.', hintFr: 'Sujet, brauchten, nicht, puis l’infinitif avec zu à l’intérieur.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l20-e11', prompt: 'Listen. Who is at the door?', promptFr: 'Écoute. Qui est à la porte ?', audio: { ttsText: 'Es klingelt an der Tür. Ich mache auf, und da steht mein Onkel aus Hamburg!' }, options: ['An uncle from Hamburg', 'The neighbour', 'A pizza courier'], optionsFr: ['Un oncle de Hambourg', 'Le voisin', 'Un livreur de pizza'], answer: 0, hint: 'Listen for the person after "da steht".', hintFr: 'Écoute la personne après « da steht ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l20-e12', prompt: 'Which sentence is wrong?', promptFr: 'Quelle phrase est fausse ?', options: ['Du brauchst keine Angst zu haben.', 'Du brauchst nur zu fragen.', 'Du brauchst morgen zu kommen.'], answer: 2, explain: '"brauchen zu" needs a negation or "nur". For a necessity, use "müssen".', explainFr: '« brauchen zu » exige une négation ou « nur ». Pour une nécessité, utilise « müssen ».', hint: 'One sentence has no negation and no "nur".', hintFr: 'Une phrase n’a ni négation ni « nur ».' } },

    { kind: 'pronunciation', focus: 'Three letters that surprise English speakers: j = "y", w = "v", z = "ts"', focusFr: 'Trois lettres qui surprennent : j = « y », w = « v », z = « ts »', items: [
      { id: 'b1l20-jung-pron', german: 'jung', english: 'young', french: 'jeune', gender: null, syllables: ['JUNG'], pronunciation: 'yoong', example: { de: 'Als ich jung war, spielte ich viel draußen.', en: 'When I was young, I played outside a lot.', fr: 'Quand j’étais jeune, je jouais beaucoup dehors.' } },
      { id: 'b1l20-wetter-pron', german: 'das Wetter', english: 'the weather', french: 'le temps', gender: 'das', syllables: ['WET', 'ter'], pronunciation: 'dahss VET-ter', example: { de: 'Das Wetter ist heute schlecht.', en: 'The weather is bad today.', fr: 'Le temps est mauvais aujourd’hui.' } },
      { id: 'b1l20-zeit-pron', german: 'die Zeit', english: 'the time', french: 'le temps / l’heure', gender: 'die', syllables: ['ZEIT'], pronunciation: 'dee tsite', example: { de: 'Wir hatten damals viel Zeit.', en: 'We had a lot of time back then.', fr: 'Nous avions beaucoup de temps à l’époque.' } },
      { id: 'b1l20-zusammen-pron', german: 'zusammen', english: 'together', french: 'ensemble', gender: null, syllables: ['zu', 'SAM', 'men'], pronunciation: 'tsoo-ZAH-men', example: { de: 'Wir haben zusammen gelacht.', en: 'We laughed together.', fr: 'Nous avons ri ensemble.' } },
      { id: 'b1l20-jahr-pron', german: 'das Jahr', english: 'the year', french: 'l’année', gender: 'das', syllables: ['JAHR'], pronunciation: 'dahss yahr', example: { de: 'Jedes Jahr feiern wir zusammen.', en: 'Every year we celebrate together.', fr: 'Chaque année, nous fêtons ensemble.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now say what is **not necessary** with **brauchen nicht/nur/kein … zu** (Du brauchst nicht zu kommen). You know that **es** appears in fixed phrases (**es gibt, es regnet, es geht mir gut, es klingelt**) and as a placeholder that vanishes when something else opens the sentence. And you can tell a lively story in the **present tense**: *Stell dir vor … Plötzlich … Guck mal!* 🎉',
      summaryFr: 'Tu sais maintenant dire ce qui n’est **pas nécessaire** avec **brauchen nicht/nur/kein … zu** (Du brauchst nicht zu kommen). Tu sais que **es** apparaît dans des expressions figées (**es gibt, es regnet, es geht mir gut, es klingelt**) et comme élément de remplacement qui disparaît quand autre chose ouvre la phrase. Et tu peux raconter une histoire vivante au **présent** : *Stell dir vor … Plötzlich … Guck mal !* 🎉' },
  ],
};
