import type { Lesson } from '../types';

export const b1lektion16: Lesson = {
  id: 'b1-l16', level: 'B1', module: 1, number: 4,
  title: { de: 'Falls, da, bevor, während', en: '"falls", "da", "bevor", "während"', fr: '« falls », « da », « bevor », « während »' },
  theme: 'Conditions, reasons and time relations with falls, da, bevor and während',
  themeFr: 'Conditions, raisons et relations de temps avec falls, da, bevor et während',
  goals: ['Express a possible condition with "falls"', 'Give a known reason with "da"', 'Order events with "bevor"', 'Describe simultaneous actions with "während"'],
  goalsFr: ['Exprimer une condition possible avec « falls »', 'Donner une raison connue avec « da »', 'Ordonner des événements avec « bevor »', 'Décrire des actions simultanées avec « während »'],
  steps: [
    { kind: 'intro', title: 'Fühlen Sie sich wie zu Hause 🏨', titleFr: 'Faites comme chez vous 🏨',
      scene: 'A small hotel and a dinner party: the hosts welcome guests, plan ahead, and some people decide in a second while others think for ages.', sceneFr: 'Un petit hôtel et un dîner entre amis : les hôtes accueillent leurs invités, anticipent, et certains décident en une seconde tandis que d’autres réfléchissent des heures.',
      goals: ['Use "falls" for "in case"', 'Use "da" for a reason everyone knows', 'Use "bevor" for "before"', 'Use "während" for "while"'],
      goalsFr: ['Utiliser « falls » pour « au cas où / si »', 'Utiliser « da » pour une raison que tout le monde connaît', 'Utiliser « bevor » pour « avant que »', 'Utiliser « während » pour « pendant que »'] },

    { kind: 'vocab', item: { id: 'b1l16-gastgeber', german: 'der Gastgeber', english: 'the host', french: 'l’hôte', gender: 'der', syllables: ['GAST', 'ge', 'ber'], pronunciation: 'dair GAHST-gay-ber', example: { de: 'Der Gastgeber begrüßt jeden Gast an der Tür.', en: 'The host greets every guest at the door.', fr: 'L’hôte accueille chaque invité à la porte.' } } },
    { kind: 'vocab', item: { id: 'b1l16-unterkunft', german: 'die Unterkunft', english: 'the accommodation', french: 'l’hébergement', gender: 'die', syllables: ['UN', 'ter', 'kunft'], pronunciation: 'dee OON-ter-koonft', example: { de: 'Die Unterkunft liegt direkt am See.', en: 'The accommodation is right by the lake.', fr: 'L’hébergement est juste au bord du lac.' } } },
    { kind: 'vocab', item: { id: 'b1l16-rezeption', german: 'die Rezeption', english: 'the reception desk', french: 'la réception', gender: 'die', syllables: ['re', 'zep', 'ZION'], pronunciation: 'dee ray-tsep-TSYOHN', example: { de: 'Die Rezeption ist rund um die Uhr besetzt.', en: 'The reception desk is staffed around the clock.', fr: 'La réception est ouverte jour et nuit.' } } },
    { kind: 'vocab', item: { id: 'b1l16-buchung', german: 'die Buchung', english: 'the booking', french: 'la réservation', gender: 'die', syllables: ['BU', 'chung'], pronunciation: 'dee BOO-khoong', example: { de: 'Wir haben Ihre Buchung leider nicht gefunden.', en: 'Unfortunately we could not find your booking.', fr: 'Nous n’avons malheureusement pas trouvé votre réservation.' } } },
    { kind: 'vocab', item: { id: 'b1l16-sonderwunsch', german: 'der Sonderwunsch', english: 'the special request', french: 'la demande particulière', gender: 'der', syllables: ['SON', 'der', 'wunsch'], pronunciation: 'dair ZON-der-voonsh', example: { de: 'Haben Sie noch einen Sonderwunsch für das Menü?', en: 'Do you have any special request for the menu?', fr: 'Avez-vous une demande particulière pour le menu ?' } } },
    { kind: 'vocab', item: { id: 'b1l16-allergie', german: 'die Allergie', english: 'the allergy', french: 'l’allergie', gender: 'die', syllables: ['al', 'er', 'GIE'], pronunciation: 'dee ah-ler-GHEE', example: { de: 'Mein Gast hat eine Allergie gegen Nüsse.', en: 'My guest has an allergy to nuts.', fr: 'Mon invité est allergique aux noix.' } } },
    { kind: 'vocab', item: { id: 'b1l16-anbieten', german: 'anbieten', english: 'to offer', french: 'proposer / offrir', gender: null, syllables: ['AN', 'bie', 'ten'], pronunciation: 'AHN-bee-ten', example: { de: 'Darf ich Ihnen etwas zu trinken anbieten?', en: 'May I offer you something to drink?', fr: 'Puis-je vous offrir quelque chose à boire ?' } } },
    { kind: 'vocab', item: { id: 'b1l16-zusagen', german: 'zusagen', english: 'to accept (an invitation)', french: 'accepter (une invitation)', gender: null, syllables: ['ZU', 'sa', 'gen'], pronunciation: 'TSOO-zah-gen', example: { de: 'Wir haben gern zugesagt.', en: 'We gladly accepted.', fr: 'Nous avons accepté avec plaisir.' } } },
    { kind: 'vocab', item: { id: 'b1l16-absagen', german: 'absagen', english: 'to decline / to cancel', french: 'décliner / annuler', gender: null, syllables: ['AB', 'sa', 'gen'], pronunciation: 'AHP-zah-gen', example: { de: 'Leider muss ich den Termin absagen.', en: 'Unfortunately I have to cancel the appointment.', fr: 'Je dois malheureusement annuler le rendez-vous.' } } },
    { kind: 'vocab', item: { id: 'b1l16-entscheiden', german: 'sich entscheiden', english: 'to decide', french: 'se décider', gender: null, syllables: ['ent', 'SCHEI', 'den'], pronunciation: 'zikh ent-SHY-den', example: { de: 'Ich kann mich nicht zwischen Fisch und Fleisch entscheiden.', en: 'I cannot decide between fish and meat.', fr: 'Je n’arrive pas à choisir entre le poisson et la viande.' } } },
    { kind: 'vocab', item: { id: 'b1l16-ueberlegen', german: 'überlegen', english: 'to think over / to consider', french: 'réfléchir', gender: null, syllables: ['ü', 'ber', 'LE', 'gen'], pronunciation: 'ue-ber-LAY-gen', example: { de: 'Er überlegt lange, bevor er antwortet.', en: 'He thinks for a long time before he answers.', fr: 'Il réfléchit longtemps avant de répondre.' } } },
    { kind: 'vocab', item: { id: 'b1l16-spontan', german: 'spontan', english: 'spontaneous / on the spot', french: 'spontané', gender: null, syllables: ['spon', 'TAN'], pronunciation: 'shpon-TAHN', example: { de: 'Sie entscheidet sich immer spontan.', en: 'She always decides on the spur of the moment.', fr: 'Elle se décide toujours sur un coup de tête.' } } },
    { kind: 'vocab', item: { id: 'b1l16-gruendlich', german: 'gründlich', english: 'thorough', french: 'minutieux / approfondi', gender: null, syllables: ['GRÜND', 'lich'], pronunciation: 'GRUENT-likh', example: { de: 'Er prüft jedes Angebot gründlich.', en: 'He checks every offer thoroughly.', fr: 'Il examine chaque offre minutieusement.' } } },

    { kind: 'grammar', note: {
      id: 'b1l16-falls', title: 'Conditions with "falls"', titleFr: 'Les conditions avec « falls »',
      explanationMd: '**falls** means "if / in case" and introduces a **possible but uncertain** situation. It is a subordinating conjunction: the **conjugated verb goes to the end** of its clause.\n\n- **Falls** du Hunger **hast**, koche ich noch etwas.\n- Ich koche noch etwas, **falls** du Hunger **hast**.\n\nThe clause can come **first or second**. If it comes **first**, the main clause starts with the **verb** (Falls …, **koche** ich …). An imperative also works: *Falls Sie Fragen haben, **fragen** Sie an der Rezeption.*\n\n**falls** vs. **wenn**: *wenn* is often "whenever" or a certain event; *falls* stresses "it might not happen".',
      explanationMdFr: '**falls** signifie « si / au cas où » et introduit une situation **possible mais incertaine**. C’est une conjonction de subordination : le **verbe conjugué va à la fin** de sa proposition.\n\n- **Falls** du Hunger **hast**, koche ich noch etwas.\n- Ich koche noch etwas, **falls** du Hunger **hast**.\n\nLa proposition peut venir **en premier ou en second**. Si elle vient **en premier**, la principale commence par le **verbe** (Falls …, **koche** ich …). Un impératif est aussi possible : *Falls Sie Fragen haben, **fragen** Sie an der Rezeption.*\n\n**falls** ou **wenn** : *wenn* exprime souvent « chaque fois que » ou un événement certain ; *falls* souligne que « ça n’arrivera peut-être pas ».',
      diagram: 'satzklammer',
      examples: [
        { de: 'Falls Sie eine Allergie haben, sagen Sie es bitte vor dem Essen.', en: 'If you have an allergy, please say so before the meal.', fr: 'Si vous avez une allergie, dites-le s’il vous plaît avant le repas.' },
        { de: 'Wir bringen eine Flasche Wasser mit, falls es heiß wird.', en: 'We’ll bring a bottle of water in case it gets hot.', fr: 'Nous apportons une bouteille d’eau au cas où il ferait chaud.' },
        { de: 'Falls Ihnen das Zimmer nicht gefällt, finden wir eine andere Lösung.', en: 'If you don’t like the room, we’ll find another solution.', fr: 'Si la chambre ne vous plaît pas, nous trouverons une autre solution.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l16-da', title: 'Reasons with "da"', titleFr: 'Les raisons avec « da »',
      explanationMd: '**da** means "since / as" and gives a **reason that the listener already knows or can see**. Like *weil*, it sends the verb to the **end**. It is typical of **writing and formal speech**, and it usually stands at the **beginning** of the sentence:\n\n- **Da** das Hotel ausgebucht **ist**, suchen wir eine andere Unterkunft.\n- **Da** Sie gern früh **frühstücken**, öffnen wir den Saal schon um sechs.\n\nUse **weil** when the reason is **new information** or answers *Warum?*: *Warum kommst du nicht? — **Weil** ich krank bin.*',
      explanationMdFr: '**da** signifie « puisque / comme » et donne une **raison que l’interlocuteur connaît déjà ou voit**. Comme *weil*, il envoie le verbe **à la fin**. C’est typique de l’**écrit et du registre formel**, et il se place en général **au début** de la phrase :\n\n- **Da** das Hotel ausgebucht **ist**, suchen wir eine andere Unterkunft.\n- **Da** Sie gern früh **frühstücken**, öffnen wir den Saal schon um sechs.\n\nUtilise **weil** quand la raison est une **information nouvelle** ou répond à *Warum ?* : *Warum kommst du nicht ? — **Weil** ich krank bin.*',
      examples: [
        { de: 'Da es in Strömen regnet, servieren wir den Kaffee drinnen.', en: 'Since it’s pouring with rain, we’ll serve the coffee inside.', fr: 'Comme il pleut à verse, nous servons le café à l’intérieur.' },
        { de: 'Da Tom Vegetarier ist, bestellen wir keine Würstchen.', en: 'Since Tom is a vegetarian, we won’t order sausages.', fr: 'Puisque Tom est végétarien, nous ne commandons pas de saucisses.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l16-bevor-waehrend', title: 'Time: "bevor" and "während"', titleFr: 'Le temps : « bevor » et « während »',
      explanationMd: '**bevor** = "before" — the action in the **bevor**-clause happens **later**. **während** = "while" — two actions happen **at the same time**. Both send the verb to the **end**:\n\n- **Bevor** die Gäste **kommen**, decke ich den Tisch.\n- Ich decke den Tisch, **bevor** die Gäste **kommen**.\n- **Während** ich **koche**, räumst du auf.\n\nWith the clause **first**, the main clause starts with its **verb**. Use the **same tense** in both clauses (present + present, Präteritum + Präteritum).\n\n**während** can also contrast two people: *Während Nora sofort **entscheidet**, **überlegt** Tim noch.* (= "whereas").',
      explanationMdFr: '**bevor** = « avant que » — l’action de la proposition en **bevor** a lieu **plus tard**. **während** = « pendant que » — deux actions ont lieu **en même temps**. Les deux envoient le verbe **à la fin** :\n\n- **Bevor** die Gäste **kommen**, decke ich den Tisch.\n- Ich decke den Tisch, **bevor** die Gäste **kommen**.\n- **Während** ich **koche**, räumst du auf.\n\nQuand la subordonnée est **en premier**, la principale commence par son **verbe**. Utilise le **même temps** dans les deux propositions (présent + présent, prétérit + prétérit).\n\n**während** peut aussi opposer deux personnes : *Während Nora sofort **entscheidet**, **überlegt** Tim noch.* (= « alors que »).',
      examples: [
        { de: 'Bevor du die Buchung bestätigst, lies die Bedingungen.', en: 'Before you confirm the booking, read the conditions.', fr: 'Avant de confirmer la réservation, lis les conditions.' },
        { de: 'Während die Gäste frühstücken, bereitet das Team die Zimmer vor.', en: 'While the guests have breakfast, the team prepares the rooms.', fr: 'Pendant que les clients prennent le petit-déjeuner, l’équipe prépare les chambres.' },
        { de: 'Während Jana spontan entscheidet, prüft Ben jedes Detail gründlich.', en: 'Whereas Jana decides spontaneously, Ben checks every detail thoroughly.', fr: 'Alors que Jana décide spontanément, Ben vérifie chaque détail minutieusement.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l16-e1', prompt: 'Which conjunction means "in case / if it happens"?', promptFr: 'Quelle conjonction signifie « au cas où / si cela arrive » ?', options: ['falls', 'da', 'während'], answer: 0, explain: '"falls" introduces a possible condition.', explainFr: '« falls » introduit une condition possible.', hint: 'Think of an uncertain possibility.', hintFr: 'Pense à une possibilité incertaine.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l16-e2', prompt: '___ Sie Fragen haben, fragen Sie bitte an der Rezeption. (condition)', promptFr: '___ Sie Fragen haben, fragen Sie bitte an der Rezeption. (condition)', answer: 'Falls', hint: 'in case …', hintFr: 'au cas où …' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l16-e3', prompt: '___ das Hotel ausgebucht ist, suchen wir eine andere Unterkunft. (known reason)', promptFr: '___ das Hotel ausgebucht ist, suchen wir eine andere Unterkunft. (raison connue)', answer: 'Da', hint: 'a reason everyone can see, verb at the end', hintFr: 'une raison que tout le monde voit, verbe à la fin' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l16-e4', tokens: ['koche', 'Falls', 'Hunger', 'ich', 'du', 'hast', 'Pasta'], answer: ['Falls', 'du', 'Hunger', 'hast', 'koche', 'ich', 'Pasta'], hint: 'Subordinate clause first (verb at the end), then the main clause starts with its verb.', hintFr: 'Subordonnée d’abord (verbe à la fin), puis la principale commence par son verbe.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l16-e5', prompt: 'Bevor die Gäste kommen, ___ ich die Wohnung auf. (aufräumen)', promptFr: 'Bevor die Gäste kommen, ___ ich die Wohnung auf. (aufräumen)', answer: 'räume', hint: 'separable verb: the verb is second, "auf" goes to the end', hintFr: 'verbe séparable : le verbe est en 2e position, « auf » à la fin' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l16-e6', prompt: 'Listen. Who decides quickly?', promptFr: 'Écoute. Qui décide rapidement ?', audio: { ttsText: 'Während Tim lange überlegt, entscheidet Nora sofort.' }, options: ['Nora', 'Tim', 'Both of them'], optionsFr: ['Nora', 'Tim', 'Les deux'], answer: 0, hint: '"sofort" means immediately.', hintFr: '« sofort » signifie tout de suite.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l16-e7', pairs: [ { de: 'falls', en: 'in case / if', fr: 'au cas où / si' }, { de: 'da', en: 'since (reason)', fr: 'puisque (raison)' }, { de: 'bevor', en: 'before', fr: 'avant que' }, { de: 'während', en: 'while', fr: 'pendant que' } ], hint: 'Match each conjunction to its meaning.', hintFr: 'Associe chaque conjonction à son sens.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l16-e8', tokens: ['deckt', 'Bevor', 'Lea', 'kommen', 'die', 'Gäste', 'den', 'Tisch'], answer: ['Bevor', 'die', 'Gäste', 'kommen', 'deckt', 'Lea', 'den', 'Tisch'], hint: 'Clause with "Bevor" first, verb at its end; then "deckt" + subject.', hintFr: 'Proposition en « Bevor » d’abord, verbe à la fin ; puis « deckt » + sujet.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l16-e9', prompt: 'Listen. What should guests do?', promptFr: 'Écoute. Que doivent faire les invités ?', audio: { ttsText: 'Falls Sie eine Allergie haben, sagen Sie es bitte vor dem Essen.' }, options: ['Tell the host about allergies before eating', 'Bring their own food', 'Come earlier'], optionsFr: ['Signaler leurs allergies à l’hôte avant le repas', 'Apporter leur propre repas', 'Venir plus tôt'], answer: 0, hint: 'Listen to what comes after "Falls …".', hintFr: 'Écoute ce qui vient après « Falls … ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l16-e10', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Während ich koche, deckst du den Tisch.', 'Während ich koche, du deckst den Tisch.', 'Während ich kochen, deckst du den Tisch.'], answer: 0, explain: 'The clause comes first, so the main clause starts with the verb: deckst du.', explainFr: 'La subordonnée est en premier, donc la principale commence par le verbe : deckst du.', hint: 'Main clause after a clause: verb first.', hintFr: 'Principale après une subordonnée : verbe en premier.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l16-e11', word: 'Rezeption', answer: 'die', hint: 'nouns ending in -tion are feminine', hintFr: 'les noms en -tion sont féminins' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l16-e12', word: 'Gastgeber', answer: 'der', hint: 'the last part is "Geber" (m)', hintFr: 'la dernière partie est « Geber » (m)' } },

    { kind: 'pronunciation', focus: 'Long "ä" (während) sounds like "ai" in "hair"; "ü" is a rounded "ee" (überlegen, gründlich)', focusFr: '« ä » long (während) sonne comme « è » ; « ü » est un « i » arrondi (überlegen, gründlich)', items: [
      { id: 'b1l16-waehrend-pron', german: 'während', english: 'while / whereas', french: 'pendant que / alors que', gender: null, syllables: ['WÄH', 'rend'], pronunciation: 'VAIR-ent', example: { de: 'Während ich koche, liest du.', en: 'While I cook, you read.', fr: 'Pendant que je cuisine, tu lis.' } },
      { id: 'b1l16-bevor-pron', german: 'bevor', english: 'before', french: 'avant que', gender: null, syllables: ['be', 'FOR'], pronunciation: 'be-FOR', example: { de: 'Bevor wir essen, trinken wir etwas.', en: 'Before we eat, we have a drink.', fr: 'Avant de manger, nous buvons quelque chose.' } },
      { id: 'b1l16-ueberlegen-pron', german: 'überlegen', english: 'to consider', french: 'réfléchir', gender: null, syllables: ['ü', 'ber', 'LE', 'gen'], pronunciation: 'ue-ber-LAY-gen', example: { de: 'Ich muss kurz überlegen.', en: 'I need to think for a moment.', fr: 'Je dois réfléchir un instant.' } },
      { id: 'b1l16-gruendlich-pron', german: 'gründlich', english: 'thorough', french: 'minutieux', gender: null, syllables: ['GRÜND', 'lich'], pronunciation: 'GRUENT-likh', example: { de: 'Sie arbeitet sehr gründlich.', en: 'She works very thoroughly.', fr: 'Elle travaille très minutieusement.' } },
      { id: 'b1l16-rezeption-pron', german: 'Rezeption', english: 'reception desk', french: 'réception', gender: 'die', syllables: ['re', 'zep', 'ZION'], pronunciation: 'ray-tsep-TSYOHN', example: { de: 'Fragen Sie an der Rezeption.', en: 'Ask at the reception desk.', fr: 'Demandez à la réception.' } },
    ] },

    { kind: 'wrapup', summary: 'You now have four new conjunctions, all sending the verb to the **end**: **falls** (a possible condition), **da** (a known reason, often at the start), **bevor** (before) and **während** (while / whereas). When the clause comes **first**, the main clause begins with its **verb**: *Falls du Hunger hast, koche ich.* Perfect for hotels, dinners and decisions. 🎉',
      summaryFr: 'Tu disposes maintenant de quatre nouvelles conjonctions, qui envoient toutes le verbe **à la fin** : **falls** (condition possible), **da** (raison connue, souvent en début de phrase), **bevor** (avant que) et **während** (pendant que / alors que). Quand la proposition vient **en premier**, la principale commence par son **verbe** : *Falls du Hunger hast, koche ich.* Parfait pour les hôtels, les dîners et les décisions. 🎉' },
  ],
};
