import type { Lesson } from '../types';

export const b1lektion21: Lesson = {
  id: 'b1-l21', level: 'B1', module: 3, number: 11,
  title: { de: 'Modalpartikeln und „je … desto“', en: 'Modal particles and "je … desto"', fr: 'Particules modales et « je … desto »' },
  theme: 'Sounding natural: je … desto / umso, and the modal particles denn, doch, eigentlich, ja, mal, eben, halt, aber',
  themeFr: 'Parler naturellement : je … desto / umso et les particules modales denn, doch, eigentlich, ja, mal, eben, halt, aber',
  goals: ['Build "je … desto/umso" sentences, also in the past', 'Understand what modal particles add to the tone', 'Use denn, doch, eigentlich, ja, mal, eben, halt, aber naturally', 'Talk about ageing, generations and childhood memories'],
  goalsFr: ['Construire des phrases « je … desto/umso », aussi au passé', 'Comprendre ce qu’apportent les particules modales au ton', 'Employer naturellement denn, doch, eigentlich, ja, mal, eben, halt, aber', 'Parler du vieillissement, des générations et des souvenirs d’enfance'],
  steps: [
    { kind: 'intro', title: 'Je älter, desto weiser? 🧓', titleFr: 'Plus on vieillit, plus on est sage ? 🧓',
      scene: 'Three generations share a table: grandpa Walter, his daughter Petra and her son Nico. They compare how life changed, tease each other, and every sentence has a little word that changes the mood.',
      sceneFr: 'Trois générations autour d’une table : grand-père Walter, sa fille Petra et son fils Nico. Ils comparent comment la vie a changé, se taquinent, et chaque phrase contient un petit mot qui change l’ambiance.',
      goals: ['Say "the more … the more …" in any tense', 'Decode the tiny words that carry attitude', 'Soften requests and show surprise', 'Share childhood memories'],
      goalsFr: ['Dire « plus … plus … » à tous les temps', 'Décoder les petits mots qui portent une attitude', 'Adoucir des demandes et exprimer la surprise', 'Partager des souvenirs d’enfance'] },

    { kind: 'vocab', item: { id: 'b1l21-alter', german: 'das Alter', english: 'the age / old age', french: 'l’âge / la vieillesse', gender: 'das', syllables: ['AL', 'ter'], pronunciation: 'dahss AHL-ter', example: { de: 'Im Alter wird man oft ruhiger.', en: 'In old age people often become calmer.', fr: 'En vieillissant, on devient souvent plus calme.' } } },
    { kind: 'vocab', item: { id: 'b1l21-kindheit', german: 'die Kindheit', english: 'the childhood', french: 'l’enfance', gender: 'die', syllables: ['KIND', 'heit'], pronunciation: 'dee KINT-hite', example: { de: 'Meine Kindheit war sehr glücklich.', en: 'My childhood was very happy.', fr: 'Mon enfance a été très heureuse.' } } },
    { kind: 'vocab', item: { id: 'b1l21-generation', german: 'die Generation', english: 'the generation', french: 'la génération', gender: 'die', syllables: ['ge', 'ne', 'ra', 'TION'], pronunciation: 'dee geh-neh-rah-TSYOHN', example: { de: 'Drei Generationen leben in diesem Haus.', en: 'Three generations live in this house.', fr: 'Trois générations vivent dans cette maison.' } } },
    { kind: 'vocab', item: { id: 'b1l21-taschengeld', german: 'das Taschengeld', english: 'the pocket money', french: 'l’argent de poche', gender: 'das', syllables: ['TA', 'schen', 'geld'], pronunciation: 'dahss TAH-shen-gelt', example: { de: 'Als Kind bekam ich fünf Euro Taschengeld.', en: 'As a child I got five euros pocket money.', fr: 'Enfant, je recevais cinq euros d’argent de poche.' } } },
    { kind: 'vocab', item: { id: 'b1l21-spielplatz', german: 'der Spielplatz', english: 'the playground', french: 'l’aire de jeux', gender: 'der', syllables: ['SPIEL', 'platz'], pronunciation: 'dair SHPEEL-plahts', example: { de: 'Wir haben jeden Nachmittag auf dem Spielplatz gespielt.', en: 'We played at the playground every afternoon.', fr: 'Nous jouions chaque après-midi sur l’aire de jeux.' } } },
    { kind: 'vocab', item: { id: 'b1l21-aufwachsen', german: 'aufwachsen', english: 'to grow up', french: 'grandir / être élevé', gender: null, syllables: ['AUF', 'wach', 'sen'], pronunciation: 'OWF-vahk-sen', example: { de: 'Ich bin in einem kleinen Dorf aufgewachsen.', en: 'I grew up in a small village.', fr: 'J’ai grandi dans un petit village.' } } },
    { kind: 'vocab', item: { id: 'b1l21-erinnern', german: 'sich erinnern an', english: 'to remember', french: 'se souvenir de', gender: null, syllables: ['sich', 'er', 'IN', 'nern', 'an'], pronunciation: 'zish air-IN-ern ahn', example: { de: 'Ich erinnere mich gern an die Ferien bei Oma.', en: 'I like remembering the holidays at Grandma’s.', fr: 'J’aime me souvenir des vacances chez Mamie.' } } },
    { kind: 'vocab', item: { id: 'b1l21-erwachsen', german: 'erwachsen', english: 'grown-up / adult', french: 'adulte', gender: null, syllables: ['er', 'WACH', 'sen'], pronunciation: 'air-VAHK-sen', example: { de: 'Mit achtzehn ist man erwachsen.', en: 'At eighteen you are an adult.', fr: 'À dix-huit ans, on est adulte.' } } },
    { kind: 'vocab', item: { id: 'b1l21-altmodisch', german: 'altmodisch', english: 'old-fashioned', french: 'démodé', gender: null, syllables: ['ALT', 'mo', 'disch'], pronunciation: 'AHLT-moh-dish', example: { de: 'Opas Hut ist ziemlich altmodisch.', en: 'Grandpa’s hat is rather old-fashioned.', fr: 'Le chapeau de papi est plutôt démodé.' } } },
    { kind: 'vocab', item: { id: 'b1l21-frueher', german: 'früher', english: 'earlier / in the past', french: 'autrefois', gender: null, syllables: ['FRÜ', 'her'], pronunciation: 'FREW-er', example: { de: 'Früher hatten wir kein Internet.', en: 'In the past we had no internet.', fr: 'Autrefois, nous n’avions pas Internet.' } } },
    { kind: 'vocab', item: { id: 'b1l21-eigentlich', german: 'eigentlich', english: 'actually / really', french: 'au fond / en fait', gender: null, syllables: ['EI', 'gent', 'lich'], pronunciation: 'EYE-gent-lish', example: { de: 'Wie alt bist du eigentlich?', en: 'How old are you, actually?', fr: 'Au fait, quel âge as-tu ?' } } },
    { kind: 'vocab', item: { id: 'b1l21-halt', german: 'halt / eben', english: 'simply / just (it can’t be helped)', french: 'tout simplement / c’est comme ça', gender: null, syllables: ['HALT'], pronunciation: 'hahlt / AY-ben', example: { de: 'Das ist halt so, da kann man nichts machen.', en: 'That’s just how it is, you can’t do anything about it.', fr: 'C’est comme ça, on n’y peut rien.' } } },
    { kind: 'vocab', item: { id: 'b1l21-doch', german: 'doch', english: 'but / yes (contradicting) / do', french: 'si / pourtant / donc', gender: null, syllables: ['DOCH'], pronunciation: 'dokh', example: { de: 'Hast du keinen Hunger? – Doch!', en: 'Aren’t you hungry? – Yes, I am!', fr: 'Tu n’as pas faim ? – Si !' } } },

    { kind: 'grammar', note: {
      id: 'b1l21-je-desto', title: 'je … desto / umso in all tenses', titleFr: 'je … desto / umso à tous les temps',
      explanationMd: 'You met **je … desto** in an earlier lesson. Here is the full picture.\n\n- The **je**-clause is a subordinate clause: **verb at the end**.\n- Both parts contain a **comparative** (älter, mehr, länger …).\n- In the **desto**-clause, the comparative comes first, then the **verb in position 2**.\n- **desto** and **umso** mean the same (umso is a bit more common in writing).\n\nThe tense stays the same in both parts — also in the **past**:\n\n- **Je älter** ich **wurde**, **desto** mehr **schätzte** ich meine Großeltern.\n- **Je weniger** Taschengeld er **bekam**, **desto** kreativer **wurde** er.\n\nShort forms are common: **Je früher, desto besser.** · **Umso besser!** (all the better)\n\nWith a noun, the comparative goes in front of it: **Je mehr Zeit** wir hatten, **desto länger** spielten wir draußen.',
      explanationMdFr: 'Tu as déjà rencontré **je … desto** dans une leçon précédente. Voici le tableau complet.\n\n- La proposition **je** est subordonnée : **verbe à la fin**.\n- Les deux parties contiennent un **comparatif** (älter, mehr, länger …).\n- Dans la proposition **desto**, le comparatif vient d’abord, puis le **verbe en position 2**.\n- **desto** et **umso** veulent dire la même chose (umso est un peu plus courant à l’écrit).\n\nLe temps reste le même dans les deux parties — aussi au **passé** :\n\n- **Je älter** ich **wurde**, **desto** mehr **schätzte** ich meine Großeltern.\n- **Je weniger** Taschengeld er **bekam**, **desto** kreativer **wurde** er.\n\nLes formes courtes sont courantes : **Je früher, desto besser.** · **Umso besser !** (tant mieux)\n\nAvec un nom, le comparatif se place devant lui : **Je mehr Zeit** wir hatten, **desto länger** spielten wir draußen.',
      examples: [
        { de: 'Je älter ich wurde, desto mehr interessierte ich mich für Geschichte.', en: 'The older I got, the more interested I became in history.', fr: 'Plus je vieillissais, plus je m’intéressais à l’histoire.' },
        { de: 'Je mehr Zeit wir hatten, desto länger spielten wir draußen.', en: 'The more time we had, the longer we played outside.', fr: 'Plus nous avions de temps, plus nous jouions longtemps dehors.' },
        { de: 'Je früher wir losfahren, umso weniger Verkehr gibt es.', en: 'The earlier we set off, the less traffic there is.', fr: 'Plus nous partons tôt, moins il y a de circulation.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l21-modalpartikeln', title: 'Modal particles: denn, doch, eigentlich, ja', titleFr: 'Particules modales : denn, doch, eigentlich, ja',
      explanationMd: '**Modal particles** are small, **unstressed** words in the middle of a sentence. They do not change the facts — they add **attitude**: curiosity, surprise, impatience, friendliness. They rarely translate word by word.\n\n- **denn** (in questions): friendly interest or impatience. **Wie alt bist du denn?** · Was machst du **denn** da?\n- **doch**: "but, you know": reminder, contradiction or encouragement. **Das weißt du doch!** · **Komm doch mit!**\n- **eigentlich**: "by the way / actually", a softer, more casual question. **Wie alt bist du eigentlich?**\n- **ja**: a fact both know, or surprise. **Das ist ja toll!** · Du kennst **ja** Oma.\n\nThey stand **in the middle field** (after the verb and pronoun subject), never in position 1, and never carry the stress.',
      explanationMdFr: 'Les **particules modales** sont de petits mots **non accentués** au milieu de la phrase. Elles ne changent pas les faits — elles ajoutent une **attitude** : curiosité, surprise, impatience, amabilité. Elles se traduisent rarement mot à mot.\n\n- **denn** (dans les questions) : intérêt amical ou impatience. **Wie alt bist du denn?** · Was machst du **denn** da ?\n- **doch** : « mais tu sais » : rappel, contradiction ou encouragement. **Das weißt du doch!** · **Komm doch mit!**\n- **eigentlich** : « au fait / en fait », une question plus douce et plus décontractée. **Wie alt bist du eigentlich?**\n- **ja** : un fait connu des deux, ou la surprise. **Das ist ja toll!** · Du kennst **ja** Oma.\n\nElles se placent **au milieu de la phrase** (après le verbe et le pronom sujet), jamais en position 1, et ne portent jamais l’accent.',
      examples: [
        { de: 'Wo wohnst du denn jetzt?', en: 'So where do you live now? (friendly interest)', fr: 'Et où habites-tu maintenant ? (intérêt amical)' },
        { de: 'Nimm doch noch ein Stück Kuchen!', en: 'Do have another piece of cake!', fr: 'Reprends donc une part de gâteau !' },
        { de: 'Das ist ja eine Überraschung!', en: 'Well, that’s a surprise!', fr: 'Quelle surprise !' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l21-mal-eben-aber', title: 'mal, eben/halt and aber', titleFr: 'mal, eben/halt et aber',
      explanationMd: 'Three more particles you will hear every day:\n\n- **mal** softens an **imperative or request**: **Komm mal her!** · **Kannst du mir mal helfen?** · **Sag mal, …** It makes the demand friendlier.\n- **eben / halt** show **resignation**: "that’s how it is, nothing to do". **Dann gehen wir eben zu Fuß.** · **Das ist halt so.** (**halt** is more southern/colloquial, **eben** more northern and general.)\n- **aber** (in an exclamation) shows **surprise**: **Du bist aber groß geworden!** · **Das ist aber nett!**\n\n**Careful:** many of these words also exist as normal words: **doch** = "yes" after a negative question (Hast du **keinen** Hunger? – **Doch!**), **aber** = "but", **eben** = "just now". Only the unstressed, mid-sentence use is a modal particle.',
      explanationMdFr: 'Trois autres particules que tu entendras tous les jours :\n\n- **mal** adoucit un **impératif ou une demande** : **Komm mal her!** · **Kannst du mir mal helfen?** · **Sag mal, …** Il rend l’exigence plus amicale.\n- **eben / halt** montrent la **résignation** : « c’est comme ça, on n’y peut rien ». **Dann gehen wir eben zu Fuß.** · **Das ist halt so.** (**halt** est plus sudiste/familier, **eben** plus nordique et général.)\n- **aber** (dans une exclamation) montre la **surprise** : **Du bist aber groß geworden!** · **Das ist aber nett!**\n\n**Attention :** beaucoup de ces mots existent aussi comme mots ordinaires : **doch** = « si » après une question négative (Hast du **keinen** Hunger ? – **Doch !**), **aber** = « mais », **eben** = « à l’instant ». Seul l’emploi non accentué, au milieu de la phrase, est une particule modale.',
      examples: [
        { de: 'Komm mal her und hilf mir kurz!', en: 'Come over here and help me for a moment!', fr: 'Viens ici m’aider un instant !' },
        { de: 'Es regnet. Dann nehmen wir eben den Bus.', en: 'It’s raining. Then we’ll just take the bus.', fr: 'Il pleut. Alors on prend le bus, tant pis.' },
        { de: 'Du hast aber schöne Fotos aus deiner Kindheit!', en: 'You have such lovely photos from your childhood!', fr: 'Tu as de si belles photos de ton enfance !' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l21-e1', prompt: 'Je älter ich werde, ___ ruhiger werde ich. (desto)', promptFr: 'Je älter ich werde, ___ ruhiger werde ich. (desto)', answer: 'desto', hint: 'je … desto + comparative', hintFr: 'je … desto + comparatif' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l21-e2', tokens: ['wurde', 'Je älter', 'ich'], answer: ['Je älter', 'ich', 'wurde'], hint: 'je-clause: the verb goes to the end.', hintFr: 'proposition je : le verbe va à la fin.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l21-e3', prompt: '"Wie heißt du denn?" — What does "denn" add?', promptFr: '« Wie heißt du denn ? » — Qu’apporte « denn » ?', options: ['Friendly interest in the question', 'A time: "then"', 'A negation'], optionsFr: ['Un intérêt amical pour la question', 'Un moment : « alors »', 'Une négation'], answer: 0, explain: 'In questions, "denn" sounds curious or friendly.', explainFr: 'Dans les questions, « denn » sonne curieux ou amical.', hint: 'It changes the tone, not the facts.', hintFr: 'Il change le ton, pas les faits.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l21-e4', pairs: [ { de: 'denn', en: 'friendly curiosity in questions', fr: 'curiosité amicale dans les questions' }, { de: 'mal', en: 'softens a request', fr: 'adoucit une demande' }, { de: 'halt / eben', en: 'it can’t be helped', fr: 'on n’y peut rien' }, { de: 'ja', en: 'known fact or surprise', fr: 'fait connu ou surprise' } ], hint: 'Match each particle to its effect.', hintFr: 'Associe chaque particule à son effet.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l21-e5', prompt: 'Komm ___ her und hilf mir!', promptFr: 'Komm ___ her und hilf mir !', answer: 'mal', hint: 'softens the imperative', hintFr: 'adoucit l’impératif' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l21-e6', prompt: 'Listen. What does the speaker express?', promptFr: 'Écoute. Qu’exprime le locuteur ?', audio: { ttsText: 'Du bist aber groß geworden!' }, options: ['Surprise', 'Anger', 'A question about age'], optionsFr: ['La surprise', 'La colère', 'Une question sur l’âge'], answer: 0, hint: 'It is an exclamation with "aber".', hintFr: 'C’est une exclamation avec « aber ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l21-e7', prompt: 'Es regnet. – Dann nehmen wir ___ den Bus. (resignation)', promptFr: 'Es regnet. – Dann nehmen wir ___ den Bus. (résignation)', options: ['eben', 'denn', 'aber'], answer: 0, explain: '"eben" (or "halt") shows "it can’t be helped".', explainFr: '« eben » (ou « halt ») montre « on n’y peut rien ».', hint: 'Which particle means "then we just…"?', hintFr: 'Quelle particule veut dire « alors on va simplement… » ?' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l21-e8', prompt: 'Wo wohnst du ___ jetzt? (friendly interest)', promptFr: 'Wo wohnst du ___ jetzt ? (intérêt amical)', answer: 'denn', hint: 'the question particle', hintFr: 'la particule des questions' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l21-e9', tokens: ['mehr', 'Je', 'ich', 'lerne', 'desto', 'verstehe', 'ich'], answer: ['Je', 'mehr', 'ich', 'lerne', 'desto', 'verstehe', 'ich'], hint: 'je-clause verb last; in the desto-clause the verb comes second after "desto".', hintFr: 'verbe final dans la proposition je ; dans desto, le verbe vient en deuxième après « desto ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l21-e10', prompt: 'Listen. Where did the children play?', promptFr: 'Écoute. Où jouaient les enfants ?', audio: { ttsText: 'Früher hatten wir kein Handy. Wir haben halt draußen gespielt.' }, options: ['Outside', 'On the phone', 'At the computer'], optionsFr: ['Dehors', 'Sur le téléphone', 'À l’ordinateur'], answer: 0, hint: 'Listen for what they did instead.', hintFr: 'Écoute ce qu’ils faisaient à la place.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l21-e11', prompt: '"Hast du keinen Hunger?" – "___, ich habe Hunger!"', promptFr: '« Hast du keinen Hunger ? » – « ___, ich habe Hunger ! »', options: ['Ja', 'Doch', 'Nein'], answer: 1, explain: '"doch" contradicts a negative question: "Yes, I do!"', explainFr: '« doch » contredit une question négative : « Si, j’en ai ! »', hint: 'You are saying the opposite of the negative question.', hintFr: 'Tu dis le contraire de la question négative.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l21-e12', prompt: 'Complete: "Je älter wir werden, ___ …"', promptFr: 'Complète : « Je älter wir werden, ___ … »', options: ['desto mehr schätzen wir Ruhe', 'desto mehr wir schätzen Ruhe', 'desto wir mehr schätzen Ruhe'], answer: 0, explain: 'After desto + comparative, the verb comes second: desto mehr schätzen wir …', explainFr: 'Après desto + comparatif, le verbe vient en deuxième : desto mehr schätzen wir …', hint: 'Verb in position 2 of the desto-clause.', hintFr: 'Verbe en position 2 dans la proposition desto.' } },

    { kind: 'pronunciation', focus: 'Particles are short and unstressed: say them quickly, without emphasis — but "doch" keeps its back "ch" sound', focusFr: 'Les particules sont courtes et non accentuées : dis-les vite, sans insister — mais « doch » garde son « ch » guttural', items: [
      { id: 'b1l21-mal-pron', german: 'mal', english: 'just / once (softener)', french: 'donc / un peu (adoucisseur)', gender: null, syllables: ['mal'], pronunciation: 'mahl', example: { de: 'Sag mal, was machst du da?', en: 'Tell me, what are you doing there?', fr: 'Dis-moi, que fais-tu là ?' } },
      { id: 'b1l21-ja-pron', german: 'ja', english: 'you know / indeed', french: 'justement / bien sûr', gender: null, syllables: ['ja'], pronunciation: 'yah', example: { de: 'Das ist ja schön!', en: 'Well, that’s nice!', fr: 'Mais c’est joli !' } },
      { id: 'b1l21-denn-pron', german: 'denn', english: 'then / ever (in questions)', french: 'donc (dans les questions)', gender: null, syllables: ['denn'], pronunciation: 'den', example: { de: 'Was ist denn los?', en: 'What’s going on, then?', fr: 'Mais que se passe-t-il ?' } },
      { id: 'b1l21-eben-pron', german: 'eben', english: 'just / precisely', french: 'justement / tout simplement', gender: null, syllables: ['E', 'ben'], pronunciation: 'AY-ben', example: { de: 'Das ist eben so.', en: 'That’s just how it is.', fr: 'C’est comme ça, voilà.' } },
      { id: 'b1l21-aber-pron', german: 'aber', english: 'but / my (surprise)', french: 'mais / alors (surprise)', gender: null, syllables: ['A', 'ber'], pronunciation: 'AH-ber', example: { de: 'Das ist aber lecker!', en: 'Wow, that’s tasty!', fr: 'Mais c’est délicieux !' } },
    ] },

    { kind: 'wrapup', summary: 'You can now say "the more … the more …" with **je … desto/umso** in any tense (verb last in the je-clause, verb second in the desto-clause). You also met the tiny words that make German sound alive: **denn** (curious), **doch** (reminder/contradiction), **eigentlich** (casual), **ja** (known or surprising), **mal** (softer request), **eben/halt** (resignation) and **aber** (surprise). Listen for them — they carry the mood. 🎉',
      summaryFr: 'Tu sais maintenant dire « plus … plus … » avec **je … desto/umso** à tous les temps (verbe final dans la proposition je, verbe en deuxième dans la proposition desto). Tu as aussi découvert les petits mots qui donnent vie à l’allemand : **denn** (curieux), **doch** (rappel/contradiction), **eigentlich** (décontracté), **ja** (connu ou surprenant), **mal** (demande adoucie), **eben/halt** (résignation) et **aber** (surprise). Écoute-les — ils portent l’humeur. 🎉' },
  ],
};
