import type { Lesson } from '../types';

export const b1lektion25: Lesson = {
  id: 'b1-l25', level: 'B1', module: 6, number: 24,
  title: { de: '(An)statt … zu und ohne … zu', en: '"(an)statt … zu" and "ohne … zu"', fr: '« (an)statt … zu » et « ohne … zu »' },
  theme: 'Trends and habits: "(an)statt … zu", "ohne … zu", "(an)statt dass", "ohne dass"',
  themeFr: 'Tendances et habitudes : « (an)statt … zu », « ohne … zu », « (an)statt dass », « ohne dass »',
  goals: ['Say what you do instead of something else', 'Say what you do without doing something', 'Choose between the zu-clause and the dass-clause', 'Agree, disagree or shrug off a trend'],
  goalsFr: ['Dire ce qu’on fait au lieu d’autre chose', 'Dire ce qu’on fait sans faire autre chose', 'Choisir entre la proposition en zu et celle en dass', 'Approuver, contredire ou balayer une tendance'],
  steps: [
    { kind: 'intro', title: 'Statt Auto lieber Rad 🚲', titleFr: 'Plutôt le vélo que la voiture 🚲',
      scene: 'Your city is full of new habits: people cycle instead of driving, they buy second-hand instead of new, and they live greenly without giving up comfort. Let’s talk about trends — and about what happens instead of, or without, something else.',
      sceneFr: 'Ta ville est pleine de nouvelles habitudes : on roule à vélo au lieu de conduire, on achète d’occasion au lieu du neuf, on vit écolo sans renoncer au confort. Parlons de tendances — et de ce qui se passe à la place de quelque chose, ou sans quelque chose.',
      goals: ['Use "(an)statt … zu" and "ohne … zu" (same subject)', 'Use "(an)statt dass" and "ohne dass" (different subjects)', 'Place "zu" correctly with separable verbs', 'Discuss trends and lifestyles'],
      goalsFr: ['Utiliser « (an)statt … zu » et « ohne … zu » (même sujet)', 'Utiliser « (an)statt dass » et « ohne dass » (sujets différents)', 'Placer « zu » correctement avec les verbes séparables', 'Discuter de tendances et de modes de vie'] },

    { kind: 'vocab', item: { id: 'b1l25-anstatt', german: '(an)statt', english: 'instead of', french: 'au lieu de', gender: null, syllables: ['an', 'STATT'], pronunciation: 'ahn-SHTAHT', example: { de: 'Anstatt zu warten, rufe ich an.', en: 'Instead of waiting, I’ll call.', fr: 'Au lieu d’attendre, j’appelle.' } } },
    { kind: 'vocab', item: { id: 'b1l25-ohne', german: 'ohne', english: 'without', french: 'sans', gender: null, syllables: ['OH', 'ne'], pronunciation: 'OH-neh', example: { de: 'Ohne zu fragen, nahm er mein Fahrrad.', en: 'Without asking, he took my bike.', fr: 'Sans demander, il a pris mon vélo.' } } },
    { kind: 'vocab', item: { id: 'b1l25-trend', german: 'der Trend', english: 'the trend', french: 'la tendance', gender: 'der', syllables: ['TREND'], pronunciation: 'dair trent', example: { de: 'Lastenräder sind ein neuer Trend.', en: 'Cargo bikes are a new trend.', fr: 'Les vélos-cargos sont une nouvelle tendance.' } } },
    { kind: 'vocab', item: { id: 'b1l25-angesagt', german: 'angesagt', english: 'trendy / in', french: 'à la mode / tendance', gender: null, syllables: ['AN', 'ge', 'sagt'], pronunciation: 'AHN-ge-zahkt', example: { de: 'Second-Hand-Kleidung ist gerade angesagt.', en: 'Second-hand clothes are in right now.', fr: 'Les vêtements d’occasion sont à la mode en ce moment.' } } },
    { kind: 'vocab', item: { id: 'b1l25-mode', german: 'die Mode', english: 'fashion', french: 'la mode', gender: 'die', syllables: ['MO', 'de'], pronunciation: 'dee MOH-deh', example: { de: 'Mode interessiert mich nicht so sehr.', en: 'Fashion doesn’t interest me that much.', fr: 'La mode ne m’intéresse pas tellement.' } } },
    { kind: 'vocab', item: { id: 'b1l25-lebensstil', german: 'der Lebensstil', english: 'the lifestyle', french: 'le mode de vie', gender: 'der', syllables: ['LE', 'bens', 'stil'], pronunciation: 'dair LAY-bens-shteel', example: { de: 'Ihr Lebensstil ist sehr gesund.', en: 'Her lifestyle is very healthy.', fr: 'Son mode de vie est très sain.' } } },
    { kind: 'vocab', item: { id: 'b1l25-gewohnheit', german: 'die Gewohnheit', english: 'the habit', french: 'l’habitude', gender: 'die', syllables: ['ge', 'WOHN', 'heit'], pronunciation: 'dee ge-VOHN-hite', example: { de: 'Morgens zu joggen ist eine gute Gewohnheit.', en: 'Jogging in the morning is a good habit.', fr: 'Faire son jogging le matin est une bonne habitude.' } } },
    { kind: 'vocab', item: { id: 'b1l25-verzichten', german: 'verzichten (auf)', english: 'to do without', french: 'renoncer (à)', gender: null, syllables: ['ver', 'ZICH', 'ten'], pronunciation: 'fair-TSIKH-ten', example: { de: 'Er verzichtet auf das Auto.', en: 'He does without a car.', fr: 'Il renonce à la voiture.' } } },
    { kind: 'vocab', item: { id: 'b1l25-nachhaltig', german: 'nachhaltig', english: 'sustainable', french: 'durable', gender: null, syllables: ['NACH', 'hal', 'tig'], pronunciation: 'NAKH-hahl-tikh', example: { de: 'Sie kauft nachhaltig ein.', en: 'She shops sustainably.', fr: 'Elle fait ses achats de façon durable.' } } },
    { kind: 'vocab', item: { id: 'b1l25-umweltbewusst', german: 'umweltbewusst', english: 'environmentally conscious', french: 'soucieux de l’environnement', gender: null, syllables: ['UM', 'welt', 'be', 'wusst'], pronunciation: 'OOM-velt-be-voosst', example: { de: 'Wir leben umweltbewusst.', en: 'We live in an environmentally conscious way.', fr: 'Nous vivons en respectant l’environnement.' } } },
    { kind: 'vocab', item: { id: 'b1l25-verbrauch', german: 'der Verbrauch', english: 'consumption', french: 'la consommation', gender: 'der', syllables: ['ver', 'BRAUCH'], pronunciation: 'dair fair-BROWKH', example: { de: 'Der Stromverbrauch sinkt.', en: 'Electricity consumption is falling.', fr: 'La consommation d’électricité baisse.' } } },
    { kind: 'vocab', item: { id: 'b1l25-muell', german: 'der Müll', english: 'waste / rubbish', french: 'les déchets', gender: 'der', syllables: ['MÜLL'], pronunciation: 'dair MUELL', example: { de: 'Wir trennen den Müll sehr genau.', en: 'We separate our waste very carefully.', fr: 'Nous trions nos déchets très soigneusement.' } } },
    { kind: 'vocab', item: { id: 'b1l25-sportart', german: 'die Sportart', english: 'type of sport', french: 'le sport (discipline)', gender: 'die', syllables: ['SPORT', 'art'], pronunciation: 'dee SHPORT-ahrt', example: { de: 'Klettern ist eine beliebte Sportart.', en: 'Climbing is a popular sport.', fr: 'L’escalade est un sport populaire.' } } },

    { kind: 'grammar', note: {
      id: 'b1l25-zu', title: '(an)statt … zu and ohne … zu (same subject)', titleFr: '(an)statt … zu et ohne … zu (même sujet)',
      explanationMd: 'When both parts of the sentence have the **same subject**, use an **infinitive clause** with **zu**. It is separated by a **comma**:\n\n- **(An)statt** … **zu** + infinitive — *instead of* doing something\n- **Ohne** … **zu** + infinitive — *without* doing something\n\n- Er fährt Rad, **anstatt** mit dem Auto **zu fahren**.\n- Sie lebt nachhaltig, **ohne** auf Komfort **zu verzichten**.\n\nWith a **separable verb**, **zu** goes between prefix and verb: **auf**zu**wärmen**, **mit**zu**machen**: Sie geht laufen, ohne sich **aufzuwärmen**.',
      explanationMdFr: 'Quand les deux parties de la phrase ont le **même sujet**, on emploie une **proposition infinitive** avec **zu**, séparée par une **virgule** :\n\n- **(An)statt** … **zu** + infinitif — *au lieu de* faire quelque chose\n- **Ohne** … **zu** + infinitif — *sans* faire quelque chose\n\n- Er fährt Rad, **anstatt** mit dem Auto **zu fahren**.\n- Sie lebt nachhaltig, **ohne** auf Komfort **zu verzichten**.\n\nAvec un **verbe séparable**, **zu** se place entre le préfixe et le verbe : **auf**zu**wärmen**, **mit**zu**machen** : Sie geht laufen, ohne sich **aufzuwärmen**.',
      examples: [
        { de: 'Statt im Stau zu stehen, fährt sie mit dem Rad.', en: 'Instead of standing in traffic, she goes by bike.', fr: 'Au lieu de rester dans les embouteillages, elle y va à vélo.' },
        { de: 'Er kauft ständig neue Kleidung, ohne auf die Umwelt zu achten.', en: 'He constantly buys new clothes without thinking of the environment.', fr: 'Il achète sans cesse de nouveaux vêtements sans penser à l’environnement.' },
        { de: 'Sie geht joggen, ohne sich aufzuwärmen.', en: 'She goes jogging without warming up.', fr: 'Elle va courir sans s’échauffer.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'b1l25-dass', title: '(an)statt dass and ohne dass (different subjects)', titleFr: '(an)statt dass et ohne dass (sujets différents)',
      explanationMd: 'If the two clauses have **different subjects**, the infinitive clause is not possible. Use a full subordinate clause with **dass** — the **verb goes to the end**:\n\n- Mein Sohn fährt mit dem Rad, **anstatt dass** ich ihn mit dem Auto **bringe**.\n- Sie hat das Fahrrad repariert, **ohne dass** ich sie darum **gebeten habe**.\n\nSame subject → **zu** + infinitive. Different subject → **dass**-clause. (With the same subject, a **dass**-clause is possible but sounds heavy.)',
      explanationMdFr: 'Si les deux propositions ont des **sujets différents**, la proposition infinitive est impossible. On utilise une subordonnée complète avec **dass** — le **verbe va à la fin** :\n\n- Mein Sohn fährt mit dem Rad, **anstatt dass** ich ihn mit dem Auto **bringe**.\n- Sie hat das Fahrrad repariert, **ohne dass** ich sie darum **gebeten habe**.\n\nMême sujet → **zu** + infinitif. Sujet différent → proposition en **dass**. (Avec le même sujet, une proposition en **dass** est possible mais lourde.)',
      examples: [
        { de: 'Er verließ die Party, ohne dass es jemand merkte.', en: 'He left the party without anyone noticing.', fr: 'Il a quitté la fête sans que personne ne s’en aperçoive.' },
        { de: 'Er fährt mit dem Rad, statt dass seine Frau ihn abholt.', en: 'He cycles instead of his wife picking him up.', fr: 'Il y va à vélo au lieu que sa femme vienne le chercher.' },
      ],
      diagram: 'satzklammer' } },

    { kind: 'grammar', note: {
      id: 'b1l25-meinung', title: 'Agree, disagree, shrug: talking about trends', titleFr: 'Approuver, contredire, hausser les épaules : parler des tendances',
      explanationMd: 'Useful phrases for discussing habits and trends:\n\n- **Agree:** Da stimme ich dir zu. / Das sehe ich auch so.\n- **Disagree:** Das sehe ich anders. / Da bin ich nicht deiner Meinung.\n- **Ask on:** Und was ist mit …? / Wie meinst du das?\n- **Indifference:** Das ist mir egal. / Mode interessiert mich nicht.\n- **Trendy:** Fahrradfahren ist **in**. / Das ist gerade **angesagt**.',
      explanationMdFr: 'Expressions utiles pour discuter d’habitudes et de tendances :\n\n- **Approuver :** Da stimme ich dir zu. / Das sehe ich auch so.\n- **Contredire :** Das sehe ich anders. / Da bin ich nicht deiner Meinung.\n- **Relancer :** Und was ist mit …? / Wie meinst du das?\n- **Indifférence :** Das ist mir egal. / Mode interessiert mich nicht.\n- **Tendance :** Fahrradfahren ist **in**. / Das ist gerade **angesagt**.',
      examples: [
        { de: 'Fahrradfahren ist in – da stimme ich dir zu.', en: 'Cycling is in – I agree with you.', fr: 'Le vélo est à la mode – je suis d’accord avec toi.' },
        { de: 'Das sehe ich anders. Und was ist mit den langen Wegen?', en: 'I see it differently. And what about the long distances?', fr: 'Je vois ça autrement. Et les longues distances ?' },
      ] } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l25-e1', prompt: 'Er fährt Rad, anstatt mit dem Auto ___ fahren. (infinitive clause)', promptFr: 'Er fährt Rad, anstatt mit dem Auto ___ fahren. (proposition infinitive)', answer: 'zu', hint: '"zu" stands directly before the infinitive', hintFr: '« zu » se place juste avant l’infinitif' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l25-e2', prompt: 'Sie lebt nachhaltig, ___ auf Komfort zu verzichten. (without)', promptFr: 'Sie lebt nachhaltig, ___ auf Komfort zu verzichten. (sans)', answer: 'ohne', hint: 'the word for "without"', hintFr: 'le mot pour « sans »' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l25-e3', prompt: 'Same subject in both clauses — what do you use?', promptFr: 'Même sujet dans les deux propositions — que choisis-tu ?', options: ['ohne dass', 'ohne … zu', 'weil'], optionsFr: ['ohne dass', 'ohne … zu', 'weil'], answer: 1, explain: 'Same subject → infinitive clause with "zu".', explainFr: 'Même sujet → proposition infinitive avec « zu ».', hint: 'Different subject would need "dass".', hintFr: 'Un sujet différent demanderait « dass ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'b1l25-e4', prompt: 'Sie hat das Rad repariert, ohne ___ ich sie darum gebeten habe.', promptFr: 'Sie hat das Rad repariert, ohne ___ ich sie darum gebeten habe.', answer: 'dass', hint: 'different subjects (sie / ich)', hintFr: 'sujets différents (sie / ich)' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'b1l25-e5', tokens: ['fragen', 'Er', 'ohne', 'nimmt', 'zu', 'mein Rad'], answer: ['Er', 'nimmt', 'mein Rad', 'ohne', 'zu', 'fragen'], hint: 'Main clause first, then "ohne zu" + infinitive.', hintFr: 'Proposition principale d’abord, puis « ohne zu » + infinitif.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l25-e6', prompt: 'Sie geht laufen, ohne sich ___.', promptFr: 'Sie geht laufen, ohne sich ___.', options: ['aufzuwärmen', 'zu aufwärmen', 'aufwärmen zu'], optionsFr: ['aufzuwärmen', 'zu aufwärmen', 'aufwärmen zu'], answer: 0, explain: 'With separable verbs, "zu" goes between prefix and stem: auf-zu-wärmen.', explainFr: 'Avec les verbes séparables, « zu » se place entre le préfixe et le radical : auf-zu-wärmen.', hint: 'Where does "zu" go in a separable verb?', hintFr: 'Où va « zu » dans un verbe séparable ?' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'b1l25-e7', pairs: [ { de: 'anstatt … zu', en: 'instead of doing (same subject)', fr: 'au lieu de faire (même sujet)' }, { de: 'ohne … zu', en: 'without doing (same subject)', fr: 'sans faire (même sujet)' }, { de: 'anstatt dass', en: 'instead of (different subject)', fr: 'au lieu que (sujet différent)' }, { de: 'ohne dass', en: 'without (different subject)', fr: 'sans que (sujet différent)' } ], hint: 'Match each structure to its meaning.', hintFr: 'Associe chaque structure à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l25-e8', prompt: 'Listen. What does he do instead of standing in traffic?', promptFr: 'Écoute. Que fait-il au lieu de rester dans les embouteillages ?', audio: { ttsText: 'Er fährt mit dem Rad zur Arbeit, anstatt im Stau zu stehen.' }, options: ['He cycles to work', 'He takes the bus', 'He works from home'], optionsFr: ['Il va au travail à vélo', 'Il prend le bus', 'Il travaille à la maison'], answer: 0, hint: 'Listen before "anstatt".', hintFr: 'Écoute ce qui précède « anstatt ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l25-e9', prompt: 'Mein Sohn fährt mit dem Rad, ___ ich ihn mit dem Auto bringe.', promptFr: 'Mein Sohn fährt mit dem Rad, ___ ich ihn mit dem Auto bringe.', options: ['anstatt zu', 'anstatt dass', 'ohne zu'], answer: 1, explain: 'Different subjects (Sohn / ich) → "anstatt dass" with the verb at the end.', explainFr: 'Sujets différents (Sohn / ich) → « anstatt dass » avec le verbe à la fin.', hint: 'Who does what in each clause?', hintFr: 'Qui fait quoi dans chaque proposition ?' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'b1l25-e10', word: 'Gewohnheit', answer: 'die', hint: 'Words ending in -heit are feminine.', hintFr: 'Les mots en -heit sont féminins.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'b1l25-e11', prompt: 'Which phrase means "That’s trendy right now"?', promptFr: 'Quelle expression signifie « C’est tendance en ce moment » ?', options: ['Das ist mir egal.', 'Das ist gerade angesagt.', 'Das sehe ich anders.'], optionsFr: ['Das ist mir egal.', 'Das ist gerade angesagt.', 'Das sehe ich anders.'], answer: 1, explain: '"angesagt" (or "in") means trendy.', explainFr: '« angesagt » (ou « in ») signifie à la mode.', hint: 'Look for "angesagt" or "in".', hintFr: 'Cherche « angesagt » ou « in ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'b1l25-e12', prompt: 'Listen. What does the speaker think about fashion?', promptFr: 'Écoute. Que pense la personne de la mode ?', audio: { ttsText: 'Ehrlich gesagt ist mir Mode ziemlich egal.' }, options: ['Fashion does not matter to the speaker', 'Fashion is very important', 'The speaker wants to buy new clothes'], optionsFr: ['La mode n’a pas d’importance pour la personne', 'La mode est très importante', 'La personne veut acheter de nouveaux vêtements'], answer: 0, hint: 'Listen to "egal".', hintFr: 'Écoute « egal ».' } },

    { kind: 'pronunciation', focus: 'The "ch" after a/o/u is a rough throat sound (nachhaltig), after i/e a soft hiss (verzichten)', focusFr: 'Le « ch » après a/o/u est un son guttural (nachhaltig), après i/e un sifflement doux (verzichten)', items: [
      { id: 'b1l25-nachhaltig-pron', german: 'nachhaltig', english: 'sustainable', french: 'durable', gender: null, syllables: ['NACH', 'hal', 'tig'], pronunciation: 'NAKH-hahl-tikh', example: { de: 'Nachhaltig leben ist im Trend.', en: 'Living sustainably is trending.', fr: 'Vivre durablement est tendance.' } },
      { id: 'b1l25-verzichten-pron', german: 'verzichten', english: 'to do without', french: 'renoncer', gender: null, syllables: ['ver', 'ZICH', 'ten'], pronunciation: 'fair-TSIKH-ten', example: { de: 'Ich verzichte auf Fleisch.', en: 'I do without meat.', fr: 'Je renonce à la viande.' } },
      { id: 'b1l25-umweltbewusst-pron', german: 'umweltbewusst', english: 'environmentally conscious', french: 'soucieux de l’environnement', gender: null, syllables: ['UM', 'welt', 'be', 'wusst'], pronunciation: 'OOM-velt-be-voosst', example: { de: 'Er ist sehr umweltbewusst.', en: 'He is very environmentally conscious.', fr: 'Il est très soucieux de l’environnement.' } },
      { id: 'b1l25-trend-pron', german: 'der Trend', english: 'the trend', french: 'la tendance', gender: 'der', syllables: ['TREND'], pronunciation: 'dair trent', example: { de: 'Ein neuer Trend beginnt.', en: 'A new trend is starting.', fr: 'Une nouvelle tendance commence.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now say what happens **instead of** or **without** something: **(an)statt … zu** and **ohne … zu** for the same subject (Er fährt Rad, anstatt Auto zu fahren), **(an)statt dass** and **ohne dass** for different subjects. Put **zu** between prefix and verb for separable verbs (aufzuwärmen). 🎉',
      summaryFr: 'Tu sais maintenant dire ce qui se passe **à la place de** ou **sans** quelque chose : **(an)statt … zu** et **ohne … zu** pour le même sujet (Er fährt Rad, anstatt Auto zu fahren), **(an)statt dass** et **ohne dass** pour des sujets différents. Place **zu** entre le préfixe et le verbe pour les verbes séparables (aufzuwärmen). 🎉' },
  ],
};
