import type { Lesson } from '../types';

export const lektion16: Lesson = {
  id: 'l16', level: 'A1', module: 4, number: 14,
  title: { de: 'Regeln und Verbote', en: 'Rules and prohibitions', fr: 'Règles et interdictions' },
  theme: 'Rules and signs with dürfen, müssen and man',
  themeFr: 'Règles et panneaux avec dürfen, müssen et man',
  goals: ['Read and say rules: "Hier darf man nicht …"', 'Use verboten and erlaubt', 'Tell "nicht dürfen" (forbidden) from "nicht müssen" (not necessary)', 'Put the modal in position 2 and the infinitive at the end'],
  goalsFr: ['Lire et dire des règles : « Hier darf man nicht … »', 'Utiliser verboten et erlaubt', 'Distinguer « nicht dürfen » (interdit) de « nicht müssen » (pas nécessaire)', 'Placer le modal en position 2 et l’infinitif à la fin'],
  steps: [
    { kind: 'intro', title: 'Was darf man hier? 🚦', titleFr: 'Qu’a-t-on le droit de faire ici ? 🚦',
      scene: 'Mia is showing her cousin Ben around the town park and the street outside. There are signs everywhere: bicycles, dogs, barbecues and traffic lights. What is allowed and what is forbidden?',
      sceneFr: 'Mia fait découvrir à son cousin Ben le parc de la ville et la rue devant. Il y a des panneaux partout : vélos, chiens, barbecues et feux. Qu’est-ce qui est permis et qu’est-ce qui est interdit ?',
      goals: ['Read signs and rules', 'Say what you may and must do', 'Use "man" for general rules', 'Explain why a rule makes sense'],
      goalsFr: ['Lire des panneaux et des règles', 'Dire ce qu’on a le droit de faire et ce qu’on doit faire', 'Utiliser « man » pour les règles générales', 'Expliquer pourquoi une règle a du sens'] },

    { kind: 'vocab', item: { id: 'l16-regel', german: 'die Regel', english: 'the rule (pl. Regeln)', french: 'la règle (pl. Regeln)', gender: 'die', syllables: ['RE', 'gel'], pronunciation: 'dee RAY-gel', example: { de: 'Im Park gibt es viele Regeln.', en: 'There are many rules in the park.', fr: 'Dans le parc, il y a beaucoup de règles.' } } },
    { kind: 'vocab', item: { id: 'l16-schild', german: 'das Schild', english: 'the sign (pl. Schilder)', french: 'le panneau (pl. Schilder)', gender: 'das', syllables: ['SCHILD'], pronunciation: 'dahss shilt', example: { de: 'Das Schild ist rot.', en: 'The sign is red.', fr: 'Le panneau est rouge.' } } },
    { kind: 'vocab', item: { id: 'l16-verboten', german: 'verboten', english: 'forbidden', french: 'interdit', gender: null, syllables: ['ver', 'BO', 'ten'], pronunciation: 'fair-BOH-ten', example: { de: 'Rauchen ist hier verboten.', en: 'Smoking is forbidden here.', fr: 'Il est interdit de fumer ici.' } } },
    { kind: 'vocab', item: { id: 'l16-erlaubt', german: 'erlaubt', english: 'allowed', french: 'permis / autorisé', gender: null, syllables: ['er', 'LAUBT'], pronunciation: 'er-LOWPT', example: { de: 'Picknicken ist erlaubt.', en: 'Picnicking is allowed.', fr: 'Le pique-nique est autorisé.' } } },
    { kind: 'vocab', item: { id: 'l16-ampel', german: 'die Ampel', english: 'the traffic light (pl. Ampeln)', french: 'le feu de signalisation (pl. Ampeln)', gender: 'die', syllables: ['AM', 'pel'], pronunciation: 'dee AHM-pel', example: { de: 'An der Ampel ist es rot.', en: 'At the traffic light it is red.', fr: 'Au feu, c’est rouge.' } } },
    { kind: 'vocab', item: { id: 'l16-helm', german: 'der Helm', english: 'the helmet (pl. Helme)', french: 'le casque (pl. Helme)', gender: 'der', syllables: ['HELM'], pronunciation: 'dair helm', example: { de: 'Kinder müssen einen Helm haben.', en: 'Children must have a helmet.', fr: 'Les enfants doivent avoir un casque.' } } },
    { kind: 'vocab', item: { id: 'l16-parken', german: 'parken', english: 'to park', french: 'se garer / stationner', gender: null, syllables: ['PAR', 'ken'], pronunciation: 'PAR-ken', example: { de: 'Hier darf man nicht parken.', en: 'You may not park here.', fr: 'On n’a pas le droit de se garer ici.' } } },
    { kind: 'vocab', item: { id: 'l16-rauchen', german: 'rauchen', english: 'to smoke', french: 'fumer', gender: null, syllables: ['RAU', 'chen'], pronunciation: 'ROW-khen', example: { de: 'Im Bus darf man nicht rauchen.', en: 'You may not smoke on the bus.', fr: 'On n’a pas le droit de fumer dans le bus.' } } },
    { kind: 'vocab', item: { id: 'l16-warten', german: 'warten', english: 'to wait', french: 'attendre', gender: null, syllables: ['WAR', 'ten'], pronunciation: 'VAR-ten', example: { de: 'Bei Rot müssen wir warten.', en: 'At red we have to wait.', fr: 'Au rouge, nous devons attendre.' } } },
    { kind: 'vocab', item: { id: 'l16-hund', german: 'der Hund', english: 'the dog (pl. Hunde)', french: 'le chien (pl. Hunde)', gender: 'der', syllables: ['HUND'], pronunciation: 'dair hoont', example: { de: 'Der Hund ist freundlich.', en: 'The dog is friendly.', fr: 'Le chien est gentil.' } } },
    { kind: 'vocab', item: { id: 'l16-leine', german: 'die Leine', english: 'the leash', french: 'la laisse', gender: 'die', syllables: ['LEI', 'ne'], pronunciation: 'dee LIE-ne', example: { de: 'Der Hund ist an der Leine.', en: 'The dog is on the leash.', fr: 'Le chien est en laisse.' } } },
    { kind: 'vocab', item: { id: 'l16-wiese', german: 'die Wiese', english: 'the meadow / lawn', french: 'la pelouse / le pré', gender: 'die', syllables: ['WIE', 'se'], pronunciation: 'dee VEE-ze', example: { de: 'Auf der Wiese darf man liegen.', en: 'You may lie on the lawn.', fr: 'On a le droit de s’allonger sur la pelouse.' } } },
    { kind: 'vocab', item: { id: 'l16-gefaehrlich', german: 'gefährlich', english: 'dangerous', french: 'dangereux', gender: null, syllables: ['ge', 'FÄHR', 'lich'], pronunciation: 'ge-FAIR-likh', example: { de: 'Die Straße ist gefährlich.', en: 'The street is dangerous.', fr: 'La rue est dangereuse.' } } },
    { kind: 'vocab', item: { id: 'l16-man', german: 'man', english: 'one / you / people (in general)', french: 'on', gender: null, syllables: ['MAN'], pronunciation: 'mahn', example: { de: 'Hier darf man nicht laut sein.', en: 'You must not be loud here.', fr: 'On n’a pas le droit d’être bruyant ici.' } } },

    { kind: 'grammar', note: {
      id: 'l16-konjugation', title: 'dürfen and müssen: all forms', titleFr: 'dürfen et müssen : toutes les formes',
      explanationMd: 'You know **ich** and **du**. Here are all persons. Notice: the singular has a **different stem** from the plural (**darf-** / **dürf-**, **muss-** / **müss-**), and **ich** and **er/sie/es/man** look the same:\n\n- ich **darf** / **muss**\n- du **darfst** / **musst**\n- er / sie / es / **man**: **darf** / **muss**\n- wir **dürfen** / **müssen**\n- ihr **dürft** / **müsst**\n- sie / Sie **dürfen** / **müssen**\n\n**man** (one, people in general) takes the **er/sie/es** form and is perfect for rules: Hier **darf man** nicht parken.',
      explanationMdFr: 'Tu connais **ich** et **du**. Voici toutes les personnes. Remarque : le singulier a un **radical différent** du pluriel (**darf-** / **dürf-**, **muss-** / **müss-**), et **ich** et **er/sie/es/man** sont identiques :\n\n- ich **darf** / **muss**\n- du **darfst** / **musst**\n- er / sie / es / **man**: **darf** / **muss**\n- wir **dürfen** / **müssen**\n- ihr **dürft** / **müsst**\n- sie / Sie **dürfen** / **müssen**\n\n**man** (on) prend la forme **er/sie/es** et convient parfaitement aux règles : Hier **darf man** nicht parken.',
      examples: [
        { de: 'Ihr dürft hier nicht spielen.', en: 'You (pl.) may not play here.', fr: 'Vous n’avez pas le droit de jouer ici.' },
        { de: 'Wir müssen an der Ampel warten.', en: 'We have to wait at the traffic light.', fr: 'Nous devons attendre au feu.' },
        { de: 'Darf man hier Fahrrad fahren?', en: 'Is one allowed to cycle here?', fr: 'A-t-on le droit de faire du vélo ici ?' },
      ],
      diagram: 'conjugation-table' } },

    { kind: 'grammar', note: {
      id: 'l16-verbot-pflicht', title: 'Forbidden or not necessary? nicht dürfen vs nicht müssen', titleFr: 'Interdit ou pas nécessaire ? nicht dürfen / nicht müssen',
      explanationMd: 'Careful — the two negations mean **very different** things:\n\n- **nicht dürfen** = it is **forbidden**: Hier **darf** man **nicht** parken. (= Parken ist **verboten**.)\n- **nicht müssen** = it is **not necessary** (you may, but you do not have to): Du **musst nicht** kommen. (= You can stay at home.)\n\nTwo useful adjectives: **verboten** (forbidden) and **erlaubt** (allowed). They follow **sein**: Rauchen **ist verboten**. Picknicken **ist erlaubt**.\n\nExplain a rule with a short sentence: Das ist gefährlich. Das ist laut.',
      explanationMdFr: 'Attention — les deux négations ont des sens **très différents** :\n\n- **nicht dürfen** = c’est **interdit** : Hier **darf** man **nicht** parken. (= Parken ist **verboten**.)\n- **nicht müssen** = ce n’est **pas nécessaire** (tu peux, mais tu n’y es pas obligé) : Du **musst nicht** kommen. (= Tu peux rester chez toi.)\n\nDeux adjectifs utiles : **verboten** (interdit) et **erlaubt** (permis). Ils s’emploient avec **sein** : Rauchen **ist verboten**. Picknicken **ist erlaubt**.\n\nPour expliquer une règle, une courte phrase suffit : Das ist gefährlich. Das ist laut.',
      examples: [
        { de: 'Hunde dürfen nicht auf die Wiese.', en: 'Dogs are not allowed on the lawn.', fr: 'Les chiens n’ont pas le droit d’aller sur la pelouse.' },
        { de: 'Du musst nicht warten, die Ampel ist grün.', en: 'You do not have to wait, the light is green.', fr: 'Tu n’as pas besoin d’attendre, le feu est vert.' },
        { de: 'Parken ist hier verboten, das ist gefährlich.', en: 'Parking is forbidden here, it is dangerous.', fr: 'Le stationnement est interdit ici, c’est dangereux.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l16-satzklammer-regeln', title: 'Modal verb in position 2, infinitive at the end', titleFr: 'Le modal en position 2, l’infinitif à la fin',
      explanationMd: 'The modal verb is the **conjugated** verb, so it stands in **position 2**. The second verb stays in the **infinitive** and goes to the **very end**. **nicht** comes just before it:\n\n- Man **darf** hier **parken**.\n- Man **darf** hier **nicht parken**.\n- **Hier** **darf** man nicht **parken**. (time/place first → the subject follows the verb)\n- **Darf** man hier **parken**? (question: modal first)\n\nYou can leave out the movement verb when it is obvious: Hunde **dürfen nicht** auf die Wiese.',
      explanationMdFr: 'Le verbe modal est le verbe **conjugué**, il est donc en **position 2**. Le deuxième verbe reste à l’**infinitif** et va **tout à la fin**. **nicht** se place juste avant :\n\n- Man **darf** hier **parken**.\n- Man **darf** hier **nicht parken**.\n- **Hier** **darf** man nicht **parken**. (lieu/temps en tête → le sujet suit le verbe)\n- **Darf** man hier **parken** ? (question : le modal en premier)\n\nOn peut omettre le verbe de mouvement quand c’est évident : Hunde **dürfen nicht** auf die Wiese.',
      examples: [
        { de: 'Bei Rot müssen Autos warten.', en: 'At red, cars have to wait.', fr: 'Au rouge, les voitures doivent attendre.' },
        { de: 'Im Park darf man nicht laut Musik hören.', en: 'You may not listen to loud music in the park.', fr: 'Dans le parc, on n’a pas le droit d’écouter de la musique fort.' },
        { de: 'Darf ich hier mein Fahrrad parken?', en: 'May I park my bike here?', fr: 'Puis-je garer mon vélo ici ?' },
      ],
      diagram: 'satzklammer' } },

    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l16-e1', prompt: 'Hier ___ man nicht parken. (dürfen)', promptFr: 'Hier ___ man nicht parken. (dürfen)', answer: 'darf', hint: '"man" takes the same form as "er/sie/es".', hintFr: '« man » prend la même forme que « er/sie/es ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l16-e2', prompt: 'Wir ___ an der Ampel warten. (müssen)', promptFr: 'Wir ___ an der Ampel warten. (müssen)', answer: 'müssen', hint: 'wir → same as the infinitive.', hintFr: 'wir → comme l’infinitif.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l16-e3', prompt: 'A sign says "Rauchen verboten". What does it mean?', promptFr: 'Un panneau indique « Rauchen verboten ». Que signifie-t-il ?', options: ['You may not smoke here.', 'You must smoke here.', 'You may smoke here.'], optionsFr: ['Il est interdit de fumer ici.', 'Il faut fumer ici.', 'On peut fumer ici.'], answer: 0, explain: '"verboten" = forbidden.', explainFr: '« verboten » = interdit.', hint: '"verboten" is the opposite of "erlaubt".', hintFr: '« verboten » est le contraire de « erlaubt ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l16-e4', prompt: 'What does "Du musst nicht kommen" mean?', promptFr: 'Que signifie « Du musst nicht kommen » ?', options: ['You are not allowed to come.', 'You do not have to come.', 'You must come.'], optionsFr: ['Tu n’as pas le droit de venir.', 'Tu n’es pas obligé de venir.', 'Tu dois venir.'], answer: 1, explain: '"nicht müssen" = not necessary. "nicht dürfen" would mean forbidden.', explainFr: '« nicht müssen » = pas nécessaire. « nicht dürfen » signifierait interdit.', hint: 'Is it forbidden, or just not necessary?', hintFr: 'Est-ce interdit, ou simplement pas nécessaire ?' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l16-e5', tokens: ['man', 'darf', 'nicht', 'Hier', 'parken'], answer: ['Hier', 'darf', 'man', 'nicht', 'parken'], hint: 'Hier (pos. 1), modal (pos. 2), man, nicht, infinitive at the end.', hintFr: 'Hier (pos. 1), modal (pos. 2), man, nicht, infinitif à la fin.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l16-e6', pairs: [ { de: 'verboten', en: 'forbidden', fr: 'interdit' }, { de: 'erlaubt', en: 'allowed', fr: 'permis' }, { de: 'gefährlich', en: 'dangerous', fr: 'dangereux' }, { de: 'die Regel', en: 'the rule', fr: 'la règle' } ], hint: 'Match each word to its meaning.', hintFr: 'Associe chaque mot à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l16-e7', prompt: 'Listen. Where must dogs be in the park?', promptFr: 'Écoute. Où les chiens doivent-ils être dans le parc ?', audio: { ttsText: 'Im Park müssen Hunde an der Leine sein. Auf der Wiese dürfen sie nicht laufen.' }, options: ['On a leash', 'On the lawn', 'At home'], optionsFr: ['En laisse', 'Sur la pelouse', 'À la maison'], answer: 0, hint: 'Listen for "müssen" and the word after "an der".', hintFr: 'Écoute « müssen » et le mot après « an der ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l16-e8', prompt: 'Ihr ___ hier nicht spielen. (dürfen)', promptFr: 'Ihr ___ hier nicht spielen. (dürfen)', answer: 'dürft', hint: 'ihr → stem dürf- + t', hintFr: 'ihr → radical dürf- + t' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l16-e9', prompt: 'Listen. When may the cars drive?', promptFr: 'Écoute. Quand les voitures peuvent-elles rouler ?', audio: { ttsText: 'Bei Rot müssen Autos warten. Bei Grün dürfen sie fahren.' }, options: ['At red', 'At green', 'Never'], optionsFr: ['Au rouge', 'Au vert', 'Jamais'], answer: 1, hint: 'Listen for "dürfen".', hintFr: 'Écoute « dürfen ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l16-e10', prompt: 'Which sentence has the correct word order?', promptFr: 'Quelle phrase a le bon ordre des mots ?', options: ['Man darf hier rauchen nicht.', 'Man darf hier nicht rauchen.', 'Man hier darf nicht rauchen.'], answer: 1, explain: 'Modal in position 2, "nicht" and the infinitive at the end.', explainFr: 'Modal en position 2, « nicht » et l’infinitif à la fin.', hint: 'The infinitive is the very last word.', hintFr: 'L’infinitif est le tout dernier mot.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l16-e11', word: 'Regel', answer: 'die', hint: 'Plural: die Regeln — it is feminine.', hintFr: 'Pluriel : die Regeln — c’est un féminin.' } },

    { kind: 'pronunciation', focus: 'The ü in dürfen/müssen and the long e in verboten, erlaubt: lips rounded for ü', focusFr: 'Le ü dans dürfen/müssen et les mots verboten, erlaubt : lèvres arrondies pour ü', items: [
      { id: 'l16-duerfen-pron', german: 'dürfen', english: 'to be allowed to', french: 'avoir le droit de', gender: null, syllables: ['DÜR', 'fen'], pronunciation: 'DUER-fen', example: { de: 'Hier dürfen wir spielen.', en: 'We may play here.', fr: 'Ici, nous avons le droit de jouer.' } },
      { id: 'l16-muessen-pron', german: 'müssen', english: 'to have to', french: 'devoir', gender: null, syllables: ['MÜS', 'sen'], pronunciation: 'MUES-sen', example: { de: 'Wir müssen warten.', en: 'We have to wait.', fr: 'Nous devons attendre.' } },
      { id: 'l16-verboten-pron', german: 'verboten', english: 'forbidden', french: 'interdit', gender: null, syllables: ['ver', 'BO', 'ten'], pronunciation: 'fair-BOH-ten', example: { de: 'Das ist verboten!', en: 'That is forbidden!', fr: 'C’est interdit !' } },
      { id: 'l16-erlaubt-pron', german: 'erlaubt', english: 'allowed', french: 'permis', gender: null, syllables: ['er', 'LAUBT'], pronunciation: 'er-LOWPT', example: { de: 'Ist das erlaubt?', en: 'Is that allowed?', fr: 'Est-ce permis ?' } },
      { id: 'l16-gefaehrlich-pron', german: 'gefährlich', english: 'dangerous', french: 'dangereux', gender: null, syllables: ['ge', 'FÄHR', 'lich'], pronunciation: 'ge-FAIR-likh', example: { de: 'Das ist zu gefährlich.', en: 'That is too dangerous.', fr: 'C’est trop dangereux.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now read and state rules. **dürfen** and **müssen** have a singular stem (**darf / muss**) and a plural stem (**dürfen / müssen**); **man** takes the **er/sie/es** form. **nicht dürfen** = **verboten**, but **nicht müssen** = not necessary! The modal is in **position 2**, the infinitive at the **end**: **Hier darf man nicht parken.** 🎉',
      summaryFr: 'Tu sais maintenant lire et énoncer des règles. **dürfen** et **müssen** ont un radical au singulier (**darf / muss**) et un autre au pluriel (**dürfen / müssen**) ; **man** prend la forme **er/sie/es**. **nicht dürfen** = **verboten**, mais **nicht müssen** = pas nécessaire ! Le modal est en **position 2**, l’infinitif à la **fin** : **Hier darf man nicht parken.** 🎉' },
  ],
};
