import type { Lesson } from '../types';

export const lektion18: Lesson = {
  id: 'l18', level: 'A1', module: 5, number: 17,
  title: { de: 'Feste, Ferien und „denn“', en: 'Holidays, events and "denn"', fr: 'Fêtes, vacances et « denn »' },
  theme: 'Holidays, festivals and giving reasons with "denn"',
  themeFr: 'Vacances, fêtes et raisons avec « denn »',
  goals: ['Talk about when with vor / nach / in + dative', 'Talk about how long with für + accusative', 'Give a reason with "denn"', 'Describe a holiday with war / hatte', 'Name seasons, holidays and holiday things'],
  goalsFr: ['Dire quand avec vor / nach / in + datif', 'Dire combien de temps avec für + accusatif', 'Donner une raison avec « denn »', 'Décrire des vacances avec war / hatte', 'Nommer les saisons, les fêtes et les objets de vacances'],
  steps: [
    { kind: 'intro', title: 'Endlich Ferien! 🏖️', titleFr: 'Enfin les vacances ! 🏖️',
      scene: 'Mia and Jonas plan a trip to the sea. When do they leave? How long do they stay? And why is the suitcase still empty?', sceneFr: 'Mia et Jonas organisent un voyage à la mer. Quand partent-ils ? Combien de temps restent-ils ? Et pourquoi la valise est-elle encore vide ?',
      goals: ['Say "in einer Woche", "vor drei Tagen", "für zwei Wochen"', 'Say why with "denn"', 'Tell about a past holiday: "Es war schön."', 'Learn holiday and season words'],
      goalsFr: ['Dire « in einer Woche », « vor drei Tagen », « für zwei Wochen »', 'Dire pourquoi avec « denn »', 'Raconter des vacances passées : « Es war schön. »', 'Apprendre le vocabulaire des vacances et des saisons'] },

    { kind: 'vocab', item: { id: 'l18-ferien', german: 'die Ferien (Pl.)', english: 'the holidays / school break', french: 'les vacances', gender: 'die', syllables: ['FE', 'ri', 'en'], pronunciation: 'dee FAY-ree-en', example: { de: 'Die Ferien beginnen bald.', en: 'The holidays start soon.', fr: 'Les vacances commencent bientôt.' } } },
    { kind: 'vocab', item: { id: 'l18-urlaub', german: 'der Urlaub', english: 'the vacation (from work)', french: 'les congés / le séjour de vacances', gender: 'der', syllables: ['UR', 'laub'], pronunciation: 'dair OOR-lowp', example: { de: 'Mein Urlaub ist kurz.', en: 'My vacation is short.', fr: 'Mes congés sont courts.' } } },
    { kind: 'vocab', item: { id: 'l18-fest', german: 'das Fest', english: 'the party / festival', french: 'la fête', gender: 'das', syllables: ['FEST'], pronunciation: 'dahs fest', example: { de: 'Das Fest ist am Samstag.', en: 'The party is on Saturday.', fr: 'La fête a lieu samedi.' } } },
    { kind: 'vocab', item: { id: 'l18-feiertag', german: 'der Feiertag', english: 'the public holiday', french: 'le jour férié', gender: 'der', syllables: ['FEI', 'er', 'tag'], pronunciation: 'dair FY-er-tahk', example: { de: 'Montag ist ein Feiertag.', en: 'Monday is a public holiday.', fr: 'Lundi est un jour férié.' } } },
    { kind: 'vocab', item: { id: 'l18-weihnachten', german: 'Weihnachten', english: 'Christmas', french: 'Noël', gender: null, syllables: ['WEIH', 'nach', 'ten'], pronunciation: 'VY-nakh-ten', example: { de: 'Zu Weihnachten kochen wir viel.', en: 'At Christmas we cook a lot.', fr: 'À Noël, nous cuisinons beaucoup.' } } },
    { kind: 'vocab', item: { id: 'l18-fruehling', german: 'der Frühling', english: 'spring', french: 'le printemps', gender: 'der', syllables: ['FRÜH', 'ling'], pronunciation: 'dair FREW-ling', example: { de: 'Im Frühling ist es schön.', en: 'In spring it is lovely.', fr: 'Au printemps, c’est beau.' } } },
    { kind: 'vocab', item: { id: 'l18-herbst', german: 'der Herbst', english: 'autumn / fall', french: 'l’automne', gender: 'der', syllables: ['HERBST'], pronunciation: 'dair hairpst', example: { de: 'Im Herbst regnet es oft.', en: 'In autumn it often rains.', fr: 'En automne, il pleut souvent.' } } },
    { kind: 'vocab', item: { id: 'l18-woche', german: 'die Woche', english: 'the week', french: 'la semaine', gender: 'die', syllables: ['WO', 'che'], pronunciation: 'dee VOKH-eh', example: { de: 'Eine Woche hat sieben Tage.', en: 'A week has seven days.', fr: 'Une semaine a sept jours.' } } },
    { kind: 'vocab', item: { id: 'l18-strand', german: 'der Strand', english: 'the beach', french: 'la plage', gender: 'der', syllables: ['STRAND'], pronunciation: 'dair shtrahnt', example: { de: 'Der Strand ist sehr schön.', en: 'The beach is very beautiful.', fr: 'La plage est très belle.' } } },
    { kind: 'vocab', item: { id: 'l18-meer', german: 'das Meer', english: 'the sea', french: 'la mer', gender: 'das', syllables: ['MEER'], pronunciation: 'dahs mair', example: { de: 'Das Meer ist heute warm.', en: 'The sea is warm today.', fr: 'La mer est chaude aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'l18-koffer', german: 'der Koffer', english: 'the suitcase', french: 'la valise', gender: 'der', syllables: ['KOF', 'fer'], pronunciation: 'dair KOF-fer', example: { de: 'Mein Koffer ist schwer.', en: 'My suitcase is heavy.', fr: 'Ma valise est lourde.' } } },
    { kind: 'vocab', item: { id: 'l18-sonnig', german: 'sonnig', english: 'sunny', french: 'ensoleillé', gender: null, syllables: ['SON', 'nig'], pronunciation: 'ZON-nikh', example: { de: 'Heute ist es sonnig.', en: 'Today it is sunny.', fr: 'Aujourd’hui, il fait soleil.' } } },
    { kind: 'vocab', item: { id: 'l18-windig', german: 'windig', english: 'windy', french: 'venteux', gender: null, syllables: ['WIN', 'dig'], pronunciation: 'VIN-dikh', example: { de: 'Am Meer ist es oft windig.', en: 'By the sea it is often windy.', fr: 'Au bord de la mer, il y a souvent du vent.' } } },
    { kind: 'vocab', item: { id: 'l18-denn', german: 'denn', english: 'because / for (gives a reason)', french: 'car / parce que', gender: null, syllables: ['DENN'], pronunciation: 'den', example: { de: 'Ich bleibe hier, denn ich bin müde.', en: 'I am staying here, because I am tired.', fr: 'Je reste ici, car je suis fatigué.' } } },

    { kind: 'grammar', note: {
      id: 'l18-zeit-praepositionen', title: 'Time with vor / nach / in + dative, für + accusative', titleFr: 'Le temps avec vor / nach / in + datif, für + accusatif',
      explanationMd: 'Four little words answer **"When?"** and **"How long?"**:\n\n- **vor** + dative = before / **ago**: vor drei Tagen (three days ago)\n- **nach** + dative = **after**: nach dem Urlaub (after the vacation)\n- **in** + dative = **in (from now)**: in einer Woche (in a week)\n- **für** + accusative = **for** (a planned length of time): für zwei Wochen\n\nDative articles: **dem** (der/das-words), **der** (die-words), and plural nouns add **-n**: vor drei Tage**n**.\n\n- vor **dem** Fest · vor **der** Reise · vor drei Tage**n**\n- in **einer** Woche · in **einem** Monat',
      explanationMdFr: 'Quatre petits mots répondent à **« Quand ? »** et **« Combien de temps ? »** :\n\n- **vor** + datif = avant / **il y a** : vor drei Tagen (il y a trois jours)\n- **nach** + datif = **après** : nach dem Urlaub (après les vacances)\n- **in** + datif = **dans** (à partir de maintenant) : in einer Woche (dans une semaine)\n- **für** + accusatif = **pour** (une durée prévue) : für zwei Wochen\n\nArticles au datif : **dem** (mots en der/das), **der** (mots en die), et les noms au pluriel prennent **-n** : vor drei Tage**n**.\n\n- vor **dem** Fest · vor **der** Reise · vor drei Tage**n**\n- in **einer** Woche · in **einem** Monat',
      examples: [
        { de: 'Die Ferien beginnen in einer Woche.', en: 'The holidays start in a week.', fr: 'Les vacances commencent dans une semaine.' },
        { de: 'Vor drei Tagen war das Wetter schön.', en: 'Three days ago the weather was nice.', fr: 'Il y a trois jours, il faisait beau.' },
        { de: 'Wir bleiben für zwei Wochen in Italien.', en: 'We are staying in Italy for two weeks.', fr: 'Nous restons deux semaines en Italie.' },
        { de: 'Nach dem Urlaub bin ich müde.', en: 'After the vacation I am tired.', fr: 'Après les vacances, je suis fatigué.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l18-denn', title: 'Giving a reason with "denn"', titleFr: 'Donner une raison avec « denn »',
      explanationMd: '**denn** = "because / for". It joins two main clauses and gives the **reason**. The good news: **denn does not change the word order**. The verb stays in second position as usual!\n\n- Ich bleibe zu Hause**,** **denn** es regnet.\n- Wir bleiben zu Hause**,** **denn** der Koffer ist kaputt.\n\nPut a **comma** before denn. After denn, the next clause is a normal sentence: **denn** morgen **fahren** wir (verb 2nd).\n\nAnswer "Warum …?" with denn when you talk to friends.',
      explanationMdFr: '**denn** = « car ». Il relie deux propositions principales et donne la **raison**. Bonne nouvelle : **denn ne change pas l’ordre des mots**. Le verbe reste en deuxième position comme d’habitude !\n\n- Ich bleibe zu Hause**,** **denn** es regnet.\n- Wir bleiben zu Hause**,** **denn** der Koffer ist kaputt.\n\nMets une **virgule** avant denn. Après denn, la proposition suivante est une phrase normale : **denn** morgen **fahren** wir (verbe en 2e).\n\nRéponds à « Warum …? » avec denn entre amis.',
      examples: [
        { de: 'Ich mag den Sommer, denn die Sonne scheint lange.', en: 'I like summer, because the sun shines for a long time.', fr: 'J’aime l’été, car le soleil brille longtemps.' },
        { de: 'Wir bleiben im Hotel, denn es ist windig und kalt.', en: 'We are staying in the hotel because it is windy and cold.', fr: 'Nous restons à l’hôtel, car il y a du vent et il fait froid.' },
        { de: 'Ich packe den Koffer, denn morgen fahren wir.', en: 'I am packing the suitcase because we leave tomorrow.', fr: 'Je fais la valise, car nous partons demain.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l18-war-hatte', title: 'Telling about a holiday: war and hatte', titleFr: 'Raconter des vacances : war et hatte',
      explanationMd: 'To tell about a past holiday, use the past forms of **sein** and **haben**:\n\n- **war**: ich war · du warst · er/sie/es war · wir waren · ihr wart · sie/Sie waren\n- **hatte**: ich hatte · du hattest · er/sie/es hatte · wir hatten · ihr hattet · sie/Sie hatten\n\nNotice that **ich** and **er/sie/es** have the same form (war / hatte).\n\nThey are perfect for weather and feelings: Es **war** sonnig. Wir **hatten** Glück.',
      explanationMdFr: 'Pour raconter des vacances passées, utilise le passé de **sein** et de **haben** :\n\n- **war** : ich war · du warst · er/sie/es war · wir waren · ihr wart · sie/Sie waren\n- **hatte** : ich hatte · du hattest · er/sie/es hatte · wir hatten · ihr hattet · sie/Sie hatten\n\nRemarque : **ich** et **er/sie/es** ont la même forme (war / hatte).\n\nIdéal pour la météo et les sentiments : Es **war** sonnig. Wir **hatten** Glück.',
      examples: [
        { de: 'Der Urlaub war schön, aber das Wetter war schlecht.', en: 'The vacation was nice, but the weather was bad.', fr: 'Les vacances étaient belles, mais le temps était mauvais.' },
        { de: 'Wir waren zwei Wochen am Meer.', en: 'We were at the sea for two weeks.', fr: 'Nous avons passé deux semaines à la mer.' },
        { de: 'Im Hotel hatten wir ein großes Zimmer.', en: 'In the hotel we had a big room.', fr: 'À l’hôtel, nous avions une grande chambre.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l18-e1', prompt: 'How do you say "three days ago"?', promptFr: 'Comment dit-on « il y a trois jours » ?', options: ['in drei Tagen', 'vor drei Tagen', 'für drei Tage'], answer: 1, explain: '"vor" + dative looks back in time: vor drei Tagen.', explainFr: '« vor » + datif regarde en arrière : vor drei Tagen.', hint: 'You are looking back, not forward.', hintFr: 'Tu regardes en arrière, pas vers l’avenir.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l18-e2', prompt: 'Die Ferien beginnen ___ einer Woche. (in a week)', promptFr: 'Die Ferien beginnen ___ einer Woche. (dans une semaine)', answer: 'in', hint: 'Time from now: in + dative', hintFr: 'Temps à partir de maintenant : in + datif' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l18-e3', prompt: 'Wir bleiben ___ zwei Wochen in Italien. (for two weeks)', promptFr: 'Wir bleiben ___ zwei Wochen in Italien. (pendant deux semaines)', answer: 'für', hint: 'A planned duration takes "für".', hintFr: 'Une durée prévue s’exprime avec « für ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l18-e4', prompt: 'Complete: "Nach ___ Urlaub bin ich müde."', promptFr: 'Complète : « Nach ___ Urlaub bin ich müde. »', options: ['dem', 'den', 'der'], answer: 0, explain: '"der Urlaub" is masculine, so nach + dative gives "dem".', explainFr: '« der Urlaub » est masculin ; nach + datif donne « dem ».', hint: 'Dative of der-words: dem.', hintFr: 'Datif des mots en der : dem.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l18-e5', pairs: [ { de: 'in einer Woche', en: 'in a week (future)', fr: 'dans une semaine' }, { de: 'vor einer Woche', en: 'a week ago', fr: 'il y a une semaine' }, { de: 'für eine Woche', en: 'for one week', fr: 'pour une semaine' }, { de: 'nach einer Woche', en: 'after one week', fr: 'après une semaine' } ], hint: 'Match each time phrase with its meaning.', hintFr: 'Associe chaque expression de temps à son sens.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l18-e6', tokens: ['denn', 'es', 'regnet', 'Ich', 'bleibe', 'zu', 'Hause,'], answer: ['Ich', 'bleibe', 'zu', 'Hause,', 'denn', 'es', 'regnet'], hint: 'Main clause first, then "denn" with a normal sentence.', hintFr: 'D’abord la proposition principale, puis « denn » avec une phrase normale.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l18-e7', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Ich bleibe hier, denn ich bin müde.', 'Ich bleibe hier, denn ich müde bin.', 'Ich bleibe hier, denn bin ich müde.'], answer: 0, explain: 'After "denn" the word order does not change: ich bin müde.', explainFr: 'Après « denn », l’ordre des mots ne change pas : ich bin müde.', hint: 'The verb stays in second position.', hintFr: 'Le verbe reste en deuxième position.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l18-e8', prompt: 'Der Urlaub ___ schön, aber das Wetter war schlecht. (sein, past)', promptFr: 'Der Urlaub ___ schön, aber das Wetter war schlecht. (sein, passé)', answer: 'war', hint: 'er/sie/es → war', hintFr: 'er/sie/es → war' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l18-e9', prompt: 'Im Hotel ___ wir ein großes Zimmer. (haben, past)', promptFr: 'Im Hotel ___ wir ein großes Zimmer. (haben, passé)', answer: 'hatten', hint: 'wir → hatten', hintFr: 'wir → hatten' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l18-e10', prompt: 'Listen. Why were they at the beach?', promptFr: 'Écoute. Pourquoi étaient-ils à la plage ?', audio: { ttsText: 'Vor drei Tagen waren wir am Strand, denn es war sonnig.' }, options: ['It was sunny', 'It was windy', 'It was a holiday'], optionsFr: ['Il faisait soleil', 'Il y avait du vent', 'C’était un jour férié'], answer: 0, hint: 'Listen for the word after "denn".', hintFr: 'Écoute le mot après « denn ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l18-e11', prompt: 'Listen. When do they leave?', promptFr: 'Écoute. Quand partent-ils ?', audio: { ttsText: 'Wir fahren in einer Woche in die Ferien.' }, options: ['In a week', 'A week ago', 'For a week'], optionsFr: ['Dans une semaine', 'Il y a une semaine', 'Pour une semaine'], answer: 0, hint: 'Listen for "in einer Woche".', hintFr: 'Écoute « in einer Woche ».' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l18-e12', word: 'Meer', answer: 'das', hint: 'Words ending in -er can be any gender — learn it with its article!', hintFr: 'Les mots en -er peuvent avoir n’importe quel genre — apprends-le avec son article !' } },

    { kind: 'pronunciation', focus: 'v sounds like "f" in "vor", w sounds like English "v" in "Woche"', focusFr: 'v se prononce « f » dans « vor », w se prononce « v » dans « Woche »', items: [
      { id: 'l18-vor-pron', german: 'vor', english: 'before / ago', french: 'avant / il y a', gender: null, syllables: ['VOR'], pronunciation: 'fohr', example: { de: 'Vor einer Woche war ich hier.', en: 'A week ago I was here.', fr: 'Il y a une semaine, j’étais ici.' } },
      { id: 'l18-woche-pron', german: 'die Woche', english: 'the week', french: 'la semaine', gender: 'die', syllables: ['WO', 'che'], pronunciation: 'dee VOKH-eh', example: { de: 'Diese Woche bin ich hier.', en: 'This week I am here.', fr: 'Cette semaine, je suis ici.' } },
      { id: 'l18-ferien-pron', german: 'die Ferien', english: 'the holidays', french: 'les vacances', gender: 'die', syllables: ['FE', 'ri', 'en'], pronunciation: 'dee FAY-ree-en', example: { de: 'Wir haben drei Wochen Ferien.', en: 'We have three weeks of holidays.', fr: 'Nous avons trois semaines de vacances.' } },
      { id: 'l18-fruehling-pron', german: 'der Frühling', english: 'spring', french: 'le printemps', gender: 'der', syllables: ['FRÜH', 'ling'], pronunciation: 'dair FREW-ling', example: { de: 'Im Frühling ist es warm.', en: 'In spring it is warm.', fr: 'Au printemps, il fait doux.' } },
      { id: 'l18-weihnachten-pron', german: 'Weihnachten', english: 'Christmas', french: 'Noël', gender: null, syllables: ['WEIH', 'nach', 'ten'], pronunciation: 'VY-nakh-ten', example: { de: 'Frohe Weihnachten!', en: 'Merry Christmas!', fr: 'Joyeux Noël !' } },
    ] },

    { kind: 'wrapup', summary: 'You can now place things in time: **vor** (ago), **nach** (after), **in** (from now) + dative and **für** (for) + accusative. Give reasons with **denn** (word order stays normal!) and tell about your holiday with **war** and **hatte**. Schöne Ferien! 🎉',
      summaryFr: 'Tu sais maintenant situer dans le temps : **vor** (il y a), **nach** (après), **in** (dans) + datif et **für** (pour) + accusatif. Donne des raisons avec **denn** (l’ordre des mots reste normal !) et raconte tes vacances avec **war** et **hatte**. Schöne Ferien ! 🎉' },
  ],
};
