import type { Lesson } from '../types';

export const lektion14: Lesson = {
  id: 'l14', level: 'A1', module: 2, number: 7,
  title: { de: 'Verabredungen und Wortstellung', en: 'Making plans & word order', fr: 'Rendez-vous et ordre des mots' },
  theme: 'Arranging to meet, time words, and verb position',
  themeFr: 'Fixer un rendez-vous, les indications de temps et la place du verbe',
  goals: ['Suggest a meeting and answer: accept, decline, be unsure', 'Keep the verb in position 2', 'Start a sentence with a time word (inversion)', 'Use am, um and von … bis for time'],
  goalsFr: ['Proposer un rendez-vous et répondre : accepter, refuser, hésiter', 'Garder le verbe en position 2', 'Commencer une phrase par une indication de temps (inversion)', 'Utiliser am, um et von … bis pour le temps'],
  steps: [
    { kind: 'intro', title: 'Hast du Zeit? 📅', titleFr: 'Tu as le temps ? 📅',
      scene: 'Yara and Jonas chat on their phones. Yara wants to go to the cinema or a concert this week, but Jonas’s calendar is full. Which day works for both of them?',
      sceneFr: 'Yara et Jonas discutent sur leurs téléphones. Yara voudrait aller au cinéma ou à un concert cette semaine, mais l’agenda de Jonas est plein. Quel jour leur convient à tous les deux ?',
      goals: ['Ask "Hast du Zeit?"', 'Say yes, no or maybe politely', 'Name parts of the day', 'Put the time word first without breaking the word order'],
      goalsFr: ['Demander « Hast du Zeit ? »', 'Dire oui, non ou peut-être poliment', 'Nommer les moments de la journée', 'Placer l’indication de temps en tête sans casser l’ordre des mots'] },

    { kind: 'vocab', item: { id: 'l14-verabredung', german: 'die Verabredung', english: 'the date / arrangement to meet', french: 'le rendez-vous (entre amis)', gender: 'die', syllables: ['fer', 'AP', 're', 'dung'], pronunciation: 'dee fair-AHP-ray-doong', example: { de: 'Ich habe heute eine Verabredung.', en: 'I have plans to meet someone today.', fr: 'J’ai un rendez-vous aujourd’hui.' } } },
    { kind: 'vocab', item: { id: 'l14-termin', german: 'der Termin', english: 'the appointment', french: 'le rendez-vous (officiel)', gender: 'der', syllables: ['ter', 'MIN'], pronunciation: 'dair ter-MEEN', example: { de: 'Am Dienstag habe ich einen Termin.', en: 'On Tuesday I have an appointment.', fr: 'Mardi, j’ai un rendez-vous.' } } },
    { kind: 'vocab', item: { id: 'l14-zeit', german: 'die Zeit', english: 'the time (to spare)', french: 'le temps (libre)', gender: 'die', syllables: ['ZEIT'], pronunciation: 'dee tsite', example: { de: 'Hast du morgen Zeit?', en: 'Do you have time tomorrow?', fr: 'Tu as du temps demain ?' } } },
    { kind: 'vocab', item: { id: 'l14-lust', german: 'die Lust', english: 'the desire / feeling like it', french: 'l’envie', gender: 'die', syllables: ['LUST'], pronunciation: 'dee loost', example: { de: 'Hast du Lust auf Kino?', en: 'Do you feel like going to the cinema?', fr: 'Tu as envie d’aller au cinéma ?' } } },
    { kind: 'vocab', item: { id: 'l14-kino', german: 'das Kino', english: 'the cinema', french: 'le cinéma', gender: 'das', syllables: ['KI', 'no'], pronunciation: 'dahss KEE-no', example: { de: 'Wir gehen ins Kino.', en: 'We are going to the cinema.', fr: 'Nous allons au cinéma.' } } },
    { kind: 'vocab', item: { id: 'l14-konzert', german: 'das Konzert', english: 'the concert', french: 'le concert', gender: 'das', syllables: ['kon', 'ZERT'], pronunciation: 'dahss kon-TSERT', example: { de: 'Das Konzert beginnt um 20 Uhr.', en: 'The concert starts at 8 pm.', fr: 'Le concert commence à 20 heures.' } } },
    { kind: 'vocab', item: { id: 'l14-museum', german: 'das Museum', english: 'the museum', french: 'le musée', gender: 'das', syllables: ['mu', 'ZE', 'um'], pronunciation: 'dahss moo-ZAY-oom', example: { de: 'Das Museum ist am Montag zu.', en: 'The museum is closed on Monday.', fr: 'Le musée est fermé le lundi.' } } },
    { kind: 'vocab', item: { id: 'l14-vormittag', german: 'der Vormittag', english: 'the (late) morning', french: 'la matinée', gender: 'der', syllables: ['FOR', 'mit', 'tag'], pronunciation: 'dair FOR-mit-tahk', example: { de: 'Am Vormittag lerne ich Deutsch.', en: 'In the morning I study German.', fr: 'Le matin, j’apprends l’allemand.' } } },
    { kind: 'vocab', item: { id: 'l14-nachmittag', german: 'der Nachmittag', english: 'the afternoon', french: 'l’après-midi', gender: 'der', syllables: ['NACH', 'mit', 'tag'], pronunciation: 'dair NAHKH-mit-tahk', example: { de: 'Am Nachmittag habe ich Zeit.', en: 'In the afternoon I have time.', fr: 'L’après-midi, j’ai du temps.' } } },
    { kind: 'vocab', item: { id: 'l14-abend', german: 'der Abend', english: 'the evening', french: 'le soir', gender: 'der', syllables: ['A', 'bend'], pronunciation: 'dair AH-bent', example: { de: 'Am Abend gehe ich ins Kino.', en: 'In the evening I go to the cinema.', fr: 'Le soir, je vais au cinéma.' } } },
    { kind: 'vocab', item: { id: 'l14-wochenende', german: 'das Wochenende', english: 'the weekend', french: 'le week-end', gender: 'das', syllables: ['WO', 'chen', 'en', 'de'], pronunciation: 'dahss VOKH-en-en-de', example: { de: 'Am Wochenende schlafe ich lange.', en: 'At the weekend I sleep in.', fr: 'Le week-end, je dors longtemps.' } } },
    { kind: 'vocab', item: { id: 'l14-treffen', german: 'treffen', english: 'to meet', french: 'rencontrer / retrouver', gender: null, syllables: ['TREF', 'fen'], pronunciation: 'TREF-fen', example: { de: 'Ich treffe Yara um sechs Uhr.', en: 'I meet Yara at six o’clock.', fr: 'Je retrouve Yara à six heures.' } } },
    { kind: 'vocab', item: { id: 'l14-leider', german: 'leider', english: 'unfortunately', french: 'malheureusement', gender: null, syllables: ['LEI', 'der'], pronunciation: 'LIE-der', example: { de: 'Leider habe ich keine Zeit.', en: 'Unfortunately I have no time.', fr: 'Malheureusement, je n’ai pas le temps.' } } },
    { kind: 'vocab', item: { id: 'l14-vielleicht', german: 'vielleicht', english: 'maybe / perhaps', french: 'peut-être', gender: null, syllables: ['viel', 'LEICHT'], pronunciation: 'fee-LIKHT', example: { de: 'Vielleicht habe ich am Freitag Zeit.', en: 'Maybe I have time on Friday.', fr: 'Peut-être que j’ai du temps vendredi.' } } },

    { kind: 'grammar', note: {
      id: 'l14-position2', title: 'The verb stays in position 2', titleFr: 'Le verbe reste en position 2',
      explanationMd: 'In a German statement the **conjugated verb is always the second element** (not always the second word!). The first place can be the subject or something else:\n\n- **Ich** **habe** am Montag Zeit.\n- **Am Montag** **habe** ich Zeit.\n- **Heute Abend** **gehe** ich ins Kino.\n\nIf you put a time word first, the **subject moves behind the verb** (inversion). The meaning stays the same — only the focus changes. Never say *Am Montag ich habe Zeit.*',
      explanationMdFr: 'Dans une phrase affirmative allemande, le **verbe conjugué est toujours le deuxième élément** (pas forcément le deuxième mot !). La première place peut être le sujet ou autre chose :\n\n- **Ich** **habe** am Montag Zeit.\n- **Am Montag** **habe** ich Zeit.\n- **Heute Abend** **gehe** ich ins Kino.\n\nSi tu mets une indication de temps en premier, le **sujet passe derrière le verbe** (inversion). Le sens reste le même — seul l’accent change. Ne dis jamais *Am Montag ich habe Zeit.*',
      examples: [
        { de: 'Am Samstag habe ich Zeit.', en: 'On Saturday I have time.', fr: 'Samedi, j’ai du temps.' },
        { de: 'Heute Abend treffe ich Jonas.', en: 'This evening I am meeting Jonas.', fr: 'Ce soir, je retrouve Jonas.' },
        { de: 'Am Nachmittag arbeitet er.', en: 'In the afternoon he works.', fr: 'L’après-midi, il travaille.' },
      ],
      diagram: 'verb-second' } },

    { kind: 'grammar', note: {
      id: 'l14-am-um-von-bis', title: 'Telling when: am, um, von … bis', titleFr: 'Dire quand : am, um, von … bis',
      explanationMd: 'Three small words for time:\n\n- **am** + day or part of the day: **am** Montag, **am** Wochenende, **am** Morgen, **am** Vormittag, **am** Nachmittag, **am** Abend (but: **in der** Nacht)\n- **um** + clock time: **um** 18 Uhr, **um** halb acht\n- **von … bis** for a period: **von** 14 **bis** 16 Uhr\n\nQuestions: **Wann** hast du Zeit? (When?) — **Um wie viel Uhr** beginnt der Film? (At what time?)',
      explanationMdFr: 'Trois petits mots pour le temps :\n\n- **am** + jour ou moment de la journée : **am** Montag, **am** Wochenende, **am** Morgen, **am** Vormittag, **am** Nachmittag, **am** Abend (mais : **in der** Nacht)\n- **um** + heure : **um** 18 Uhr, **um** halb acht\n- **von … bis** pour une durée : **von** 14 **bis** 16 Uhr\n\nQuestions : **Wann** hast du Zeit ? (Quand ?) — **Um wie viel Uhr** beginnt der Film ? (À quelle heure ?)',
      examples: [
        { de: 'Am Freitag gehe ich um 19 Uhr ins Konzert.', en: 'On Friday I go to the concert at 7 pm.', fr: 'Vendredi, je vais au concert à 19 heures.' },
        { de: 'Von 14 bis 16 Uhr habe ich einen Termin.', en: 'From 2 to 4 pm I have an appointment.', fr: 'De 14 à 16 heures, j’ai un rendez-vous.' },
        { de: 'Wann treffen wir uns?', en: 'When are we meeting?', fr: 'Quand est-ce qu’on se retrouve ?' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l14-vorschlag', title: 'Suggest, accept, decline', titleFr: 'Proposer, accepter, refuser',
      explanationMd: '**Suggest:** Hast du **Zeit**? / Hast du **Lust** auf Kino? / **Treffen wir uns** um 18 Uhr? (*Treffen wir uns* is a fixed phrase for "shall we meet?")\n\n**Accept:** Ja, **gern**! / **Gute Idee!** / Das passt.\n\n**Decline:** **Leider** nicht. / Tut mir leid, ich habe **keine Zeit**. / Ich habe **keine Lust**.\n\n**Unsure:** **Vielleicht.** / Ich weiß noch nicht.\n\nNote: **keine Zeit** and **keine Lust** use **keine**, because Zeit and Lust are nouns.',
      explanationMdFr: '**Proposer :** Hast du **Zeit** ? / Hast du **Lust** auf Kino ? / **Treffen wir uns** um 18 Uhr ? (*Treffen wir uns* est une expression figée pour « on se retrouve ? »)\n\n**Accepter :** Ja, **gern** ! / **Gute Idee !** / Das passt.\n\n**Refuser :** **Leider** nicht. / Tut mir leid, ich habe **keine Zeit**. / Ich habe **keine Lust**.\n\n**Hésiter :** **Vielleicht.** / Ich weiß noch nicht.\n\nAttention : **keine Zeit** et **keine Lust** utilisent **keine**, car Zeit et Lust sont des noms.',
      examples: [
        { de: 'Hast du am Sonntag Zeit? – Ja, gern!', en: 'Do you have time on Sunday? – Yes, gladly!', fr: 'Tu as du temps dimanche ? – Oui, avec plaisir !' },
        { de: 'Hast du Lust auf Kino? – Leider nicht, ich habe keine Zeit.', en: 'Do you feel like the cinema? – Unfortunately not, I have no time.', fr: 'Ça te dit d’aller au cinéma ? – Malheureusement non, je n’ai pas le temps.' },
        { de: 'Treffen wir uns um sechs? – Gute Idee!', en: 'Shall we meet at six? – Good idea!', fr: 'On se retrouve à six heures ? – Bonne idée !' },
      ] } },

    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l14-e1', tokens: ['habe', 'Am', 'ich', 'Montag', 'Zeit'], answer: ['Am', 'Montag', 'habe', 'ich', 'Zeit'], hint: 'Am Montag (position 1), then the verb, then the subject.', hintFr: 'Am Montag (position 1), puis le verbe, puis le sujet.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l14-e2', prompt: '___ Samstag habe ich keine Zeit.', promptFr: '___ Samstag habe ich keine Zeit.', answer: 'Am', hint: 'Which small word goes with days of the week?', hintFr: 'Quel petit mot va avec les jours de la semaine ?' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l14-e3', prompt: 'Der Film beginnt ___ 20 Uhr.', promptFr: 'Der Film beginnt ___ 20 Uhr.', answer: 'um', hint: 'Which word goes with clock times?', hintFr: 'Quel mot va avec les heures ?' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l14-e4', prompt: 'Which sentence is correct?', promptFr: 'Quelle phrase est correcte ?', options: ['Heute ich habe Zeit.', 'Heute habe ich Zeit.', 'Heute Zeit habe ich.'], answer: 1, explain: 'The verb must be in position 2, so the subject "ich" comes after it.', explainFr: 'Le verbe doit être en position 2, donc le sujet « ich » vient après.', hint: 'The conjugated verb is the 2nd element.', hintFr: 'Le verbe conjugué est le 2e élément.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l14-e5', pairs: [ { de: 'Ja, gern!', en: 'Yes, gladly!', fr: 'Oui, avec plaisir !' }, { de: 'Leider nicht.', en: 'Unfortunately not.', fr: 'Malheureusement non.' }, { de: 'Vielleicht.', en: 'Maybe.', fr: 'Peut-être.' }, { de: 'Ich habe keine Lust.', en: 'I do not feel like it.', fr: 'Je n’en ai pas envie.' } ], hint: 'Match each reply to its meaning.', hintFr: 'Associe chaque réponse à sa signification.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l14-e6', prompt: 'Listen. When does Jonas have time?', promptFr: 'Écoute. Quand Jonas a-t-il du temps ?', audio: { ttsText: 'Hast du am Samstag Zeit? – Leider nicht. Am Samstag arbeite ich. Aber am Sonntag habe ich Zeit.' }, options: ['On Saturday', 'On Sunday', 'On Monday'], optionsFr: ['Samedi', 'Dimanche', 'Lundi'], answer: 1, hint: 'Listen for "Aber am …".', hintFr: 'Écoute « Aber am … ».' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l14-e7', prompt: 'What does "von 14 bis 16 Uhr" mean?', promptFr: 'Que signifie « von 14 bis 16 Uhr » ?', options: ['at 2 pm', 'from 2 to 4 pm', 'after 4 pm'], optionsFr: ['à 14 heures', 'de 14 à 16 heures', 'après 16 heures'], answer: 1, explain: '"von … bis" marks the beginning and the end of a period.', explainFr: '« von … bis » marque le début et la fin d’une période.', hint: '"von" = from, "bis" = until.', hintFr: '« von » = de, « bis » = jusqu’à.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l14-e8', prompt: 'Tut mir leid, ich habe ___ Zeit.', promptFr: 'Tut mir leid, ich habe ___ Zeit.', answer: 'keine', hint: 'Zeit is a feminine noun: use kein + e.', hintFr: 'Zeit est un nom féminin : kein + e.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l14-e9', prompt: 'Listen. At what time do they meet?', promptFr: 'Écoute. À quelle heure se retrouvent-ils ?', audio: { ttsText: 'Treffen wir uns um sechs Uhr vor dem Kino?' }, options: ['At 5 o’clock', 'At 6 o’clock', 'At 8 o’clock'], optionsFr: ['À 5 heures', 'À 6 heures', 'À 8 heures'], answer: 1, hint: 'Listen for the number after "um".', hintFr: 'Écoute le nombre après « um ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l14-e10', tokens: ['Hast', 'Zeit', 'du', 'morgen'], answer: ['Hast', 'du', 'morgen', 'Zeit'], hint: 'A yes/no question: the verb goes first.', hintFr: 'Une question fermée : le verbe vient en premier.' } },

    { kind: 'pronunciation', focus: 'Stress and sounds in places and plans: Kino, Konzert, Museum, Termin', focusFr: 'Accent et sons dans les lieux et les projets : Kino, Konzert, Museum, Termin', items: [
      { id: 'l14-kino-pron', german: 'das Kino', english: 'the cinema', french: 'le cinéma', gender: 'das', syllables: ['KI', 'no'], pronunciation: 'dahss KEE-no', example: { de: 'Wir gehen ins Kino.', en: 'We are going to the cinema.', fr: 'Nous allons au cinéma.' } },
      { id: 'l14-konzert-pron', german: 'das Konzert', english: 'the concert', french: 'le concert', gender: 'das', syllables: ['kon', 'ZERT'], pronunciation: 'dahss kon-TSERT', example: { de: 'Das Konzert ist toll.', en: 'The concert is great.', fr: 'Le concert est génial.' } },
      { id: 'l14-museum-pron', german: 'das Museum', english: 'the museum', french: 'le musée', gender: 'das', syllables: ['mu', 'ZE', 'um'], pronunciation: 'dahss moo-ZAY-oom', example: { de: 'Das Museum öffnet um zehn.', en: 'The museum opens at ten.', fr: 'Le musée ouvre à dix heures.' } },
      { id: 'l14-termin-pron', german: 'der Termin', english: 'the appointment', french: 'le rendez-vous', gender: 'der', syllables: ['ter', 'MIN'], pronunciation: 'dair ter-MEEN', example: { de: 'Ich habe einen Termin.', en: 'I have an appointment.', fr: 'J’ai un rendez-vous.' } },
      { id: 'l14-vielleicht-pron', german: 'vielleicht', english: 'maybe', french: 'peut-être', gender: null, syllables: ['viel', 'LEICHT'], pronunciation: 'fee-LIKHT', example: { de: 'Vielleicht komme ich mit.', en: 'Maybe I will come along.', fr: 'Peut-être que je viens.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now arrange to meet: ask **Hast du Zeit?**, accept (**Ja, gern!**), decline (**Leider nicht**) or hesitate (**Vielleicht**). The conjugated verb stays in **position 2**, so after a time word the subject follows the verb: **Am Montag habe ich Zeit.** Use **am** (days, parts of the day), **um** (clock times) and **von … bis** (periods). 🎉',
      summaryFr: 'Tu sais maintenant fixer un rendez-vous : demande **Hast du Zeit ?**, accepte (**Ja, gern !**), refuse (**Leider nicht**) ou hésite (**Vielleicht**). Le verbe conjugué reste en **position 2**, donc après une indication de temps le sujet suit le verbe : **Am Montag habe ich Zeit.** Utilise **am** (jours, moments de la journée), **um** (heures) et **von … bis** (périodes). 🎉' },
  ],
};
