import type { Lesson } from '../types';

export const lektion13: Lesson = {
  id: 'l13', level: 'A1', module: 2, number: 5,
  title: { de: 'Gegenstände und Plural', en: 'Things and plurals', fr: 'Les objets et le pluriel' },
  theme: 'Everyday objects, the plural, and "kein / keine"',
  themeFr: 'Les objets du quotidien, le pluriel et « kein / keine »',
  goals: ['Ask "Was ist das?" and name objects', 'Form the plural of German nouns', 'Say what something is not with "kein / keine"', 'Say what you need or do not need: "Ich brauche keinen …"'],
  goalsFr: ['Demander « Was ist das ? » et nommer des objets', 'Former le pluriel des noms allemands', 'Dire ce que quelque chose n’est pas avec « kein / keine »', 'Dire ce dont on a besoin ou non : « Ich brauche keinen … »'],
  steps: [
    { kind: 'intro', title: 'Mein erstes Zimmer 📦', titleFr: 'Ma première chambre 📦',
      scene: 'Fenja has just moved into her first flat. Her friend Malik helps her unpack boxes and asks what each thing is, what she already has and what she still needs.',
      sceneFr: 'Fenja vient d’emménager dans son premier appartement. Son ami Malik l’aide à déballer les cartons et demande ce qu’est chaque objet, ce qu’elle a déjà et ce qu’il lui manque encore.',
      goals: ['Name furniture and office things', 'Ask "Was ist das?"', 'Use the plural forms', 'Use "kein / keine / keinen"'],
      goalsFr: ['Nommer des meubles et des objets de bureau', 'Demander « Was ist das ? »', 'Utiliser les formes du pluriel', 'Utiliser « kein / keine / keinen »'] },

    { kind: 'vocab', item: { id: 'l13-was-ist-das', german: 'Was ist das?', english: 'What is that?', french: 'Qu’est-ce que c’est ?', gender: null, syllables: ['WAS', 'IST', 'DAS'], pronunciation: 'vahss ist dahss', example: { de: 'Was ist das? – Das ist ein Regal.', en: 'What is that? – That is a shelf.', fr: 'Qu’est-ce que c’est ? – C’est une étagère.' } } },
    { kind: 'vocab', item: { id: 'l13-schrank', german: 'der Schrank', english: 'the cupboard / wardrobe (pl. Schränke)', french: 'l’armoire (pl. Schränke)', gender: 'der', syllables: ['SCHRANK'], pronunciation: 'dair shrahnk', example: { de: 'Wir haben zwei Schränke.', en: 'We have two cupboards.', fr: 'Nous avons deux armoires.' } } },
    { kind: 'vocab', item: { id: 'l13-regal', german: 'das Regal', english: 'the shelf (pl. Regale)', french: 'l’étagère (pl. Regale)', gender: 'das', syllables: ['re', 'GAL'], pronunciation: 'dahss re-GAHL', example: { de: 'Das Regal ist neu.', en: 'The shelf is new.', fr: 'L’étagère est neuve.' } } },
    { kind: 'vocab', item: { id: 'l13-sofa', german: 'das Sofa', english: 'the sofa (pl. Sofas)', french: 'le canapé (pl. Sofas)', gender: 'das', syllables: ['SO', 'fa'], pronunciation: 'dahss ZOH-fah', example: { de: 'Das Sofa ist sehr bequem.', en: 'The sofa is very comfortable.', fr: 'Le canapé est très confortable.' } } },
    { kind: 'vocab', item: { id: 'l13-lampe', german: 'die Lampe', english: 'the lamp (pl. Lampen)', french: 'la lampe (pl. Lampen)', gender: 'die', syllables: ['LAM', 'pe'], pronunciation: 'dee LAHM-pe', example: { de: 'Die Lampe steht neben dem Bett.', en: 'The lamp is next to the bed.', fr: 'La lampe est à côté du lit.' } } },
    { kind: 'vocab', item: { id: 'l13-fenster', german: 'das Fenster', english: 'the window (pl. Fenster)', french: 'la fenêtre (pl. Fenster)', gender: 'das', syllables: ['FENS', 'ter'], pronunciation: 'dahss FENS-ter', example: { de: 'Das Zimmer hat zwei Fenster.', en: 'The room has two windows.', fr: 'La pièce a deux fenêtres.' } } },
    { kind: 'vocab', item: { id: 'l13-stift', german: 'der Stift', english: 'the pen / pencil (pl. Stifte)', french: 'le stylo / crayon (pl. Stifte)', gender: 'der', syllables: ['STIFT'], pronunciation: 'dair shtift', example: { de: 'Ich brauche einen Stift.', en: 'I need a pen.', fr: 'J’ai besoin d’un stylo.' } } },
    { kind: 'vocab', item: { id: 'l13-buch', german: 'das Buch', english: 'the book (pl. Bücher)', french: 'le livre (pl. Bücher)', gender: 'das', syllables: ['BUCH'], pronunciation: 'dahss bookh', example: { de: 'Auf dem Tisch liegen drei Bücher.', en: 'Three books are lying on the table.', fr: 'Trois livres sont posés sur la table.' } } },
    { kind: 'vocab', item: { id: 'l13-schluessel', german: 'der Schlüssel', english: 'the key (pl. Schlüssel)', french: 'la clé (pl. Schlüssel)', gender: 'der', syllables: ['SCHLÜS', 'sel'], pronunciation: 'dair SHLUES-sel', example: { de: 'Wo ist mein Schlüssel?', en: 'Where is my key?', fr: 'Où est ma clé ?' } } },
    { kind: 'vocab', item: { id: 'l13-tasche', german: 'die Tasche', english: 'the bag (pl. Taschen)', french: 'le sac (pl. Taschen)', gender: 'die', syllables: ['TA', 'sche'], pronunciation: 'dee TAH-she', example: { de: 'Die Tasche ist schwer.', en: 'The bag is heavy.', fr: 'Le sac est lourd.' } } },
    { kind: 'vocab', item: { id: 'l13-handy', german: 'das Handy', english: 'the mobile phone (pl. Handys)', french: 'le portable (pl. Handys)', gender: 'das', syllables: ['HEN', 'dy'], pronunciation: 'dahss HEN-dee', example: { de: 'Mein Handy ist neu.', en: 'My phone is new.', fr: 'Mon portable est neuf.' } } },
    { kind: 'vocab', item: { id: 'l13-laptop', german: 'der Laptop', english: 'the laptop (pl. Laptops)', french: 'l’ordinateur portable (pl. Laptops)', gender: 'der', syllables: ['LEP', 'top'], pronunciation: 'dair LEP-top', example: { de: 'Er hat einen Laptop.', en: 'He has a laptop.', fr: 'Il a un ordinateur portable.' } } },
    { kind: 'vocab', item: { id: 'l13-drucker', german: 'der Drucker', english: 'the printer (pl. Drucker)', french: 'l’imprimante (pl. Drucker)', gender: 'der', syllables: ['DRU', 'cker'], pronunciation: 'dair DROO-ker', example: { de: 'Der Drucker ist kaputt.', en: 'The printer is broken.', fr: 'L’imprimante est en panne.' } } },
    { kind: 'vocab', item: { id: 'l13-brille', german: 'die Brille', english: 'the glasses (pl. Brillen)', french: 'les lunettes (pl. Brillen)', gender: 'die', syllables: ['BRIL', 'le'], pronunciation: 'dee BRIL-le', example: { de: 'Ich suche meine Brille.', en: 'I am looking for my glasses.', fr: 'Je cherche mes lunettes.' } } },

    { kind: 'grammar', note: {
      id: 'l13-plural', title: 'The plural: five patterns', titleFr: 'Le pluriel : cinq modèles',
      explanationMd: 'In the plural the article is always **die**. The noun itself changes in one of five ways, so learn the plural **with** every new noun:\n\n- **-e / ¨e**: der Stift → die Stift**e**, der Schrank → die Schr**ä**nk**e**\n- **-(e)n**: die Lampe → die Lampe**n**, die Tasche → die Tasche**n**\n- **-s** (often foreign words): das Handy → die Handy**s**, das Sofa → die Sofa**s**\n- **-er / ¨er** (always with an umlaut if possible): das Buch → die B**ü**ch**er**\n- **no ending** (sometimes an umlaut): der Schlüssel → die Schlüssel, das Fenster → die Fenster\n\nTip: most **die** nouns take **-n/-en**; words ending in **-el/-er** usually stay the same.',
      explanationMdFr: 'Au pluriel, l’article est toujours **die**. Le nom lui-même change de cinq façons : apprends donc le pluriel **avec** chaque nouveau nom :\n\n- **-e / ¨e** : der Stift → die Stift**e**, der Schrank → die Schr**ä**nk**e**\n- **-(e)n** : die Lampe → die Lampe**n**, die Tasche → die Tasche**n**\n- **-s** (souvent des mots étrangers) : das Handy → die Handy**s**, das Sofa → die Sofa**s**\n- **-er / ¨er** (avec tréma si possible) : das Buch → die B**ü**ch**er**\n- **sans terminaison** (parfois un tréma) : der Schlüssel → die Schlüssel, das Fenster → die Fenster\n\nAstuce : la plupart des noms en **die** prennent **-n/-en** ; les mots en **-el/-er** restent souvent identiques.',
      examples: [
        { de: 'Das Zimmer hat zwei Fenster und drei Lampen.', en: 'The room has two windows and three lamps.', fr: 'La pièce a deux fenêtres et trois lampes.' },
        { de: 'Die Bücher liegen im Regal.', en: 'The books are in the shelf.', fr: 'Les livres sont dans l’étagère.' },
        { de: 'Wir brauchen zwei Schränke.', en: 'We need two cupboards.', fr: 'Il nous faut deux armoires.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l13-kein', title: 'Saying "not a": kein / keine', titleFr: 'Dire « pas de / pas un » : kein / keine',
      explanationMd: 'To negate a noun with **ein/eine** (or with no article), use **kein / keine** — not *nicht*. It has the same endings as **ein / eine**, plus **keine** in the plural:\n\n- Das ist **ein** Tisch. → Das ist **kein** Tisch.\n- Das ist **eine** Lampe. → Das ist **keine** Lampe.\n- Das ist **ein** Sofa. → Das ist **kein** Sofa.\n- Plural: Das sind **keine** Bücher.\n\nAsk with **Was ist das?** and answer **Das ist …**. For plural: **Was sind das? – Das sind …**\n\nTo replace the noun, use **er / es / sie**: Der Tisch ist neu. **Er** ist schön.',
      explanationMdFr: 'Pour nier un nom précédé de **ein/eine** (ou sans article), on utilise **kein / keine** — pas *nicht*. Mêmes terminaisons que **ein / eine**, et **keine** au pluriel :\n\n- Das ist **ein** Tisch. → Das ist **kein** Tisch.\n- Das ist **eine** Lampe. → Das ist **keine** Lampe.\n- Das ist **ein** Sofa. → Das ist **kein** Sofa.\n- Pluriel : Das sind **keine** Bücher.\n\nDemande avec **Was ist das ?** et réponds **Das ist …**. Au pluriel : **Was sind das ? – Das sind …**\n\nPour remplacer le nom, utilise **er / es / sie** : Der Tisch ist neu. **Er** ist schön.',
      examples: [
        { de: 'Das ist kein Stuhl, das ist ein Schrank.', en: 'That is not a chair, it is a wardrobe.', fr: 'Ce n’est pas une chaise, c’est une armoire.' },
        { de: 'Was sind das? – Das sind Schlüssel.', en: 'What are those? – Those are keys.', fr: 'Qu’est-ce que c’est ? – Ce sont des clés.' },
        { de: 'Das ist keine Brille.', en: 'That is not a pair of glasses.', fr: 'Ce ne sont pas des lunettes.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l13-kein-akkusativ', title: '"Ich brauche keinen …": kein with haben / brauchen / suchen', titleFr: '« Ich brauche keinen … » : kein avec haben / brauchen / suchen',
      explanationMd: 'After **haben, brauchen** and **suchen** the noun is the direct object (accusative). Good news: only the **masculine** changes (you will study the accusative in detail later in the course):\n\n- der → Ich brauche **einen** / **keinen** Drucker.\n- das → Ich habe **ein** / **kein** Sofa.\n- die → Ich suche **eine** / **keine** Lampe.\n- plural → Ich habe **keine** Bücher.\n\nSo: masculine **keinen**; neuter **kein**; feminine and plural **keine**.',
      explanationMdFr: 'Après **haben, brauchen** et **suchen**, le nom est le complément d’objet direct (accusatif). Bonne nouvelle : seul le **masculin** change (tu étudieras l’accusatif en détail plus loin dans le cours) :\n\n- der → Ich brauche **einen** / **keinen** Drucker.\n- das → Ich habe **ein** / **kein** Sofa.\n- die → Ich suche **eine** / **keine** Lampe.\n- pluriel → Ich habe **keine** Bücher.\n\nDonc : masculin **keinen** ; neutre **kein** ; féminin et pluriel **keine**.',
      examples: [
        { de: 'Ich brauche keinen Laptop, ich habe ein Handy.', en: 'I do not need a laptop, I have a phone.', fr: 'Je n’ai pas besoin d’un ordinateur portable, j’ai un portable.' },
        { de: 'Fenja hat kein Regal, aber zwei Schränke.', en: 'Fenja has no shelf, but two cupboards.', fr: 'Fenja n’a pas d’étagère, mais deux armoires.' },
        { de: 'Malik sucht keine Lampe, er sucht seinen Schlüssel.', en: 'Malik is not looking for a lamp, he is looking for his key.', fr: 'Malik ne cherche pas de lampe, il cherche sa clé.' },
      ] } },

    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l13-e1', word: 'Regal', answer: 'das', hint: 'Learn it with its article: das Regal (neuter).', hintFr: 'Apprends-le avec son article : das Regal (neutre).' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l13-e2', prompt: 'What is the plural of "das Buch"?', promptFr: 'Quel est le pluriel de « das Buch » ?', options: ['die Buchs', 'die Bücher', 'die Buchen'], answer: 1, explain: 'Das Buch → die Bücher: ¨er plural with an umlaut.', explainFr: 'Das Buch → die Bücher : pluriel en ¨er avec un tréma.', hint: 'The vowel gets an umlaut and -er is added.', hintFr: 'La voyelle prend un tréma et on ajoute -er.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l13-e3', prompt: 'Das ist ___ Tisch. Das ist ein Schrank.', promptFr: 'Das ist ___ Tisch. Das ist ein Schrank.', answer: 'kein', hint: 'Negation of "ein Tisch" (masculine, nominative).', hintFr: 'Négation de « ein Tisch » (masculin, nominatif).' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l13-e4', pairs: [ { de: 'der Schrank', en: 'die Schränke', fr: 'die Schränke' }, { de: 'die Lampe', en: 'die Lampen', fr: 'die Lampen' }, { de: 'das Handy', en: 'die Handys', fr: 'die Handys' }, { de: 'das Fenster', en: 'die Fenster', fr: 'die Fenster' } ], hint: 'Match each singular word to its plural.', hintFr: 'Associe chaque singulier à son pluriel.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l13-e5', prompt: 'Listen. What does the speaker need?', promptFr: 'Écoute. De quoi la personne a-t-elle besoin ?', audio: { ttsText: 'Ich brauche keinen Laptop, aber ich brauche ein Handy.' }, options: ['A phone', 'A laptop', 'A printer'], optionsFr: ['Un portable', 'Un ordinateur portable', 'Une imprimante'], answer: 0, hint: 'Listen for "keinen" (not needed) and "aber" (but).', hintFr: 'Écoute « keinen » (pas besoin) et « aber » (mais).' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l13-e6', prompt: 'Ich brauche ___ Stuhl. (Ich habe schon drei.)', promptFr: 'Ich brauche ___ Stuhl. (J’en ai déjà trois.)', answer: 'keinen', hint: 'Masculine accusative: kein + en', hintFr: 'Accusatif masculin : kein + en' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l13-e7', tokens: ['keine', 'ist', 'Lampe', 'Das'], answer: ['Das', 'ist', 'keine', 'Lampe'], hint: 'Das ist + kein/keine + noun.', hintFr: 'Das ist + kein/keine + nom.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l13-e8', prompt: 'What is the plural of "der Schlüssel"?', promptFr: 'Quel est le pluriel de « der Schlüssel » ?', options: ['die Schlüsseln', 'die Schlüssel', 'die Schlüssele'], answer: 1, explain: 'Nouns ending in -el stay the same in the plural.', explainFr: 'Les noms en -el restent identiques au pluriel.', hint: 'Words ending in -el often have no plural ending.', hintFr: 'Les mots en -el n’ont souvent pas de terminaison au pluriel.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l13-e9', prompt: 'Listen. What is it?', promptFr: 'Écoute. Qu’est-ce que c’est ?', audio: { ttsText: 'Was ist das? Das ist kein Tisch. Das ist ein Regal.' }, options: ['A table', 'A shelf', 'A lamp'], optionsFr: ['Une table', 'Une étagère', 'Une lampe'], answer: 1, hint: 'Listen after "kein" and after "ein".', hintFr: 'Écoute ce qui suit « kein » et « ein ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l13-e10', prompt: 'Ich habe zwei ___. (das Handy → plural)', promptFr: 'Ich habe zwei ___. (das Handy → pluriel)', answer: 'Handys', hint: 'Foreign words usually add -s.', hintFr: 'Les mots étrangers prennent souvent -s.' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l13-e11', tokens: ['brauche', 'keinen', 'Ich', 'Drucker'], answer: ['Ich', 'brauche', 'keinen', 'Drucker'], hint: 'Subject, verb, then keinen + masculine noun.', hintFr: 'Sujet, verbe, puis keinen + nom masculin.' } },

    { kind: 'pronunciation', focus: 'Umlauts in plurals: ä, ü — round your lips for ü, keep them spread for ä', focusFr: 'Les trémas au pluriel : ä, ü — arrondis les lèvres pour ü, garde-les étirées pour ä', items: [
      { id: 'l13-buecher-pron', german: 'die Bücher', english: 'the books', french: 'les livres', gender: null, syllables: ['BÜ', 'cher'], pronunciation: 'dee BUE-kher', example: { de: 'Die Bücher sind neu.', en: 'The books are new.', fr: 'Les livres sont neufs.' } },
      { id: 'l13-schraenke-pron', german: 'die Schränke', english: 'the cupboards', french: 'les armoires', gender: null, syllables: ['SCHRÄN', 'ke'], pronunciation: 'dee SHREN-ke', example: { de: 'Die Schränke sind groß.', en: 'The cupboards are big.', fr: 'Les armoires sont grandes.' } },
      { id: 'l13-schluessel-pron', german: 'die Schlüssel', english: 'the keys', french: 'les clés', gender: null, syllables: ['SCHLÜS', 'sel'], pronunciation: 'dee SHLUES-sel', example: { de: 'Wo sind die Schlüssel?', en: 'Where are the keys?', fr: 'Où sont les clés ?' } },
      { id: 'l13-stuehle-pron', german: 'die Stühle', english: 'the chairs', french: 'les chaises', gender: null, syllables: ['STÜH', 'le'], pronunciation: 'dee SHTUE-le', example: { de: 'Wir brauchen vier Stühle.', en: 'We need four chairs.', fr: 'Il nous faut quatre chaises.' } },
      { id: 'l13-tueren-pron', german: 'die Türen', english: 'the doors', french: 'les portes', gender: null, syllables: ['TÜ', 'ren'], pronunciation: 'dee TUE-ren', example: { de: 'Die Türen sind offen.', en: 'The doors are open.', fr: 'Les portes sont ouvertes.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now name everyday objects and ask **Was ist das?** The plural always uses **die** and comes in five patterns (**-e/¨e, -(e)n, -s, -er/¨er, no ending**) — learn it with each noun. Negate nouns with **kein / keine** (masculine accusative: **keinen**): **Ich brauche keinen Drucker.** 🎉',
      summaryFr: 'Tu sais maintenant nommer des objets du quotidien et demander **Was ist das ?** Le pluriel utilise toujours **die** et suit cinq modèles (**-e/¨e, -(e)n, -s, -er/¨er, sans terminaison**) — apprends-le avec chaque nom. Nie les noms avec **kein / keine** (accusatif masculin : **keinen**) : **Ich brauche keinen Drucker.** 🎉' },
  ],
};
