import type { Lesson } from '../types';

export const lektion19: Lesson = {
  id: 'l19', level: 'A1', module: 5, number: 19,
  title: { de: 'Datum, Ordnungszahlen und Wünsche', en: 'Dates, ordinals and wishes', fr: 'Dates, nombres ordinaux et souhaits' },
  theme: 'Saying dates, inviting people and expressing wishes',
  themeFr: 'Dire la date, inviter et exprimer des souhaits',
  goals: ['Count with ordinal numbers: der erste … der dreißigste', 'Say dates with "am" and name the months', 'Understand and write a party invitation', 'Express wishes with "ich würde gern / am liebsten …"', 'Congratulate people'],
  goalsFr: ['Compter avec les nombres ordinaux : der erste … der dreißigste', 'Dire la date avec « am » et nommer les mois', 'Comprendre et écrire une invitation', 'Exprimer des souhaits avec « ich würde gern / am liebsten … »', 'Féliciter quelqu’un'],
  steps: [
    { kind: 'intro', title: 'Wann ist die Party? 🎂', titleFr: 'Quand est la fête ? 🎂',
      scene: 'Lena turns 25 and wants a big party. She writes an invitation with the date and tells her friends what she would love to do.', sceneFr: 'Lena fête ses 25 ans et veut une grande fête. Elle écrit une invitation avec la date et raconte ce qu’elle aimerait faire.',
      goals: ['Say "am dritten Mai"', 'Learn ordinal numbers to 31', 'Wish: "Ich würde am liebsten tanzen."', 'Say "Alles Gute zum Geburtstag!"'],
      goalsFr: ['Dire « am dritten Mai »', 'Apprendre les nombres ordinaux jusqu’à 31', 'Souhaiter : « Ich würde am liebsten tanzen. »', 'Dire « Alles Gute zum Geburtstag ! »'] },

    { kind: 'vocab', item: { id: 'l19-datum', german: 'das Datum', english: 'the date', french: 'la date', gender: 'das', syllables: ['DA', 'tum'], pronunciation: 'dahs DAH-toom', example: { de: 'Welches Datum haben wir heute?', en: 'What is the date today?', fr: 'Quelle est la date aujourd’hui ?' } } },
    { kind: 'vocab', item: { id: 'l19-monat', german: 'der Monat', english: 'the month', french: 'le mois', gender: 'der', syllables: ['MO', 'nat'], pronunciation: 'dair MOH-naht', example: { de: 'Ein Jahr hat zwölf Monate.', en: 'A year has twelve months.', fr: 'Une année a douze mois.' } } },
    { kind: 'vocab', item: { id: 'l19-geburtstag', german: 'der Geburtstag', english: 'the birthday', french: 'l’anniversaire', gender: 'der', syllables: ['ge', 'BURTS', 'tag'], pronunciation: 'dair geh-BOORTS-tahk', example: { de: 'Heute ist mein Geburtstag!', en: 'Today is my birthday!', fr: 'Aujourd’hui, c’est mon anniversaire !' } } },
    { kind: 'vocab', item: { id: 'l19-party', german: 'die Party', english: 'the party', french: 'la fête / la soirée', gender: 'die', syllables: ['PAR', 'ty'], pronunciation: 'dee PAR-tee', example: { de: 'Die Party beginnt um acht.', en: 'The party starts at eight.', fr: 'La fête commence à huit heures.' } } },
    { kind: 'vocab', item: { id: 'l19-hochzeit', german: 'die Hochzeit', english: 'the wedding', french: 'le mariage', gender: 'die', syllables: ['HOCH', 'zeit'], pronunciation: 'dee HOKH-tsite', example: { de: 'Die Hochzeit ist im Juni.', en: 'The wedding is in June.', fr: 'Le mariage a lieu en juin.' } } },
    { kind: 'vocab', item: { id: 'l19-geschenk', german: 'das Geschenk', english: 'the gift', french: 'le cadeau', gender: 'das', syllables: ['ge', 'SCHENK'], pronunciation: 'dahs geh-SHENK', example: { de: 'Das Geschenk ist für dich.', en: 'The gift is for you.', fr: 'Le cadeau est pour toi.' } } },
    { kind: 'vocab', item: { id: 'l19-kuchen', german: 'der Kuchen', english: 'the cake', french: 'le gâteau', gender: 'der', syllables: ['KU', 'chen'], pronunciation: 'dair KOO-khen', example: { de: 'Ich backe einen Kuchen.', en: 'I am baking a cake.', fr: 'Je fais un gâteau.' } } },
    { kind: 'vocab', item: { id: 'l19-feiern', german: 'feiern', english: 'to celebrate', french: 'fêter', gender: null, syllables: ['FEI', 'ern'], pronunciation: 'FY-ern', example: { de: 'Wir feiern im Garten.', en: 'We are celebrating in the garden.', fr: 'Nous fêtons ça dans le jardin.' } } },
    { kind: 'vocab', item: { id: 'l19-einladung', german: 'die Einladung', english: 'the invitation', french: 'l’invitation', gender: 'die', syllables: ['EIN', 'la', 'dung'], pronunciation: 'dee YNE-lah-doong', example: { de: 'Ich schreibe eine Einladung.', en: 'I am writing an invitation.', fr: 'J’écris une invitation.' } } },
    { kind: 'vocab', item: { id: 'l19-glueckwunsch', german: 'der Glückwunsch', english: 'the congratulation', french: 'la félicitation', gender: 'der', syllables: ['GLÜCK', 'wunsch'], pronunciation: 'dair GLEWK-voonsh', example: { de: 'Herzlichen Glückwunsch!', en: 'Congratulations!', fr: 'Félicitations !' } } },
    { kind: 'vocab', item: { id: 'l19-wunsch', german: 'der Wunsch', english: 'the wish', french: 'le souhait', gender: 'der', syllables: ['WUNSCH'], pronunciation: 'dair voonsh', example: { de: 'Hast du einen Wunsch?', en: 'Do you have a wish?', fr: 'As-tu un souhait ?' } } },
    { kind: 'vocab', item: { id: 'l19-silvester', german: 'Silvester', english: 'New Year’s Eve', french: 'la Saint-Sylvestre', gender: null, syllables: ['sil', 'VES', 'ter'], pronunciation: 'zil-VES-ter', example: { de: 'An Silvester feiern wir mit Freunden.', en: 'On New Year’s Eve we celebrate with friends.', fr: 'Le 31 décembre, nous fêtons avec des amis.' } } },
    { kind: 'vocab', item: { id: 'l19-amliebsten', german: 'am liebsten', english: 'most of all / I’d love to', french: 'le plus volontiers / ce que je préfère', gender: null, syllables: ['am', 'LIEB', 'sten'], pronunciation: 'ahm LEEP-sten', example: { de: 'Ich tanze am liebsten.', en: 'Most of all, I like to dance.', fr: 'Ce que je préfère, c’est danser.' } } },
    { kind: 'vocab', item: { id: 'l19-wuerde', german: 'würde', english: 'would', french: 'je voudrais / j’aimerais (avec un infinitif)', gender: null, syllables: ['WÜR', 'de'], pronunciation: 'VUER-deh', example: { de: 'Ich würde gern tanzen.', en: 'I would like to dance.', fr: 'J’aimerais danser.' } } },

    { kind: 'grammar', note: {
      id: 'l19-ordinalzahlen', title: 'Ordinal numbers: der erste … der dreißigste', titleFr: 'Les nombres ordinaux : der erste … der dreißigste',
      explanationMd: 'Ordinals tell the **order** ("third", "fifth"). In writing you use the number + a **dot**: 3. = der dritte.\n\n**1–19**: number + **-te**\n- 2. zweite · 4. vierte · 5. fünfte · 6. sechste · 9. neunte · 10. zehnte · 12. zwölfte · 19. neunzehnte\n\n**Four irregular ones** — learn them by heart:\n- 1. → **erste** · 3. → **dritte** · 7. → **siebte** · 8. → **achte**\n\n**From 20**: number + **-ste**\n- 20. zwanzigste · 21. einundzwanzigste · 30. dreißigste · 31. einunddreißigste\n\nAn ordinal is an adjective, so it has an ending: der dritte Mai, am dritten Mai.',
      explanationMdFr: 'Les ordinaux indiquent l’**ordre** (« troisième », « cinquième »). À l’écrit, on met le chiffre + un **point** : 3. = der dritte.\n\n**1–19** : nombre + **-te**\n- 2. zweite · 4. vierte · 5. fünfte · 6. sechste · 9. neunte · 10. zehnte · 12. zwölfte · 19. neunzehnte\n\n**Quatre irréguliers** — à apprendre par cœur :\n- 1. → **erste** · 3. → **dritte** · 7. → **siebte** · 8. → **achte**\n\n**À partir de 20** : nombre + **-ste**\n- 20. zwanzigste · 21. einundzwanzigste · 30. dreißigste · 31. einunddreißigste\n\nUn ordinal est un adjectif, il a donc une terminaison : der dritte Mai, am dritten Mai.',
      examples: [
        { de: 'Der erste Mai ist ein Feiertag.', en: 'The first of May is a public holiday.', fr: 'Le premier mai est un jour férié.' },
        { de: 'Heute ist der siebte Juni.', en: 'Today is the seventh of June.', fr: 'Aujourd’hui, nous sommes le sept juin.' },
        { de: 'Der dreißigste April ist ein Montag.', en: 'The thirtieth of April is a Monday.', fr: 'Le trente avril tombe un lundi.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l19-datum-am', title: 'Saying the date: am + ordinal, and the months', titleFr: 'Dire la date : am + ordinal, et les mois',
      explanationMd: 'To say **when** something happens on a date, use **am** + ordinal + **-en**:\n\n- Wann hast du Geburtstag? — **Am 3. Mai** = am **dritten** Mai.\n- Am **ersten** Januar · am **achten** März · am **zwanzigsten** Oktober\n\nTo ask for today\'s date: **Der Wievielte ist heute?** — Heute ist **der 12.** (der zwölfte).\n\n**From … to …**: **vom** 1. **bis zum** 14. August = vom ersten bis zum vierzehnten August.\n\nThe months (all **der**): **Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember**. With just the month: **im** Mai.',
      explanationMdFr: 'Pour dire **quand** quelque chose a lieu à une date, utilise **am** + ordinal + **-en** :\n\n- Wann hast du Geburtstag ? — **Am 3. Mai** = am **dritten** Mai.\n- Am **ersten** Januar · am **achten** März · am **zwanzigsten** Oktober\n\nPour demander la date du jour : **Der Wievielte ist heute ?** — Heute ist **der 12.** (der zwölfte).\n\n**Du … au …** : **vom** 1. **bis zum** 14. August = vom ersten bis zum vierzehnten August.\n\nLes mois (tous **der**) : **Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember**. Avec le mois seul : **im** Mai.',
      examples: [
        { de: 'Ich habe am zwölften Juli Geburtstag.', en: 'My birthday is on the twelfth of July.', fr: 'Mon anniversaire est le douze juillet.' },
        { de: 'Die Party ist am fünften August.', en: 'The party is on the fifth of August.', fr: 'La fête a lieu le cinq août.' },
        { de: 'Wir sind vom ersten bis zum vierzehnten August im Urlaub.', en: 'We are on vacation from the first to the fourteenth of August.', fr: 'Nous sommes en vacances du premier au quatorze août.' },
      ] } },

    { kind: 'grammar', note: {
      id: 'l19-wuerde-wuensche', title: 'Wishes with "würde gern / am liebsten" and congratulations', titleFr: 'Les souhaits avec « würde gern / am liebsten » et les félicitations',
      explanationMd: 'To say what you **would like to do**, use **würde** + **gern** (or **am liebsten** = most of all) and an **infinitive at the end**:\n\n- ich **würde** · du **würdest** · er/sie/es **würde**\n- wir **würden** · ihr **würdet** · sie/Sie **würden**\n\nIch **würde gern** reisen. — Ich **würde am liebsten** jeden Tag feiern.\n\nThis sounds softer and more dreamy than "Ich will …".\n\n**Congratulations and good wishes**:\n- **Alles Gute zum Geburtstag!** — Happy birthday!\n- **Herzlichen Glückwunsch!** — Congratulations!\n- **Frohe Weihnachten!** · **Viel Glück!** · **Gute Besserung!**',
      explanationMdFr: 'Pour dire ce que tu **aimerais faire**, utilise **würde** + **gern** (ou **am liebsten** = par-dessus tout) et un **infinitif à la fin** :\n\n- ich **würde** · du **würdest** · er/sie/es **würde**\n- wir **würden** · ihr **würdet** · sie/Sie **würden**\n\nIch **würde gern** reisen. — Ich **würde am liebsten** jeden Tag feiern.\n\nCela sonne plus doux et plus rêveur que « Ich will … ».\n\n**Félicitations et vœux** :\n- **Alles Gute zum Geburtstag !** — Joyeux anniversaire !\n- **Herzlichen Glückwunsch !** — Félicitations !\n- **Frohe Weihnachten !** · **Viel Glück !** · **Gute Besserung !**',
      examples: [
        { de: 'Ich würde gern eine Party machen.', en: 'I would like to throw a party.', fr: 'J’aimerais organiser une fête.' },
        { de: 'Wir würden am liebsten am Meer feiern.', en: 'Most of all we would love to celebrate by the sea.', fr: 'Ce que nous aimerions le plus, c’est fêter au bord de la mer.' },
        { de: 'Alles Gute zum Geburtstag, Lena!', en: 'Happy birthday, Lena!', fr: 'Joyeux anniversaire, Lena !' },
      ] } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l19-e1', prompt: 'How do you say "the third" (3.)?', promptFr: 'Comment dit-on « le troisième » (3.) ?', options: ['der dritte', 'der dreite', 'der drite'], answer: 0, explain: '1., 3., 7. and 8. are irregular: erste, dritte, siebte, achte.', explainFr: '1., 3., 7. et 8. sont irréguliers : erste, dritte, siebte, achte.', hint: 'One of the four irregular ordinals.', hintFr: 'L’un des quatre ordinaux irréguliers.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l19-e2', prompt: 'Der 1. Mai = der ___ Mai.', promptFr: 'Der 1. Mai = der ___ Mai.', answer: 'erste', hint: 'Irregular: not "einte"!', hintFr: 'Irrégulier : pas « einte » !' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l19-e3', pairs: [ { de: 'der siebte', en: '7th', fr: '7e' }, { de: 'der achte', en: '8th', fr: '8e' }, { de: 'der zwölfte', en: '12th', fr: '12e' }, { de: 'der dreißigste', en: '30th', fr: '30e' } ], hint: 'Remember: 20 and above take -ste.', hintFr: 'Rappel : à partir de 20, on met -ste.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l19-e4', prompt: 'Ich habe ___ zwölften Juli Geburtstag.', promptFr: 'Ich habe ___ zwölften Juli Geburtstag.', answer: 'am', hint: 'A date on a specific day: am + ordinal.', hintFr: 'Une date précise : am + ordinal.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l19-e5', prompt: 'How do you say "on the 3rd of May"?', promptFr: 'Comment dit-on « le 3 mai » ?', options: ['am dritten Mai', 'am dritte Mai', 'im dritten Mai'], answer: 0, explain: 'After "am" the ordinal takes -en: am dritten Mai.', explainFr: 'Après « am », l’ordinal prend -en : am dritten Mai.', hint: 'am + ordinal + -en', hintFr: 'am + ordinal + -en' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l19-e6', tokens: ['Geburtstag', 'Ich', 'am', 'habe', 'fünften', 'August'], answer: ['Ich', 'habe', 'am', 'fünften', 'August', 'Geburtstag'], hint: 'Start with "Ich habe", then the date, then "Geburtstag".', hintFr: 'Commence par « Ich habe », puis la date, puis « Geburtstag ».' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l19-e7', prompt: 'Listen. When is the birthday?', promptFr: 'Écoute. Quand est l’anniversaire ?', audio: { ttsText: 'Mein Geburtstag ist am siebzehnten Oktober.' }, options: ['October 17', 'October 7', 'July 17'], optionsFr: ['17 octobre', '7 octobre', '17 juillet'], answer: 0, hint: 'Listen for "siebzehnten" — seven-teen.', hintFr: 'Écoute « siebzehnten » — dix-sept.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l19-e8', prompt: 'Ich ___ am liebsten jeden Tag feiern. (would)', promptFr: 'Ich ___ am liebsten jeden Tag feiern. (je voudrais)', answer: 'würde', hint: 'würde + infinitive at the end', hintFr: 'würde + infinitif à la fin' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l19-e9', prompt: 'It is your friend’s birthday. What do you say?', promptFr: 'C’est l’anniversaire de ton ami. Que dis-tu ?', options: ['Frohe Weihnachten!', 'Alles Gute zum Geburtstag!', 'Gute Besserung!'], answer: 1, explain: '"Alles Gute zum Geburtstag!" is the standard birthday wish.', explainFr: '« Alles Gute zum Geburtstag ! » est le vœu d’anniversaire standard.', hint: 'Look for the word "Geburtstag".', hintFr: 'Cherche le mot « Geburtstag ».' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l19-e10', tokens: ['schlafen', 'am', 'Ich', 'lange', 'liebsten', 'würde'], answer: ['Ich', 'würde', 'am', 'liebsten', 'lange', 'schlafen'], hint: 'The infinitive "schlafen" goes at the very end.', hintFr: 'L’infinitif « schlafen » va tout à la fin.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l19-e11', prompt: 'Listen. What would she like to do?', promptFr: 'Écoute. Qu’aimerait-elle faire ?', audio: { ttsText: 'Ich würde gern nach Italien fahren, aber ich habe keine Zeit.' }, options: ['Travel to Italy', 'Stay at home', 'Go to a party'], optionsFr: ['Voyager en Italie', 'Rester à la maison', 'Aller à une fête'], answer: 0, hint: 'Listen for what comes after "würde gern".', hintFr: 'Écoute ce qui vient après « würde gern ».' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l19-e12', word: 'Datum', answer: 'das', hint: 'Many words ending in -um are neuter.', hintFr: 'Beaucoup de mots en -um sont neutres.' } },

    { kind: 'pronunciation', focus: 'ü, ö, ß and the tricky "chs" in sechste', focusFr: 'ü, ö, ß et le « chs » difficile dans sechste', items: [
      { id: 'l19-wuerde-pron', german: 'würde', english: 'would', french: 'je voudrais', gender: null, syllables: ['WÜR', 'de'], pronunciation: 'VUER-deh', example: { de: 'Ich würde gern kommen.', en: 'I would love to come.', fr: 'J’aimerais venir.' } },
      { id: 'l19-zwoelfte-pron', german: 'zwölfte', english: 'twelfth', french: 'douzième', gender: null, syllables: ['ZWÖLF', 'te'], pronunciation: 'TSVOELF-teh', example: { de: 'Der zwölfte Juli ist ein Samstag.', en: 'The twelfth of July is a Saturday.', fr: 'Le douze juillet tombe un samedi.' } },
      { id: 'l19-dreissigste-pron', german: 'dreißigste', english: 'thirtieth', french: 'trentième', gender: null, syllables: ['DREI', 'ßig', 'ste'], pronunciation: 'DRY-ssikh-steh', example: { de: 'Der dreißigste Juni ist ein Feiertag.', en: 'The thirtieth of June is a holiday.', fr: 'Le trente juin est un jour férié.' } },
      { id: 'l19-sechste-pron', german: 'sechste', english: 'sixth', french: 'sixième', gender: null, syllables: ['SECHS', 'te'], pronunciation: 'ZEKS-teh', example: { de: 'Am sechsten Mai feiern wir.', en: 'On the sixth of May we celebrate.', fr: 'Le six mai, nous fêtons.' } },
      { id: 'l19-glueckwunsch-pron', german: 'Glückwunsch', english: 'congratulations', french: 'félicitations', gender: 'der', syllables: ['GLÜCK', 'wunsch'], pronunciation: 'GLEWK-voonsh', example: { de: 'Herzlichen Glückwunsch!', en: 'Congratulations!', fr: 'Félicitations !' } },
    ] },

    { kind: 'wrapup', summary: 'You can now read and say dates: ordinals (**der erste, dritte, siebte, achte … der dreißigste**), **am** + ordinal + **-en** (am dritten Mai) and the twelve months. You can dream with **ich würde gern / am liebsten + Infinitiv** and congratulate with **Alles Gute zum Geburtstag!** 🎉',
      summaryFr: 'Tu sais maintenant lire et dire des dates : les ordinaux (**der erste, dritte, siebte, achte … der dreißigste**), **am** + ordinal + **-en** (am dritten Mai) et les douze mois. Tu peux rêver avec **ich würde gern / am liebsten + infinitif** et féliciter avec **Alles Gute zum Geburtstag !** 🎉' },
  ],
};
