import type { Lesson } from '../types';

export const lektion3: Lesson = {
  id: 'l3', level: 'A1', module: 1, number: 3,
  title: { de: 'Das ist meine Mutter', en: 'This is my mother', fr: 'C’est ma mère' },
  theme: 'Family, languages & numbers 100–1,000,000',
  themeFr: 'La famille, les langues et les nombres de 100 à 1 000 000',
  goals: ['Talk about your family', 'Say which languages you speak', 'Use possessives (mein/dein)', 'Use the definite article with the right gender'],
  goalsFr: ['Parler de ta famille', 'Dire quelles langues tu parles', 'Utiliser les possessifs (mein/dein)', 'Utiliser l’article défini avec le bon genre'],
  steps: [
    { kind: 'intro', title: 'Willkommen zurück! 👋', titleFr: 'Bon retour ! 👋',
      scene: 'Someone shows a family photo and talks about their parents, siblings and grandparents.',
      sceneFr: 'Quelqu’un montre une photo de famille et parle de ses parents, de sa fratrie et de ses grands-parents.',
      goals: ['Talk about your family', 'Say which languages you speak', 'Use possessives (mein/dein)', 'Use the definite article with the right gender'],
      goalsFr: ['Parler de ta famille', 'Dire quelles langues tu parles', 'Utiliser les possessifs (mein/dein)', 'Utiliser l’article défini avec le bon genre'] },

    { kind: 'vocab', item: { id: 'l3-familie', german: 'die Familie', english: 'the family', french: 'la famille', gender: 'die', syllables: ['fa', 'MI', 'lie'], pronunciation: 'dee fah-MEE-lee-uh', example: { de: 'Meine Familie ist groß.', en: 'My family is big.', fr: 'Ma famille est grande.' } } },
    { kind: 'vocab', item: { id: 'l3-mutter', german: 'die Mutter', english: 'the mother', french: 'la mère', gender: 'die', syllables: ['MUT', 'ter'], pronunciation: 'dee MOO-ter', example: { de: 'Das ist meine Mutter.', en: 'This is my mother.', fr: 'C’est ma mère.' } } },
    { kind: 'vocab', item: { id: 'l3-vater', german: 'der Vater', english: 'the father', french: 'le père', gender: 'der', syllables: ['VA', 'ter'], pronunciation: 'dair FAH-ter', example: { de: 'Das ist mein Vater.', en: 'This is my father.', fr: 'C’est mon père.' } } },
    { kind: 'vocab', item: { id: 'l3-eltern', german: 'die Eltern', english: 'the parents', french: 'les parents', gender: 'die', syllables: ['EL', 'tern'], pronunciation: 'dee EL-tern', example: { de: 'Meine Eltern kommen aus Kamerun.', en: 'My parents come from Cameroon.', fr: 'Mes parents viennent du Cameroun.' } } },
    { kind: 'vocab', item: { id: 'l3-bruder', german: 'der Bruder', english: 'the brother', french: 'le frère', gender: 'der', syllables: ['BRU', 'der'], pronunciation: 'dair BROO-der', example: { de: 'Mein Bruder heißt Paul.', en: 'My brother is called Paul.', fr: 'Mon frère s’appelle Paul.' } } },
    { kind: 'vocab', item: { id: 'l3-schwester', german: 'die Schwester', english: 'the sister', french: 'la sœur', gender: 'die', syllables: ['SCHWES', 'ter'], pronunciation: 'dee SHVES-ter', example: { de: 'Meine Schwester ist Studentin.', en: 'My sister is a student.', fr: 'Ma sœur est étudiante.' } } },
    { kind: 'vocab', item: { id: 'l3-geschwister', german: 'die Geschwister', english: 'the siblings', french: 'les frères et sœurs', gender: 'die', syllables: ['ge', 'SCHWIS', 'ter'], pronunciation: 'dee guh-SHVIS-ter', example: { de: 'Ich habe zwei Geschwister.', en: 'I have two siblings.', fr: 'J’ai deux frères et sœurs.' } } },
    { kind: 'vocab', item: { id: 'l3-sohn', german: 'der Sohn', english: 'the son', french: 'le fils', gender: 'der', syllables: ['SOHN'], pronunciation: 'dair ZOHN', example: { de: 'Mein Sohn ist zehn Jahre alt.', en: 'My son is ten years old.', fr: 'Mon fils a dix ans.' } } },
    { kind: 'vocab', item: { id: 'l3-tochter', german: 'die Tochter', english: 'the daughter', french: 'la fille', gender: 'die', syllables: ['TOCH', 'ter'], pronunciation: 'dee TOKH-ter', example: { de: 'Meine Tochter spricht Englisch.', en: 'My daughter speaks English.', fr: 'Ma fille parle anglais.' } } },
    { kind: 'vocab', item: { id: 'l3-kind', german: 'das Kind', english: 'the child', french: 'l’enfant', gender: 'das', syllables: ['KIND'], pronunciation: 'dahs KINT', example: { de: 'Das Kind spricht Deutsch und Englisch.', en: 'The child speaks German and English.', fr: 'L’enfant parle allemand et anglais.' } } },
    { kind: 'vocab', item: { id: 'l3-grossmutter', german: 'die Großmutter', english: 'the grandmother', french: 'la grand-mère', gender: 'die', syllables: ['GROSS', 'mut', 'ter'], pronunciation: 'dee GROHSS-moo-ter', example: { de: 'Meine Großmutter wohnt in Yaoundé.', en: 'My grandmother lives in Yaoundé.', fr: 'Ma grand-mère habite à Yaoundé.' } } },
    { kind: 'vocab', item: { id: 'l3-grossvater', german: 'der Großvater', english: 'the grandfather', french: 'le grand-père', gender: 'der', syllables: ['GROSS', 'va', 'ter'], pronunciation: 'dair GROHSS-fah-ter', example: { de: 'Mein Großvater ist verheiratet.', en: 'My grandfather is married.', fr: 'Mon grand-père est marié.' } } },

    { kind: 'grammar', note: {
      id: 'l3-artikel', title: 'The definite article: der/die/das', titleFr: 'L’article défini : der/die/das',
      explanationMd: 'Every German noun has a fixed grammatical gender: **der** (masculine), **die** (feminine), or **das** (neuter). You must learn the article together with the noun — der Vater, die Mutter, das Kind.\n\nIn the **plural**, the article is always **die**, no matter what the singular gender is:\n\n- der Bruder → die Brüder\n- die Schwester → die Schwestern\n- das Kind → die Kinder\n\nWords that only exist in the plural, like **die Eltern** (parents) and **die Geschwister** (siblings), also take **die**.',
      explanationMdFr: 'Chaque nom allemand a un genre grammatical fixe : **der** (masculin), **die** (féminin) ou **das** (neutre). Tu dois apprendre l’article en même temps que le nom — der Vater, die Mutter, das Kind.\n\nAu **pluriel**, l’article est toujours **die**, quel que soit le genre au singulier :\n\n- der Bruder → die Brüder\n- die Schwester → die Schwestern\n- das Kind → die Kinder\n\nLes mots qui n’existent qu’au pluriel, comme **die Eltern** (les parents) et **die Geschwister** (les frères et sœurs), prennent aussi **die**.',
      examples: [ { de: 'Der Vater und die Mutter sind die Eltern.', en: 'The father and the mother are the parents.', fr: 'Le père et la mère sont les parents.' }, { de: 'Die Kinder spielen.', en: 'The children are playing.', fr: 'Les enfants jouent.' }, { de: 'Das ist das Kind von Frau Meier.', en: 'That is Mrs Meier’s child.', fr: 'C’est l’enfant de Madame Meier.' } ] } },

    { kind: 'grammar', note: {
      id: 'l3-possessiv', title: 'Possessive articles: mein/dein', titleFr: 'Les articles possessifs : mein/dein',
      explanationMd: 'Possessive articles agree with the **gender** of the noun they describe, just like der/die/das:\n\n- **mein** Vater (der → mein) — my father\n- **meine** Mutter (die → meine) — my mother\n- **mein** Kind (das → mein) — my child\n- Plural: **meine** Eltern — my parents (the plural always uses *meine*)\n\nThe same pattern works for **dein** (your, informal): dein Vater, deine Mutter, dein Kind, deine Eltern.',
      explanationMdFr: 'Les articles possessifs s’accordent avec le **genre** du nom qu’ils décrivent, tout comme der/die/das :\n\n- **mein** Vater (der → mein) — mon père\n- **meine** Mutter (die → meine) — ma mère\n- **mein** Kind (das → mein) — mon enfant\n- Pluriel : **meine** Eltern — mes parents (le pluriel utilise toujours *meine*)\n\nLe même schéma fonctionne avec **dein** (ton/ta, informel) : dein Vater, deine Mutter, dein Kind, deine Eltern.',
      examples: [ { de: 'Das ist mein Vater.', en: 'This is my father.', fr: 'C’est mon père.' }, { de: 'Das ist meine Mutter.', en: 'This is my mother.', fr: 'C’est ma mère.' }, { de: 'Wie heißt dein Bruder?', en: 'What is your brother called?', fr: 'Comment s’appelle ton frère ?' } ] } },

    { kind: 'grammar', note: {
      id: 'l3-pronomen', title: 'Pronouns: er/es/sie', titleFr: 'Les pronoms : er/es/sie',
      explanationMd: 'The pronoun that replaces a noun depends on the noun’s **grammatical gender**, not on whether it is a person:\n\n- **der** Vater → **er** (he)\n- **die** Mutter → **sie** (she)\n- **das** Kind → **es** (it)\n\nThe same rule applies to any der/die/das noun: der Bruder → er, die Schwester → sie, das Kind → es.',
      explanationMdFr: 'Le pronom qui remplace un nom dépend du **genre grammatical** du nom, et non du fait qu’il s’agisse d’une personne :\n\n- **der** Vater → **er** (il)\n- **die** Mutter → **sie** (elle)\n- **das** Kind → **es** (il/elle, neutre)\n\nLa même règle s’applique à tout nom en der/die/das : der Bruder → er, die Schwester → sie, das Kind → es.',
      examples: [ { de: 'Wo ist dein Vater? — Er ist in Deutschland.', en: 'Where is your father? — He is in Germany.', fr: 'Où est ton père ? — Il est en Allemagne.' }, { de: 'Wo ist deine Mutter? — Sie ist zu Hause.', en: 'Where is your mother? — She is at home.', fr: 'Où est ta mère ? — Elle est à la maison.' }, { de: 'Wo ist das Kind? — Es ist hier.', en: 'Where is the child? — It is here.', fr: 'Où est l’enfant ? — Il est là.' } ] } },

    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l3-e1', word: 'Mutter', answer: 'die', hint: 'Think about the noun\'s gender — is it der, die, or das?', hintFr: 'Pense au genre du nom — der, die ou das ?' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l3-e2', word: 'Kind', answer: 'das', hint: 'This is one of the neuter family words.', hintFr: "C'est l'un des mots de famille neutres." } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l3-e3', word: 'Vater', answer: 'der', hint: 'Think about the noun\'s gender — is it der, die, or das?', hintFr: 'Pense au genre du nom — der, die ou das ?' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l3-e4', pairs: [ { de: 'die Mutter', en: 'the mother', fr: 'la mère' }, { de: 'der Vater', en: 'the father', fr: 'le père' }, { de: 'die Geschwister', en: 'the siblings', fr: 'les frères et sœurs' }, { de: 'das Kind', en: 'the child', fr: 'l’enfant' } ], hint: 'These are family members from this lesson\'s vocab — match each to its meaning.', hintFr: 'Ce sont des membres de la famille du vocabulaire de cette leçon — associe chacun à son sens.' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l3-e5', prompt: 'Meine Schwester und mein Bruder sind meine ___. (Geschwister)', answer: 'Geschwister', hint: 'siblings', hintFr: 'frères et sœurs' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l3-e6', tokens: ['ist', 'Das', 'meine', 'Mutter'], answer: ['Das', 'ist', 'meine', 'Mutter'], hint: 'In a German statement, the verb comes second.', hintFr: 'Dans une phrase allemande, le verbe est en deuxième position.' } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l3-e7', prompt: 'Listen. Which languages does the mother speak?', promptFr: 'Écoute. Quelles langues parle la mère ?', audio: { ttsText: 'Das ist meine Familie. Mein Vater heißt Michael, er ist Lehrer. Meine Mutter heißt Nicole, sie spricht Französisch und Englisch.' }, options: ['French and English', 'German and Spanish', 'English and Spanish'], optionsFr: ['Français et anglais', 'Allemand et espagnol', 'Anglais et espagnol'], answer: 0, hint: 'Listen for the two language names right after "sie spricht".', hintFr: 'Écoute les deux langues nommées juste après « sie spricht ».' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l3-e8', prompt: '___ Vater ist Lehrer. (mein)', answer: 'Mein', hint: 'possessive for a der-word', hintFr: 'possessif pour un mot en der' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l3-e9', prompt: '___ Mutter ist Ärztin. (mein)', answer: 'Meine', hint: 'possessive for a die-word', hintFr: 'possessif pour un mot en die' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l3-e10', prompt: 'Which is correct for "my child"?', promptFr: 'Laquelle est correcte pour « mon enfant » ?', options: ['mein Kind', 'meine Kind', 'meiner Kind'], answer: 0, explain: '"Kind" is neuter (das), so the possessive is "mein".', explainFr: '« Kind » est neutre (das), donc le possessif est « mein ».', hint: 'What gender article does "Kind" take — der, die, or das?', hintFr: 'Quel article de genre prend « Kind » — der, die ou das ?' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l3-e11', prompt: 'Which is correct for "your (informal) sister"?', promptFr: 'Laquelle est correcte pour « ta sœur » (informel) ?', options: ['dein Schwester', 'deine Schwester', 'deins Schwester'], answer: 1, explain: '"Schwester" is feminine (die), so the possessive is "deine".', explainFr: '« Schwester » est féminin (die), donc le possessif est « deine ».', hint: 'What gender article does "Schwester" take — der, die, or das?', hintFr: 'Quel article de genre prend « Schwester » — der, die ou das ?' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l3-e12', tokens: ['heißt', 'dein', 'Wie', 'Bruder'], answer: ['Wie', 'heißt', 'dein', 'Bruder'], hint: 'This is a W-question: the question word starts the sentence, then the verb.', hintFr: "C'est une question en W : le mot interrogatif commence la phrase, puis vient le verbe." } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l3-e13', prompt: 'What is the plural definite article for all German nouns, regardless of gender?', promptFr: 'Quel est l’article défini au pluriel pour tous les noms allemands, quel que soit leur genre ?', options: ['der', 'die', 'das'], answer: 1, explain: 'The plural article is always "die": die Kinder, die Eltern, die Geschwister.', explainFr: 'L’article au pluriel est toujours « die » : die Kinder, die Eltern, die Geschwister.', hint: 'The plural article is the same for every noun, no matter its singular gender.', hintFr: "L'article au pluriel est le même pour tous les noms, quel que soit leur genre au singulier." } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l3-e14', prompt: 'Das ist ___ Familie. (die)', answer: 'die', hint: 'definite article for "Familie" (feminine)', hintFr: 'article défini pour « Familie » (féminin)' } },

    { kind: 'vocab', item: { id: 'l3-deutsch', german: 'Deutsch', english: 'German (language)', french: 'l’allemand', gender: null, syllables: ['DEUTSCH'], pronunciation: 'DOYTCH', example: { de: 'Ich spreche Deutsch.', en: 'I speak German.', fr: 'Je parle allemand.' } } },
    { kind: 'vocab', item: { id: 'l3-englisch', german: 'Englisch', english: 'English (language)', french: 'l’anglais', gender: null, syllables: ['ENG', 'lisch'], pronunciation: 'ENG-lish', example: { de: 'Sprichst du Englisch?', en: 'Do you speak English?', fr: 'Parles-tu anglais ?' } } },
    { kind: 'vocab', item: { id: 'l3-franzoesisch', german: 'Französisch', english: 'French (language)', french: 'le français', gender: null, syllables: ['fran', 'ZÖ', 'sisch'], pronunciation: 'frahn-TSÖ-zish', example: { de: 'Meine Schwester spricht Französisch.', en: 'My sister speaks French.', fr: 'Ma sœur parle français.' } } },
    { kind: 'vocab', item: { id: 'l3-spanisch', german: 'Spanisch', english: 'Spanish (language)', french: 'l’espagnol', gender: null, syllables: ['SPA', 'nisch'], pronunciation: 'SHPAH-nish', example: { de: 'Er spricht Spanisch.', en: 'He speaks Spanish.', fr: 'Il parle espagnol.' } } },
    { kind: 'vocab', item: { id: 'l3-sprache', german: 'die Sprache', english: 'the language', french: 'la langue', gender: 'die', syllables: ['SPRA', 'che'], pronunciation: 'dee SHPRAH-khuh', example: { de: 'Deutsch ist eine Sprache.', en: 'German is a language.', fr: 'L’allemand est une langue.' } } },
    { kind: 'vocab', item: { id: 'l3-sprechen', german: 'sprechen', english: 'to speak', french: 'parler', gender: null, syllables: ['SPRE', 'chen'], pronunciation: 'SHPREH-khen', example: { de: 'Wir sprechen Deutsch und Englisch.', en: 'We speak German and English.', fr: 'Nous parlons allemand et anglais.' } } },

    { kind: 'grammar', note: {
      id: 'l3-sprechen-note', title: 'The verb "sprechen" — vowel change e → i', titleFr: 'Le verbe « sprechen » — changement de voyelle e → i',
      explanationMd: '**sprechen** (to speak) changes its stem vowel from **e** to **i** in the **du** and **er/sie/es** forms:\n\n- ich **spreche** — I speak\n- du **sprichst** — you speak\n- er/sie/es **spricht** — he/she/it speaks\n- wir **sprechen** — we speak\n- ihr **sprecht** — you (pl.) speak\n- sie/Sie **sprechen** — they/you speak',
      explanationMdFr: '**sprechen** (parler) change sa voyelle radicale de **e** à **i** aux formes **du** et **er/sie/es** :\n\n- ich **spreche** — je parle\n- du **sprichst** — tu parles\n- er/sie/es **spricht** — il/elle/on parle\n- wir **sprechen** — nous parlons\n- ihr **sprecht** — vous parlez (pluriel)\n- sie/Sie **sprechen** — ils/elles parlent / vous parlez (formel)',
      examples: [ { de: 'Ich spreche Deutsch.', en: 'I speak German.', fr: 'Je parle allemand.' }, { de: 'Sprichst du Englisch?', en: 'Do you speak English?', fr: 'Parles-tu anglais ?' }, { de: 'Sie spricht Französisch und Spanisch.', en: 'She speaks French and Spanish.', fr: 'Elle parle français et espagnol.' } ],
      diagram: 'conjugation-table' } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l3-e15', prompt: 'Which sentence means "I speak German"?', promptFr: 'Quelle phrase signifie « Je parle allemand » ?', options: ['Ich spreche Deutsch.', 'Du sprichst Deutsch.', 'Er spricht Deutsch.'], answer: 0, explain: '"spreche" is the ich-form of sprechen.', explainFr: '« spreche » est la forme ich de sprechen.', hint: 'Which subject pronoun means "I"?', hintFr: 'Quel pronom sujet signifie « je » ?' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l3-e16', prompt: 'Er ___ Spanisch. (sprechen)', answer: 'spricht', hint: 'er-form: vowel change e→i', hintFr: 'forme er : changement de voyelle e→i' } },
    { kind: 'exercise', exercise: { type: 'fillBlank', id: 'l3-e17', prompt: 'Du ___ Französisch. (sprechen)', answer: 'sprichst', hint: 'du-form: vowel change e→i', hintFr: 'forme du : changement de voyelle e→i' } },
    { kind: 'exercise', exercise: { type: 'wordOrder', id: 'l3-e18', tokens: ['Deutsch', 'Ich', 'spreche'], answer: ['Ich', 'spreche', 'Deutsch'], hint: 'In a German statement, the verb comes second.', hintFr: 'Dans une phrase allemande, le verbe est en deuxième position.' } },
    { kind: 'exercise', exercise: { type: 'match', id: 'l3-e19', pairs: [ { de: 'Deutsch', en: 'German', fr: 'allemand' }, { de: 'Englisch', en: 'English', fr: 'anglais' }, { de: 'Französisch', en: 'French', fr: 'français' }, { de: 'Spanisch', en: 'Spanish', fr: 'espagnol' } ], hint: 'These are the four language names from this lesson\'s vocab.', hintFr: 'Ce sont les quatre noms de langues du vocabulaire de cette leçon.' } },
    { kind: 'exercise', exercise: { type: 'articlePicker', id: 'l3-e20', word: 'Sprache', answer: 'die', hint: 'Think about the noun\'s gender — is it der, die, or das?', hintFr: 'Pense au genre du nom — der, die ou das ?' } },

    { kind: 'vocab', item: { id: 'l3-hundert', german: 'hundert', english: 'hundred', french: 'cent', gender: null, syllables: ['HUN', 'dert'], pronunciation: 'HOON-dert', example: { de: 'Hundert plus hundert sind zweihundert.', en: 'One hundred plus one hundred is two hundred.', fr: 'Cent plus cent égalent deux cents.' } } },
    { kind: 'vocab', item: { id: 'l3-tausend', german: 'tausend', english: 'thousand', french: 'mille', gender: null, syllables: ['TAU', 'send'], pronunciation: 'TOW-zent', example: { de: 'Ich zähle von hundert bis tausend.', en: 'I count from a hundred to a thousand.', fr: 'Je compte de cent à mille.' } } },
    { kind: 'vocab', item: { id: 'l3-million', german: 'eine Million', english: 'a million', french: 'un million', gender: null, syllables: ['EI', 'ne', 'Mil', 'li', 'ON'], pronunciation: 'EYE-nuh mil-lee-OHN', example: { de: 'Diese Stadt hat eine Million Einwohner.', en: 'This city has a million inhabitants.', fr: 'Cette ville a un million d’habitants.' } } },
    { kind: 'vocab', item: { id: 'l3-fahren', german: 'fahren', english: 'to drive / to travel', french: 'conduire / voyager', gender: null, syllables: ['FAH', 'ren'], pronunciation: 'FAH-ren', example: { de: 'Wir fahren nach Deutschland.', en: 'We are going to Germany.', fr: 'Nous allons en Allemagne.' } } },

    { kind: 'grammar', note: {
      id: 'l3-fahren-note', title: 'The verb "fahren" — vowel change a → ä', titleFr: 'Le verbe « fahren » — changement de voyelle a → ä',
      explanationMd: '**fahren** (to drive / to travel) changes its stem vowel from **a** to **ä** in the **du** and **er/sie/es** forms:\n\n- ich **fahre** — I drive\n- du **fährst** — you drive\n- er/sie/es **fährt** — he/she/it drives\n- wir **fahren** — we drive\n- ihr **fahrt** — you (pl.) drive\n- sie/Sie **fahren** — they/you drive',
      explanationMdFr: '**fahren** (conduire / voyager) change sa voyelle radicale de **a** à **ä** aux formes **du** et **er/sie/es** :\n\n- ich **fahre** — je conduis\n- du **fährst** — tu conduis\n- er/sie/es **fährt** — il/elle/on conduit\n- wir **fahren** — nous conduisons\n- ihr **fahrt** — vous conduisez (pluriel)\n- sie/Sie **fahren** — ils/elles conduisent / vous conduisez (formel)',
      examples: [ { de: 'Wir fahren nach Deutschland.', en: 'We are going to Germany.', fr: 'Nous allons en Allemagne.' }, { de: 'Fährst du nach Hause?', en: 'Are you going home?', fr: 'Rentres-tu chez toi ?' }, { de: 'Mein Vater fährt nach Yaoundé.', en: 'My father is going to Yaoundé.', fr: 'Mon père va à Yaoundé.' } ],
      diagram: 'conjugation-table' } },

    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l3-e21', prompt: 'Which number is "tausend"?', promptFr: 'Quel est le nombre « tausend » ?', options: ['100', '1.000', '1.000.000'], answer: 1, explain: '"tausend" means one thousand (1.000).', explainFr: '« tausend » signifie mille (1 000).', hint: '"hundert" is 100 and "Million" is much bigger — tausend is in between.', hintFr: '« hundert » c\'est 100 et « Million » est bien plus grand — tausend est entre les deux.' } },
    { kind: 'exercise', exercise: { type: 'multipleChoice', id: 'l3-e22', prompt: 'Which number is "eine Million"?', promptFr: 'Quel est le nombre « eine Million » ?', options: ['100', '1.000', '1.000.000'], answer: 2, explain: '"eine Million" means one million (1.000.000).', explainFr: '« eine Million » signifie un million (1 000 000).', hint: 'This is the biggest of the three numbers.', hintFr: "C'est le plus grand des trois nombres." } },
    { kind: 'exercise', exercise: { type: 'listenChoose', id: 'l3-e23', prompt: 'Listen. Where does the grandmother live?', promptFr: 'Écoute. Où habite la grand-mère ?', audio: { ttsText: 'Das ist meine Familie. Mein Bruder heißt Paul. Meine Großmutter wohnt in Yaoundé.' }, options: ['Yaoundé', 'Deutschland', 'Berlin'], optionsFr: ['Yaoundé', 'Allemagne', 'Berlin'], answer: 0, hint: 'Listen for the place name right after "meine Großmutter wohnt in".', hintFr: 'Écoute le lieu juste après « meine Großmutter wohnt in ».' } },

    { kind: 'pronunciation', focus: 'The "ö" sound in Französisch and the stress on the first part of compound words like Großmutter', focusFr: 'Le son « ö » dans Französisch et l’accent sur la première partie des mots composés comme Großmutter', items: [
      { id: 'l3-franzoesisch-pron', german: 'Französisch', english: 'French (language)', french: 'le français', gender: null, syllables: ['fran', 'ZÖ', 'sisch'], pronunciation: 'frahn-TSÖ-zish', example: { de: 'Meine Schwester spricht Französisch.', en: 'My sister speaks French.', fr: 'Ma sœur parle français.' } },
      { id: 'l3-grossmutter-pron', german: 'die Großmutter', english: 'the grandmother', french: 'la grand-mère', gender: 'die', syllables: ['GROSS', 'mut', 'ter'], pronunciation: 'dee GROHSS-moo-ter', example: { de: 'Meine Großmutter wohnt in Yaoundé.', en: 'My grandmother lives in Yaoundé.', fr: 'Ma grand-mère habite à Yaoundé.' } },
    ] },

    { kind: 'wrapup', summary: 'You can now talk about your family, say which languages you speak with **sprechen**, use **mein/dein** with the correct gender, and use **der/die/das** — including the plural **die**. 🎉',
      summaryFr: 'Tu sais maintenant parler de ta famille, dire quelles langues tu parles avec **sprechen**, utiliser **mein/dein** avec le bon genre, et utiliser **der/die/das** — y compris le pluriel **die**. 🎉' },
  ],
};
