import type { Locale } from './locale-store';

// Every hardcoded UI-chrome string in the app (buttons, labels, headings,
// hints, aria-labels), in English and French. This intentionally does NOT
// cover lesson content (vocab meanings, example translations, grammar or
// exercise text) — that stays as-authored for now; see the i18n foundation
// report for the line between chrome and content.
export const UI = {
  back: { en: 'Back', fr: 'Retour' },
  next: { en: 'Next', fr: 'Suivant' },
  done: { en: 'Done', fr: 'Terminé' },

  openLessonNav: { en: 'Open lesson navigation', fr: 'Ouvrir la navigation de la leçon' },
  closeLessonNav: { en: 'Close lesson navigation', fr: 'Fermer la navigation de la leçon' },
  lessonStepsNav: { en: 'Lesson steps', fr: 'Étapes de la leçon' },
  contents: { en: 'Contents', fr: 'Sommaire' },
  hideContents: { en: 'Hide contents', fr: 'Masquer le sommaire' },
  showContents: { en: 'Show contents', fr: 'Afficher le sommaire' },
  completeEarlierSteps: {
    en: 'Complete the earlier steps to unlock this one',
    fr: 'Termine les étapes précédentes pour déverrouiller celle-ci',
  },

  sayIt: { en: 'say it:', fr: 'prononce :' },
  markDifficult: { en: 'Mark as difficult — save to review', fr: 'Marquer comme difficile — à réviser' },
  savedToReview: { en: 'Saved to review', fr: 'Enregistré pour révision' },
  savedToReviewTapRemove: {
    en: 'Saved to review — tap to remove',
    fr: 'Enregistré pour révision — touche pour retirer',
  },
  saveWordHint: {
    en: "Save this word to your 'Words to review' list on the home page",
    fr: "Enregistre ce mot dans ta liste « Mots à réviser » sur la page d'accueil",
  },

  wordsToReview: { en: 'Words to review', fr: 'Mots à réviser' },
  noWordsYet: {
    en: 'No saved words yet — tap “Als schwierig markieren” (mark as difficult) on a word while learning, and it will appear here.',
    fr: 'Aucun mot enregistré pour l’instant — appuie sur « Als schwierig markieren » (marquer comme difficile) sur un mot pendant l’apprentissage, et il apparaîtra ici.',
  },
  removeWord: { en: 'Remove', fr: 'Supprimer' },
  fromReview: { en: 'from hard words', fr: 'de la liste à réviser' },

  check: { en: 'Check', fr: 'Vérifier' },
  notQuite: { en: 'Not quite.', fr: 'Pas tout à fait.' },
  tip: { en: 'Tip', fr: 'Astuce' },
  tryAgain: { en: 'Try again', fr: 'Réessayer' },
  showAnswer: { en: 'Show answer', fr: 'Voir la réponse' },
  answerLabel: { en: 'Answer', fr: 'Réponse' },
  tapToPair: { en: 'Tap a word, then its meaning', fr: 'Touche un mot, puis sa signification' },
  listenThenChoose: { en: 'Listen, then choose', fr: 'Écoute, puis choisis' },
  playClip: { en: 'Play the clip', fr: 'Écoute le clip' },
  typeYourAnswer: { en: 'Type your answer', fr: 'Tape ta réponse' },
  chooseEllipsis: { en: 'choose…', fr: 'choisis…' },
  reset: { en: 'reset', fr: 'réinitialiser' },

  comingSoon: { en: 'Coming soon', fr: 'Bientôt disponible' },
  review: { en: 'Review', fr: 'Réviser' },
  completeLessonUnlockReview: {
    en: 'Complete the lesson to unlock review',
    fr: 'Termine la leçon pour débloquer la révision',
  },

  inThisLessonYouWill: { en: 'In this lesson you will:', fr: 'Dans cette leçon, tu vas :' },

  pronunciation: { en: 'Pronunciation', fr: 'Prononciation' },

  homeSubtitle: {
    en: 'Your German A1 learning path — work through each lesson, track your progress, and review the words you find hard.',
    fr: 'Ton parcours d’apprentissage de l’allemand A1 — parcours chaque leçon, suis ta progression, et révise les mots que tu trouves difficiles.',
  },

  // Lesson results / celebration
  lessonComplete: { en: 'Lesson complete!', fr: 'Leçon terminée !' },
  greatJob: { en: 'Great work — keep the streak going.', fr: 'Beau travail — continue sur ta lancée.' },
  exercisesCorrect: { en: 'Exercises correct', fr: 'Exercices réussis' },
  wordsLearned: { en: 'Words learned', fr: 'Mots appris' },
  savedForReview: { en: 'Saved to review', fr: 'À réviser' },
  backToHome: { en: 'Back to home', fr: 'Retour à l’accueil' },
  reviewThisLesson: { en: 'Review this lesson', fr: 'Réviser cette leçon' },

  // Audio speed
  playbackSpeed: { en: 'Playback speed', fr: 'Vitesse de lecture' },
  speedNormal: { en: 'Normal speed', fr: 'Vitesse normale' },
  speedSlow: { en: 'Slow speed', fr: 'Vitesse lente' },

  // Home stats + review
  dayStreak: { en: 'day streak', fr: 'jours de suite' },
  dailyGoal: { en: 'Daily goal', fr: 'Objectif du jour' },
  level: { en: 'Level', fr: 'Niveau' },
  reviewDueToday: { en: 'Review due today', fr: 'À réviser aujourd’hui' },
  keepStreakAlive: { en: 'Keep your streak alive', fr: 'Garde ta série active' },
  reviewNow: { en: 'Review now', fr: 'Réviser' },
  wordsDue: { en: 'words due', fr: 'mots à réviser' },

  // Review session
  reviewHeading: { en: 'Review', fr: 'Révision' },
  whatDoesItMean: { en: 'What does this word mean?', fr: 'Que signifie ce mot ?' },
  nothingDue: { en: 'Nothing due right now', fr: 'Rien à réviser pour l’instant' },
  comeBackLater: { en: 'Come back later to keep your words fresh — or mark more words difficult while learning.', fr: 'Reviens plus tard pour entretenir tes mots — ou marque d’autres mots comme difficiles pendant l’apprentissage.' },
  reviewComplete: { en: 'Review complete!', fr: 'Révision terminée !' },
  wordsReviewed: { en: 'Words reviewed', fr: 'Mots révisés' },

  // Settings
  settings: { en: 'Settings', fr: 'Paramètres' },
  openSettings: { en: 'Open settings', fr: 'Ouvrir les paramètres' },
  theme: { en: 'Theme', fr: 'Thème' },
  themeLight: { en: 'Light', fr: 'Clair' },
  themeDark: { en: 'Dark', fr: 'Sombre' },
  language: { en: 'Language', fr: 'Langue' },
  xpPerDay: { en: 'XP / day', fr: 'XP / jour' },
  activity: { en: 'Activity', fr: 'Activité' },
  totalXp: { en: 'Total XP', fr: 'XP total' },
  wordsSaved: { en: 'Saved words', fr: 'Mots enregistrés' },

  // Onboarding
  onboardingTitle: { en: 'Set your daily pace', fr: 'Choisis ton rythme quotidien' },
  onboardingSubtitle: { en: 'How much German do you want to learn each day? You can change this anytime in settings.', fr: 'Combien d’allemand veux-tu apprendre chaque jour ? Modifiable à tout moment dans les paramètres.' },
  startLearning: { en: 'Start learning', fr: 'Commencer' },
  goalRelaxed: { en: 'Relaxed', fr: 'Tranquille' },
  goalRegular: { en: 'Regular', fr: 'Régulier' },
  goalSerious: { en: 'Serious', fr: 'Sérieux' },
  goalIntense: { en: 'Intense', fr: 'Intense' },

  // Speaking practice
  speak: { en: 'Speak', fr: 'Parler' },
  listening: { en: 'Listening…', fr: 'Écoute…' },
  soundsGood: { en: 'Sounds good!', fr: 'Bien prononcé !' },
  notQuiteHeard: { en: 'Heard', fr: 'Entendu' },

  // Top navigation / shell
  navHome: { en: 'Home', fr: 'Accueil' },
  navTextbook: { en: 'Textbook', fr: 'Manuel' },
  navStatistics: { en: 'Statistics', fr: 'Statistiques' },
  navGames: { en: 'Games', fr: 'Jeux' },
  navSprint: { en: 'Sprint', fr: 'Sprint' },
  navAudioCall: { en: 'Audio-Call', fr: 'Audio-Call' },
  navReview: { en: 'Review', fr: 'Révision' },
  start: { en: 'Start', fr: 'Commencer' },
  continue: { en: 'Continue', fr: 'Continuer' },
  yourCourse: { en: 'Your course', fr: 'Ton cours' },
  lektionen: { en: 'lessons', fr: 'leçons' },

  // Games
  sprintTitle: { en: 'Word Sprint', fr: 'Sprint de mots' },
  sprintTagline: { en: 'How many words can you match before the clock runs out?', fr: 'Combien de mots peux-tu associer avant la fin du chrono ?' },
  audioTitle: { en: 'Audio-Call', fr: 'Audio-Call' },
  audioTagline: { en: 'Listen, then tap the word you hear. Train your ear against the clock.', fr: 'Écoute, puis tape le mot entendu. Entraîne ton oreille contre le chrono.' },
  howToPlaySprint: { en: 'You have 60 seconds. Read the German word and tap its meaning. Each correct answer adds time — keep the streak alive!', fr: 'Tu as 60 secondes. Lis le mot allemand et tape son sens. Chaque bonne réponse ajoute du temps — garde la cadence !' },
  howToPlayAudio: { en: 'You have 60 seconds. Listen to the German word and tap the matching meaning. Tap the speaker to replay.', fr: 'Tu as 60 secondes. Écoute le mot allemand et tape le sens correspondant. Tape le haut-parleur pour réécouter.' },
  gamesHubTitle: { en: 'Games', fr: 'Jeux' },
  gamesHubSubtitle: { en: 'Short, fast rounds that lock your vocabulary in. Every point is XP.', fr: 'Des parties courtes et rapides qui fixent ton vocabulaire. Chaque point vaut des XP.' },
  reviewGameTitle: { en: 'Review queue', fr: 'File de révision' },
  reviewGameTagline: { en: 'Words that are due today, spaced so you remember them for good.', fr: 'Les mots à revoir aujourd’hui, espacés pour que tu les retiennes pour de bon.' },
  playNow: { en: 'Play', fr: 'Jouer' },
  startReview: { en: 'Start review', fr: 'Réviser' },
  startGame: { en: 'Start game', fr: 'Commencer' },
  playAgain: { en: 'Play again', fr: 'Rejouer' },
  backToGames: { en: 'Back to games', fr: 'Retour aux jeux' },
  timeLeft: { en: 'Time', fr: 'Temps' },
  score: { en: 'Score', fr: 'Score' },
  best: { en: 'Best', fr: 'Record' },
  newBest: { en: 'New best!', fr: 'Nouveau record !' },
  yourScore: { en: 'Your score', fr: 'Ton score' },
  tapWhatYouHear: { en: 'Tap the word you hear', fr: 'Tape le mot que tu entends' },
  replayAudio: { en: 'Replay', fr: 'Réécouter' },
  xpEarned: { en: 'XP earned', fr: 'XP gagnés' },

  // Statistics
  statsTitle: { en: 'Your statistics', fr: 'Tes statistiques' },
  statsSubtitle: { en: 'Every answer, streak and word you’ve learned so far.', fr: 'Chaque réponse, série et mot appris jusqu’ici.' },
  currentLevel: { en: 'Level', fr: 'Niveau' },
  lessonsDone: { en: 'Lessons done', fr: 'Leçons finies' },
  accuracy: { en: 'Accuracy', fr: 'Précision' },
  activityHeading: { en: 'Activity', fr: 'Activité' },
  last12Weeks: { en: 'Last 12 weeks', fr: '12 dernières semaines' },
  byLevelHeading: { en: 'Progress by level', fr: 'Progression par niveau' },
  noActivityYet: { en: 'Start a lesson to see your activity here.', fr: 'Commence une leçon pour voir ton activité ici.' },
  xpToNext: { en: 'XP to next level', fr: 'XP avant le niveau suivant' },
  navDictionary: { en: 'Dictionary', fr: 'Dictionnaire' },
  myWords: { en: 'My words', fr: 'Mes mots' },
  dictSubtitle: { en: 'Look up any German word, or search in English. Genders, plurals, verb forms and examples included.', fr: 'Cherche n’importe quel mot allemand, ou tape un mot en anglais. Genres, pluriels, formes verbales et exemples inclus.' },
  dictPlaceholder: { en: 'Search German or English…', fr: 'Chercher en allemand ou en anglais…' },
  dictTypeMin: { en: 'Type at least 2 letters to start searching.', fr: 'Tape au moins 2 lettres pour lancer la recherche.' },
  dictTypeMore: { en: 'Keep typing: this word needs at least 3 letters.', fr: 'Continue de taper : il faut au moins 3 lettres.' },
  dictNoResults: { en: 'No matches. Check the spelling, or try the English word.', fr: 'Aucun résultat. Vérifie l’orthographe ou essaie le mot anglais.' },
  dictLoadError: { en: 'Couldn’t load the dictionary. Check your connection and try again.', fr: 'Impossible de charger le dictionnaire. Vérifie ta connexion et réessaie.' },
  dictFormOf: { en: 'is a form of', fr: 'est une forme de' },
  dictEnglishMatch: { en: 'English match', fr: 'Correspondance anglaise' },
  dictDidYouMean: { en: 'Did you mean', fr: 'Tu voulais dire' },
  dictPlural: { en: 'Plural', fr: 'Pluriel' },
  dictGenitive: { en: 'Genitive', fr: 'Génitif' },
  dictForms: { en: 'Forms', fr: 'Formes' },
  dictExample: { en: 'Example', fr: 'Exemple' },
  dictInLessons: { en: 'In your lessons', fr: 'Dans tes leçons' },
  dictEnglishOnly: { en: 'Extra dictionary meanings are in English.', fr: 'Les définitions du dictionnaire sont en anglais.' },
  dictAttribution: { en: 'Dictionary data from Wiktionary (CC BY-SA 4.0), extracted by kaikki.org / wiktextract.', fr: 'Données du dictionnaire issues de Wiktionary (CC BY-SA 4.0), extraites par kaikki.org / wiktextract.' },
  dictSearching: { en: 'Searching…', fr: 'Recherche…' },
  dictListen: { en: 'Listen', fr: 'Écouter' },
  dictStarHint: { en: 'Star it to add it to your review words', fr: 'Ajoute-le en favori pour le réviser' },
  dictOpenWord: { en: 'Open word page', fr: 'Ouvrir la fiche du mot' },
  dictBackToSearch: { en: 'Back to search', fr: 'Retour à la recherche' },
  dictWordNotFound: { en: 'We couldn’t find this word in the dictionary.', fr: 'Nous n’avons pas trouvé ce mot dans le dictionnaire.' },
  dictInOurLessons: { en: 'In our lessons', fr: 'Dans nos leçons' },
  dictMeanings: { en: 'Meanings', fr: 'Sens' },
  dictCheckForms: { en: 'These forms are generated by rules and may be wrong for this verb. Check a reliable source before using them.', fr: 'Ces formes sont générées par des règles et peuvent être fausses pour ce verbe. Vérifie-les dans une source fiable avant de les utiliser.' },
  dictCaseTable: { en: 'Declension', fr: 'Déclinaison' },
  dictComparison: { en: 'Comparison', fr: 'Comparaison' },
  tensePraesens: { en: 'Present (Präsens)', fr: 'Présent (Präsens)' },
  tensePraeteritum: { en: 'Simple past (Präteritum)', fr: 'Prétérit (Präteritum)' },
  tensePerfekt: { en: 'Present perfect (Perfekt)', fr: 'Passé composé (Perfekt)' },
  tensePlusquamperfekt: { en: 'Past perfect (Plusquamperfekt)', fr: 'Plus-que-parfait (Plusquamperfekt)' },
  tenseFutur1: { en: 'Future (Futur I)', fr: 'Futur (Futur I)' },
  tenseFutur2: { en: 'Future perfect (Futur II)', fr: 'Futur antérieur (Futur II)' },
  tenseKonj1: { en: 'Subjunctive I (Konjunktiv I)', fr: 'Subjonctif I (Konjunktiv I)' },
  tenseKonj2: { en: 'Subjunctive II (Konjunktiv II)', fr: 'Subjonctif II (Konjunktiv II)' },
  tenseImperativ: { en: 'Imperative (Imperativ)', fr: 'Impératif (Imperativ)' },
  tensePassiv: { en: 'Passive (Passiv)', fr: 'Passif (Passiv)' },
  dictTenses: { en: 'Tenses', fr: 'Temps' },
  dictHowToForm: { en: 'How it is formed', fr: 'Comment on la forme' },
  dictWhenToUse: { en: 'When to use it', fr: 'Quand l’utiliser' },
  dictLearnMoreSpecial: { en: 'Full special course', fr: 'Cours spécial complet' },
  dictAuxBoth: { en: 'This verb takes haben or sein depending on its meaning.', fr: 'Ce verbe se conjugue avec haben ou sein selon son sens.' },
  dictSeparableNote: { en: 'Separable verb: the prefix goes to the end of the main clause.', fr: 'Verbe séparable : le préfixe passe à la fin de la proposition principale.' },
  dictWuerdeForm: { en: 'Everyday alternative with würde + infinitive', fr: 'Alternative courante avec würde + infinitif' },
  dictPassivPast: { en: 'Passive in the past', fr: 'Passif au passé' },
  dictPassivPraeteritum: { en: 'Past (Präteritum)', fr: 'Prétérit (Präteritum)' },
  dictPassivPerfekt: { en: 'Perfect (Perfekt)', fr: 'Parfait (Perfekt)' },
  dictPlay: { en: 'Play', fr: 'Écouter' },
  caseNom: { en: 'Nominative', fr: 'Nominatif' },
  caseAcc: { en: 'Accusative', fr: 'Accusatif' },
  caseDat: { en: 'Dative', fr: 'Datif' },
  caseGen: { en: 'Genitive', fr: 'Génitif' },
  numSingular: { en: 'Singular', fr: 'Singulier' },
  numPlural: { en: 'Plural', fr: 'Pluriel' },
  dictPluralMissing: { en: 'This noun is usually not used in the plural.', fr: 'Ce nom ne s’emploie généralement pas au pluriel.' },
  dictGenderAmbiguous: { en: 'This noun has more than one gender; the first one is shown.', fr: 'Ce nom a plusieurs genres ; le premier est affiché.' },
  dictPositive: { en: 'Base form', fr: 'Forme de base' },
  dictComparative: { en: 'Comparative', fr: 'Comparatif' },
  dictSuperlative: { en: 'Superlative', fr: 'Superlatif' },
  dictIrregularComparison: { en: 'Irregular comparison', fr: 'Comparaison irrégulière' },
  dictLoadingWord: { en: 'Loading word…', fr: 'Chargement du mot…' },
  dictOpenLessonLink: { en: 'Open lesson', fr: 'Ouvrir la leçon' },
  dictLearnMore: { en: 'Learn more', fr: 'Pour aller plus loin' },
  dictLearnMoreTenses: { en: 'Verb tenses in detail', fr: 'Les temps verbaux en détail' },
  dictFromLessonsOnly: { en: 'This word comes from our lessons. Dictionary details are not available for it.', fr: 'Ce mot vient de nos leçons. Les détails du dictionnaire ne sont pas disponibles pour lui.' },
  dictSearchAnother: { en: 'Search another word', fr: 'Chercher un autre mot' },
  dictResultsCount: { en: 'results', fr: 'résultats' },
  posNoun: { en: 'noun', fr: 'nom' },
  posVerb: { en: 'verb', fr: 'verbe' },
  posAdj: { en: 'adjective', fr: 'adjectif' },
  posAdv: { en: 'adverb', fr: 'adverbe' },
  posPrep: { en: 'preposition', fr: 'préposition' },
  posConj: { en: 'conjunction', fr: 'conjonction' },
  posPron: { en: 'pronoun', fr: 'pronom' },
  posNum: { en: 'numeral', fr: 'numéral' },
  posIntj: { en: 'interjection', fr: 'interjection' },
  posDet: { en: 'article / determiner', fr: 'article / déterminant' },
  posPart: { en: 'particle', fr: 'particule' },
  login: { en: 'Login', fr: 'Connexion' },
  signUpNav: { en: 'Sign Up', fr: 'S’inscrire' },
  openMenu: { en: 'Open menu', fr: 'Ouvrir le menu' },
  speedTask: { en: 'speed task', fr: 'épreuve de vitesse' },
  auditionTask: { en: 'audition task', fr: 'épreuve d’écoute' },
  forTheDay: { en: 'For the day', fr: 'Aujourd’hui' },
  forAllTime: { en: 'For all the time', fr: 'Depuis le début' },
  wordsStudied: { en: 'words studied', fr: 'mots étudiés' },
  correctAnswers: { en: 'correct answers', fr: 'bonnes réponses' },
  addToLearned: { en: 'Add to learned', fr: 'Marquer comme appris' },
  removeFromDict: { en: 'Remove from dictionary', fr: 'Retirer du dictionnaire' },
  nextPage: { en: 'Next page', fr: 'Page suivante' },
  easy: { en: 'Easy', fr: 'Facile' },
  medium: { en: 'Medium', fr: 'Moyen' },
  hard: { en: 'Hard', fr: 'Difficile' },

  // Account / sync
  account: { en: 'Account', fr: 'Compte' },
  signIn: { en: 'Sign in', fr: 'Se connecter' },
  signUp: { en: 'Create account', fr: 'Créer un compte' },
  signOut: { en: 'Sign out', fr: 'Se déconnecter' },
  emailLabel: { en: 'Email', fr: 'E-mail' },
  passwordLabel: { en: 'Password', fr: 'Mot de passe' },
  syncOn: { en: 'Your progress syncs across your devices.', fr: 'Ta progression est synchronisée sur tes appareils.' },
  signInToSync: { en: 'Sign in to sync your progress across devices', fr: 'Connecte-toi pour synchroniser ta progression sur tes appareils' },
  checkEmailConfirm: { en: 'Almost there — check your email to confirm your account, then sign in.', fr: 'Presque fini — vérifie ta boîte mail pour confirmer ton compte, puis connecte-toi.' },
  toggleToSignIn: { en: 'Already have an account? Sign in', fr: 'Déjà un compte ? Se connecter' },
  toggleToSignUp: { en: 'New here? Create an account', fr: 'Nouveau ? Créer un compte' },
  deleteData: { en: 'Delete my synced data', fr: 'Supprimer mes données synchronisées' },
  // Speak & Write studios
  navSpeak: { en: 'Speak', fr: 'Parler' },
  navWrite: { en: 'Write', fr: 'Écrire' },
  speakTitle: { en: 'Speak', fr: 'Parler' },
  speakSubtitle: { en: 'Listen, repeat, and get word-by-word feedback on your pronunciation.', fr: 'Écoute, répète et obtiens un retour mot par mot sur ta prononciation.' },
  speakModeRepeat: { en: 'Listen & repeat', fr: 'Écouter et répéter' },
  speakModeRead: { en: 'Read aloud', fr: 'Lire à voix haute' },
  speakListen: { en: 'Listen', fr: 'Écouter' },
  speakListenAfter: { en: 'Hear it', fr: 'Écouter' },
  speakTap: { en: 'Tap and say the sentence', fr: 'Touche et dis la phrase' },
  speakStop: { en: 'Tap to stop', fr: 'Touche pour arrêter' },
  speakScore: { en: 'Score', fr: 'Score' },
  speakGreat: { en: 'Excellent!', fr: 'Excellent !' },
  speakAlmost: { en: 'Almost there', fr: 'Presque' },
  speakRetry: { en: 'Give it another go', fr: 'Réessaie encore' },
  speakYouSaid: { en: 'You said', fr: 'Tu as dit' },
  speakExtra: { en: 'Extra words', fr: 'Mots en trop' },
  speakLegend: { en: 'Green: clear · Amber: close · Red: missed', fr: 'Vert : clair · Orange : proche · Rouge : manqué' },
  speakUnsupported: { en: "Speech recognition isn't available in this browser. Open this page in Chrome or Edge to practise speaking. You can still listen to every sentence.", fr: "La reconnaissance vocale n'est pas disponible dans ce navigateur. Ouvre cette page dans Chrome ou Edge pour t'entraîner à parler. Tu peux quand même écouter chaque phrase." },
  speakDenied: { en: 'Microphone access is blocked. Allow the microphone in your browser settings, then try again.', fr: "L'accès au micro est bloqué. Autorise le micro dans les réglages du navigateur, puis réessaie." },
  speakNoSpeech: { en: "I didn't hear anything. Tap the mic and try again.", fr: "Je n'ai rien entendu. Touche le micro et réessaie." },
  speakNetwork: { en: "The speech service couldn't be reached. Check your connection.", fr: "Le service vocal est injoignable. Vérifie ta connexion." },
  speakOther: { en: 'Something went wrong with the microphone. Try again.', fr: 'Un problème est survenu avec le micro. Réessaie.' },
  speakSetDone: { en: 'Set complete', fr: 'Série terminée' },
  speakAverage: { en: 'Average score', fr: 'Score moyen' },
  speakNewSet: { en: 'New set', fr: 'Nouvelle série' },
  speakPrivacy: { en: "Your voice is processed by your browser's speech service (Google, in Chrome). This app never receives or stores recordings.", fr: "Ta voix est traitée par le service vocal de ton navigateur (Google, dans Chrome). Cette appli ne reçoit ni ne conserve d'enregistrements." },
  speakShowMeaning: { en: 'Show meaning', fr: 'Voir le sens' },
  speakSkip: { en: 'Skip', fr: 'Passer' },
  writeTitle: { en: 'Write', fr: 'Écrire' },
  writeSubtitle: { en: 'Write in German and get live grammar and spelling feedback.', fr: "Écris en allemand et reçois des corrections de grammaire et d'orthographe en direct." },
  writeChooseTask: { en: 'Choose a task', fr: 'Choisis un exercice' },
  writeFree: { en: 'Free writing', fr: 'Écriture libre' },
  writeFreeTask: { en: 'Write anything you like: a diary entry, a message, a story.', fr: "Écris ce que tu veux : un journal, un message, une histoire." },
  writePlaceholder: { en: 'Start writing in German…', fr: 'Commence à écrire en allemand…' },
  writeUsefulPhrases: { en: 'Useful phrases', fr: 'Expressions utiles' },
  wordsUnit: { en: 'words', fr: 'mots' },
  writeGoal: { en: 'Goal', fr: 'Objectif' },
  writeChecking: { en: 'Checking…', fr: 'Vérification…' },
  writeAllGood: { en: 'No issues found', fr: 'Aucun problème trouvé' },
  writeIssuesUnit: { en: 'to review', fr: 'à revoir' },
  writePaused: { en: 'Checking paused: too many requests. It will resume in a moment.', fr: 'Vérification en pause : trop de requêtes. Elle reprendra dans un instant.' },
  writeCheckError: { en: "Couldn't reach the grammar checker. Your text is safe; we'll retry as you type.", fr: "Impossible de joindre le correcteur. Ton texte est en sécurité ; on réessaiera pendant que tu écris." },
  writeTooLong: { en: 'Only the first 2,000 characters are checked.', fr: 'Seuls les 2 000 premiers caractères sont vérifiés.' },
  writeIgnore: { en: 'Ignore', fr: 'Ignorer' },
  writeWhy: { en: 'Why?', fr: 'Pourquoi ?' },
  writeWhyLoading: { en: 'Thinking…', fr: 'Réflexion…' },
  writeWhyError: { en: 'Explanations are unavailable right now.', fr: 'Les explications sont indisponibles pour le moment.' },
  writeSuggestions: { en: 'Suggestions', fr: 'Suggestions' },
  writePrivacy: { en: 'Grammar check by LanguageTool. Your text is sent to languagetool.org while you write. This app does not store it.', fr: "Correction par LanguageTool. Ton texte est envoyé à languagetool.org pendant que tu écris. Cette appli ne le conserve pas." },
  writeFinish: { en: 'Finish', fr: 'Terminer' },
  writeMoreWords: { en: 'more words to finish', fr: 'mots de plus pour terminer' },
  writeDone: { en: 'Nice work!', fr: 'Bravo !' },
  writeXpAlready: { en: "You've already earned XP for this task today.", fr: "Tu as déjà gagné des XP pour cet exercice aujourd'hui." },
  writeDraftSaved: { en: 'Draft saved on this device', fr: 'Brouillon enregistré sur cet appareil' },
  writeClear: { en: 'Clear', fr: 'Effacer' },
  writeKeepEditing: { en: 'Keep editing', fr: 'Continuer' },
  footerCredits: { en: 'Grammar checking by', fr: 'Correction grammaticale par' },
  writeKindSpelling: { en: 'Spelling', fr: 'Orthographe' },
  writeKindGrammar: { en: 'Grammar', fr: 'Grammaire' },
  writeKindStyle: { en: 'Style', fr: 'Style' },
  writeStale: { en: 'Updating suggestions…', fr: 'Mise à jour des suggestions…' },
  assistExplain: { en: 'Explain more', fr: 'Expliquer' },
  assistExamples: { en: '5 more examples', fr: '5 autres exemples' },
  assistQuiz: { en: 'Quiz me', fr: 'Teste-moi' },
  assistUnavailable: { en: 'Assist is unavailable right now.', fr: "L'assistant est indisponible pour le moment." },
  assistError: { en: 'Something went wrong asking for assist. Please try again.', fr: "Un problème est survenu avec l'assistant. Réessaie." },
  deleteDataConfirm: { en: 'Permanently delete your synced cloud data? Your local progress on this device stays.', fr: 'Supprimer définitivement tes données synchronisées ? Ta progression locale sur cet appareil reste.' },
  chapterLabel: { en: 'Chapter', fr: 'Chapitre' },
  quizLabel: { en: 'Final quiz', fr: 'Quiz final' },
  quizQuestions: { en: 'questions', fr: 'questions' },
  quizPassMark: { en: 'pass mark', fr: 'seuil de réussite' },
  quizRetake: { en: 'You can retake it as often as you like — your best result counts.', fr: 'Tu peux le refaire autant que tu veux — ton meilleur résultat compte.' },
  quizPassed: { en: 'Quiz passed', fr: 'Quiz réussi' },
  quizNotPassed: { en: 'Not passed yet', fr: 'Pas encore réussi' },
  quizScore: { en: 'Quiz score', fr: 'Score du quiz' },
  retakeQuiz: { en: 'Retake the quiz', fr: 'Refaire le quiz' },
  backToSpecial: { en: 'Back to the special', fr: 'Retour au spécial' },
  reviewThisSpecial: { en: 'Review this special', fr: 'Réviser ce spécial' },
  navSpecials: { en: 'Specials', fr: 'Spéciaux' },
  specialsTitle: { en: 'Special courses', fr: 'Cours spéciaux' },
  specialsSubtitle: { en: 'Short, focused courses on one topic — modal verbs, cases, colours, the body and more — each with its own final quiz.', fr: 'Des cours courts sur un seul sujet — verbes modaux, cas, couleurs, le corps et plus — chacun avec son quiz final.' },
  specialsAll: { en: 'All', fr: 'Tous' },
  specialsGroupFilter: { en: 'Filter by topic', fr: 'Filtrer par thème' },
  specialsChapters: { en: 'chapters', fr: 'chapitres' },
  specialsExercises: { en: 'exercises', fr: 'exercices' },
  specialsWords: { en: 'words', fr: 'mots' },
  specialsStart: { en: 'Start course', fr: 'Commencer le cours' },
  specialsContinue: { en: 'Continue course', fr: 'Continuer le cours' },
  specialsReviewCta: { en: 'Review the content', fr: 'Relire le contenu' },
  specialsInside: { en: 'What is inside', fr: 'Au programme' },
  specialsBuildsOn: { en: 'Builds on lessons', fr: 'S’appuie sur les leçons' },
  specialsBookPages: { en: 'Go deeper in the textbook', fr: 'Pour aller plus loin dans le manuel' },
  specialsBackToHub: { en: 'All special courses', fr: 'Tous les cours spéciaux' },
  specialsRelatedHeading: { en: 'Go further with a special course', fr: 'Va plus loin avec un cours spécial' },
  specialsEmpty: { en: 'Nothing here yet.', fr: 'Rien ici pour l’instant.' },
  specialsRowTitle: { en: 'Special courses', fr: 'Cours spéciaux' },
  specialsSeeAll: { en: 'See all', fr: 'Tout voir' },
} as const;

export type UIKey = keyof typeof UI;

export function t(key: UIKey, locale: Locale): string {
  return UI[key][locale];
}
