import { defineSpecial, intro, chapter, vocab, grammar, mc, fb, wo, match, ap, lc, wrapup, quiz } from './kit';

export const koerperGesundheit = defineSpecial({
  slug: 'koerper-gesundheit',
  number: 22,
  group: 'words',
  levels: ['A1', 'A2'],
  related: ['l10'],
  title: ['Körper & Gesundheit', 'Body & health', 'Corps & santé'],
  theme: [
    'Body parts, “weh tun” and “-schmerzen”, at the doctor’s and at the pharmacy, health advice',
    'Parties du corps, « weh tun » et « -schmerzen », chez le médecin et à la pharmacie, conseils de santé',
  ],
  goals: [
    'Name the main parts of the body with article and plural',
    'Say where it hurts with weh tun and -schmerzen',
    'Describe symptoms and make a doctor’s appointment',
    'Understand the doctor’s questions: Was fehlt Ihnen? Seit wann?',
    'Give and understand simple health advice (Sie sollten …, Nehmen Sie …)',
  ],
  goalsFr: [
    'Nommer les principales parties du corps avec article et pluriel',
    'Dire où l’on a mal avec weh tun et -schmerzen',
    'Décrire des symptômes et prendre rendez-vous chez le médecin',
    'Comprendre les questions du médecin : Was fehlt Ihnen ? Seit wann ?',
    'Donner et comprendre des conseils de santé simples (Sie sollten …, Nehmen Sie …)',
  ],
  steps: [
    intro(
      'Ich bin krank', 'Je suis malade',
      'You wake up with a sore throat and a fever. In Germany you ring the practice, make an appointment, explain what hurts and then collect your medicine at the pharmacy. This special gives you every word and phrase for that whole journey.',
      'Tu te réveilles avec mal à la gorge et de la fièvre. En Allemagne, tu appelles le cabinet, tu prends rendez-vous, tu expliques où tu as mal, puis tu retires tes médicaments à la pharmacie. Ce spécial te donne tous les mots et toutes les tournures pour ce parcours.',
      [
        'Body parts with der/die/das and plural',
        'Where it hurts: weh tun and -schmerzen',
        'Symptoms: Fieber, Husten, Erkältung',
        'Doctor’s visit and appointment dialogue',
        'Pharmacy and advice with sollen and the imperative',
      ],
      [
        'Les parties du corps avec der/die/das et le pluriel',
        'Où l’on a mal : weh tun et -schmerzen',
        'Symptômes : Fieber, Husten, Erkältung',
        'Visite chez le médecin et dialogue pour un rendez-vous',
        'Pharmacie et conseils avec sollen et l’impératif',
      ],
    ),

    // ── Chapter 1 ────────────────────────────────────────────────
    chapter(
      'Head and face', 'La tête et le visage',
      'The first body words you need — and their articles.', 'Les premiers mots du corps dont tu as besoin — et leurs articles.',
    ),
    vocab('sp-koerper-gesundheit-kopf', 'der Kopf', 'the head', 'la tête', 'der', 'KOPF', 'dair KOPF', ['Mein Kopf tut weh.', 'My head hurts.', 'J’ai mal à la tête.']),
    vocab('sp-koerper-gesundheit-gesicht', 'das Gesicht', 'the face', 'le visage', 'das', 'ge-SICHT', 'dahs geh-ZIKHT', ['Du hast ein freundliches Gesicht.', 'You have a friendly face.', 'Tu as un visage sympathique.']),
    vocab('sp-koerper-gesundheit-auge', 'das Auge', 'the eye', 'l’œil', 'das', 'AU-ge', 'dahs OW-geh', ['Meine Augen sind braun.', 'My eyes are brown.', 'Mes yeux sont marron.']),
    vocab('sp-koerper-gesundheit-ohr', 'das Ohr', 'the ear', 'l’oreille', 'das', 'OHR', 'dahs OHR', ['Das linke Ohr tut mir weh.', 'My left ear hurts.', 'J’ai mal à l’oreille gauche.']),
    vocab('sp-koerper-gesundheit-nase', 'die Nase', 'the nose', 'le nez', 'die', 'NA-se', 'dee NAH-zeh', ['Meine Nase ist verstopft.', 'My nose is blocked.', 'J’ai le nez bouché.']),
    vocab('sp-koerper-gesundheit-mund', 'der Mund', 'the mouth', 'la bouche', 'der', 'MUND', 'dair MOONT', ['Bitte öffnen Sie den Mund.', 'Please open your mouth.', 'Ouvrez la bouche, s’il vous plaît.']),
    vocab('sp-koerper-gesundheit-zahn', 'der Zahn', 'the tooth', 'la dent', 'der', 'ZAHN', 'dair TSAHN', ['Ich putze meine Zähne zweimal am Tag.', 'I brush my teeth twice a day.', 'Je me brosse les dents deux fois par jour.']),
    vocab('sp-koerper-gesundheit-hals', 'der Hals', 'the neck, the throat', 'le cou, la gorge', 'der', 'HALS', 'dair HAHLS', ['Mein Hals ist ganz rot.', 'My throat is all red.', 'Ma gorge est toute rouge.']),
    ap('sp-kg-e1', 'Kopf', 'der', ['Kopf is masculine: der Kopf.', 'Kopf est masculin : der Kopf.']),
    ap('sp-kg-e2', 'Auge', 'das', ['Auge is neuter, even though it ends in -e.', 'Auge est neutre, même s’il finit par -e.']),
    ap('sp-kg-e3', 'Nase', 'die', ['Nase ends in -e and is feminine.', 'Nase finit par -e et est féminin.']),
    ap('sp-kg-e4', 'Zahn', 'der', ['Zahn is masculine; the plural is die Zähne.', 'Zahn est masculin ; le pluriel est die Zähne.']),
    match(
      'sp-kg-e5',
      [
        ['der Kopf', 'the head', 'la tête'],
        ['das Auge', 'the eye', 'l’œil'],
        ['das Ohr', 'the ear', 'l’oreille'],
        ['die Nase', 'the nose', 'le nez'],
        ['der Mund', 'the mouth', 'la bouche'],
        ['der Zahn', 'the tooth', 'la dent'],
      ],
      ['Match each body part with its translation.', 'Associe chaque partie du corps à sa traduction.'],
    ),

    // ── Chapter 2 ────────────────────────────────────────────────
    chapter(
      'Arms, legs and the rest', 'Bras, jambes et le reste',
      'The rest of the body — and the plurals you need to know.', 'Le reste du corps — et les pluriels à connaître.',
    ),
    vocab('sp-koerper-gesundheit-arm', 'der Arm', 'the arm', 'le bras', 'der', 'ARM', 'dair ARM', ['Mein rechter Arm ist gebrochen.', 'My right arm is broken.', 'Mon bras droit est cassé.']),
    vocab('sp-koerper-gesundheit-hand', 'die Hand', 'the hand', 'la main', 'die', 'HAND', 'dee HAHNT', ['Wasch dir die Hände!', 'Wash your hands!', 'Lave-toi les mains !']),
    vocab('sp-koerper-gesundheit-finger', 'der Finger', 'the finger', 'le doigt', 'der', 'FIN-ger', 'dair FIN-ger', ['Ich habe mir den Finger geschnitten.', 'I cut my finger.', 'Je me suis coupé le doigt.']),
    vocab('sp-koerper-gesundheit-ruecken', 'der Rücken', 'the back', 'le dos', 'der', 'RÜ-cken', 'dair RUE-ken', ['Mein Rücken tut vom Sitzen weh.', 'My back hurts from sitting.', 'J’ai mal au dos à force d’être assis.']),
    vocab('sp-koerper-gesundheit-bauch', 'der Bauch', 'the belly, the stomach', 'le ventre', 'der', 'BAUCH', 'dair BOWKH', ['Nach dem Essen tut mir der Bauch weh.', 'My stomach hurts after eating.', 'J’ai mal au ventre après le repas.']),
    vocab('sp-koerper-gesundheit-bein', 'das Bein', 'the leg', 'la jambe', 'das', 'BEIN', 'dahs BYN', ['Er hat sich das Bein gebrochen.', 'He broke his leg.', 'Il s’est cassé la jambe.']),
    vocab('sp-koerper-gesundheit-knie', 'das Knie', 'the knee', 'le genou', 'das', 'KNIE', 'dahs k-NEE', ['Mein Knie ist geschwollen.', 'My knee is swollen.', 'Mon genou est enflé.']),
    vocab('sp-koerper-gesundheit-fuss', 'der Fuß', 'the foot', 'le pied', 'der', 'FUSS', 'dair FOOSS', ['Meine Füße sind kalt.', 'My feet are cold.', 'Mes pieds sont froids.']),
    vocab('sp-koerper-gesundheit-herz', 'das Herz', 'the heart', 'le cœur', 'das', 'HERZ', 'dahs HAIRTS', ['Sein Herz schlägt sehr schnell.', 'His heart is beating very fast.', 'Son cœur bat très vite.']),
    grammar(
      'sp-kg-plural',
      ['Plurals of body parts', 'Pluriel des parties du corps'],
      [
        'Body parts are very often irregular in the plural — learn them together with the singular:\n\n- das Auge → **die Augen** (-n)\n- das Ohr → **die Ohren** (-en)\n- die Nase → **die Nasen** (-n)\n- der Zahn → **die Zähne** (umlaut + -e)\n- der Arm → **die Arme** (-e)\n- die Hand → **die Hände** (umlaut + -e)\n- der Finger → **die Finger** (no change)\n- der Fuß → **die Füße** (umlaut + -e, ß)\n- das Bein → **die Beine** (-e)\n- das Knie → **die Knie** (no change)\n- das Herz → **die Herzen** (-en)\n- der Kopf → **die Köpfe** (umlaut + -e)\n\nTo describe a body part you can use a possessive (**mein Kopf**, **meine Augen**); with actions on your own body German often uses **mir / dir + article** instead: *Ich wasche **mir die** Hände.*',
        'Les parties du corps ont très souvent un pluriel irrégulier — apprends-les avec le singulier :\n\n- das Auge → **die Augen** (-n)\n- das Ohr → **die Ohren** (-en)\n- die Nase → **die Nasen** (-n)\n- der Zahn → **die Zähne** (tréma + -e)\n- der Arm → **die Arme** (-e)\n- die Hand → **die Hände** (tréma + -e)\n- der Finger → **die Finger** (inchangé)\n- der Fuß → **die Füße** (tréma + -e, ß)\n- das Bein → **die Beine** (-e)\n- das Knie → **die Knie** (inchangé)\n- das Herz → **die Herzen** (-en)\n- der Kopf → **die Köpfe** (tréma + -e)\n\nPour décrire une partie du corps, on peut employer un possessif (**mein Kopf**, **meine Augen**) ; pour une action sur son propre corps, l’allemand utilise souvent **mir / dir + article** : *Ich wasche **mir die** Hände.*',
      ],
      [
        ['Er hat blaue Augen und große Hände.', 'He has blue eyes and big hands.', 'Il a les yeux bleus et de grandes mains.'],
        ['Meine Füße sind müde.', 'My feet are tired.', 'Mes pieds sont fatigués.'],
        ['Der Zahnarzt kontrolliert meine Zähne.', 'The dentist checks my teeth.', 'Le dentiste contrôle mes dents.'],
      ],
    ),
    match(
      'sp-kg-e6',
      [
        ['der Arm', 'the arm', 'le bras'],
        ['die Hand', 'the hand', 'la main'],
        ['der Rücken', 'the back', 'le dos'],
        ['der Bauch', 'the belly', 'le ventre'],
        ['das Bein', 'the leg', 'la jambe'],
        ['der Fuß', 'the foot', 'le pied'],
      ],
      ['Match the body parts.', 'Associe les parties du corps.'],
    ),
    mc(
      'sp-kg-e7',
      ['What is the plural of "die Hand"?', 'Quel est le pluriel de « die Hand » ?'],
      ['die Hände', 'die Hands', 'die Handen'], ['die Hände', 'die Hands', 'die Handen'], 0,
      ['Hand → Hände (umlaut + -e).', 'Hand → Hände (tréma + -e).'],
    ),
    mc(
      'sp-kg-e8',
      ['What is the plural of "das Auge"?', 'Quel est le pluriel de « das Auge » ?'],
      ['die Augen', 'die Auger', 'die Auge'], ['die Augen', 'die Auger', 'die Auge'], 0,
      ['Auge → Augen (-n).', 'Auge → Augen (-n).'],
    ),
    ap('sp-kg-e9', 'Fuß', 'der', ['Fuß is masculine; the plural is die Füße.', 'Fuß est masculin ; le pluriel est die Füße.']),
    ap('sp-kg-e10', 'Herz', 'das', ['Herz is neuter: das Herz.', 'Herz est neutre : das Herz.']),
    ap('sp-kg-e11', 'Hand', 'die', ['Hand is feminine: die Hand.', 'Hand est féminin : die Hand.']),

    // ── Chapter 3 ────────────────────────────────────────────────
    chapter(
      'Where does it hurt?', 'Où as-tu mal ?',
      'Two patterns say it all: weh tun and -schmerzen.', 'Deux tournures disent tout : weh tun et -schmerzen.',
    ),
    vocab('sp-koerper-gesundheit-schmerzen', 'die Schmerzen', 'the pain', 'la douleur, les douleurs', 'die', 'SCHMER-zen', 'dee SHMAIR-tsen', ['Ich habe starke Schmerzen im Rücken.', 'I have strong pain in my back.', 'J’ai de fortes douleurs dans le dos.']),
    vocab('sp-koerper-gesundheit-fieber', 'das Fieber', 'the fever', 'la fièvre', 'das', 'FIE-ber', 'dahs FEE-ber', ['Mein Sohn hat Fieber.', 'My son has a fever.', 'Mon fils a de la fièvre.']),
    vocab('sp-koerper-gesundheit-husten', 'der Husten', 'the cough', 'la toux', 'der', 'HUS-ten', 'dair HOO-sten', ['Ich habe seit drei Tagen Husten.', 'I have had a cough for three days.', 'Je tousse depuis trois jours.']),
    vocab('sp-koerper-gesundheit-erkaeltung', 'die Erkältung', 'the cold', 'le rhume', 'die', 'er-KÄL-tung', 'dee er-KEL-toong', ['Eine Erkältung dauert ungefähr eine Woche.', 'A cold lasts about a week.', 'Un rhume dure environ une semaine.']),
    vocab('sp-koerper-gesundheit-krank', 'krank', 'ill, sick', 'malade', null, 'KRANK', 'KRAHNK', ['Ich bin heute krank.', 'I am ill today.', 'Je suis malade aujourd’hui.']),
    vocab('sp-koerper-gesundheit-gesund', 'gesund', 'healthy', 'en bonne santé', null, 'ge-SUND', 'geh-ZOONT', ['Obst und Gemüse sind gesund.', 'Fruit and vegetables are healthy.', 'Les fruits et les légumes sont bons pour la santé.']),
    grammar(
      'sp-kg-wehtun',
      ['weh tun — it hurts', 'weh tun — avoir mal'],
      [
        'To say what hurts, German uses **weh tun** with the **dative** (mir, dir, ihm, ihr, uns, Ihnen). The **body part is the subject** and the verb agrees with it:\n\n- **Der Kopf tut mir weh.** (The head hurts me.)\n- **Die Augen tun mir weh.** (plural → *tun*)\n- **Mir tut der Bauch weh.** (starting with mir is very common)\n\nQuestion: **Was tut dir weh?** — **Wo tut es weh?**\n\n| person | dative |\n|---|---|\n| ich | **mir** |\n| du | **dir** |\n| er / es | **ihm** |\n| sie | **ihr** |\n| wir | **uns** |\n| Sie | **Ihnen** |\n\nNever say *Ich tue weh* — that would mean you hurt someone else.',
        'Pour dire ce qui fait mal, l’allemand emploie **weh tun** avec le **datif** (mir, dir, ihm, ihr, uns, Ihnen). La **partie du corps est le sujet** et le verbe s’accorde avec elle :\n\n- **Der Kopf tut mir weh.** (La tête me fait mal.)\n- **Die Augen tun mir weh.** (pluriel → *tun*)\n- **Mir tut der Bauch weh.** (commencer par mir est très fréquent)\n\nQuestion : **Was tut dir weh ?** — **Wo tut es weh ?**\n\n| personne | datif |\n|---|---|\n| ich | **mir** |\n| du | **dir** |\n| er / es | **ihm** |\n| sie | **ihr** |\n| wir | **uns** |\n| Sie | **Ihnen** |\n\nNe dis jamais *Ich tue weh* — cela signifierait que tu fais mal à quelqu’un d’autre.',
      ],
      [
        ['Der Kopf tut mir weh.', 'My head hurts.', 'J’ai mal à la tête.'],
        ['Die Füße tun ihm weh.', 'His feet hurt.', 'Il a mal aux pieds.'],
        ['Wo tut es Ihnen weh?', 'Where does it hurt (you)?', 'Où avez-vous mal ?'],
        ['Mir tut der Rücken weh.', 'My back hurts.', 'J’ai mal au dos.'],
      ],
    ),
    grammar(
      'sp-kg-schmerzen',
      ['-schmerzen and symptoms', '-schmerzen et symptômes'],
      [
        'The second, very common pattern uses **haben** with a **compound noun** ending in **-schmerzen** (almost always plural):\n\n- **Kopf**schmerzen · **Hals**schmerzen · **Bauch**schmerzen · **Zahn**schmerzen · **Rücken**schmerzen · **Ohren**schmerzen\n- **Ich habe Kopfschmerzen.** = *Mir tut der Kopf weh.*\n\nOther symptoms also use **haben** — and there is **no article**:\n\n- Ich habe **Fieber** / **Husten** / **Schnupfen** / **Durchfall**.\n- Ich habe **eine Erkältung** (with article, because the noun is countable).\n\nFor a state, use **sein**: Ich bin **krank**, **müde**, **erkältet**, **gesund**.',
        'La deuxième tournure, très courante, emploie **haben** avec un **nom composé** en **-schmerzen** (presque toujours au pluriel) :\n\n- **Kopf**schmerzen · **Hals**schmerzen · **Bauch**schmerzen · **Zahn**schmerzen · **Rücken**schmerzen · **Ohren**schmerzen\n- **Ich habe Kopfschmerzen.** = *Mir tut der Kopf weh.*\n\nLes autres symptômes s’expriment aussi avec **haben** — et **sans article** :\n\n- Ich habe **Fieber** / **Husten** / **Schnupfen** / **Durchfall**.\n- Ich habe **eine Erkältung** (avec article, car le nom est dénombrable).\n\nPour un état, utilise **sein** : Ich bin **krank**, **müde**, **erkältet**, **gesund**.',
      ],
      [
        ['Ich habe Halsschmerzen und Husten.', 'I have a sore throat and a cough.', 'J’ai mal à la gorge et je tousse.'],
        ['Hast du Fieber?', 'Do you have a fever?', 'As-tu de la fièvre ?'],
        ['Meine Tochter hat Bauchschmerzen.', 'My daughter has a stomach ache.', 'Ma fille a mal au ventre.'],
        ['Er ist erkältet.', 'He has a cold.', 'Il est enrhumé.'],
      ],
    ),
    fb(
      'sp-kg-e12',
      ['Der Kopf tut ___ weh. (ich — dative)', 'Der Kopf tut ___ weh. (ich — datif)'],
      'mir',
      ['ich → mir in the dative.', 'ich → mir au datif.'],
    ),
    fb(
      'sp-kg-e13',
      ['Die Augen ___ mir weh. (tun / tut)', 'Die Augen ___ mir weh. (tun / tut)'],
      'tun',
      ['Plural subject → tun.', 'Sujet pluriel → tun.'],
    ),
    fb(
      'sp-kg-e14',
      ['Ich habe Kopf___. (pain)', 'Ich habe Kopf___. (douleurs)'],
      'schmerzen',
      ['Compound: Kopf + schmerzen.', 'Mot composé : Kopf + schmerzen.'],
    ),
    fb(
      'sp-kg-e15',
      ['Wo tut es ___ weh? (Sie — formal dative)', 'Wo tut es ___ weh ? (Sie — datif de politesse)'],
      'Ihnen',
      ['Formal dative: Ihnen.', 'Datif de politesse : Ihnen.'],
    ),
    mc(
      'sp-kg-e16',
      ['Which sentence is correct?', 'Quelle phrase est correcte ?'],
      ['Mir tut der Bauch weh.', 'Ich tue Bauch weh.', 'Mich tut der Bauch weh.'],
      ['Mir tut der Bauch weh.', 'Ich tue Bauch weh.', 'Mich tut der Bauch weh.'], 0,
      ['Weh tun takes the dative: mir.', 'Weh tun se construit avec le datif : mir.'],
    ),
    wo('sp-kg-e17', ['tut', 'Der', 'weh', 'mir', 'Rücken'], ['Der', 'Rücken', 'tut', 'mir', 'weh'], ['Body part first, then tut mir weh.', 'La partie du corps d’abord, puis tut mir weh.']),

    // ── Chapter 4 ────────────────────────────────────────────────
    chapter(
      'At the doctor’s', 'Chez le médecin',
      'Make an appointment and answer the doctor’s questions.', 'Prends rendez-vous et réponds aux questions du médecin.',
    ),
    vocab('sp-koerper-gesundheit-arzt', 'der Arzt', 'the doctor (male)', 'le médecin', 'der', 'ARZT', 'dair ARTST', ['Der Arzt untersucht den Patienten.', 'The doctor examines the patient.', 'Le médecin examine le patient.']),
    vocab('sp-koerper-gesundheit-aerztin', 'die Ärztin', 'the doctor (female)', 'la femme médecin', 'die', 'ÄRZ-tin', 'dee ERTS-tin', ['Die Ärztin hat heute bis 18 Uhr Sprechstunde.', 'The doctor has office hours until 6 p.m. today.', 'La médecin consulte aujourd’hui jusqu’à 18 h.']),
    vocab('sp-koerper-gesundheit-termin', 'der Termin', 'the appointment', 'le rendez-vous', 'der', 'ter-MIN', 'dair ter-MEEN', ['Ich möchte einen Termin vereinbaren.', 'I would like to make an appointment.', 'Je voudrais prendre rendez-vous.']),
    grammar(
      'sp-kg-seit',
      ['seit + dative: how long?', 'seit + datif : depuis combien de temps ?'],
      [
        'The doctor will ask **Seit wann …?** (since when). Answer with **seit + dative** and the **present tense** — for something that is still going on, German uses the present, not the perfect:\n\n- **Seit wann haben Sie Fieber?** — **Seit zwei Tagen.**\n- Ich habe **seit gestern** Halsschmerzen.\n- Mir ist **seit einer Woche** schlecht.\n\n**seit** + dative: *seit einem Tag, seit einer Woche, seit zwei Tagen* (the dative plural ends in **-n**: *drei Wochen*).\n\nOther doctor questions: **Was fehlt Ihnen?** (What is wrong?) · **Wo tut es weh?** · **Haben Sie Fieber?** · **Nehmen Sie Medikamente?**',
        'Le médecin demandera **Seit wann …?** (depuis quand). Réponds avec **seit + datif** et le **présent** — pour ce qui dure encore, l’allemand emploie le présent, pas le passé composé :\n\n- **Seit wann haben Sie Fieber ?** — **Seit zwei Tagen.**\n- Ich habe **seit gestern** Halsschmerzen.\n- Mir ist **seit einer Woche** schlecht.\n\n**seit** + datif : *seit einem Tag, seit einer Woche, seit zwei Tagen* (le datif pluriel se termine en **-n** : *drei Wochen*).\n\nAutres questions du médecin : **Was fehlt Ihnen ?** (Qu’est-ce qui ne va pas ?) · **Wo tut es weh ?** · **Haben Sie Fieber ?** · **Nehmen Sie Medikamente ?**',
      ],
      [
        ['Seit wann haben Sie Fieber?', 'Since when have you had a fever?', 'Depuis quand avez-vous de la fièvre ?'],
        ['Seit zwei Tagen.', 'For two days.', 'Depuis deux jours.'],
        ['Ich habe seit einer Woche Husten.', 'I have had a cough for a week.', 'Je tousse depuis une semaine.'],
        ['Was fehlt Ihnen?', 'What is the matter with you?', 'Qu’est-ce qui ne va pas ?'],
      ],
    ),
    grammar(
      'sp-kg-dialog-arzt',
      ['Dialogue: Beim Arzt', 'Dialogue : Beim Arzt'],
      [
        'A short appointment between **Frau Keller** and **Dr. Weber**:\n\n- **Dr. Weber:** Guten Tag, Frau Keller. **Was fehlt Ihnen?**\n- **Frau Keller:** Guten Tag. Ich habe **Halsschmerzen** und **Husten**.\n- **Dr. Weber:** **Seit wann** haben Sie die Beschwerden?\n- **Frau Keller:** **Seit drei Tagen.** Und ich habe auch **Fieber**.\n- **Dr. Weber:** Bitte **öffnen Sie den Mund**. … Ja, der Hals ist ganz rot. Sie haben eine **Erkältung**.\n- **Frau Keller:** Muss ich **Tabletten** nehmen?\n- **Dr. Weber:** Ich schreibe Ihnen ein **Rezept**. Und **bleiben Sie zu Hause**!\n\nOn the phone: **Ich möchte einen Termin vereinbaren.** — **Passt Ihnen Montag um 10 Uhr?**',
        'Un court rendez-vous entre **Frau Keller** et **Dr. Weber** :\n\n- **Dr. Weber :** Guten Tag, Frau Keller. **Was fehlt Ihnen ?**\n- **Frau Keller :** Guten Tag. Ich habe **Halsschmerzen** und **Husten**.\n- **Dr. Weber :** **Seit wann** haben Sie die Beschwerden ?\n- **Frau Keller :** **Seit drei Tagen.** Und ich habe auch **Fieber**.\n- **Dr. Weber :** Bitte **öffnen Sie den Mund**. … Ja, der Hals ist ganz rot. Sie haben eine **Erkältung**.\n- **Frau Keller :** Muss ich **Tabletten** nehmen ?\n- **Dr. Weber :** Ich schreibe Ihnen ein **Rezept**. Und **bleiben Sie zu Hause** !\n\nAu téléphone : **Ich möchte einen Termin vereinbaren.** — **Passt Ihnen Montag um 10 Uhr ?**',
      ],
      [
        ['Guten Tag, was fehlt Ihnen?', 'Hello, what is the matter?', 'Bonjour, qu’est-ce qui ne va pas ?'],
        ['Ich habe Halsschmerzen und Fieber.', 'I have a sore throat and a fever.', 'J’ai mal à la gorge et de la fièvre.'],
        ['Ich möchte einen Termin vereinbaren.', 'I would like to make an appointment.', 'Je voudrais prendre rendez-vous.'],
        ['Passt Ihnen Montag um 10 Uhr?', 'Does Monday at 10 suit you?', 'Lundi à 10 h, est-ce que cela vous convient ?'],
      ],
    ),
    fb(
      'sp-kg-e18',
      ['Seit wann haben Sie Fieber? — ___ zwei Tagen. (for)', 'Seit wann haben Sie Fieber ? — ___ zwei Tagen. (depuis)'],
      'Seit',
      ['“For two days” = seit zwei Tagen.', '« Depuis deux jours » = seit zwei Tagen.'],
    ),
    fb(
      'sp-kg-e19',
      ['Ich möchte einen ___ vereinbaren. (appointment)', 'Ich möchte einen ___ vereinbaren. (rendez-vous)'],
      'Termin',
      ['der Termin = the appointment.', 'der Termin = le rendez-vous.'],
    ),
    mc(
      'sp-kg-e20',
      ['"Was fehlt Ihnen?" means…', '« Was fehlt Ihnen ? » signifie…'],
      ['What is the matter with you?', 'What are you missing?', 'What do you eat?'],
      ['Qu’est-ce qui ne va pas ?', 'Que vous manque-t-il ?', 'Que mangez-vous ?'], 0,
      ['A standard doctor’s opener.', 'La phrase d’ouverture classique du médecin.'],
    ),
    wo('sp-kg-e21', ['haben', 'Seit', 'Fieber', 'wann', 'Sie'], ['Seit', 'wann', 'haben', 'Sie', 'Fieber'], ['Question word first, then the verb, then the subject.', 'Mot interrogatif d’abord, puis le verbe, puis le sujet.']),
    wo('sp-kg-e22', ['möchte', 'einen', 'Ich', 'Termin', 'vereinbaren'], ['Ich', 'möchte', 'einen', 'Termin', 'vereinbaren'], ['Verb 2nd, infinitive at the end.', 'Verbe en 2e position, infinitif à la fin.']),
    lc(
      'sp-kg-e23',
      ['Listen. What is the patient’s problem?', 'Écoute. Quel est le problème du patient ?'],
      'Ich habe seit drei Tagen Halsschmerzen und Husten.',
      ['A sore throat and a cough', 'A broken leg', 'A toothache'], ['Mal à la gorge et toux', 'Une jambe cassée', 'Mal aux dents'], 0,
      ['Listen for Halsschmerzen and Husten.', 'Écoute Halsschmerzen et Husten.'],
    ),

    // ── Chapter 5 ────────────────────────────────────────────────
    chapter(
      'Pharmacy and advice', 'Pharmacie et conseils',
      'Collect your medicine and understand what to do next.', 'Retire tes médicaments et comprends ce qu’il faut faire ensuite.',
    ),
    vocab('sp-koerper-gesundheit-apotheke', 'die Apotheke', 'the pharmacy', 'la pharmacie', 'die', 'a-po-THE-ke', 'dee ah-poh-TAY-keh', ['Die Apotheke ist neben der Bank.', 'The pharmacy is next to the bank.', 'La pharmacie est à côté de la banque.']),
    vocab('sp-koerper-gesundheit-tablette', 'die Tablette', 'the tablet', 'le comprimé', 'die', 'ta-BLET-te', 'dee tah-BLET-teh', ['Nehmen Sie dreimal täglich eine Tablette.', 'Take one tablet three times a day.', 'Prenez un comprimé trois fois par jour.']),
    vocab('sp-koerper-gesundheit-rezept', 'das Rezept', 'the prescription', 'l’ordonnance', 'das', 're-ZEPT', 'dahs reh-TSEPT', ['Ohne Rezept bekommen Sie das nicht.', 'You cannot get that without a prescription.', 'Vous ne l’obtenez pas sans ordonnance.']),
    grammar(
      'sp-kg-ratschlaege',
      ['Giving advice: Sie sollten …, Nehmen Sie …', 'Donner des conseils : Sie sollten …, Nehmen Sie …'],
      [
        'Doctors and pharmacists give advice in two ways:\n\n**1. sollen / sollten + infinitive** (should)\n- **Sie sollten viel Wasser trinken.** — *You should drink a lot of water.*\n- **Du solltest** im Bett bleiben. (informal)\n\n**2. The formal imperative:** verb + **Sie**, first position, infinitive form:\n- **Nehmen Sie** eine Tablette. · **Trinken Sie** Tee. · **Bleiben Sie** zu Hause.\n- Informal (du): **Nimm** eine Tablette. · **Trink** Tee. · **Bleib** zu Hause.\n\nUseful frequency: **einmal / zweimal / dreimal täglich** (once / twice / three times a day), **vor / nach dem Essen** (before / after eating).',
        'Médecins et pharmaciens donnent des conseils de deux façons :\n\n**1. sollen / sollten + infinitif** (devoir, il faudrait)\n- **Sie sollten viel Wasser trinken.** — *Vous devriez boire beaucoup d’eau.*\n- **Du solltest** im Bett bleiben. (familier)\n\n**2. L’impératif de politesse :** verbe + **Sie**, en première position, à l’infinitif :\n- **Nehmen Sie** eine Tablette. · **Trinken Sie** Tee. · **Bleiben Sie** zu Hause.\n- Familier (du) : **Nimm** eine Tablette. · **Trink** Tee. · **Bleib** zu Hause.\n\nFréquence utile : **einmal / zweimal / dreimal täglich** (une / deux / trois fois par jour), **vor / nach dem Essen** (avant / après le repas).',
      ],
      [
        ['Sie sollten viel Wasser trinken.', 'You should drink a lot of water.', 'Vous devriez boire beaucoup d’eau.'],
        ['Nehmen Sie dreimal täglich eine Tablette.', 'Take one tablet three times a day.', 'Prenez un comprimé trois fois par jour.'],
        ['Bleiben Sie zu Hause und ruhen Sie sich aus.', 'Stay at home and rest.', 'Restez chez vous et reposez-vous.'],
        ['Du solltest mehr schlafen.', 'You should sleep more.', 'Tu devrais dormir davantage.'],
      ],
    ),
    grammar(
      'sp-kg-dialog-apotheke',
      ['Dialogue: In der Apotheke', 'Dialogue : In der Apotheke'],
      [
        'Samuel has a cold and goes to the pharmacy:\n\n- **Apothekerin:** Guten Tag, womit kann ich Ihnen helfen?\n- **Samuel:** Guten Tag. Ich habe **Husten** und **Kopfschmerzen**. Haben Sie etwas dagegen?\n- **Apothekerin:** Haben Sie **Fieber**?\n- **Samuel:** Nein, kein Fieber.\n- **Apothekerin:** Dann **nehmen Sie** diese **Tabletten**, **zweimal täglich nach dem Essen**. Und **trinken Sie viel Tee**.\n- **Samuel:** Brauche ich ein **Rezept**?\n- **Apothekerin:** Nein, das gibt es ohne Rezept. Das macht 7,50 Euro.\n\n**etwas gegen …** = something for/against: *Haben Sie etwas gegen Husten?*',
        'Samuel est enrhumé et va à la pharmacie :\n\n- **Apothekerin :** Guten Tag, womit kann ich Ihnen helfen ?\n- **Samuel :** Guten Tag. Ich habe **Husten** und **Kopfschmerzen**. Haben Sie etwas dagegen ?\n- **Apothekerin :** Haben Sie **Fieber** ?\n- **Samuel :** Nein, kein Fieber.\n- **Apothekerin :** Dann **nehmen Sie** diese **Tabletten**, **zweimal täglich nach dem Essen**. Und **trinken Sie viel Tee**.\n- **Samuel :** Brauche ich ein **Rezept** ?\n- **Apothekerin :** Nein, das gibt es ohne Rezept. Das macht 7,50 Euro.\n\n**etwas gegen …** = quelque chose contre : *Haben Sie etwas gegen Husten ?*',
      ],
      [
        ['Haben Sie etwas gegen Husten?', 'Do you have something for a cough?', 'Avez-vous quelque chose contre la toux ?'],
        ['Nehmen Sie die Tabletten zweimal täglich.', 'Take the tablets twice a day.', 'Prenez les comprimés deux fois par jour.'],
        ['Brauche ich ein Rezept?', 'Do I need a prescription?', 'Ai-je besoin d’une ordonnance ?'],
      ],
    ),
    mc(
      'sp-kg-e24',
      ['The doctor says: "Nehmen Sie dreimal täglich eine Tablette." You should…', 'Le médecin dit : « Nehmen Sie dreimal täglich eine Tablette. » Tu dois…'],
      ['take one tablet three times a day', 'take three tablets once a day', 'buy three tablets'],
      ['prendre un comprimé trois fois par jour', 'prendre trois comprimés une fois par jour', 'acheter trois comprimés'], 0,
      ['dreimal täglich = three times a day.', 'dreimal täglich = trois fois par jour.'],
    ),
    mc(
      'sp-kg-e25',
      ['Which one is the formal imperative of "trinken"?', 'Laquelle est l’impératif de politesse de « trinken » ?'],
      ['Trinken Sie Tee!', 'Trinke Sie Tee!', 'Sie trinken Tee!'], ['Trinken Sie Tee !', 'Trinke Sie Tee !', 'Sie trinken Tee !'], 0,
      ['Verb in first position + Sie.', 'Verbe en première position + Sie.'],
    ),
    fb(
      'sp-kg-e26',
      ['Sie ___ viel Wasser trinken. (sollten — should)', 'Sie ___ viel Wasser trinken. (sollten — devriez)'],
      'sollten',
      ['sollten + infinitive at the end.', 'sollten + infinitif à la fin.'],
    ),
    fb(
      'sp-kg-e27',
      ['___ Sie zu Hause! (bleiben)', '___ Sie zu Hause ! (bleiben)'],
      'Bleiben',
      ['Imperative: verb first, then Sie.', 'Impératif : verbe d’abord, puis Sie.'],
    ),
    wo('sp-kg-e28', ['Wasser', 'viel', 'Sie', 'Trinken'], ['Trinken', 'Sie', 'viel', 'Wasser'], ['Formal imperative: verb first, then Sie.', 'Impératif de politesse : verbe d’abord, puis Sie.']),

    wrapup(
      '**Body** — der Kopf, das Auge, das Ohr, die Nase, der Mund, der Zahn, der Hals, der Arm, die Hand, der Rücken, der Bauch, das Bein, der Fuß. Plurals: Augen, Ohren, Zähne, Hände, Füße.\n\n**Pain** — two patterns: *Der Kopf tut mir weh* (dative mir/dir/ihm/ihr/Ihnen, verb agrees with the body part) and *Ich habe Kopfschmerzen* (haben + -schmerzen).\n\n**Symptoms** — Fieber, Husten, eine Erkältung; krank / gesund.\n\n**Doctor** — Was fehlt Ihnen? Seit wann? seit + dative: seit zwei Tagen. Ich möchte einen Termin vereinbaren.\n\n**Advice** — Sie sollten …; Nehmen Sie … / Bleiben Sie …; dreimal täglich, nach dem Essen.',
      '**Corps** — der Kopf, das Auge, das Ohr, die Nase, der Mund, der Zahn, der Hals, der Arm, die Hand, der Rücken, der Bauch, das Bein, der Fuß. Pluriels : Augen, Ohren, Zähne, Hände, Füße.\n\n**Douleur** — deux tournures : *Der Kopf tut mir weh* (datif mir/dir/ihm/ihr/Ihnen, le verbe s’accorde avec la partie du corps) et *Ich habe Kopfschmerzen* (haben + -schmerzen).\n\n**Symptômes** — Fieber, Husten, eine Erkältung ; krank / gesund.\n\n**Médecin** — Was fehlt Ihnen ? Seit wann ? seit + datif : seit zwei Tagen. Ich möchte einen Termin vereinbaren.\n\n**Conseils** — Sie sollten … ; Nehmen Sie … / Bleiben Sie … ; dreimal täglich, nach dem Essen.',
    ),

    // ── Quiz ─────────────────────────────────────────────────────
    quiz('Final quiz: Body & health', 'Quiz final : corps & santé'),
    match(
      'sp-kg-q1',
      [
        ['der Kopf', 'the head', 'la tête'],
        ['der Rücken', 'the back', 'le dos'],
        ['das Fieber', 'the fever', 'la fièvre'],
        ['der Husten', 'the cough', 'la toux'],
        ['die Apotheke', 'the pharmacy', 'la pharmacie'],
      ],
      ['Match each word with its translation.', 'Associe chaque mot à sa traduction.'],
    ),
    ap('sp-kg-q2', 'Bauch', 'der', ['Bauch is masculine.', 'Bauch est masculin.']),
    ap('sp-kg-q3', 'Knie', 'das', ['Knie is neuter: das Knie.', 'Knie est neutre : das Knie.']),
    mc(
      'sp-kg-q4',
      ['What is the plural of "der Zahn"?', 'Quel est le pluriel de « der Zahn » ?'],
      ['die Zähne', 'die Zahnen', 'die Zahns'], ['die Zähne', 'die Zahnen', 'die Zahns'], 0,
      ['Zahn → Zähne (umlaut + -e).', 'Zahn → Zähne (tréma + -e).'],
    ),
    mc(
      'sp-kg-q5',
      ['Which sentence says "My feet hurt"?', 'Quelle phrase dit « J’ai mal aux pieds » ?'],
      ['Die Füße tun mir weh.', 'Die Füße tut mir weh.', 'Ich tue die Füße weh.'],
      ['Die Füße tun mir weh.', 'Die Füße tut mir weh.', 'Ich tue die Füße weh.'], 0,
      ['Plural body part → tun + dative mir.', 'Partie du corps au pluriel → tun + datif mir.'],
    ),
    mc(
      'sp-kg-q6',
      ['Which sentence means the same as "Mir tut der Hals weh"?', 'Quelle phrase a le même sens que « Mir tut der Hals weh » ?'],
      ['Ich habe Halsschmerzen.', 'Ich habe Hals.', 'Ich bin Halsschmerzen.'],
      ['Ich habe Halsschmerzen.', 'Ich habe Hals.', 'Ich bin Halsschmerzen.'], 0,
      ['haben + -schmerzen.', 'haben + -schmerzen.'],
    ),
    fb(
      'sp-kg-q7',
      ['Der Rücken tut ___ weh. (du — dative)', 'Der Rücken tut ___ weh. (du — datif)'],
      'dir',
      ['du → dir in the dative.', 'du → dir au datif.'],
    ),
    fb(
      'sp-kg-q8',
      ['Ich habe Bauch___. (pain)', 'Ich habe Bauch___. (douleurs)'],
      'schmerzen',
      ['Compound: Bauch + schmerzen.', 'Mot composé : Bauch + schmerzen.'],
    ),
    fb(
      'sp-kg-q9',
      ['Ich habe ___ drei Tagen Husten. (since)', 'Ich habe ___ drei Tagen Husten. (depuis)'],
      'seit',
      ['seit + dative.', 'seit + datif.'],
    ),
    fb(
      'sp-kg-q10',
      ['Sie ___ im Bett bleiben. (sollten)', 'Sie ___ im Bett bleiben. (sollten)'],
      'sollten',
      ['sollten + infinitive at the end.', 'sollten + infinitif à la fin.'],
    ),
    wo('sp-kg-q11', ['weh', 'Der', 'Kopf', 'mir', 'tut'], ['Der', 'Kopf', 'tut', 'mir', 'weh'], ['Body part, tut, mir, weh.', 'Partie du corps, tut, mir, weh.']),
    wo('sp-kg-q12', ['Sie', 'Nehmen', 'Tablette', 'eine'], ['Nehmen', 'Sie', 'eine', 'Tablette'], ['Imperative: verb first, then Sie.', 'Impératif : verbe d’abord, puis Sie.']),
    lc(
      'sp-kg-q13',
      ['Listen. What does the doctor advise?', 'Écoute. Que conseille le médecin ?'],
      'Bleiben Sie zu Hause und trinken Sie viel Tee.',
      ['Stay at home and drink a lot of tea', 'Go to work and drink coffee', 'Go to the pharmacy'], ['Rester chez soi et boire beaucoup de thé', 'Aller travailler et boire du café', 'Aller à la pharmacie'], 0,
      ['Listen for bleiben and Tee.', 'Écoute bleiben et Tee.'],
    ),
    lc(
      'sp-kg-q14',
      ['Listen. Where does it hurt?', 'Écoute. Où a-t-il mal ?'],
      'Mir tut der Rücken weh.',
      ['In the back', 'In the head', 'In the foot'], ['Au dos', 'À la tête', 'Au pied'], 0,
      ['Der Rücken = the back.', 'Der Rücken = le dos.'],
    ),
  ],
});
